### ISSUE TITLE
Helping hash depend on Master Password only

### ISSUE THREAD

**Issue by Zykino** [lesspass/lesspass#10]
Something I noticed is the helping hash (with color) is generated thanks to the Login and Master Password (MP).

I think it's not a good thing since I have not all the time the same login (Zykino, e-mail, ...). So when I first used an other login I thought I misspelled my MP. My thought may come from the fact that the hash is in the MP input.

_Cons:_
* May be less secure against a man in your back (But he will see your login anyway so not sure)
* Check only typos on the MP and not the Login
* Everyone will have to remember a new hash (But only one this time)

_Pros:_
* The hash depend only on the hidden input -> Change Login keep the same hash
* You are sure the MP is the good one without clicking to see it (Man in your back will only see the hash even if you misspelled, and you will type it again)

There may be more of pros/cons.
What do you think about it?

**Comment by guillaumevincent** [comment]
@Zykino helping hash + color was here to help user to detect a mistake.
If we implement the feature in the next version, we should help existing user with the breaking change.

@edouard-lopez how can we handle this from user point of view ?

Example of the new interface

![screenshot from 2016-09-26 13-54-24](https://cloud.githubusercontent.com/assets/943762/18833481/2dc4dbe8-83f1-11e6-9260-81e0b151baf6.png)

**Comment by guillaumevincent** [comment]
@edouard-lopez we probably need to make this breaking change soon. More we wait, more the impacted users will be important.

Love the `#2` because of the arrow shows the information is about the password only

**Comment by edouard-lopez** [comment]
Just tried with icons

### Hash Checksum
![lesspass-hash-checksum](https://cloud.githubusercontent.com/assets/1212392/19109307/09da5248-8af5-11e6-95f8-2d23555d5dcf.png)

# Icon checksum
![lesspass-hash-icon](https://cloud.githubusercontent.com/assets/1212392/19109308/09e0053a-8af5-11e6-8bf4-2c01019ca325.png)

**Comment by Zykino** [comment]
This is just a suggestion but for a month, or I don't know how many times, you may add an equivalent of a bootstrap alert https://getbootstrap.com/components/#alerts-dismissible
If the user dismiss it make a cookie and do not print it again, or if the merge was done more than X months ago.

Then you could reuse this for any breaking change.

For the propositions I like #2 and #3. (#1 is the current one isn't it? I still like it)

**Comment by guillaumevincent** [comment]
@Zykino After a discussion with @edouard-lopez and some test with some early adopters we are going to make the breaking change with the implementation of the icon version : 

you can test a preview here : https://lesspass.github.io/vue/ 

This will fix this issue and existing users will notice the difference with previous version.

**Comment by guillaumevincent** [comment]
Here a gif of the implementation : 

![lesspass_360](https://cloud.githubusercontent.com/assets/943762/19182312/dc7d3dcc-8c72-11e6-99dc-f492bd09faff.gif)


will be in version 1.0.0
