### ISSUE TITLE
Different version between Firefox and Chrome store 

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#100]
As of today [Chrome store](https://chrome.google.com/webstore/detail/lesspass/lcmbpoclaodbgkbjafnkbbinogcbnjih?hl=en-US) has `v1.1.1` while [Mozilla add-ons](https://addons.mozilla.org/en-US/firefox/addon/lesspass/?src=search) has `v1.2.0`.

This Chrome version doesn't offer the `use my master password` feature in the login form.

![lesspass-chrome-version-different-from-firefox](https://cloud.githubusercontent.com/assets/1212392/20531085/e9068e72-b0d5-11e6-82fc-337489085ea3.png)

**Comment by guillaumevincent** [comment]
Fixed. I forgot to click on `publish` button.
