### ISSUE TITLE
How would you use Lesspass for Windows session authentication ?

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#101]
My use case : In my company we have to change every month our windows session password.

**Comment by guillaumevincent** [comment]
These rules make the passwords of their employees increasingly weak.
This is one of the completely absurd passwords rules encouraged by Microsoft.
If Microsoft can make stats on those passwords, I will bet that this GPO will disappear from all big companies.

Two ideas: 
 * use one LessPass password and add at the end an index like (year+month)
 * you can use LessPass connected version and increment index every month
 * Or you give up and you use the name of your dog plus an index and you put that on a post if under your screen. Nah, I'm joking.

**Comment by edouard-lopez** [comment]
While we were discussing the difficulty of using the LessPass for such scenario:

> compute on the mobile then type manually on the desktop.

It is possible but a bit tedious. 

### Dedicated app

A dedicated app on mobile phone would be better as we know the specific profile need for that. It would only require to type the _masterpassword_ and _counter_ (_username_ and other options might be fill at the first start of the app). The idea here is to reduce the number of information the user need to provide as it will need to type the generated password, which is the biggest hurdle.

An alternative would be to whisper the generated password to the user when he plug its earphone, so it reduce the cognitive load as user won't need to memorize the generated password but simply follow the voice. This improve workflow and privacy, without any additional cost!

### Lock screen widget

Even better a [widget on the lock screen](https://code.msdn.microsoft.com/windowsapps/Lock-screen-apps-sample-9843dc3a) reduce even more the friction

**Comment by guillaumevincent** [comment]
@edouard-lopez or use LessPass App on your phone like a physical keyboard. Click on the button to fill the password field on your computer.

So the question is not how to create a different password every month but how to log in on your computer.

**Comment by guillaumevincent** [comment]
@delphine-graeff I close this one,

For now  there is three solutions:
- every month you increase counter of this password profile and save it in LessPass Database
you open your phone, generate password and copy manually on your computer.
- you open your phone, generate password and copy manually on your computer and add current month at the end 
- talk to your boss to introduce SSO with physical dongles. Forcing password change every month is not a good idea

**Comment by guillaumevincent** [comment]
If you need some white paper to encourage your SI to change: https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-verifiers
