### ISSUE TITLE
fr: Cliquer sur l'icone disquette ne fait rien 

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#102]
> Plus pour information qu'un réel problème :  Sur le site des impots les carctères spéciaux autorisés sont les suivants: `! # $ % & * + - / = ? ^_ '. { | }`. Étant donné que le mot de passe généré comportait un le caractère "`:`" (deux points), j'ai du décocher la case "caractères spéciaux".
> 
> **Issue LessPass** qui a suivi cette manip : J'avais déjà sauvegardé le profil avant de tester le mot de passe (et me rendre compte que le "`:`" ne passait pas). Du coup j'ai du écraser mon profil une fois la case "caractères spéciaux" décochée. Sauf que la BUG: **la disquette apparait mais je ne peux pas cliquer dessus pour écraser le profil** (je clique sur la disquette et rien ne se passe). 
>
> Pour écraser mon profil j'ai du cliquer sur la page des profils, sélectionner un profil, le modifier puis l'écraser.

**Comment by guillaumevincent** [comment]
corrigé en version 2
