### ISSUE TITLE
fr: impossible de sauvegader deux profils d'affilé sur un même domaine

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#103]
follows #102 

> Issue Lesspass : Même problème si l'on souhaite **sauvegader deux profils d'affilée sur un même domaine** (par exemple si on a deux compte sur le même site) la disquette ne veut pas réapparaitre pour sauvegarder le nouveau profil. 
> 
> Obligé de quitter l'interface d'une façon ou d'une autre et d'y revenir.

**Comment by guillaumevincent** [comment]
corrigé en version 2
