### ISSUE TITLE
fr: Suppression du mauvais profil par manque de feedback

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#104]
> gros problème de comportement des boutons à la suppression d'un profil. Scénario: 
> 1. Je fais un click rapide sur la poubelle. Le bouton se transforme en _`Long press to confirm`_. 
> 1. Je fais un long press sans bouger mon curseur. 
>
> **problème:** Une fois la suppression effectuée le bouton _`Long press to confirm`_ reste en place. Mon profil a bien été supprimé mais je n'ai **eu aucun feedback sur la suppression de mon profil...** 
>
> Je pense du coup que je n'ai pas cliqué assez longtemps. D'ou la présence du bouton _`Long press to confirm`_ Du coup je **refais un click long... et là j'ai supprimé le profil suivant** que je ne voulais absolument pas supprimer..
>

**Comment by guillaumevincent** [comment]
Long press to confirm a disparu en version 2
![screenshot from 2016-11-23 17-35-02](https://cloud.githubusercontent.com/assets/943762/20570259/3598af04-b1a3-11e6-9cc6-2753839e0c14.png)

**Comment by edouard-lopez** [comment]
ping @delphine-graeff

@guillaumevincent when deleting a profile we should give a visual feedback of the active profile so it stand out. This will provide a better experience of the item removal (currently all item look alike so no real difference when active profile is removed).
