### ISSUE TITLE
Indeed, there is no need to use username&password in the meantime.

### ISSUE THREAD

**Issue by zpfsqzyl** [lesspass/lesspass#106]
😂I have a similar product as yours: kpass.tk  , and  I think there is no need to use username&password at the same time, only a master password is enough.
But all in all, good work you have done!

**Comment by philip-ulrich** [comment]
If you don't understand why they are there, you might want to look into this project a little more. It's quite a lot different than yours. Many discerning features.

**Comment by guillaumevincent** [comment]
hello @zpfsqzyl 
maybe you want to generate different passwords for the same site. For this you need a login field.
I close
