### ISSUE TITLE
Checkboxes miss tick marks (Firefox Ubuntu)

### ISSUE THREAD

**Issue by Prinzhorn** [lesspass/lesspass#107]
![screenshot from 2016-11-28 07-45-59](https://cloud.githubusercontent.com/assets/679144/20658665/bf35bd80-b53e-11e6-90b3-791befbf8a79.png)

**Comment by guillaumevincent** [comment]
@Prinzhorn This is a known v4 bootstrap bug
We use bootstrap v4 alpha. This will be corrected in alpha version 6.

Thank you btw for your feedback, we love that !
