### ISSUE TITLE
Revealing password / can't manually select/copy password

### ISSUE THREAD

**Issue by Prinzhorn** [lesspass/lesspass#108]
I know that there is a dedicated button to copy the password to the clipboard, but that's not an excuse to break the default behavior. Clicking the input currently toggles it's type between text and password. This breaks:

1. Double clicking the input to select all text (I'm training to double click and ctrl+c)
2. Dragging left/right to select the password

Revealing the master password and the generated password should both use a dedicated button. Consistency is key and you're currently using two completely different patterns for the same thing on two adjacent input elements.

**Comment by guillaumevincent** [comment]
Yes this is definitively a bug, I will fix this with a eye button

**Comment by edouard-lopez** [comment]
We can try this approach, but might get an icon overload:

![](http://uxmovement.com/wp-content/uploads/2015/08/eye-icon-toggle.png)

Also, we need to be more consistent with the color of the generated input.
