### ISSUE TITLE
Resetting Password with Master Password

### ISSUE THREAD

**Issue by nashley** [lesspass/lesspass#110]
I recently reset the password for my lesspass database account, and I realized that there's no way to use your master password (i.e., have lesspass generate a password for itself based on your master password) like there is in the browser extension.
Adding this functionality to the web interface's password reset page would be nice.

**Comment by benrubson** [comment]
@guillaumevincent, what kind of operation is done on the given master password when we tick `Check me if you want to use your master password here` ?
A `sha256` which is then sent to lesspass.com as the password to use ?

**Comment by guillaumevincent** [comment]
@benrubson we generate LessPass password with the master password and default password profile for LessPass: https://github.com/lesspass/pure/blob/master/src/views/Login.vue#L252-L285

Then the master password is replaced by the generated password (https://github.com/lesspass/pure/blob/master/src/views/Login.vue#L284). Like this your master password is never sent on LessPass server.

**Comment by benrubson** [comment]
OK, it simply uses the default LessPass rules :)
Perfect, understood, many thanks 👍

**Comment by guillaumevincent** [comment]
@edouard-lopez the feature is for the reset password page ;)

**Comment by guillaumevincent** [comment]
![screen shot 2017-05-20 at 12 45 32](https://cloud.githubusercontent.com/assets/943762/26275141/3b9eca62-3d5a-11e7-96fc-b7badc04c999.png)

The encrypt password feature is now present on reset password page
