### ISSUE TITLE
Firefox extension still in 1.2.0

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#111]
I guess it's due to Mozilla review process, but can you confirm the status?

**Comment by guillaumevincent** [comment]
@edouard-lopez yes 
![screenshot from 2016-11-28 22-42-29](https://cloud.githubusercontent.com/assets/943762/20687236/fae24a6a-b5bb-11e6-9a92-0f96a5a73c42.png)

the process from Mozilla takes around 7 days
