### ISSUE TITLE
Is there a way to get the v2 as default for now?

### ISSUE THREAD

**Issue by jajajaime** [lesspass/lesspass#116]
For when the webpage or browser extension is open.

**Comment by guillaumevincent** [comment]
@jajajaime when Mozilla will accept the web extension!
Mozilla addon validation process is crap

Chrome web extension and web site allow to save options.
And Firefox with web extension version 2.1.0 will come with this functionnality.

![image](https://cloud.githubusercontent.com/assets/943762/20798173/33475b60-b7de-11e6-9057-f1877b7962bd.png)

**Comment by jajajaime** [comment]
I dunno if you understood me, but what I´m saying is that when I click the icon, v1 is the one that always opens, instead of v2. Since I already changed all my password to v2, is there a way to have it open on v2 and have to press the button to go to v1, instead of the other way around?

**Comment by guillaumevincent** [comment]
@jajajaime

when you open LessPass: 

![image](https://cloud.githubusercontent.com/assets/943762/20828204/98463a16-b876-11e6-9423-c4aff106ba48.png)

you click on v2:
![image](https://cloud.githubusercontent.com/assets/943762/20828224/bf72116e-b876-11e6-9b30-c69077948df2.png)

then you click on option and `save as default`:
![image](https://cloud.githubusercontent.com/assets/943762/20828245/e77cd216-b876-11e6-8aa4-72a78a0ca84e.png)

If you restart LessPass, you will be on v2 no ?

**Comment by jajajaime** [comment]
Thanks. That's exactly what I was looking for! I thought that was only for the character options.

Keep up the good work!

**Comment by guillaumevincent** [comment]
maybe we can improve this with a button tooltip "save current password profile as default" ?
