### ISSUE TITLE
[bug] extension invisible in firefox

### ISSUE THREAD

**Issue by sg-s** [lesspass/lesspass#120]
i've installed the lesspass extension on firefox:

<img width="1366" alt="screen shot 2016-12-02 at 16 40 17" src="https://cloud.githubusercontent.com/assets/6005346/20851354/0c16d4d2-b8ae-11e6-8815-41ae86bc1ad5.png">

but I don't see it anywhere:

<img width="306" alt="screen shot 2016-12-02 at 16 40 56" src="https://cloud.githubusercontent.com/assets/6005346/20851381/1fcb57be-b8ae-11e6-9301-c08005fbd6c9.png">

It used to work fine for the v1 plugin. Help!

running firefox 50.0.2 on macOS Sierra.

**Comment by sg-s** [comment]
nevermind. i was stupid

**Comment by guillaumevincent** [comment]
What happens ? To many add-ons and LessPass was in the dropdown menu ?

**Comment by sg-s** [comment]
yup, firefox was hiding the button and I had to click on "customise" to find it.
