### ISSUE TITLE
Colors theme is Ambiguous between V2/V1 addons, since V2 Update

### ISSUE THREAD

**Issue by sctfic** [lesspass/lesspass#121]
in V1 the Addon color theme is Blue

Now, on V2/V1 Addons the blue Theme is for the V2 and the V1 change to Orange ! Why ? it is not intuitive...

**Comment by sctfic** [comment]
le bouton en bas de l'addon [V1] est une indication pas une action, or un bouton sert a faire une action.
indique plutôt la version dans le titre, et change le bouton du bas en : [Switch to V2] ca sera probablement plus clair pour les utilisateur externe au projet

**Comment by edouard-lopez** [comment]
Je suis d'accord c'est perturbant, et la fin de support de la v1 va nous demander de refaire le changement. 

@guillaumevincent on devrait basculer la v2/bleue comme version par défaut.

**Comment by guillaumevincent** [comment]
@edouard-lopez on january 10th
