### ISSUE TITLE
Use toggle button for version

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#122]
Current component is really ambiguous as it look like a label in box, a button or an input. 

Most of all, it **lacks the fordance of its function: changing version.**

### Wireframe 

An improvement would be to use a `toggle button` that shows current state.

| component | ui |
| -- | -- 
| ![version-toggle](https://cloud.githubusercontent.com/assets/1212392/21044675/70159564-bdfd-11e6-97d0-a7377afb5013.jpg) | ![version-toggle-button](https://cloud.githubusercontent.com/assets/1212392/21044750/c0498c52-bdfd-11e6-88ea-8ad42ff2a2e8.jpg)

There is plenty of idea on [dribble.com](https://dribbble.com/search?q=toggle+button).

**related to:** discussion on #121

**Comment by guillaumevincent** [comment]
![toggle](https://cloud.githubusercontent.com/assets/943762/21045585/4dcdc7e8-be01-11e6-87e9-e684a9aa81a0.png)

**Comment by edouard-lopez** [comment]
I like the rounded style but will it fits with current UI (squarish)?

**Comment by guillaumevincent** [comment]
yes it was just for an example of version toggle. 
Building a toggle in javascript and css is not easy.

@abe33 Do you have in your pocket somewhere an open source component that does that? :relaxed:

**Comment by abe33** [comment]
I had made a codepen like that before, based on IOS 7  design, but it's easily customizable: http://codepen.io/abe33/pen/tjFvJ

The nice thing is that it only involve CSS.

**Comment by abe33** [comment]
Here's a simple version based on the current lesspass theme: http://codepen.io/abe33/pen/zoLGNr

**Comment by edouard-lopez** [comment]
I made the UI [focusable](http://webaim.org/techniques/css/invisiblecontent/) and add a discrete shadow on the side of the button: http://codepen.io/edouard-lopez/pen/rWrVQM?editors=1100

| state | screenshot 
| -- | --
![selection_034](https://cloud.githubusercontent.com/assets/1212392/21051626/853fb608-be21-11e6-9733-bc379a248079.png) | original
![selection_032](https://cloud.githubusercontent.com/assets/1212392/21051558/275480a0-be21-11e6-9243-6cb378b1e9d3.png) | discrete shadow
![selection_033](https://cloud.githubusercontent.com/assets/1212392/21051585/4523dfb8-be21-11e6-9358-13870d9eae87.png) | focus (increase border)

### Alternative
| state | screenshot 
| -- | --
![selection_035](https://cloud.githubusercontent.com/assets/1212392/21051671/bbad1a1e-be21-11e6-89d5-f4d70644b468.png) | alternative focus (`dotted` border)
