### ISSUE TITLE
Do we need a copy button?

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#123]
| current workflow | comments
| -- | --
![do we need generate button](https://cloud.githubusercontent.com/assets/1212392/21046093/41a81d54-be03-11e6-8ac5-369073d09d1a.jpg) | current workflow might be simplified in order to reduce errors and streamline the process.

### Currently

![do we need generate button old](https://cloud.githubusercontent.com/assets/1212392/21046144/80eea172-be03-11e6-932a-f19be53e2a5a.jpg)

Currently we need to:
1. click `generate` button ;
2. click `copy` ;
3. click :eye:.

The `copy` button being narrower than the `generate` one, I always click into the input field instead of the button. Thus requiring an extra click due to the error.

### Proposal

Removing the copy step by auto-copying would reduce error rate. It is acceptable to do so as ① the user came for this specific purpose (getting its password), ② there is a timeout that clear the field.

![do we need generate button propal](https://cloud.githubusercontent.com/assets/1212392/21046143/80c273fe-be03-11e6-8517-3fd38db5cc66.jpg)

**Comment by guillaumevincent** [comment]
Yeah, the only problem I get is how to copy the generated password.
I will add a jsfiddle to show the clipboard paradox in html5

**Comment by guillaumevincent** [comment]
Maybe we can fix this one after this pull request being merged: https://github.com/zenorocha/clipboard.js/pull/338

**Comment by benrubson** [comment]
And add a last step to clear the clipboard after X seconds if password still in the clipboard ?
Not sure however if JS can access the clipboard content...

**Comment by tpruzina** [comment]
I think it's mostly about PBKGFv2 being slow, if you generated a new password automagically after each character input then you would do a lot of useless generation.

**Comment by guillaumevincent** [comment]
The only reason why we use a generate button is because clipboard don't handle promise. When the feature will be implemented, we will remove the "generate password" button and add a simple copy button. It will generate a password and copy it to clipboard.

**Comment by edouard-lopez** [comment]
So closing for now. Let's re-open it when `clipboardjs` had the feature.
