### ISSUE TITLE
Your opinion on the new api of lesspass-cli

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#124]
I created a lesspass-cli version 4 with a new API. Can I have you opinion about it ?

```
$ lesspass --help

  build LessPass passwords directly in command line

  Usage
    $ lesspass <site> <login> [masterPassword] [options] 

  Options
      -l                  add lowercase in password
      -u                  add uppercase in password
      -d                  add digits in password
      -s                  add symbols in password

      --no-lowercase      remove lowercase from password
      --no-uppercase      remove uppercase from password
      --no-digits         remove digits from password
      --no-symbols        remove symbols from password

      --length, -L        int (default 16)
      --counter, -c       int (default 1)
    
      --clipboard, -C     copy generated password to clipboard rather than displaying it.
                          Need pbcopy (OSX), xclip (Linux) or clip (Windows).

  Examples
    # no symbols
    $ lesspass lesspass.com contact@lesspass.com password --no-symbols 
    OlfK63bmUhqrGODR
  
    # no symbols shortcut
    $ lesspass lesspass.com contact@lesspass.com password -lud
    OlfK63bmUhqrGODR
  
    # only digits and length of 8
    $ lesspass lesspass.com contact@lesspass.com  -d -L8
      master password: 
      75837019
```

There is some breaking changes with the version 2 :

* By default, all character sets are enabled ;
* `-l=false` become `--no-lowercase`;
* `-l=true` doesn't work anymore, you can just remove this option in your use ;
* `-l` add only lowercase  ;
* `--numbers` or `-n` doesn't work and are replace by `--no-digits`.

cc @trygveaa @oscarsaleta @sctfic @edouard-lopez

**Comment by oscarsaleta** [comment]
LGTM!

**Comment by sctfic** [comment]
test sur window 2012 en Powershell 3.0

MAJ ok
commandes standand OK (sauf les caractères '<' et '>' )
commandes avancée (switch) OK

Merci ;-)

PS C:\Users\alopez> npm install --global lesspass-cli
[XXXX..............] / fetchMetadata: sill mapToRegistry uri
https://registry.npmjs.org/meow

`-- lesspass-cli@3.0.0
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.0.0
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- copy-paste@1.3.0
  | +-- iconv-lite@0.4.15
  | `-- sync-exec@0.6.2
  +-- lesspass@6.0.0
  | +-- big-integer@1.6.17
  | +-- create-hmac@1.1.4
  | | +-- create-hash@1.1.2
  | | | +-- cipher-base@1.0.3
  | | | +-- ripemd160@1.0.1
  | | | `-- sha.js@2.4.8
  | | `-- inherits@2.0.3
  | +-- pbkdf2@3.0.9
  | `-- unibabel@2.1.3
  `-- meow@3.7.0
    +-- loud-rejection@1.6.0
    | `-- signal-exit@3.0.2
    `-- read-pkg-up@1.0.1
      `-- read-pkg@1.1.0
        `-- load-json-file@1.1.0
          `-- graceful-fs@4.1.11



--
[image: Probe-meteo.com] <http://probe-meteo.com/dashboard/global/VP2_GTD>
Alb@n LOPEZ
address: Gontaud, france
<https://www.google.fr/maps/place/Gontaud-de-Nogaret/@44.4597865,0.2503817,13z/data=!3m1!4b1!4m2!3m1!1s0x12aa8b41549f4cd3:0x40665174815b520>
mobile: +33 6 51 81 81 24 <+33+6+51+81+81+24>
phone: +33 9 70 96 83 54 <+33+9+52+58+40+23>
social: [image: GitLab Perso]
<http://git.edouard-lopez.com:81/groups/PowerTech>[image: stackoverflow]
<http://stackoverflow.com/users/1911082/alban>

**Comment by edouard-lopez** [comment]
Man page use bracket for optional arguments and just the name for the mandatory ones. So it should be:

    $ lesspass [options] site login

cc @oscarsaleta

**Comment by oscarsaleta** [comment]
@edouard-lopez You are absolutely right, thanks for pointing that out.

**Comment by guillaumevincent** [comment]
Thank you for your feedback, I updated lesspass-cli to version 4.0.0 with 4 shortcuts positives (`-luds`) and change the usage line
