### ISSUE TITLE
Could not resolve host when running sh script.

### ISSUE THREAD

**Issue by thebetterjort** [lesspass/lesspass#125]
0curl: (6) Could not resolve host: docker-compose.yml

ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by guillaumevincent** [comment]
this is strange, what do you type in your terminal ?

    bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/lesspass.sh)

What is your OS ?
Which terminal do you use ? If bash can you type `bash --version` ?

**Comment by thebetterjort** [comment]
I think its related to my self signed security certificate.
I'm behind a corporate proxy.

**Comment by guillaumevincent** [comment]
I tested my script at my place and it works.

Don't know how your proxy is configured, but here the manual installation: 

 * create LessPass directory: `mkdir LessPass`
 * move inside LessPass directory: `cd LessPass`
 * download [docker-compose.prod.yml](https://raw.githubusercontent.com/lesspass/lesspass/master/docker-compose.prod.yml)
 * rename `docker-compose.prod.yml` into docker-compose.yml
 * create a `lesspass.sh` script with the following content:

```
#!/usr/bin/env bash

DATABASE_PASSWORD=$(LC_ALL=C tr -dc A-Za-z0-9_ </dev/urandom | head -c 32)
SECRET_KEY=$(LC_ALL=C tr -dc A-Za-z0-9_ </dev/urandom | head -c 32)

echo "Please enter your domain name: "
read DOMAIN

# create env file
cat >> .env << EOF
ALLOWED_HOSTS=.$DOMAIN
DATABASE_PASSWORD=$DATABASE_PASSWORD
SECRET_KEY=$SECRET_KEY
DOMAIN=$DOMAIN
EOF

# pull new images
docker-compose pull

# restart container
docker-compose down
docker-compose up -d
```

 * run `lesspass.sh` script

Feel free to ask some help if it doesn't work.
