### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by benrubson** [lesspass/lesspass#126]
Hello,

Do you think it would be a good idea to create a Safari extension ?
Would be nice for Mac users !

Thank you very much for your work 👍 

Ben

**Comment by guillaumevincent** [comment]
For now Safari extension cost 99$ per year (Apple Developer Program) and I do not have a mac to test.
Moreover Safari does not implement webcrypto and therefore is very slow to generate password (100k pbkdf2 iterations)

For the moment we have not planned to develop an extension for Safari.

**Comment by benrubson** [comment]
OK Guillaume, let's then wait for webcrypto support (#127) first 👍

**Comment by edouard-lopez** [comment]
Safari now support webcrypto [since version `11` (sept. 2017)](https://caniuse.com/#search=cryptograp) :tada: 

![selection_105](https://user-images.githubusercontent.com/1212392/31675101-f22bedb2-b363-11e7-9acc-b4803a652a75.png)
