### ISSUE TITLE
Safari performance issue

### ISSUE THREAD

**Issue by benrubson** [lesspass/lesspass#127]
Hello,

On a Mac OS 10.11 machine, Safari 10.0.2.
It takes around 6 or 7 seconds to generate a V2 password, whereas it only takes around 100ms with Chrome & Firefox on the same machine.

A Safari issue ?

Many thanks 👍 

Ben

**Comment by benrubson** [comment]
In addition, I clearly see that during password generation, Safari lesspass.com page takes all the CPU.

**Comment by benrubson** [comment]
Strangely there is no performance issue with the `pure-latest` version run locally.

**Comment by guillaumevincent** [comment]
@benrubson We use webcrypto to generate password and fallback to javascript polyfill when webcrypto is not available. For now Safari doesn't implement webcrypto.

It is a compromise between safety and usability. When Safari will implement webcrypto, it will be ok

**Comment by benrubson** [comment]
Thanks Guillaume !

**Comment by benrubson** [comment]
After some more investigation regarding webcrypto & Safari, Safari Technology Preview should support it with sha256, as [this bug](https://bugs.webkit.org/show_bug.cgi?id=151308) has been solved.
Waiting for all this stuff to come into regular Safari version then...

**Comment by guillaumevincent** [comment]
@benrubson yes but this one is not: https://github.com/diafygi/webcrypto-examples/issues/27

**Comment by benrubson** [comment]
Yep but should now work, at least with Safari Technology Preview, as we can see in [the commit](https://trac.webkit.org/changeset/208548) related to [this bug](https://bugs.webkit.org/show_bug.cgi?id=151308) :
`It implements importKey operations of following algorithms: AES-CBC, AES-KW, HMAC, RSAES-PKCS1-V1_5, RSASSA-PKCS1-V1_5, and RSA-OAEP.`
And that 256/512 keys are now supported.

**Comment by guillaumevincent** [comment]
Good news :)
Feel free to ping us when Safari push this feature into production
