### ISSUE TITLE
Allow blank Login field

### ISSUE THREAD

**Issue by benrubson** [lesspass/lesspass#128]
Hello,

What about allowing a blank `Login` field ?
This would allow to compute passwords for things which do not need a login, such as SSH keys, certificates, some devices without username...

Thank you 👍 

Ben

**Comment by guillaumevincent** [comment]
@benrubson it will reduce the entropy of the generated password. But yes we can remove this protection

**Comment by benrubson** [comment]
As you just concat `Site`+`Login`, we will just have to choose a long enough `Site` for `Login`-less computation, so that entropy is good enough :)
Am I right ?

And thank you for your help on this 👍

**Comment by guillaumevincent** [comment]
If I got your generated password for `adobe.com` when database leak, I know that your site is `adobe.com`. 
Because people use web extension, site is autofill.
For cli this is different. And yes `site+login` are concatenated

**Comment by benrubson** [comment]
Leaving `Login` empty is not intended to be used with web accounts, but with things such as SSH keys passphrase (you just then only put the "name" of the key in `Site`), SSL certificates passphrase (once again, you just use for example the certificate name (or fingerprint) in `Site`) etc...
It allows to use LessPass for other things than just web accounts :)

**Comment by guillaumevincent** [comment]
@benrubson Do you use lesspass-cli for this ? I can update the API easily

**Comment by benrubson** [comment]
I had a look at lesspass-cli but as I may require the connected version, I kept the pure version :)

**Comment by benrubson** [comment]
Many thx 👍
