### ISSUE TITLE
Scrollbars in Firefox addon

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#129]
On Firefox 52, I get scrollbars when displaying the options:
![lesspass firefox](https://cloud.githubusercontent.com/assets/840125/21287916/58bce578-c476-11e6-91ab-36a8d17a546f.png)

**Comment by guillaumevincent** [comment]
hum, this is ugly :)
thanks I will fix this

**Comment by guillaumevincent** [comment]
@Rudloff Does ctrl+shift+L works on Firefox 52 ?

**Comment by Rudloff** [comment]
Yes 😄

**Comment by guillaumevincent** [comment]
nice :) thanks
