### ISSUE TITLE
Self-Hosted Layout Messed Up After Recent Commits (see screenshot)

### ISSUE THREAD

**Issue by philip-ulrich** [lesspass/lesspass#130]
Hey guys,

It looks like the latest commit(s) have broken the self-hosted version.. See screenshot below:

![screenshot](http://i.exec.tech/9945/4RrcVNq3.png)

This is hosted at https://pass.z3r0.tech/ if you want to review the HTML that it is returning.

I have attempted to remove the docker containers, images, and re-pull... but it returns the same. The only thing non-stock that I have is that I have removed the nginx container, replaced it with my own local nginx and assigned static ips to the containers. I doubt this will prove to be an issue, but might as well disclose it.

- Phil

**Comment by guillaumevincent** [comment]
Hi Phil, thank you for posting this.
I will look at this one as soon as I can. But during Christmas holidays I don't have a lot of time. I can't use my computer. 

I will :

 - use the pure component instead of the site for the hosted version
 - add some render tests 

Thank you

**Comment by philip-ulrich** [comment]
No worries. I totally understand. Thanks for your attention to this issue.

**Comment by philip-ulrich** [comment]
Correct me if I am wrong, but this appears to be fixed so I will close this issue

**Comment by guillaumevincent** [comment]
@philip-ulrich nop you're right, one commit message should have close this one automatically. don't know why github didn't close it. Thank you
