### ISSUE TITLE
Still Get Warnings Even Though Using All v2

### ISSUE THREAD

**Issue by philip-ulrich** [lesspass/lesspass#132]
I have migrated all my passwords to v2, but I am still getting the warning:

```You are using a deprecated version of LessPass. The default version will be version 2 in 40 days. You can continue to use version 1, but we strongly advise you to migrate your passwords to version 2.```

When I logged into the connected version (having selected v2), initially it will be blue and show no warning. On a refresh, it goes back to v1 as default. This seems to go back to a real persistence issue that happens with this. When changing the self-hosted url and logging in, I would expect it to remember that I want to use my self hosted URL. This is not the case. I also would expect that when I am not using any v1 any longer, that I would not get that warning and not be defaulted to using v1. This is also not the case. I think it would be wise to store some user variables both in cookies and in the self-hosted database; whichever is appropriate (obviously the self hosted URL can't be in the database, whereas the default settings for your user would be).

**Comment by philip-ulrich** [comment]
I noticed that this is somewhat addressed in issue 116. The defaults really should be store on the remote storage though and not just locally (or maybe both?). The entire fact that this is a very fluid application that is being accessed from multiple locations makes the setting of a default on every location very painful.

**Comment by guillaumevincent** [comment]
@philip-ulrich in one month, the default will be version 2.
Every password profiles save the version number.

And default should be save on remote. You're right. There is an issue for this one: https://github.com/lesspass/lesspass/issues/71

I close this one.
