### ISSUE TITLE
Infinite loop when Lenth <= 4

### ISSUE THREAD

**Issue by mesjetiu** [lesspass/lesspass#133]
If the field "Length" has a value 4 or less, password generation does not stop. It seems to enter in an Infinite loop. 
I confirm this behavior in web and Android app.

**Comment by guillaumevincent** [comment]
Android App and every LessPass "app" use the same component.
So If the bug exists in one place, it exists everywhere.

Thank you for reporting this issue

**Comment by mesjetiu** [comment]
Also this problem remains if Lenth has as value a negative number or 0: generation never stops.
I think it should be checked that a positive value is entered, since 0 or negative value as Lenth makes no sense.
