### ISSUE TITLE
Interface Annoyances

### ISSUE THREAD

**Issue by tatums** [lesspass/lesspass#134]
First off, Great work! I really like this project and I hope it will keep improving. I do however have a couple of UI annoyances with Chrome Extension I want to share. 

1. When I login to my master account (via lasspass server).  I type out my username/password and I expect the [ENTER/Return] key to submit the form.  BUT it doesn't :(   I have to click the "Sign In" button.

2. When I'm generating a new password for a client site. My instincts are to generate the password then immediacy switch to the client site to enter and confirm.  I then want to return to the Chrome extension to SAVE.  But everything is lost and I have to re-create the steps and then save.  This can be error prone. Now, I realize I **could** first save in the Chrome Extension and then update the client site. But that it's not my natural instinct and Im guessing others have experienced this annoyance.  Perhaps the copy password button could have additional options (eg copy and save).

Thanks for listening and again, great project!

**Comment by guillaumevincent** [comment]
@tatums those two annoyances are real and will be fixed in the following weeks.
I will close this one and create 2 issues for every points.

Thank you for your feedback, much appreciate
