### ISSUE TITLE
Save last profile in local storage instead of removing it

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#136]
split https://github.com/lesspass/lesspass/issues/134

> When I'm generating a new password for a client site. My instincts are to generate the password then immediacy switch to the client site to enter and confirm. I then want to return to the Chrome extension to SAVE. But everything is lost and I have to re-create the steps and then save. This can be error prone. Now, I realize I could first save in the Chrome Extension and then update the client site. But that it's not my natural instinct and Im guessing others have experienced this annoyance. Perhaps the copy password button could have additional options (eg copy and save).

**Comment by guillaumevincent** [comment]
@tatums maybe we should not delete the password profile and save it on local storage. When user open web extension again, it reuse the last password profile.

It will allow user to save password profile on LessPass Database.

What do you think ?

**Comment by tatums** [comment]
Yep, that would solve my pain point. 👍

**Comment by edouard-lopez** [comment]
@guillaumevincent so when we go back to the extension we still need to type the master password to generate the password?

**Comment by guillaumevincent** [comment]
@edouard-lopez yes, we try hard not to save user master password. Even on local storage, browser passwords, encrypted on LessPass database. 

Your master password is in your head.
And yes you need to enter your master password everytime you use LessPass.

**Comment by guillaumevincent** [comment]
ping @edouard-lopez @tatums
I need your feedback

How long do we have to wait before the application loads the default profile instead of the last profile?

**Comment by tatums** [comment]
@guillaumevincent IMO somewhere between 30-60 seconds be enough.

**Comment by guillaumevincent** [comment]
ok I will put 1 min
