### ISSUE TITLE
Is there someway for the lesspass extention to automatically populate the "Login" field?

### ISSUE THREAD

**Issue by sg-s** [lesspass/lesspass#137]
it's a pain to type my username twice -- once on the webpage, and once again into the lesspass extension. 

is it possible to make the lesspass extension "read" the webpage, figure out what the username input box is, and read data from there?

**Comment by guillaumevincent** [comment]
@sg-s for this feature webextension should load a javascript file on every webpage you visit even if you don't open the extension. 

I don't like this (for security reason).
When webextension will load javascript file on client side when the user click on the extension icon, we will look at those kind of features.

For now I close

**Comment by sg-s** [comment]
hi @guillaumevincent  thanks for the response.

> for this feature webextension should load a javascript file on every webpage you visit even if you don't open the extension.

no-- there is another way. what if, when you click on the extension, it then loads a js file and reads the page? nothing would happen if you don't click on the extension

**Comment by guillaumevincent** [comment]
@sg-s you can't inject a javascript on a page 
https://developer.chrome.com/extensions/content_scripts
content_scripts should be defined before and are injected on every page defined in permissions field in manisfest.json

This is one of some missing feature in web extension: load a script on the page only when user open de extension.

**Comment by sg-s** [comment]
thanks for the reply; that's a shame!

**Comment by guillaumevincent** [comment]
trully yes
