### ISSUE TITLE
Length and count button are lacking visual feedback

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#138]
In the options there is no change of the button state when clicking them. I had to click several to realize the value had changed.

![selection_047](https://cloud.githubusercontent.com/assets/1212392/21682054/b798eb60-d352-11e6-9be7-1c74973f7309.png)

**Comment by guillaumevincent** [comment]
Fixed in version 4.3.0

![image](https://cloud.githubusercontent.com/assets/943762/21764512/cfecb494-d663-11e6-806d-4785788e5027.png)
