### ISSUE TITLE
Remove Comodo and use Let's Encrypt

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#14]
_From @guillaumevincent on July 11, 2016 12:32_

Because Comodo try to register at least three trademarks for the term “Let’s Encrypt,” for a variety of CA-related services, we need to stop using their services : 

https://letsencrypt.org/2016/06/23/defending-our-brand.html

_Copied from original issue: lesspass/nginx#1_

**Comment by guillaumevincent** [comment]
I started working on this one using `http://traefik.io/`
Hope I can replace the Comodo certificate soon

**Comment by deurk** [comment]
Let me know if I can help.

**Comment by guillaumevincent** [comment]
@deurk if you have some time maybe try to find a similar project (docker-compose app) installing or refreshing a certificate at startup.

traefik is too intrusive

**Comment by guillaumevincent** [comment]
I need to do more tests, but normaly running the following command will install LessPass Database with a valid SSL certificate:

    bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/letsencrypt.sh) [DOMAIN] [EMAIL]

**Comment by deurk** [comment]
Will test right now

**Comment by deurk** [comment]
Worked like a charm for me.

One warning during the install:
> WARNING: Network lesspass_default not found.

Created a super-user and can access the `/admin` URL.

Nice work, thanks a lot! This will probably help the popularity of the app now that a proper secured self-hosted deployment is possible with a one-liner!

**Comment by guillaumevincent** [comment]
Thanks for the tests
I have an issue with dhparam file on centos

The warning is normal when you start the app the first time

**Comment by deurk** [comment]
FYI: my tests were run on a Docker ImageHub from Scaleway.

On Sat, Jul 29, 2017 at 3:04 PM, Guillaume Vincent <notifications@github.com

**Comment by guillaumevincent** [comment]
my problem was a problem with my firewall
