### ISSUE TITLE
No profile suggestion in extension on Firefox when connected

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#140]
### Reproduce
1. In Firefox (`50.1.0`) ;
1. Open Lesspass extension ;
1. Login with credentials ;
1. Back to main interface ;
1. Type something.

### Expected

* List of saved profiles are displayed
![selection_051](https://cloud.githubusercontent.com/assets/1212392/21884429/8ddb69d6-d8b3-11e6-9759-26dc672e5c32.png)

### Result

* break on Firefox extension
![selection_052](https://cloud.githubusercontent.com/assets/1212392/21884591/44f1739a-d8b4-11e6-924f-cc03dffae4b6.png)

* works in:
  * Chrome extension and webpage
  * Firefox webpage

**Comment by guillaumevincent** [comment]
use http://leaverou.github.io/awesomplete/ from @LeaVerou and remove datalist for now

**Comment by guillaumevincent** [comment]
We got the same error with awesomplete too, reopen

**Comment by guillaumevincent** [comment]
Fix by https://github.com/lesspass/pure/commit/6523044754aa5ded017ea75d096ff20b1dcf66a5
Will be in Firefox extension version 2.3.2
