### ISSUE TITLE
Add parameters to the url of lesspass.com 

### ISSUE THREAD

**Issue by Johjo** [lesspass/lesspass#142]
The idea is to fill the fields with parameters present in the url. In this way, it will be easy to bookmarks and to share passwords to other people (team, customer, family, friends, etc...)

An example of url :
https://lesspass.com/#/?site=example.com&login=Johjo&abc=True&ABC=False&123=True&symbol=False&length=5&counter=17&version=2

Each parameters must be present in case of a change of the default parameters.

A link with the parameters must be generated when the fields are filled manually.

**Comment by guillaumevincent** [comment]
![screen shot 2017-02-03 at 11 19 05](https://cloud.githubusercontent.com/assets/943762/22587600/98d0830c-ea02-11e6-967b-6ff1253cb6a1.png)

The feature will be in the next release

**Comment by guillaumevincent** [comment]
the url follow the common API for LessPass:

https://lesspass.com/#/?login=contact@lesspass.com&site=lesspass.com&uppercase=true&lowercase=true&numbers=true&symbols=true&length=20&counter=3&version=2
