### ISSUE TITLE
Alternative input of master password

### ISSUE THREAD

**Issue by sctfic** [lesspass/lesspass#144]
Alternative input of masterPassword like select a fingerprint

en solution alternative au masterPasswod, j'imagine une solution similaire au site bancaire, un pave d'icone cliquable pour choisir le fingerPrint.

et ce fingerprint serai utilisé pour générer le LessPassword

**Comment by sctfic** [comment]
Comme la longueur du MasterPassword ne change rien au niveau de complexité du LessPassword, même un fingerPrint de 3 idéogramme suffit !

**Comment by guillaumevincent** [comment]
Quel problème on cherche à résoudre ?
La seule raison les sites bancaires mettent le login avec des numéros est d'éviter les keys loggers.

**Comment by edouard-lopez** [comment]
1. Ça serait une alternative au mot de passe texte ou un remplacement ?

**Comment by sctfic** [comment]
justement, je suis sur un poste que je ne connais pas et/ou qui semble douteux, comment ne pas compromettre mon MasterPassword qui est **_ULTRA critique_** avec ce type d'outil !

**Comment by guillaumevincent** [comment]
Sur un poste douteux tu n'utilises pas LessPass. Peut importe les techniques, un poste douteux peut enregistrer un flux vidéo, contenir un keylogger our une fausse application. Les icônes ne protège que contre les keyloggers et encore.

10 icônes (comme les chiffres d'une banque) ce n'est pas assez pour résister contre le Brutus Force. 

Seul la double authentification ou un mot de passe à usage unique offre une toute petite protection sur un poste corrompu. Mais LessPass à cause de son implémentation ne peut pas offrir ces 2 services.

Regarde ça http://security.stackexchange.com/questions/6272/how-can-i-avoid-my-password-being-harvested-by-key-loggers-from-internet-cafes

Je ferme

N'hésite pas à demander plus de précisions
