### ISSUE TITLE
FIDO U2F for multifactor auth?

### ISSUE THREAD

**Issue by cboettig** [lesspass/lesspass#145]
In addition to the master password, I'd love to see support for [FIDO U2F open authentication standard](https://developers.yubico.com/U2F/) protocol for 2 factor authentication (e.g. see https://developers.yubico.com/U2F/Libraries/List_of_libraries.html for libraries.)  Could this get on the roadmap?

**Comment by guillaumevincent** [comment]
@cboettig I always wanted to add a physical dongle with open hardware associated with LessPass. I did not know FIDO U2F before. I will look at it.

Thank you for this request

**Comment by guillaumevincent** [comment]
@cboettig we bought two FIDO U2F Security Key from Yubico to see if we can innovate in this area

**Comment by oncletom** [comment]
Especially as it's been standardised as [webauthn](https://www.w3.org/TR/webauthn/) 👍 ([ah npm](https://www.npmjs.com/search?q=webauthn))

**Comment by guillaumevincent** [comment]
Yes, you could imagine protecting your authentication to the LessPass Database with your key.
But we can imagine also using the key to generate your master password easily.

I admit this is an area where we need to experiment to see what is possible.

**Comment by JLarky** [comment]
@guillaumevincent you can probably use RSA keys like Neokey Pro to store master password or to encrypt the password :) you can also look into OpenKeychain Android app, you can even sign into ssh with it :) with [termbot](https://play.google.com/store/apps/details?id=org.sufficientlysecure.termbot)

**Comment by guillaumevincent** [comment]
I close this one for now
LessPass is developped during our free time. LessPass database don't save some sensitive information. We will probably never have some time for this one. Low priority
