### ISSUE TITLE
Can't fetch over 50 profiles

### ISSUE THREAD

**Issue by tsmd** [lesspass/lesspass#149]
Hi. LessPass is very good product! 😃 I decided to transfer all my passwords from 1Password to LessPass.
And I noticed that I can't fetch over 50 passwords at a time.

![image](https://cloud.githubusercontent.com/assets/490085/22864919/54afc6e0-f19d-11e6-9ace-6b581cdcf02b.png)

Is something wrong with my operations or is it unsupported yet?
I'm using LessPass with my own hosting.

---
Suppliment:
In response JSON, `count` prop is correctly indicates the number, but `results` contains only 50 items. and `next` url looks not to be called.

![image](https://cloud.githubusercontent.com/assets/490085/22865017/df25f99c-f19e-11e6-96ad-abaa819ec7a4.png)

**Comment by guillaumevincent** [comment]
@tsmd maybe because of this config: https://github.com/lesspass/backend/blob/master/lesspass/settings.py#L133

I will fix this one

**Comment by guillaumevincent** [comment]
There is no difference between Self hosted LessPass Database and https://lesspass.com.

**Comment by edouard-lopez** [comment]
@guillaumevincent There is a pagination on the frontend (5 items per page) and one at the backend level (50 items per page). So we need to either
* increase the `PAGE_SIZE` attribute to `100` or `1000`
* request the URL from `next`/`previous` field when reaching the end/start of the frontend page.

**Comment by guillaumevincent** [comment]
yes,
I will let a user create a Pull Request for this one.
He just need to change page `PAGE_SIZE` to 1000 in https://github.com/lesspass/backend/blob/master/lesspass/settings.py#L133

**Comment by panther2** [comment]
Thanks for the chance to contribute.

**Comment by guillaumevincent** [comment]
@panther2 thank you for you contribution ❤️
