### ISSUE TITLE
LessPass i18n

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#150]
I want translate LessPass in different languages (French and Spanish to start)
Add 👍 reaction if this is something you want too.

 * [x] add internationalization in https://github.com/lesspass/pure

translated

 * [x] [French](https://github.com/lesspass/pure/blob/master/src/i18n/fr.json)
 * [x] [Spanish](https://github.com/lesspass/pure/blob/master/src/i18n/es.json)
 * [x] [German](https://github.com/lesspass/pure/blob/master/src/i18n/de.json)
 * [x] [Chinese](https://github.com/lesspass/pure/blob/master/src/i18n/zh.json)

**Comment by mlcdf** [comment]
I'm not sure how to do this, but I would love to help you with that!

**Comment by sigerello** [comment]
I'm ready to make Ukrainian translation.

**Comment by turbogp20** [comment]
I'm echoing @mlcdf. Happy to help on this.

**Comment by edouard-lopez** [comment]
@hugolpz @cbyem40 wanna help for Chinese translation?

**Comment by panther2** [comment]
I'm happy to translate from English to German if wanted/needed :-)

What exactly do you intend to be translated?

**Comment by guillaumevincent** [comment]
@panther2 we are going to start the translation of the LessPass component for now https://github.com/lesspass/pure

**Comment by cbyem40** [comment]
@edouard-lopez Sure, count me in!

**Comment by panther2** [comment]
@guillaumevincent 
Just for my individual planning: When - approximately - are we expected to start?

**Comment by guillaumevincent** [comment]
@panther2 probably next week

**Comment by guillaumevincent** [comment]
I have working i18n plugin with some tests:

![screen shot 2017-03-22 at 19 07 28](https://cloud.githubusercontent.com/assets/943762/24213482/e514d9de-0f32-11e7-9735-4579a622e6fd.png)

I will push something tomorrow or on friday

**Comment by elopio** [comment]
spanish here.

**Comment by guillaumevincent** [comment]
Hello,
I integrate [Vue-Polyglot](https://github.com/guillaumevincent/vue-polyglot), so you can translate and/or review translation files:

translated

 * [x] [French](https://github.com/lesspass/pure/blob/master/src/i18n/fr.json)
 * [ ] [Spanish](https://github.com/lesspass/pure/blob/master/src/i18n/es.json)
 * [ ] [Ukrainian](https://github.com/lesspass/pure/blob/master/src/i18n/uk.json)
 * [ ] [German](https://github.com/lesspass/pure/blob/master/src/i18n/de.json)
 * [ ] [Chinese](https://github.com/lesspass/pure/blob/master/src/i18n/zh.json)

reviewed:

 * [ ] [French](https://github.com/lesspass/pure/blob/master/src/i18n/fr.json)
 * [ ] [Spanish](https://github.com/lesspass/pure/blob/master/src/i18n/es.json)
 * [ ] [Ukrainian](https://github.com/lesspass/pure/blob/master/src/i18n/uk.json)
 * [ ] [German](https://github.com/lesspass/pure/blob/master/src/i18n/de.json)
 * [ ] [Chinese](https://github.com/lesspass/pure/blob/master/src/i18n/zh.json)

Thank you

**Comment by guillaumevincent** [comment]
@derelk and @Facel3ss1 feel free to review https://github.com/lesspass/pure/blob/master/src/i18n/en.json
All the strings used in LessPass component are group into this file.
Thank you

**Comment by panther2** [comment]
@guillaumevincent 
Voilá the German translation:
https://github.com/lesspass/pure/pull/10

**Comment by elopio** [comment]
Spanish here: https://github.com/lesspass/pure/pull/11

**Comment by guillaumevincent** [comment]
@panther2 and @elopio that was fast! thank you very much

**Comment by Facel3ss1** [comment]
@guillaumevincent It seems to be fine. I don't know why there are two 'copied' keys ("copied" and "Copied") in the JSON as they both have the same value ("copied !"). Is this a mistake?

**Comment by guillaumevincent** [comment]
Yes it was a mistake thanks.

**Comment by guillaumevincent** [comment]
I will push a new version soon with german, spanish and french translations.
We will add Ukrainian and Chinese when translation will be available.
I will close this one soon

Thank you all of you, it was really pleasant to work on this one

**Comment by guillaumevincent** [comment]
Thanks to @r2qokk the Chinese translation is here!
I will ship a new version soon

Thanks

**Comment by dtalens** [comment]
I have translated this magnificent application into Catalan. #744

**Comment by guillaumevincent** [comment]
@dtalens I love it
I will try to push this after Christmas
