### ISSUE TITLE
Focus when opening saved site on the wrong place

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#151]
### Replicate

1. use connected mode
1. open a tab ;
1. go on a site you registred
1. invoke lessPass with shortcut (Ctrl+Shift+L)

### Expected

To have focus on the `master password` field as others are pre-filled.

### Actual

Focus is placed on the first field, i.e. the `site` instead of `master password`.

**Comment by guillaumevincent** [comment]
@edouard-lopez the focus is broken, sometimes master password field is selected, sometime is not.
