### ISSUE TITLE
[cli] LessPass should fail loudly if it can't copy password with -C option

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#153]
Hello,

On my main computer (running Debian) `lesspass -C` works perfectly but it does not work on my laptop.
It says `Copied to clipboard` but I still have the previous copied string in my clipboard.
I'm using Ubuntu 16.10 with Node 4.2.6 and Xfce.

**Comment by guillaumevincent** [comment]
Hi @Rudloff,
what is your version of xclip? `xclip -version`

**Comment by Rudloff** [comment]
Of course, xclip was not installed on this computer... Now it works correctly.
You might want to add a check for that ^^

**Comment by guillaumevincent** [comment]
Yes we need to check and raise an error if xclip not installed
For now it's only in the doc https://github.com/lesspass/cli/blob/6e7a1e6816cfc24d5a793485a1621834887394d2/cli.js#L28

**Comment by mlcdf** [comment]
I've taken a quick look at the issue, and the thing is that node-copy-paste doesn't throw an error if it doesn't find `xclip`. So we either have to check by ourself in xclip is install using `child_process` or we could just switch to [clipboardy](https://github.com/sindresorhus/clipboardy) which uses `xsel` under the hood, but [fails loudly if it doesn't find it](https://github.com/sindresorhus/clipboardy/blob/master/index.js#L28). Also, `node-copy-paste` doesn't seem maintain at the moment...

What do you think @guillaumevincent?

(I would gladly submit a PR for this!)

**Comment by guillaumevincent** [comment]
@mlcdf yes excellent idea! We are going to migrate to clipboardy

Glad if you can send us a pull request
