### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by keshto** [lesspass/lesspass#155]
The current android app (and guessing ios app) are slow and noticeably not native. For instance pressing the back key usually will get you back to the original activity or close the main activity returning you back to the main screen. The current android app acts like a web browser where back button will take you back to the last thing you did. Could we pull in https://github.com/Syject/MyLessPass-Android (there is also an ios app) to be used instead?

**Comment by keshto** [comment]
Another issue with mobile app, we should have an accessibility service (bitwarden) or keyboard (keepass) to fill in user/pass as copy and paste is a known security issue.

**Comment by edouard-lopez** [comment]
@keshto could you please move your second issue to it's own thread?

**Comment by edouard-lopez** [comment]
@keshto Being non-native allow us to provide make different version evolve at the same pace as we have a single code-base. 
Password generation is instantaneous on my tests. What kind of settings did you use for yours? 

The behavior your describe is the expected one.

**Comment by keshto** [comment]
Yes non-native allows for single code base. Have you looked at the linked repo yet?

Password generation is instantaneous. I am referring to the startup of the application. A simple web app should not be taking that long to start. The back button behavior is not the expected behavior for normal android apps is my point. 

I think having it pull in from the web is fine. However, there is the issue of lesspass getting owned and thus everyone because we all have the same client we pull from the server. However, The behavior of the app should be that of a native app. There are lots of applications (usually bank apps) that use webviews but act like native apps.

**Comment by guillaumevincent** [comment]
@keshto can we rename this into: slow startup for android app ?
This is an issue that we need to fix.

https://github.com/Syject/MyLessPass-Android is a native Android App? 

We use cordova for our Android App. https://github.com/lesspass/cordova
Feel free to inspect our code and let us know if something can slows our app.
Thank you

**Comment by edouard-lopez** [comment]
@keshto The back button behavior it is consistent with the [official Android developer _Navigation with Back and Up_ pattern](https://developer.android.com/design/patterns/navigation.html).

**Comment by keshto** [comment]
@guillaumevincent yea it is a hybrid (native but pulls from official site). encourage you to look at code. @edouard-lopez no it not consistent. go use the linked app click around and use the Cordova app you guys have and do same clicks and back button and you will see it takes max 3 back presses to exit vs your x clicks to exit the Cordova where x is the number of prior clicks.

**Comment by edouard-lopez** [comment]
@keshto ok, I get what you mean, our app doesn't have a hierarchy between screen hence the `n` hit to exit the app.

**Comment by guillaumevincent** [comment]
@keshto 

> Could we pull in https://github.com/Syject/MyLessPass-Android (there is also an ios app) to be used instead?

We do not control the release of MyLessPass-Android and more over I try to push hard to get the same user experience everywhere.

That is why:

> The current android app acts like a web browser

So for now we are working on [The icons in the header are ambiguous](https://github.com/lesspass/lesspass/issues/156). Maybe it will improve the navigation (this is your first issue).

Your second issue is how to start the application faster. Because we are loading a web context, it can't be as fast as native app. Because this is not our area of expertise, we prefer to let people create native applications. 

So for all of these we could not we pull MyLessPass-Android to be used instead of LessPass cordova.

I close this one
