### ISSUE TITLE
The icons in the header are ambiguous

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#156]
The _spy_ icon is ambiguous as there is no text to explain what it does. I know real-estate on the app is limited by icon have a really low information scent, especially this one that hide an important feature.

**Comment by guillaumevincent** [comment]
hum,
this feature is complex to explain, remember when we try to explain it with full text on ux stackexchange?
Don't know if a single small tooltip can help user.
On mobile tooltip is equivalent to a click. So click will reveal the password and display tooltip?

**Comment by mlcdf** [comment]
Maybe this is something that could be explain in a onboarding screen on the first start of the app/web extension.

Have you guys consider adding onboarding screens? It could be a way to explain confusing features.

**Comment by guillaumevincent** [comment]
@mlcdf we need to save information about the user (ip adress, last connection) if we want to make onboarding usefull.
I'm really vigilant to ask the minimum information about our users.

**Comment by mlcdf** [comment]
Arf, you're right. I hadn't thought about that.

**Comment by edouard-lopez** [comment]
I think there is too much confusion between private/connected mode. I need to do some user testing.

**Comment by guillaumevincent** [comment]
@edouard-lopez sorry I think you talk about fingerprint button

**Comment by guillaumevincent** [comment]
Are you thinking something like this @edouard-lopez?
![screen shot 2017-03-02 at 08 49 20](https://cloud.githubusercontent.com/assets/943762/23497816/32fd914a-ff25-11e6-86ad-db686a9a7d81.png)

**Comment by edouard-lopez** [comment]
Here is how I would do it [less noise, more information scent](https://jsfiddle.net/bacuz0dg/1/):

![lesspass password manager header](https://cloud.githubusercontent.com/assets/1212392/23555424/306d4916-0029-11e7-8a8a-2db6cba1e19c.png)

**Comment by guillaumevincent** [comment]
@edouard-lopez share icon to log in ?
I put only two icons but connected we got 4 icons

**Comment by edouard-lopez** [comment]
As mentioned in #163 the share icon might be a ambiguous, I [changed it to a paper-plane](https://jsfiddle.net/bacuz0dg/2/) might be better.

![best password manager ui](https://cloud.githubusercontent.com/assets/1212392/23555610/dc843598-0029-11e7-94f9-1eb141432e5d.png)

* the hint.css doesn't work but the HTML seems good to me.

**Comment by edouard-lopez** [comment]
Below I distinguish the private/anonymous mode from the connected one by using:
* color similar to firefox private windows
* _spy_ vs _home_ icon

### private

![header-anonymous](https://cloud.githubusercontent.com/assets/1212392/23559041/161682b4-0036-11e7-9f5a-534a89727da2.png)
* I would love to add an animation on the paper plane inspired by short Disney movie [_Paperman_](https://www.youtube.com/watch?v=1QAI4B_2Mfc)
* using text for `Log In` is more explicit, but I wonder if you should encourage user to connect or not.

### connected
![header-connected](https://cloud.githubusercontent.com/assets/1212392/23559040/160e5d0a-0036-11e7-8529-4b9311d9e22c.png)

* use _star_ icon instead of meaningless-skeumorphic floppy disk. 
  * This let us target millenials, but more seriously the icon is hard to recognize in monochrome, even when you know what it is ;
  * it's closer to the feature purpose, i.e. giving a quick access to profile vs. the letting user believe with save password (which we don't).
* use _list_ icon instead of key icon:
  * not sure about this one, a :mag: might be better but on the other hand it's only the list of saved profile. What do you think?

**Comment by guillaumevincent** [comment]
I still dislike the inconsistency of the actions the header.
What I have imagined is something like this: https://cdn-images-1.medium.com/max/800/1*d55w8RiaAGkt2UvdpK5OvQ.png?

+1 for the star and list icons. Those are better than the previous one

**Comment by edouard-lopez** [comment]
Wording become more important in [this one](https://jsfiddle.net/edouardlopez/b66nr8zn/4/):
![selection_011](https://cloud.githubusercontent.com/assets/1212392/23589999/623dfce6-01d8-11e7-801c-44544bd10985.png)

**Comment by guillaumevincent** [comment]
I think we are close to something far better than the existing header 👍 

Feedback:

1. @edouard-lopez remember that header color is associated with the version number?
For me we should keep the header blue. For me new color = new version

2. We lose the identity 'LessPass' without the title on the left. You probably remove it because of the space. Maybe we should use a small logo here. and remove spy icon

**Comment by edouard-lopez** [comment]
I remember, but the distinction between private and connected mode is to discrete. For instance, It took me several weeks to realize that using Chromium private mode with lesspass **doesn't disconnect lesspass addons**.
I'm just not satisfied with the current situation, color was the simplest way to clear distinguish between the two mode in the mockup. We need to find a better solution.

I asked myself the same question about the brand name, for the extension I'm note sure it's super relevant as it open after clicking the icon. Even when you come back to the browser the popup is still "connected" to the icon on the toolbar.
I'm poking around, trying and failing.

As you said the icon might be enough to identify the tool, it could also be style differently depending the mode (light/connected vs. dark/private).

**Comment by guillaumevincent** [comment]
So we can remove the color in the header and move to light/connected vs. dark/private mode

**Comment by edouard-lopez** [comment]
What icon might look like:
![lesspass-icon-dark](https://cloud.githubusercontent.com/assets/1212392/23706085/0a4ac5be-040d-11e7-8be2-78f6fe06bccb.png) ![lesspass-icon-light](https://cloud.githubusercontent.com/assets/1212392/23706088/0d81d1c8-040d-11e7-8670-d9ee0f3b073d.png) ![lesspass-icon-blue](https://cloud.githubusercontent.com/assets/1212392/23706090/0dad67ca-040d-11e7-8af7-3e42826bb911.png)

**Comment by edouard-lopez** [comment]
I restore the blue color (same on both line):

With favicon and brand name 
![lesspass favicon and brandname](https://cloud.githubusercontent.com/assets/1212392/23706653/5d015a8c-040f-11e7-81ae-5a84f74ea341.png)

With favicon only
![lesspass favicon only](https://cloud.githubusercontent.com/assets/1212392/23706700/904c8d4e-040f-11e7-9e1f-e70856bb0bd9.png)

What do you think ?

**Comment by guillaumevincent** [comment]
incognito mode in browsers:
![screenshot from 2017-03-08 15-13-52](https://cloud.githubusercontent.com/assets/943762/23707235/e64182e8-0411-11e7-8050-adece203ea22.png)

**Comment by edouard-lopez** [comment]
So that's what you mean by removing header's color I though you meant only the purple.
That's pretty neat, it feel a lot more _precise_!

**Comment by edouard-lopez** [comment]
Reading #163 I realize **we have a mix of navigation and action buttons** (back/home, login/logout vs send, save, list). It's a perfect illustration of violating the [Gestalt principles of enclosure and proximity](https://en.wikipedia.org/wiki/Gestalt_psychology#Pr.C3.A4gnanz).

The `send` button is available on the header, which stays visible on all screens, despite making sense only in the _password_ screen but none in _login_ and _default option_ one. 
In comparison, the `generate` button is only available one the _password_ screen, which is what you would expect from a feature only related to this screen.

So `send` and probably `save` buttons should only appear in the _password_ screen, in order to only keep in the header `home`, `list` and `login/out`

**Comment by guillaumevincent** [comment]
@edouard-lopez 👍  this make sens

**Comment by guillaumevincent** [comment]
@edouard-lopez I will close this one for now because:

 * we remove from the menu share button
 * I'm going to replace the spy icon with the well known sign-in button

![screen shot 2017-04-14 at 11 11 12](https://cloud.githubusercontent.com/assets/943762/25039328/4be45702-2103-11e7-86d3-1d7f0e34dca4.png)

**Comment by edouard-lopez** [comment]
No more labels? What about other features?

**Comment by guillaumevincent** [comment]
I remove the default option page: https://github.com/lesspass/lesspass/issues/206
We will redesign the component after LessPass Move.

**Comment by edouard-lopez** [comment]
@guillaumevincent Did you see the message from @krt ?

> If you happen to use Cordova>4, it can **generate all necessary files for a gradle build**, which is easier to handle. So pushing this into the/a repo will most likely help, but i havent had a look at it.
