### ISSUE TITLE
Does lesspass use a hosted database?

### ISSUE THREAD

**Issue by micah** [lesspass/lesspass#158]
Hi,

I'm looking for some clarification about LessPass. The description says, "It does not save your passwords in a database" and the Firefox extension says, "No database, no sync needed." but then what is this section of the documentation supposed to be about:

```
Self Hosted
You can host your own LessPass database if you do not want to use the official one.
```

What is the LessPass hosted database used for if LessPass doesn't save your passwords in a database?

**Comment by guillaumevincent** [comment]
Hi @micah,
You can use LessPass offline without any database. 
But we all know sites with stupid password rules. My bank only allows numbers. I don't want to remember those options (=no letters, no symbols, length of 8) So we created a "connected" version to help users to memorize complex password profiles.

![screenshot from 2017-02-28 09-41-32](https://cloud.githubusercontent.com/assets/943762/23397901/a0a8598c-fd9a-11e6-9963-aea2abb5e4f6.png)

If you inspect in your browser (right click + inspect element) you can see information stored in LessPass Database.

I hope it answers your question, if no feel free to ask

**Comment by micah** [comment]
Hi @guillaumevincent,

Thanks for your reply! I understand now the reason why that is an option.

How do you decide to use the LessPass database (either the one at https://lesspass.com or your own self-hosted one)? I installed the firefox extension and I didn't see how you decide to do that or not. I don't know a lot of javascript, but I tried to read the source here on github, and could only find a minified version, which is quite difficult to read :)

**Comment by edouard-lopez** [comment]
If you click on the spy icon ![spy icon](https://cloud.githubusercontent.com/assets/1212392/23408690/4c447e78-fdc9-11e6-9a47-dae83f288913.png) at the top-right, you will see the default value is `https://lesspass.com`, you can change that to the URL of [your `backend` instance](https://github.com/lesspass/backend) (a `docker` to deploy).

**Comment by micah** [comment]
Édouard Lopez <notifications@github.com> writes:

> If you click on the spy icon ![spy icon](https://cloud.githubusercontent.com/assets/1212392/23408690/4c447e78-fdc9-11e6-9a47-dae83f288913.png) at the top-right, you will see the default value is `https://lesspass.com`, you can change that to the URL of [your `backend` instance](https://github.com/lesspass/backend) (a `docker` to deploy).

Ah ok. I do not see this documented anywhere. Maybe I missed it, but if
not, it would be a good idea to clarify how this works!

**Comment by guillaumevincent** [comment]
@micah yes we should add this on the wiki https://github.com/lesspass/lesspass/wiki

**Comment by edouard-lopez** [comment]
@micah we have the [Private vs. connected mode](https://github.com/lesspass/lesspass/wiki/Private-vs.-connected-mode) page that explain a bit but need some love.

**Comment by guillaumevincent** [comment]
Hi @micah,
I close this one, I've updated the wiki https://github.com/lesspass/lesspass/wiki/FAQ
And we are working on improving the header: https://github.com/lesspass/lesspass/issues/156

![screen shot 2017-03-02 at 08 53 52](https://cloud.githubusercontent.com/assets/943762/23497987/d7730eee-ff25-11e6-9d0e-4c37f93b97a8.png)

Thank you for your feedback
