### ISSUE TITLE
Clean blog posts

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#159]
Blog posts become obsolete, we need to simplify and clean them

**Comment by guillaumevincent** [comment]
![hiw](https://cloud.githubusercontent.com/assets/943762/24607268/2896153c-1871-11e7-8bf5-d1307b0892de.png)

**Comment by guillaumevincent** [comment]
![hiw](https://cloud.githubusercontent.com/assets/943762/24658552/52f31922-194a-11e7-9c9e-ee6bd78edeaf.png)

**Comment by edouard-lopez** [comment]
with colours

![hiw](https://cloud.githubusercontent.com/assets/943762/24607268/2896153c-1871-11e7-8bf5-d1307b0892de.png)

**Comment by edouard-lopez** [comment]
less information noise
![hiw](https://cloud.githubusercontent.com/assets/943762/24658552/52f31922-194a-11e7-9c9e-ee6bd78edeaf.png)

**Comment by edouard-lopez** [comment]
More Inline, smaller visual footprint, clearer input/output

![hiw](https://cloud.githubusercontent.com/assets/943762/25004031/8eb21af8-2052-11e7-8355-70bf9477ef03.png)
