### ISSUE TITLE
« Copied » icon is ambiguous 

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#163]
When I click on this icon, something is copied.
What is copied ? Where ?
Could we have more information or a two-step action ?

![copied](https://cloud.githubusercontent.com/assets/18329417/23554614/321b0116-0026-11e7-8cc8-17b14a97c12c.png)

**Comment by panther2** [comment]
Just paste and you will get something like this:

https://lesspass.com/#/?login=test.user@example.com&site=lesspass.com&uppercase=true&lowercase=true&numbers=true&symbols=true&length=16&counter=1&version=2

So it represents the latest input data (without the Master Password of course) as well as the settings used.

**Comment by guillaumevincent** [comment]
yes there is an [issue](https://github.com/lesspass/lesspass/issues/156) to add context to those icons
![screen shot 2017-03-02 at 08 53 52](https://cloud.githubusercontent.com/assets/943762/23497987/d7730eee-ff25-11e6-9d0e-4c37f93b97a8.png)

**Comment by guillaumevincent** [comment]
I close this one, because we will modify the menu see #156
