### ISSUE TITLE
Local back-up of default options is not explained

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#164]
When clicking on the “Default options” Icon this message appears: “Default options are automatically saved locally. “
Could we have in this message a link to a brief explanation of the principle ? What is stored “locally” ? What is stored “online” ?

**Comment by guillaumevincent** [comment]
@delphine-graeff thank you for your feedback, I close this one because there is two issues that will fix this one
https://github.com/lesspass/lesspass/issues/162
https://github.com/lesspass/lesspass/issues/161
