### ISSUE TITLE
Scroll bar Issue when profiles are a bit long

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#165]
When website address are a bit long and do not fit into one line. Two scroll bars appear.
The "Next Page" and « Previous Page »  buttons are no longer visible.

![defilement2](https://cloud.githubusercontent.com/assets/18329417/23554753/a866c33c-0026-11e7-8ad1-5f0ba4aa9468.png)

**Comment by edouard-lopez** [comment]
@delphine-graeff thanks for the screenshot.

I'm not sure it's related to adress width as they all seems a lot shorter than the UI. It might be related to your Firefox version. Please check #129 for details.

**Comment by edouard-lopez** [comment]
Ok, The issue here is longer URL are wrapping instead of using [`text-overflow: ellipsis`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) or a shortening mechanism

**Comment by guillaumevincent** [comment]
The height of the scroll bar wasn't good
I can reproduce this problem today.

It will be fixed in a week, when mozilla will accept LessPass addon
