### ISSUE TITLE
Ambiguous message when no profile is found using the search engine

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#166]
![recherche infructueuse](https://cloud.githubusercontent.com/assets/18329417/23554775/bdf354e0-0026-11e7-8166-596afe6c8597.png)

**Comment by edouard-lopez** [comment]
@guillaumevincent we can mitigate this situation by improving the message. I reckon it's eligible to `good for beginners`.

**Comment by guillaumevincent** [comment]
![screen shot 2017-03-11 at 09 46 06](https://cloud.githubusercontent.com/assets/943762/23821870/960570e8-063f-11e7-8f0f-ffd9c7d40509.png)
