### ISSUE TITLE
Migration to a new version is not simplified 

### ISSUE THREAD

**Issue by delphine-graeff** [lesspass/lesspass#167]
When you have more than 50 profiles on your LessPass account, you could have used some assistance from the tool :
- A search filter to search for the Profile that have yet to migrate ?
- More warnings and reminders of the next migration, and the number of Profiles that still have to migrate to the next version ? 
- Something else..

**Comment by edouard-lopez** [comment]
@guillaumevincent we could display the version number when it's below latest version. A minimal solution would be like:

![erase your password](https://cloud.githubusercontent.com/assets/1212392/23556042/5e763d66-002b-11e7-8a98-8bed1de05ee3.png)

**Comment by guillaumevincent** [comment]
@edouard-lopez +1

**Comment by edouard-lopez** [comment]
@guillaumevincent sound like adding a `password.version` to the [template](https://github.com/lesspass/pure/blob/master/src/views/Passwords.vue#L22-L39) and a condition to show when `<2`.

**Comment by guillaumevincent** [comment]
![screen shot 2017-03-13 at 19 54 52](https://cloud.githubusercontent.com/assets/943762/23870547/06a5b86a-0827-11e7-846f-c06b8c43e348.png)
![screen shot 2017-03-13 at 19 54 58](https://cloud.githubusercontent.com/assets/943762/23870546/053310a4-0827-11e7-928f-f8752db7c34b.png)

Here a look at the new interface with v1 on the right

**Comment by edouard-lopez** [comment]
It looks globally tidier. 

I'm wondering why did you add the separating lines? If it's too related the right part of the UI, you could either move the component closer or use highlighting.

Also, on the second screenshot the following question arise "what is the version number of the profile I'm deleting". We should not hide it as it might be an information used to continue or cancel action.

**Comment by guillaumevincent** [comment]
> I'm wondering why did you add the separating lines? If it's too related the right part of the UI, you could either move the component closer or use highlighting.

to separate visually the elements. it's not related to the right part of the ui

> Also, on the second screenshot the following question arise "what is the version number of the profile I'm deleting". We should not hide it as it might be an information used to continue or cancel action.

you already know the information, the delete button come right after a click on the corresponding line. The version number is not relevant in this scenario; I'm deleting a password because I don't use the service anymore.

**Comment by edouard-lopez** [comment]
I was thinking about the scenario where user migrate from v1 to v2. Could you have duplicate entries with same site/login but different version?

**Comment by guillaumevincent** [comment]
@edouard-lopez nop
