### ISSUE TITLE
Firefox extension not working on FF for Android

### ISSUE THREAD

**Issue by Yajo** [lesspass/lesspass#168]
Well, not exactly not working... Just no way to launch it.

**Comment by guillaumevincent** [comment]
Yeah, I will remove it from the addons for Firefox

**Comment by guillaumevincent** [comment]
I modify the compatibility section in https://addons.mozilla.org/
Thank you @Yajo

**Comment by Yajo** [comment]
Do you mean that it's unsupported for phones? I guess in favor of Android app, isn't it?

**Comment by guillaumevincent** [comment]
Yes for know, I don't know how a Firefox extension works on mobile. You don't have the icon, and can't open the pop up. We should wait a little because Mozilla starts to add Firefox for Android Extension. It's quite young
