### ISSUE TITLE
Broken Android app link

### ISSUE THREAD

**Issue by Yajo** [lesspass/lesspass#169]
Android link on lesspass.com links to https://play.google.com/store/apps/details?id=com.lesspass.cordova&hl=en, which shows this:

![captura de pantalla de 2017-03-05 12-02-38](https://cloud.githubusercontent.com/assets/973709/23586729/a7109cda-019b-11e7-915d-82538b785aae.png)

A simple search on Google Play shows that there exists https://play.google.com/store/apps/details?id=com.lesspass.android, but given that's not what's linked from the official site, not sure on wether it should be trusted or not...

Please update website link or open that app for world-wide installations.

**Comment by guillaumevincent** [comment]
You're right, link on header is right but not here: https://github.com/lesspass/frontend/blob/master/index.html#L276
