### ISSUE TITLE
Add husky to prevent commit without green tests

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#172]
https://www.npmjs.com/package/husky

packages with husky:

- [ ] https://github.com/lesspass/cli
- [ ] https://github.com/lesspass/pure
- [ ] https://github.com/lesspass/core

**Comment by mlcdf** [comment]
In order to help beginners, you might also want to list the repositories that would be affected by this feature (core, cli & pure?).

**Comment by guillaumevincent** [comment]
yes you are right, here the 4 packages we need to add husky:

- [ ] https://github.com/lesspass/cli
- [ ] https://github.com/lesspass/webextension 
- [ ] https://github.com/lesspass/pure
- [ ] https://github.com/lesspass/core

**Comment by mlcdf** [comment]
Hum... it looks like the webextension repository doesn't have any tests (despite what the README says).

**Comment by guillaumevincent** [comment]
haha nice catch. webextension add some tests long time ago
