### ISSUE TITLE
What Coding Standards for the LessPass codebase?

### ISSUE THREAD

**Issue by mlcdf** [lesspass/lesspass#173]
The title pretty much says it all: have you consider "adhering" to any Coding Standards for the LessPass codebase (and enforcing them via linters)? 

It would:
- prevent basic errors (they would be catch by the linter).
- improve code readability & consistency across the codebase.
- lift some weight upon contributor' shoulders since they wouldn't have to triple check their code to make sure it follows the same code style as you.

Here's some options:

**JavaScript**
[Standard](https://github.com/feross/standard), [XO](https://github.com/sindresorhus/xo) or [ESLint](https://github.com/eslint/eslint) (+ a config).
[Prettier](https://github.com/prettier/prettier) looks pretty neat too, but it only formats the code so you still need a linter (for static analysis).

**Python**
[Pylint](https://github.com/PyCQA/pylint) seems like the best tool for the job.

**Shell**
[Shellcheck](https://github.com/koalaman/shellcheck) seems like the only tool for the job. It doesn't check against any code style (not sure someone even wrote a code style for Shell!) but still performs static analysis.

**CSS**
[Stylelint](https://github.com/stylelint/stylelint) works well. I didn't try any of the [others](https://github.com/caramelomartins/awesome-linters#css) tho. 

There is also one for Markdown, but I'm not sure we need to go this far.

---
Oh and, I just noticed: LessPass reached 2.000 stars !!! :star2: :star2: :star2:

**Comment by guillaumevincent** [comment]
I try to follow as much as I can yagni principals (your are not going to need it). I already tried xo, and in my day to day job, I use eslint. 
If you look at the code you will see that pep8 is respected, indent in HTML are OK, and JavaScript are almost xo valid.
This is because I use and IDE with auto format and configeditor.

We should add some features if they solve some problems. What kind of problem we had, linter can solve?

Thanks to you I see that we reach 2k stars. I'm a little proud. Thank you LessPass community

**Comment by mlcdf** [comment]
Well, I'm probably over-thinking this and planning/anticipating too far ahead. Or am I? I don't know.

Sure, for you, it wouldn't change much (well there is still the static analysis part) and only add another step to the process but I do think that for contributors, it's a great thing. Specially for the JavaScript code since there are so many different coding styles and the language has plenty of quirks (I agree that for the shell scripts and the CSS, it may be a little overkill).

If you don't fell like defining a(some) code style(s) for the project, I think you use consider adding an .editorconfig file to all the repositories.

**Comment by guillaumevincent** [comment]
@mlcdf sure let's do this, and we will use prettier in the future, so eslint will become less interesting
