### ISSUE TITLE
C version and Limits

### ISSUE THREAD

**Issue by monolifed** [lesspass/lesspass#175]
I made a [command line version](https://github.com/monolifed/lesspassc)(v2 only) which only depends on libcrypto. What are the limits for some options; like keylen, length, counter, etc.

**Comment by guillaumevincent** [comment]
@monolifed the default options?

**Comment by guillaumevincent** [comment]
here the default options: https://github.com/lesspass/core/blob/master/src/lesspass.js#L30-L41

**Comment by guillaumevincent** [comment]
I close this one, feel free to ask more information here
thank you
