### ISSUE TITLE
Android app in F-Droid

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#177]
Hello,
I'm using [F-Droid](https://f-droid.org/) instead of Google Play and would like to ask them to include the LessPass Cordova app in their reprositories.
Their policy states that the original developper must agree to this first. Would you be OK about it?
Additionnaly, does the app rely on any non-free library?

* [x] @edouard-lopez
* [x] @guillaumevincent

**Comment by edouard-lopez** [comment]
I'm totally OK with that, what about you @guillaumevincent?

AFAIK we use only free library, but we might need to check for the license of module we use in the core and [pure component](https://github.com/lesspass/pure/).

**Comment by edouard-lopez** [comment]
Here is the output given by [`license-checker`](https://github.com/davglass/license-checker) Lesspass/pure licenses as of [949bf7b](https://github.com/lesspass/pure/tree/9a10fa2545cb527142ba931efc3dc37f9489ebaf).

N.B.: `license-compatibility-checker` [isn't working](https://github.com/HansHammel/license-compatibility-checker/issues) right now

**Comment by guillaumevincent** [comment]
@Rudloff the app don't rely on any non-free library.
I'm totally OK with this too! Thank you

Feel free to close the issue, if you have everything you need
❤️

**Comment by Rudloff** [comment]
Thanks! I submitted the app here: https://gitlab.com/fdroid/rfp/issues/82
I'll keep the issue open for now in case the F-Droid team needs something else.

**Comment by edouard-lopez** [comment]
@Rudloff Thanks, maybe you can link this issue in your request to support it.

Also, the [latest release for Android](https://github.com/lesspass/cordova/releases) **is `2.0.2`** not `2.0.3`, the it's part of the [_Harmony_](Harmony) version.

**Comment by Rudloff** [comment]
Sorry, I took the version from config.xml without thinking. It's fixed now.

**Comment by guillaumevincent** [comment]
I close this one
We are waiting for some input from fdroid

**Comment by edouard-lopez** [comment]
@guillaumevincent Did you see the message from @krt ?

> If you happen to use **Cordova>4, it can generate all necessary files for a gradle build**, which is easier to handle. So pushing this into the/a repo will most likely help, but i havent had a look at it.

**Comment by guillaumevincent** [comment]
@edouard-lopez yes but I don't have the time to search how to generate the files and krt is not answering.

**Comment by Rudloff** [comment]
I think you can simply run `cordova prepare` and include `platforms/android/` in a repository.
It's what I did for my app: https://github.com/Rudloff/lesspass-cordova-android

Then this repository can be used to build the app without having to run npm or cordova. So build servers that only have the Android SDK tools can build the app.

**Comment by guillaumevincent** [comment]
thanks @Rudloff, but I don't understand
platforms size is 16Mo
Do I have to upload all the folder? 

Can I ignore `platforms/android/CordovaLib/build/`

**Comment by Rudloff** [comment]
No, you don't need to upload the build.
You can run `cordova clean` to remove it.

**Comment by magullo** [comment]
Hi, any news on LessPass on F-Droid? I am moving from passwordstore to lesspass, and I'd like to have this app on my SailfishOS device. Thanks

**Comment by edouard-lopez** [comment]
@magullo We need to push gradle file to our repo then bump the issue on [F-droid repo](https://gitlab.com/fdroid/rfp/issues/82)

**Comment by guillaumevincent** [comment]
@edouard-lopez @magullo :
@Rudloff is also waiting for the new Android app based on React Native.

I'm working on it but I'm traveling right now, so I will take a little time
