### ISSUE TITLE
variable "index" vs. "counter" in core

### ISSUE THREAD

**Issue by mevdschee** [lesspass/lesspass#178]
https://github.com/lesspass/core/blob/master/src/lesspass.js#L39

Should the variable "index" not be named "counter"?

**Comment by guillaumevincent** [comment]
interesting, I saw this error yesterday too!
I will fix this one

Thanks @mevdschee for reading the code :)

**Comment by mevdschee** [comment]
You are welcome. Thank you for creating this software!
