### ISSUE TITLE
Add a way to select frequently used usernames

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#180]
Hello,
I use a small number of usernames on most websites so it is a bit tedious to type them everytime. It would be nice to be able to select one of my favorite usernames in a list or an autocomplete field.

**Comment by guillaumevincent** [comment]
@Rudloff We can offer auto completion on login saved in LessPass Database.
Will this idea fix this issue?

**Comment by Rudloff** [comment]
I don't really use the database but I guess I could give it a try.

**Comment by guillaumevincent** [comment]
@Rudloff I do not want to force people, I just want to figure out how to respond to the need.
So only locally, you want to generate passwords and save the logins for later use?

**Comment by Rudloff** [comment]
Yes, I would prefer if it was only local.
It could be either:
* Explicitely save an username.
* Automatically remember frequently used usernames (but this might raise privacy issues, I guess).

**Comment by edouard-lopez** [comment]
@Rudloff while in private mode you can save default config, the `login` field can be a unique identifier related to you with no relation to the account you're trying to use. 

For instance, you can use `you-secret-nickname` as login value when generating password with LessPass as nothing force you to use the actual login/username from the service. 

* **pros:** this will improve protection against basic social engineering attacks based on public account information as they differ from login used with.
* **cons:** 
  * never consider opacity as sufficient protection. 
  * if someone find your lesspass' login it reduces the number of information attackers need to guess/find to generate your password, but this is already the case if you use a know/public username.

**Comment by Rudloff** [comment]
The main reason I don't do this is that I often use two accounts on some websites (e.g. personal vs. pro) and I don't want to have the same password on both accounts.
But I guess I could always use the same Lesspass username and manually type another for the few cases where I need multiple accounts.

**Comment by Rudloff** [comment]
I've been using the a default login, typing another one for the few websites where I have several and it feets most of my needs so I'm closing this.
