### ISSUE TITLE
Add the possibility to force a minimum content of the generated password

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#181]
Hello,

It would be nice to have an option to force the password to have a minimum amount of lowercase, uppercase, digits...

If it's not possible, a prefix / suffix option would be a workaround too.

Cheers.

**Comment by guillaumevincent** [comment]
We try to do this in the version 1, but it's increase the bruteforceability of the master password.
We use template to do so, for example `cvCVns` (`c`onsonms, `v`owels, etc.)

But it was not a good idea, see https://github.com/lesspass/lesspass/issues/88
So we are not going to do the same mistake this time :)

I close this one

Thanks

**Comment by kidburglar** [comment]
I will talk again about passwordmaker (sorry, but I only use this before so I don't have other applications that I can use for compare). I had many generated password but for some websites I needed to add manually sometimes digit or uppercase.

To avoid this problem, now I use prefix and suffix. So I force only first and last char to minimize this problem. If you think this not have his place in lesspass let me know and it will be ok, I will not try to force anything ^^
