### ISSUE TITLE
Add an option to remember the masterpassword and fill the password field

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#182]
Hello,
 
It would be nice to have an option to remember the password the time that we close the browser.
If it's an acceptable request, it will be usefull to have the possibility to fill all the "passwords fields" directly.

Cheers.

**Comment by guillaumevincent** [comment]
Hello @kidburglar,
this is a tricky one :)

On one side I don't want to save the master password anywhere
On other side, I will improve the user experience to save master password

This is a security problem: usability versus security

For me your master password should always be in your head, and you should use only trusted devices.

But your issue make me think about an alternative:
Generate all passwords based on all your password profiles and store them in the session. 
Like this you can open the app, enter your master password one, and copy every password for one day for example.

Let's continue the discussion here

**Comment by SoftwUser** [comment]
With all respect to the developpers for listening to feature requests as well to the users for their ideas:

Lesspass is a **stateless** open source password manager.

There are countless software solutions that save whatever information is wanted/needed...

Do we really need Lesspass becoming just another one...???

Let's keep this awesome idea and project as lean and simple as possible.

Just my opinion of course...

**Comment by kidburglar** [comment]
Hello @guillaumevincent 
Yes I know it's always tricky when it's usability vs security ^^

In passwordmaker you have 3 options (it's what I use for now but I thinking of change it)
- Not remember
- In memory (I think it's more like something in session because when you close the browser it's gone
- On hard drive and in memory

I know that it's a bad habit to compare two applications but so it can give some ideas.
If you can implement your idea, I will be happy to test it and discuss how I feel it...

**Comment by guillaumevincent** [comment]
@SoftwUser I have the same opinion. But I like to challenge ideas. We discuss new features. 
Do not hesitate to put a little reaction like 😕 if the idea does not please you.

From the beginning, LessPass is Community Driven Design

@kidburglar did you look at the last Lastpass breaches, where google engineer read some data from memory. It's really hard to mix security versus usability.

**Comment by kidburglar** [comment]
@guillaumevincent 
No I don't have read the last breach from lastpass.

I understand that it is less secure, but if it's not the defautl option and there is a warning I don't think 
there is a problem for the users that want less security for more usability (only my opinion)

Now if you find a more secure idea, it's always better of course.

**Comment by guillaumevincent** [comment]
No I don't, but keep this one open for the discussion
We need feedback :)

**Comment by guillaumevincent** [comment]
Hello,
after a discussion with @edouard-lopez we are not going to offer a way to save master password.
All the security of current passwords and future passwords is based on this master password.

We will work hard to help the user and fill in more fields automatically.

I close this one
