### ISSUE TITLE
Simplify loading of default options and old password profiles

### ISSUE THREAD

**Issue by zazard** [lesspass/lesspass#183]
Hey,

First, thanks for a great piece of software, looking forward to even more stuff :)

After some time (seems like 1-3 minutes ? Not sure), the extension automatically logs out of lesspass.com. I don't know if it's a bug or a feature, but that's not really the problem.

Problem is, after I log back in, the first profile I create sometimes erases an existing profile. I do not have this problem at all on the Android app. I have not succeeded yet in isolating the EXACT circumstances in which the problem arises, but I'll keep trying (It's not ALWAYS the case, just very frequent, and just once after logging in to lesspass.com)

Also it seems that the default settings I set while logged in to lesspass.com are reset after I get logged out and log back in. For example, I set my default password length to 32, get logged out automatically shortly after, and when I log back in, the default password length is reset to 16.

o/

**Comment by guillaumevincent** [comment]
@zazard let me try to reproduce the bug on my side

No the extension should not logout after 1 minute, the master password and generated password should be cleaned.

The default options are loaded when you open the app except when you open the app 1 minute before last generation. It will load the last profile.

But there is some tests I don't understand: https://github.com/lesspass/pure/blob/master/test/store.mutations.js#L123
Maybe I had to be drunk at that moment. 
Let me rename this issue and clear loading process.

thanks

**Comment by zazard** [comment]
The autologout problem seems to be due to overzealous cookie/session configs on my side, so nevermind.

I still get the erasure problem though ! Hope you manage to reproduce :)

**Comment by guillaumevincent** [comment]
We will try :) as soon as we have a little time
