### ISSUE TITLE
Fill in password automatically (Webextension)

### ISSUE THREAD

**Issue by vpfautz** [lesspass/lesspass#184]
Is it possible to directly insert the password in the login form? I think there is a easy solution to cover a lot of sites, where the login prompt is similar.
My ideas on doing this:
- search for form>password fields and insert the password for the given site.
- save correct id and position for every website. Would be a terrible idea to maintain
- use the form>password approach, but let the user change the insertion place if he wants to and save the position.

I don't know if this was somewhere in discussion, but from my point of view, this is a big problem in usability.

**Comment by guillaumevincent** [comment]
@vpfautz we remove this functionality because of security issue
see https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension
I close this one
