### ISSUE TITLE
Import / export profiles

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#190]
Hello, it's me again (sorry).
I was reading some issues and I was interessed in #154 

When I read it I think it's maybe close a little too fast.
It will be so awfull to add an import / export profile.

I think it can always be usefull.
When you reinstall your computer it will be a big help that not remember each configuration.

Cheers.

**Comment by guillaumevincent** [comment]
@kidburglar continue to give your thought on the issue directly.
We create LessPass database for this purpose. And you can self host it.

See my last comment to understand why we are closing those issue. My post is pretty clear.
