### ISSUE TITLE
Download page for binairies

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#191]
Hellp

Where can I find binairies for the desktop apps for windows?

It would be good to build them and put them on a page (for example as attachment in the repositorie and on a page on the website of lesspass), wouldn't it?

Thank you

**Comment by guillaumevincent** [comment]
Hello,
You can build desktop app here: https://github.com/lesspass/desktop

We removed the download from the site because there were not a lot of downloads and it costs us some money and time to maintain.

**Comment by Kcchouette** [comment]
@guillaumevincent Can you think about hosting the binaries on github like others do? Or cost to maintain the binaries is still to much?

**Comment by guillaumevincent** [comment]
I'm not sure, but I think github refuse .zip with exe, no?

**Comment by Kcchouette** [comment]
@guillaumevincent no, you can use the "Release" area to publish exe and zip file (see more on the github news here from 2013: https://github.com/blog/1547-release-your-software)

**Comment by guillaumevincent** [comment]
ok so the cost part is resolve
but if we can push zip containing .exe, I'm also looking for an automatic way to push the release.
I don't want to push the release manually

**Comment by Kcchouette** [comment]
@guillaumevincent for automatically push the release, we should think about the github API: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

See too: 

- http://stackoverflow.com/a/25386660 
- https://github.com/ungoogled-software/ungoogled-chromium-binaries/blob/master/utilities/platform_ini_generator.py (the project I've pasted)
- https://github.com/aktau/github-release

**Comment by guillaumevincent** [comment]
I created an issue for this one, I don't see the global solution. How to build the application for different platform for example. But maybe somebody will have a nice solution for an automatic deployment on github.

**Comment by guillaumevincent** [comment]
@Kcchouette an idea on How to build the application for different platforms?
I remember now why I stop doing this, the build process for different platform was manual

**Comment by Kcchouette** [comment]
@guillaumevincent You can have a look at https://github.com/integrations
You can have a look too at Jenkins.

I've found some good advice here: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build.

If after some research you have something, it would be good to share your research on the lesspass wiki about the build process and the tools you use.

And in the same idea of lesspass wiki, can you do a "technical page" that lists that for eg? https://github.com/lesspass/lesspass/issues/175#issuecomment-286739314

**Comment by guillaumevincent** [comment]
@Kcchouette I already use electron builder but I can't build OSx version of LessPass on Linux or customize icon for the window build.
This is why I stop publishing LessPass Desktop.

I will try to look at some different options, but if there is no simple way, I will close #193
