### ISSUE TITLE
[cli] Update Clipboardy to 1.1

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#192]
Hello,
Clipboardy now supports Termux (https://github.com/sindresorhus/clipboardy/pull/10) so using Clipboardy 1.1 in lesspass-cli would allow me to use LessPass on my Android's phone terminal.

**Comment by guillaumevincent** [comment]
@Rudloff can you send us a PR for this one? But sure, we use the last Clipboardy version

**Comment by guillaumevincent** [comment]
already in [lesspass-cli@4.1.0](https://www.npmjs.com/package/lesspass-cli)

thank you
