### ISSUE TITLE
[Desktop] Automatic push of releases on github

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#193]
Following the discussion #191, we need to create a script to build and deploy LessPass Desktop on github release page

 * [ ] build the application for different platforms
 * [ ] create a script to push releases on github

**Comment by panther2** [comment]
Interesting, but #191 does not say **why** we need those additional apps.
What purpose could they have that is not given by using the browser?

**Comment by Kcchouette** [comment]
I think we can answer to your question @panther2 by what if you use other browser than firefox and chrome (and their derivated browser)? (for eg Safari, IE/edge, Opera)

**Comment by panther2** [comment]
AFAIK Lesspass works fine in those browsers, does it not?

Just wondering what I might have missed so far...

**Comment by Kcchouette** [comment]
@panther2 ca you link me the itunes URL for Safari? I found nothing when I've searched it.

**Comment by guillaumevincent** [comment]
@Kcchouette there is no Safari web extension because it cost 99$ per year (Apple Developer Program)  and moreover Safari does not implement webcrypto

**Comment by panther2** [comment]
Why itunes for Safari? Just use Safari to browse to www.lesspass.com. 

Or do you want a desktop application as a surrogate for a non exisiting browser extension? Then say so!

In that case again my above question: 
What purpose could the desktop app have that is not given by using the browser?

What am I missing?

**Comment by Kcchouette** [comment]
@panther2 offline version?

**Comment by panther2** [comment]
@Kcchouette 
Indeed they can.

Don't misunderstand me... I am not against this request.
I am just wondering why I never missed a desktop app ... and why it might be nevertheless useful to others and me..

**Comment by guillaumevincent** [comment]
I put this issue to keep the idea somewhere. @edouard-lopez or me are not going to work on this one soon, except if the community start to use the desktop app a lot.
Do not spend too much energy on it, thanks

**Comment by guillaumevincent** [comment]
I close this one, 
we should encourage browser web extension instead of native app on the desktop.
And there is no easy solution to build the app on different platforms.
It will take some time
