### ISSUE TITLE
Automate the deployment of web extensions

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#194]
## Firefox
> You can upload a new version for signing by issuing a `PUT` request and including the contents of your add-on in the upload parameter as multi-part formdata. This will create a pending version on the add-on and will prevent future submissions to this version unless validation or review fails.

http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version

## Chrome
https://developer.chrome.com/webstore/using_webstore_api

**Comment by Kcchouette** [comment]
I think you can link too with #193 push release on github

**Comment by panther2** [comment]
That was quick for Chrome! Awesome!

**Comment by guillaumevincent** [comment]
Yeah and there is no manual intervention, a tag on master and the extension will be on production

**Comment by edouard-lopez** [comment]
@guillaumevincent I might have missed it, but how does your archive is pushed to the store?

**Comment by edouard-lopez** [comment]
Ok, it's a [Travis hook](https://github.com/lesspass/webextension/blob/74a642ae599d56164d8cfbf6e4b4c299bd9138a3/.travis.yml#L10
) plus a [NPM script](https://github.com/lesspass/webextension/blob/74a642ae599d56164d8cfbf6e4b4c299bd9138a3/package.json#L14) from `package.json`.
