### ISSUE TITLE
Add a "technical detail" section in the wiki

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#197]
As i've written here https://github.com/lesspass/lesspass/issues/191#issuecomment-291835832 can you add a "technical detail" section in the wiki?

This section can contains the restriction for the one who wants to do tierce application for system that lesspass don't cover, for example theses details:

```
min length password: 5
max length password: 35 (because of the length of the entropy we consume)
min counter: 1
max counter : not defined
```

**Comment by guillaumevincent** [comment]
@Kcchouette feel free to add some info in the wiki: https://github.com/lesspass/lesspass/wiki/Generated-password-info

**Comment by Kcchouette** [comment]
@guillaumevincent I'm sorry but I can't, it's restrict to you only?

I don't know how work forking/Pull Request on GitHub wiki, forking a repo doesn't fork the wiki :/

**Comment by guillaumevincent** [comment]
yes you can now
Sorry

**Comment by Kcchouette** [comment]
closed with https://github.com/lesspass/lesspass/wiki/Technical-Detail/7666a3c1a38cd9936b251b1028d3eee13c2e558d

**Comment by guillaumevincent** [comment]
Thanks, I moved it into https://github.com/lesspass/lesspass/wiki/Generated-password-info

**Comment by WagnerGMD** [comment]
For the moment, none warning is present on the page : [lesspass_v2.4.10](https://addons.mozilla.org/en-US/firefox/addon/lesspass/).
Then I will assume it might be better to recopy the message : `Please select a value that is no more than 35`. In the case it might help somebody else to find the answer (check out the last links on the [lesspass wiki](https://github.com/lesspass/lesspass/wiki/) (at the bottom))
