### ISSUE TITLE
[Frontend] Reorganize the "Supported Platforms" part

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#198]
Some ideas of how to do that:
```
<h2>Supported Platforms</h2>
	<h3>On your mobile phone</h3>
		(put here links for android & ios version)
	<h3>Directly on your browser</h3>
		(put here links for firefox and chrome)
	<h3>On your desktop</h3>
		<h4> With a graphical UI</h4>
			We don't have yet binaries for your desktop, but by installing [NodeJS](https://nodejs.org/dist/v6.10.2/)
		you can build and run your desktop client, see more here: https://github.com/lesspass/desktop
		
		<h4>Terminal/cli version</h4>
			We don't have binaries yet, but you can install it easily by using [NodeJS](https://nodejs.org/dist/v6.10.2/), 
			see more on https://github.com/lesspass/cli#install
		
		For Linux user, we have a [snapcraft](snapcraft.io) package of the cli version: sudo snap install lesspass
	<h3>You also can self host LessPass on a server</h3>
		We have a [Cozy Cloud](https://cozy.io/en/), see more here: https://github.com/lesspass/cozy#install
		
		And you can even host your own LessPass Database using [Docker](https://docs.docker.com/engine/installation/#get-started) on your server.
		More info here: https://github.com/lesspass/lesspass/#self-host-your-lesspass-database

<h2>Contribute to LessPass</h2>

By going here: https://github.com/lesspass/lesspass/issues/
```

Like that we can see easily for each situation what we have (if we want on server, on a desktop or on a smartphone)

What's the concept under sandbox? Is it a testing repo? And for nginx-lesspass? Is it a repo for the docker LessPass Database?

**Comment by guillaumevincent** [comment]
I close this one, we are not promoting desktop app because we don't offer support for it now.
Will improve frontend after #193 

The description of the repo can help: https://github.com/lesspass/lesspass#lesspass-submodules

**Comment by Kcchouette** [comment]
@guillaumevincent what about the same thing but without desktop app:

```
<h2>Supported Platforms</h2>
	<h3>On your mobile phone</h3>
		(put here links for android & ios version)
	<h3>Directly on your browser</h3>
		(put here links for firefox and chrome)
	<h3>You also can self host LessPass on a server</h3>
		We have a [Cozy Cloud](https://cozy.io/en/), see more here: https://github.com/lesspass/cozy#install
		
		And you can even host your own LessPass Database using [Docker](https://docs.docker.com/engine/installation/#get-started) on your server.
		More info here: https://github.com/lesspass/lesspass/#self-host-your-lesspass-database

<h2>Contribute to LessPass</h2>

By going here: https://github.com/lesspass/lesspass/issues/
```

And add when you want the desktop part?

It's just to be more clear of what you have in term of application.

**Comment by guillaumevincent** [comment]
> It's just to be more clear of what you have in term of application

more clear doesn't mean anything, we revamp one month ago. We got your solution before.
https://github.com/lesspass/frontend/commit/27f5e3d45b30b553f592fe53d3d0d4e634be4f0b

so no it's not more clear.

These last 3 days we spend too much time managing small issues.
Can you get us back bugs and avoid procrastination.
There are more important things and bigger things to do. 

Try to find a little more information, to save us time.
Thank you.

**Comment by Kcchouette** [comment]
@guillaumevincent You can focus on main bugs. Normally on theses improvement, I don't receive answer before 1 week or even more. If I should put a severity, I'll put "enhancement minor" or even less.

As a new user, I'm trying to help the project with my point of view and my idea of the moment to be a more user-friendly front website (the download page in lastpass website is for example more clear - with windows, linux, mac, mobile section https://lastpass.com/misc_download2.php )

Sorry that you have more thing "more important than the small issues I'm posting" and that my issue "help to procrastinate"

And remember that a first user will see the frontend page BEFORE the bugs that have the software, and a developer will see the technical detail BEFORE using it.

**Comment by guillaumevincent** [comment]
Yes and we are going to improve

> a more user-friendly front website

Without measurement `more user-friendly` don't got any value. This is a feeling, not a fact.
I would have prefer an issue with feedback, not an issue saying, `you should do like that`.

Something like:
```
As newcomer, I found difficult to ....
Here my workflow ....
```

A lot of issues doesn't help, it creates noise. 
I don't like issue 'for the future'. Will see in the future so.

We love feedback and we love to construct our solution with the community.
