### ISSUE TITLE
Offline Version does not work

### ISSUE THREAD

**Issue by SoftwUser** [lesspass/lesspass#200]
I am for the first time trying to run the offline version (4.5.0) as described in #68 using latest Chrome stable.

After starting `index.html` I only get a blank screen.
This is what I get from Chrome console:

![pure](https://cloud.githubusercontent.com/assets/26350225/24763673/5c2b9cd6-1af2-11e7-9718-734c61c11b0e.PNG)

Am I doing something wrong? Or is it a bug?

**Comment by guillaumevincent** [comment]
No Chrome refuse to access Window for a local file.
Maybe for security reason.
We can't do anything about this.

So it's a Chrome feature. 

FYI Chrome web extension works offline. Maybe you can take a look at https://github.com/lesspass/desktop
