### ISSUE TITLE
GUI allows negative values...

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#203]
... or positive but lower than intended values - and (of course) fails to create a password then:

![lp](https://cloud.githubusercontent.com/assets/20812775/24799025/6a2774b6-1b99-11e7-9c33-1c8a9261c382.gif)

This is from the Website.
The same is valid for the Chrome extension, too.

Chrome console shows this:

![lpx](https://cloud.githubusercontent.com/assets/20812775/24799125/e5d0cb26-1b99-11e7-8182-a9905756ac7f.PNG)

**Comment by Kcchouette** [comment]
I think the javascript command overwrite the html limitation fixed by the code (on the lesspass-pure, ` v-on:click="options.length+=1"`.

A verification like `SiteLoginMasterPasswordMandatory` should do the trick

**Comment by edouard-lopez** [comment]
It sounds similar to #133

**Comment by edouard-lopez** [comment]
@guillaumevincent could you review lesspass/pure@afe7700, build and push?

**Comment by panther2** [comment]
@guillaumevincent @edouard-lopez 
In the desktop app the restrictions apply now.
I suppose the browser extension(s) take some time to update?
Also on `lesspass.com` I can still enter negative values.

**Comment by guillaumevincent** [comment]
@panther2 yes, I'm working on #194 and try to push webextension automatically
It will be soon on Chrome, and in 2 weeks for Firefox web extension :(
