### ISSUE TITLE
help migration between hosting solutions

### ISSUE THREAD

**Issue by CircleCode** [lesspass/lesspass#204]
Since less pass promotes self hosting, a lot of users may want to try it on lesspass.com before switching to any other self hosting solution.
In that case, they would have to "migrate" their profiles from lesspass.com to their other hosting solution.

this migration can consist of 2 steps:

- [x] export profiles from a host
- [x] import profiles into a host

The export could either

- return a structured files (json or any other format) with profiles definition
- return the previous file encrypted with the master password

Since there can be several backends, the export and import part may need to be done on the client side.
Maybe the import and export tools can even bee totally independant tools.

**Comment by edouard-lopez** [comment]
Thanks @CircleCode, that's an interesting suggestion. 

Is this your use case or a speculative one? 
I'm asking because we try to focus on use-cases where users can provide feedback as it help drive the project toward the solution that fit best.

**Comment by CircleCode** [comment]
It could be my case. let me explain
I currently do not have hardware to run docker compose version of lesspass.
I may get some (or not) in a future, but I could also wait for #91.
In any case, I'm a little bit reluctant to the idea of hosting my passwords ; and it can be a no go if I have no way to leave the hosted version in order to migrate to a self-hosted one.

**Comment by edouard-lopez** [comment]
Just to be clear, we do NOT store password only the profile used to generate them (site, login and options).

It's currently possible to export your profiles as described in [[frontend] Export profile #154](https://github.com/lesspass/lesspass/issues/154#issuecomment-291073736).

You can follow #60 as it will help on the subject.

**Comment by guillaumevincent** [comment]
@CircleCode I wrote two scripts in the wiki to help you [managing your password profiles](https://github.com/lesspass/lesspass/wiki/password-profiles-manipulation-scripts) between LessPass Databases.

I close this one
