### ISSUE TITLE
Possibly incorrectly added German translation

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#207]
@guillaumevincent 

I saw two new phrases having been added to the German translation files:

```
25 "Next": "Neben",
...
31 "Previous": "Früher",
```

This appears to be translated incorrectly, given the English or French phrases I have compared them with.

I have a feeling that "Next" should be translated to "Nächstes"
and "Previous" to "Vorheriges" 
but to be sure I need the context, in which those words are needed.

Thank you!

**Comment by guillaumevincent** [comment]
@panther2 I use google translate from English to German. 
Can you confirm `Nächstes` and `Vorheriges` in pagination (Next page and previous page)

**Comment by panther2** [comment]
@guillaumevincent 
Indeed Google Translate is tricky sometimes, not knowing the context of words.
("Neben" would mean "à côté de qn/qc" and "Früher" would mean "plus tôt".)

In pagination the correct translation for "next page" and "prevoius page" would be
`Nächste` and `Vorherige`  (Seite).

**Comment by guillaumevincent** [comment]
Ok so you confirm:

    "Next": "Nächste",
    ...
    "Previous": "Vorherige",
