### ISSUE TITLE
What's the point of saving locally?

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#208]
I sometimes read about the benefits of storing LessPass-related information locally.

When talking about "saving locally" the local storage/browser cache is addressed.

Personally I am used to regularly clean the browser cache. So I would delete all the information that has been locally stored. So what's the point?

Do those who store locally never clean their browser cache?

What sort of data do I need to uncheck/exclude when cleaning Chrome's cache to prevent LessPass-related data from being deleted?
- Browsing History or
- Cached Images and Files or
- Cookies and other site data or
- Images and Files in Cache or
- Hosted App-Data or
- ?

Thank you for your help.

**Comment by guillaumevincent** [comment]
@panther2 only local storage is used.
You can see the information saved in local storage on https://lesspass.com with inspector in console `console.log(localStorage.getItem('lesspass'))`

local storage is only here to improve user experience, and we try hard not to save to much informations

> What sort of data do I need to uncheck/exclude when cleaning Chrome's cache to prevent LessPass-related data from being deleted?

probably: `Cookies and other site data`

See http://stackoverflow.com/a/37105645/866886

> In Chrome, localStorage is cleared when these conditions are met: (a) clear browsing data, (b) "cookies and other site data" is selected, (c) timeframe is "from beginning of time".

**Comment by panther2** [comment]
Thank you, I am not sure I like this feature, though, as saving any information locally appears to be counter-productive to the purpose of LessPass, IMHO. But using this or not is up to the user, of course.

**Comment by Kcchouette** [comment]
See an interesting explanation, I've added it to your wiki

**Comment by panther2** [comment]
Additionally I have realized when testing, that I have to change my cookie-management to make this feature work. On "delete cookies when closing browser" the local storage is deleted, too....

**Comment by guillaumevincent** [comment]
Thanks
I close this one after the @Kcchouette add in FAQ
