### ISSUE TITLE
Chrome extension update pending

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#210]
After #194 and the resulting very fast update on April, 13th (2.4.1), I would have expected another fast update including the changes of yesterday. It looks like there is no new tag for it...
Is there something wrong with the automatic process?

**Comment by guillaumevincent** [comment]
@panther2 automatic push come when I run manually https://github.com/lesspass/lesspass/blob/master/scripts/release-webextensions.sh

I don't have end to end tests on lesspass-pure yet, so before every coding session, I wait a little to catch some bug, do more manual tests. In other words, I'm not yet confident enough to push a version on every commit. But it's coming.

I will publish the new version today :)

**Comment by panther2** [comment]
Got it updated some minutes ago. Thanks.

**Comment by edouard-lopez** [comment]
@guillaumevincent I started to play with [nightwatch.js](http://nightwatchjs.org/) for end-to-end test for a work's project. Writing tests is pretty straight-forward, here are some starting point:

* [nightwatch config](https://github.com/akema-fr/apidae-frontend/blob/acd848159b1fcabe229004b030758ff813998f09/nightwatch.json)
* [npm run test:e2e](https://github.com/akema-fr/apidae-frontend/blob/acd848159b1fcabe229004b030758ff813998f09/package.json#L8) 
* [testing app title](https://github.com/akema-fr/apidae-frontend/blob/acd848159b1fcabe229004b030758ff813998f09/test/e2e/index.js)
