### ISSUE TITLE
Chrome extension doesn't populate "site" field correctly

### ISSUE THREAD

**Issue by tatums** [lesspass/lesspass#212]
I believe I've found a bug in the Chrome extension.  It doesn't appear to populate the "site" field correctly. I would expect the web and Crome extension to behave the same.  See GIF below.

Let me know if you need anything from me and cheers!

Chrome Version: 57.0.2987.133 (64-bit)
OSX Version: Sierra 10.12.4

![lesspass](https://cloud.githubusercontent.com/assets/72979/25383652/a57ad890-2982-11e7-90b9-b648a354577b.gif)

**Comment by guillaumevincent** [comment]
@tatums nice catch
it's a bug, the PasswordGenerator page always load the url and replace the site.

**Comment by guillaumevincent** [comment]
I removed your gif
