### ISSUE TITLE
Webextension's password display is a bit too small

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#214]
Currently, when hitting the "View" icon, only 14,5 characters of the created password are shown (Chrome webextension):

![lesspass](https://cloud.githubusercontent.com/assets/20812775/25434766/e20f12ec-2a8d-11e7-9066-bf58288d674a.PNG)

So you need to enter the cursor into the display field to show the rest. 

As well the website as the desktop version as the Android version (when in landscape mode) show at least the (default) 16 characters and even more.

So I would like to ask to enhance the password display to show at least the default 16 characters.

Nothing of high priority of course....

Thank you!

**Comment by guillaumevincent** [comment]
@edouard-lopez can we remove the eye icon and reveal password on simple click on obfuscated password?

**Comment by edouard-lopez** [comment]
@panther2 could you elaborate on why you want to reveal the generated password?

**Comment by edouard-lopez** [comment]
@guillaumevincent 
The eye icon is becoming a convention to toggle password visibility. Removing the icon go against that. Also we should have different icons for the different states (eye vs. slashed-eye).

How do you toggle off the visible password without the button?

**Comment by panther2** [comment]
@edouard-lopez 
@guillaumevincent 

> @panther2 could you elaborate on why you want to reveal the generated password?

Sure, with pleasure:

- At first - as the possibility is given by this feature - I would like a consistent behaviour of this feature on all platforms. So consistency would include the webextension to show at least the default 16 characters, too.
- Another question is if the revealed display of the password is a necessary feature. And I would say yes it is, as copying the hidden password to the clipboard and pasting it to any internet service does not cover all the different user cases. Take as an example a cash dispenser's PIN. Cash dispensers of today allow a user generated password longer than 4 digits. I need to see the generated password to be able to enter it into the cash dispenser.
- The third argument - it is a weaker one but still valid IMHO - having several devices I sometimes like to check and confirm that the generated passwords are the same on all device. Thus I need to see the revealed passwords, too.

**Comment by edouard-lopez** [comment]
@panther2 thanks for taking the time to reply.

## Discussion

### Consistency

On my Linux/Firefox I checked how many characters were visible and as I expected it's not the same as you. 
**I only see `13` characters**:

![master-password-characters-count-firefox](https://cloud.githubusercontent.com/assets/1212392/25639099/f33412e6-2f8a-11e7-8f83-219d8261ff84.png)

Same device but with Chrome (`13.5` characters):
![master-password-characters-count-chrome](https://cloud.githubusercontent.com/assets/1212392/25639265/8c1af326-2f8b-11e7-8932-f91f1ed4e7ed.png)

We could use a custom external font, but that will add a third-party we don't want.

**Consistency across platforms require a lot of human and technical resources** as you've to valid on different devices, form-factor, resolution, font-size, browsers and a varieties of others parameters that will make this an unrealistic goal.

Still we might be able to improve the situation with low cost.

### PIN

They are usually short `4-6` chars long, far from `16`. **The longer the PIN code the rarest it sounds**. 
So requiring so much investment for for such rare scenarios seems an inefficient use of our time.

### Manually Check

I did this once or twice on mobile device to verify a generated password after some failed attempts, but the bottleneck was more related to smart-phone keyboard behavior (auto-cap, auto-punctuation) than with the algorithm.
The visual checksum is here to help verify you input the correct value for MP as site and login are directly visible. 

We do not ease **manual validation as it goes against the project's goal** (remembering less password).

## Thoughts

I realize the _visibility toggle_ is more of a legacy from where we came from (stored password) than a major feature. But I still think it's **important for the on-boarding** for new users to whom we must gain trust and some corner case where it is useful.

## Solution

We could:
* play with the padding to reduce it a tad ;
* increase the component width a bit.

**Comment by panther2** [comment]
@edouard-lopez 
I agree, that this issue should not cost too much time and efforts. Actually I had indicated that in my very first posting when saying: 
`Nothing of high priority of course....`

Regarding **consistency** I did not expect different results on other platforms. I only have my own different devices, this is where my request originated from. One out of five shows the behaviour I posted.
I agree that the broader the issue turns out to be the higher the efforts to solve it might be and one has to question if it is worth this effort.

Regarding the **PIN** I stated explicitly that this was an **example** for a possible OFFLINE use. Now to reduce this argument to the consequence of saying 
> So requiring so much investment for for such rare scenarios seems an inefficient use of our time.
is a negation of my efforts to answer your question seriously. Of course there are other OFFLINE uses that require visibility of the Password. I have to know and frequently change log-in passwords for several computers when booting, for example. I have to enter non-trivial login passwords to business-related devices before I go online with them.... 
I never asked you for introducing a new feature. I only asked for "optimizing" a feature that **you** have provided, that has **already been present** for good reason!

Regarding the **manual check**: Before using Lesspass I used a similar solution which turned out to show different results on different devices/platforms for a while. 
It has been a problem of **Output** and not of **Input** .  Of course I want to test it from time to time. Also I fail to see why comparing the password output of different devices is an ease of
> manual validation as it goes against the project's goal (remembering less password).
as I don't have to remember any additional password when comparing the analogy of the output.

In the past I have sometimes issued optical aspects and helped out solving them by creating (simple) pull requests. Also I have contributed by doing the German translation. So I never had the intention to waste your time, to cause unnecessary efforts or to hinder the project from moving on.

**Comment by guillaumevincent** [comment]
@panther2 you probably miss understood the answer from @edouard-lopez and @edouard-lopez overestimate the time to fix this bug.

We are going to increase the size of the input to see 16 characters because seeing only 13 chars is a bug. That why I added the bug tag.

@panther2 no worries, you do not waste our time

**Comment by edouard-lopez** [comment]
@panther2 I apologized, my intent was not to refute or minimize your contributions. I'm really glad you take time to do PR and give feedbacks as it help us and the community.

Please, Ignore the "Discussion" section as it's articulation was wrong and started as a rebuttal :S

I aim to be as constructive as I can in my exchanges and provide or bootstrap solutions but sometimes I just fail :sweat_smile:

**Comment by panther2** [comment]
@edouard-lopez 
I appreciate your apology, no hard feelings!

@guillaumevincent 
Thank you.

**Comment by guillaumevincent** [comment]
![screen shot 2017-05-20 at 09 45 02](https://cloud.githubusercontent.com/assets/943762/26274209/8ae7597e-3d44-11e7-8aad-19b41ddc12be.png)

Simplify the generated password toolbar, removing space.

**Comment by panther2** [comment]
Awesome, thanks!
