### ISSUE TITLE
Clipboard security on android 

### ISSUE THREAD

**Issue by ElectricCookie** [lesspass/lesspass#219]
_This is something I first saw in a KeePass client for Android._ 

Since the clipboard can be read by any app on a phone without any notification implementing a custom keyboard is a securer workaround. 

Using this method the password is entered directly without the clipboard every containing the password.

Not sure how it is managed on the iPhone (can apps read the clipboard?)

**Comment by guillaumevincent** [comment]
@ElectricCookie there is no "user friendly" alternative. See https://github.com/lesspass/lesspass/issues/157
