### ISSUE TITLE
[Core] Build an official minified js file

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#220]
Hello

can you provide the `lesspass.min.js` file like before?

Last commit remove it, I hope it's planned to put it before here: https://github.com/lesspass/core/tree/master/dist

Thank you

**Comment by guillaumevincent** [comment]
Hi @Kcchouette, 
the lesspass.min.js is in dist folder after you install lesspass no?

    npm install --save lesspass

**Comment by Kcchouette** [comment]
I do not build on my own.

I'm asking if you can put this file in the core project, in https://github.com/lesspass/core/tree/master/dist

**Comment by Kcchouette** [comment]
Thank you :)

**Comment by guillaumevincent** [comment]
@Kcchouette sorry the file isn't minified
Maybe prettier error, let me fix this
