### ISSUE TITLE
V1 to be removed tomorrow

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#222]
Just a friendly reminder:
![lesspass](https://cloud.githubusercontent.com/assets/20812775/25905869/5d551242-35a3-11e7-8469-2d252afad028.PNG)

**Comment by guillaumevincent** [comment]
yes but we are not removing v1 without a way to migrate password for version 1 to version 2.
Il will update the message

**Comment by guillaumevincent** [comment]
@panther2 : message check

> Version 1 ist veraltet und wird bald gelöscht werden. Wir empfehlen Ihnen dringend, Ihre Passwörter auf die Version 2 zu migrieren.

is it ok?

**Comment by panther2** [comment]
That's perfect!

**Comment by guillaumevincent** [comment]
I will be fixed soon everywhere
Thank you @panther2 for your vigilance ❤️
