### ISSUE TITLE
Firefox extension does not open in Ubuntu 16.04

### ISSUE THREAD

**Issue by Roald87** [lesspass/lesspass#225]
I've installed version 2.4.6. of the Firefox add-on via the Mozilla's addon platform. The logo appears, but when I click on it, only a very small window (?) opens: 
![lesspass](https://cloud.githubusercontent.com/assets/20192767/26059304/990156fc-3981-11e7-816d-ba8daa02cc1a.png)

I'm running Ubuntu 16.04.2 LTS. It does work with Firefox on Windows.

Is anyone else facing this issue?

**Comment by guillaumevincent** [comment]
@Roald87 Can you give me your Firefox version?

in a terminal:

    firefox --version

**Comment by Roald87** [comment]
Mozilla Firefox 53.0.2

**Comment by guillaumevincent** [comment]
Strange, I'm running the extension on Ubuntu 14.04 and Fedora 25 without any problem
:(

Do you have more information on debug addon. In your URL enter `about:debugging#addons`

**Comment by Roald87** [comment]
I moved my profile data with `mv ~/.mozilla/ ~/mozilla-backup` and booted Firefox. Then installed Lesspass and now it works. Maybe I screwed up my Firefox somehow.

**Comment by guillaumevincent** [comment]
Ok don't hesitate to reopen if the problem reappears
