### ISSUE TITLE
Chrome extension view is too narrow on Vivaldi if the "panel" bar is on the right side

### ISSUE THREAD

**Issue by ColtonDRG** [lesspass/lesspass#226]
![screenshot](https://cloud.githubusercontent.com/assets/5587661/26091283/7807fa82-39c7-11e7-89e8-2d2de68d3672.png)

**Comment by guillaumevincent** [comment]
@ColtonDRG Don't you think it's a Vivaldi issue?
Vivaldi doesn't respect the body size of the popup.html

**Comment by ColtonDRG** [comment]
I suppose it might be, but I didn't encounter the issue with any other extension.

Also, after some further testing, it seems like it actually doesn't matter which side the panel bar is on, it's still too small. I honestly have no idea what would cause this.

**Comment by guillaumevincent** [comment]
@ColtonDRG ok I will test this and try to see if there is an issue I can fix on LessPass.

**Comment by ColtonDRG** [comment]
I just realized what the actual problem is. Vivaldi has an option for interface scaling, (it makes the UI elements smaller or larger than normal). Extension panels are supposed to be scaled too, so the window gets scaled, but the contents of the embedded page does not. I am still unsure as to why LessPass is the only extension I have that behaves abnormally, all of my other extensions scale the contents of their panel accordingly.

**Comment by guillaumevincent** [comment]
@ColtonDRG thank you for your tests. If you have another open source webextension working perfectly on your browser, let me know

**Comment by ColtonDRG** [comment]
Some open source extensions I have that are working okay...
uBlock Origin: https://github.com/gorhill/uBlock
HTTPS Everywhere: https://github.com/EFForg/https-everywhere
Privacy Badger: https://github.com/EFForg/privacybadger

**Comment by guillaumevincent** [comment]
strange bug,
if you click a lot on the extension sometime the layout fit in the window
try to find why

**Comment by ColtonDRG** [comment]
Huh, I never noticed that before, but you're right. If I click on it rapidly it seems to correct itself at random. It almost seems like sometimes, if you close and reopen it again rapidly enough, it doesn't reload the contents of the window, and therefore it scales the contents of the already generated window. So maybe when the window is being drawn by the javascript, it's losing the scaling applied by the browser somehow?

**Comment by guillaumevincent** [comment]
Yes but I don't know why :(
I keep this bug open

If someone have and idea :

 * put zoom to 90%
 * Open extension

**Comment by guillaumevincent** [comment]
Vivaldi uses the Blink rendering engine as Google Chrome or Opera.
But the bug is not present on Google Chrome.

So I close this one, more a bug related to Vivaldi.
