### ISSUE TITLE
Bugs with profile password and resetting password

### ISSUE THREAD

**Issue by Roald87** [lesspass/lesspass#227]
I noticed some bugs when creating a profile and resetting your password.

1. When logging in into your profile and you select _Encrypt my master password_ the box does not stay ticked. Or is this intended behaviour?
2. I tried to reset my profile password. I got the mail. Followed the link. Filled in a new password (why only one box btw?) and clicked _Reset Password_. There was no response from the page, but it did reset my password.
3. There is no option to encrypt your password when you are sent to the reset page.

**Comment by guillaumevincent** [comment]
Hello,

> When logging in into your profile and you select Encrypt my master password the box does not stay ticked. Or is this intended behaviour?

Is the intended behaviour. If you did a mistake, you can replace the existing generated password and restart again. Maybe the checkbox is not a good input in term of user interface.

> I tried to reset my profile password. I got the mail. Followed the link. Filled in a new password (why only one box btw?) and clicked Reset Password. There was no response from the page, but it did reset my password.

This is a UX bug.
I will confirm this and add an issue.

> There is no option to encrypt your password when you are sent to the reset page.

yes, we need to add the feature on this page see: https://github.com/lesspass/lesspass/issues/110

**Comment by guillaumevincent** [comment]
1. I redesign the feature with a button

![screen shot 2017-05-20 at 12 40 35](https://cloud.githubusercontent.com/assets/943762/26275111/95aea9c4-3d59-11e7-86b8-610e02438547.png)

2. you where right, there was a bug with the translation in reset password page
3. I added the encryptMasterPassword component in the reset page, this is fixed now

Thank you for your bug report, this will be in production next week
