### ISSUE TITLE
Can't login via iOS => Safari

### ISSUE THREAD

**Issue by Commifreak** [lesspass/lesspass#228]
When I try to login to the profile manager via Safari and check: Encrypt Master password, the password did not get encrypted (I notice that, because the Icons do not change after hitting the checkbox). Because of that, Login is not possible.

Can you reproduce that? Running Safari on iOS 10.3.2 (iPhone 6s)

**Comment by guillaumevincent** [comment]
@Commifreak let me check this one
did it work on Chrome or Firefox on your device?
My first idea is a bad implementation of webcrypto in Safari. See pbkdf2 SHA-256 on https://diafygi.github.io/webcrypto-examples/

**Comment by Commifreak** [comment]
Ill try this asap.

The linked live page show me the attached pic.



Gruß,
R. Kluth

**Comment by Commifreak** [comment]
![img_1021](https://cloud.githubusercontent.com/assets/87267/26165466/587f33dc-3b30-11e7-9950-d43c2a1a41ca.PNG)

**Comment by Commifreak** [comment]
More details:

* When using Safari -> Add to Home-Screen, it creates an "web-app". This was the 1st thing I did before testing LessPass. Unfortunately, these WebApp does not work with LessPass, the "Encrypt Master password" checkbox does not work.

When using real Safari, it takes a few secs to encrypt it, but it is working.

So, I my eyes we can close this bug?

**Comment by guillaumevincent** [comment]
hum this is strange Oo
I will try to add Home screen button on an iphone 6 to see if the bug is confirmed

**Comment by panther2** [comment]
I can confirm this issue on my iPad Mini.

**Comment by panther2** [comment]
Ignore the Chrome thing, I tested erroneously.

**Comment by guillaumevincent** [comment]
@Commifreak I close this one
I tested on an iPhone 6: Share button > Home Screen Button and it works
It's slow, but it works
