### ISSUE TITLE
Lesspass unusable on my osx computer: Lesspass.com "generate" unresponsive. Lesspass firefox extension will not generate passwords.  [Firefox/mac10.10.5]

### ISSUE THREAD

**Issue by saluk** [lesspass/lesspass#232]
When I click "generate" in order to generate a password at lesspass.com, nothing happens. When I use the lesspass firefox extension, the generate button turns into "generating" and then never does anything. 

Strangely, on this same computer if I use chrome, lesspass.com will generate a password, but always generates it with the default options. I am unable to change the character length or symbols used in the generated passwords.

The site works fine on my android phone.

OSX Yosemite 10.10.5
Firefox 45.9.0 esr
Chrome Version 43.0.2357.81 (64-bit)

**Comment by guillaumevincent** [comment]
Hello @saluk 
you are using an old version of Firefox and Chrome. Can you update your browsers?
LessPass needs recent browsers

Chrome 43.0.2357 release date 2015-05-19 (Linux, macOS and Windows)
Firefox 45 has a broken webcrypto implementation

**Comment by guillaumevincent** [comment]
I close this one, feel free to add any update if after the upgrade you encounter the issue again
