### ISSUE TITLE
Firefox extension: can't login

### ISSUE THREAD

**Issue by 0xCA** [lesspass/lesspass#233]
I fill everything, see correct visual checksum, encrypting, see correct encrypted-checksum, hit "Sign In" and nothing is following.
Works perfectly on the site and in the android app.
Also no auto-fill for e-mail in login form.

**Comment by guillaumevincent** [comment]
The auto fill is disabled by Firefox in web extension.
I tested the login on Firefox 2.4.10 and it works. strange
@0xCA which version do you have?

**Comment by 0xCA** [comment]
I have 53.0.3 x64.

**Comment by guillaumevincent** [comment]
@0xCA version of LessPass Web Extension?

`about:addons` > LessPass (more)

**Comment by 0xCA** [comment]
2.4.10

**Comment by guillaumevincent** [comment]
@0xCA thanks for taking the time to debug
I close this one and opened another issue for the confirmation pop up bug https://github.com/lesspass/lesspass/issues/235
