### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Commifreak** [lesspass/lesspass#237]
Sorry for the question - how may I update the docker image and setup a new container with the new image without lossing any data?

**Comment by guillaumevincent** [comment]
Hello @Commifreak 
first you can backup your data. 
See production backup script: https://github.com/lesspass/lesspass/blob/master/scripts/backup_db.sh

Then you can see deploy.sh: https://github.com/lesspass/lesspass/blob/master/scripts/deploy.sh

But the tldr:
```
# pull new images
docker-compose pull

# restart container
docker-compose down
docker-compose up -d
```

**Comment by guillaumevincent** [comment]
I close. 
Feel free to post on this thread to ask for extra help.
