### ISSUE TITLE
Improve Password Profile Update

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#238]
This is the use case:

Sometimes when browsing I am accessing many websites where I need to log in using the LessPass extension during a short time.
For example I am quickly checking my mail, then move to Github ....

In some cases I note that in the given example the chrome extension still has the mailprovider-url entered as "site" as well as my mail login when I actually already am on the Github login-site now.

I have to manually overwrite the site name and the login name then.

When does LessPass "refresh" the site info? Is there sort of a timer?

Is there a more elegant way to refresh the information? Or at least to delete/remove the "old" information added by the prior website?

Thank you!

**Comment by guillaumevincent** [comment]
Hello @panther2 
yes when you generate a password LessPass store the related password profile in local storage.
If you reopen the webextension during 1 minute, we reload the same password profile for you.

See https://github.com/lesspass/pure/blob/master/test/store.mutations.js#L171-L235

It's useful when you are on {url} and you generate a password for a new {site}. But the registration fails because {site} had dumb password rules. So you reopen the web extension, uncheck for example symbols, and regenerate password.

> Is there a more elegant way to refresh the information? Or at least to delete/remove the "old" information added by the prior website?

If you click on title `LessPass` it clears the saved password profile.
But you are right, we should improve in term of user experience for this specific use case.

Thank you for your feedback, this is another use case! Love this

**Comment by panther2** [comment]
@guillaumevincent 

Thank you for your feedback on this issue. 

> It's useful when you are on {url} and you generate a password for a new {site}. But the registration fails because {site} had dumb password rules.

Let me add some of my user experience regarding this (for sure valid) argument, just for your "statistical information": 

I recently finished converting more than 200 passwords to LessPass V2. 

171 of them were website-passwords. Out of interest I have counted my results:

171 (all) of them accepted `a-z`, `A-Z`, `0-9`
154 of them accepted the default settings (length 16, all characters)
3 of them needed a shorter (than 16) length
14 of them needed to have the setting `%!@` disabled. That has not been due to the non-acceptance of special characters in general (maybe three cases) but because of some websites not accepting every type of special character - for example some accept `@, - , %` but not `[, >, ^`

Maybe this is not a representative number of cases, but the result is interesting anyway. Before my conversions I thought that there would be a lot more exception from the default setting.
I experienced a lot more restrictions on **non web-related** use cases, but for those the auto-fill feature can not be used anyway.

> If you click on title `LessPass` it clears the saved password profile.

Great, I had not realized that before. Thank you!

**Comment by guillaumevincent** [comment]
@panther2 can we close this one?
LessPass Move will help changing a lot of passwords. So this "bug/feature" does not appear a lot.

**Comment by panther2** [comment]
@guillaumevincent 

Oh, I have not closed it, as you answered above:

> But you are right, we should improve in term of user experience this specific use case.

I don't think that the use case of "refreshing extension data fields" when changing websites during 1 minute is covered by LessPass Move, as it is not a question of changing passwords from e.g. V1 to V2 but from "gmail" to "github" to "whatever" (as described above).

**Comment by guillaumevincent** [comment]
IMO using LessPass webextension to change passwords is not a good idea. That why we are creating LessPass Move, to help user to change their passwords quickly.

My answer was to create a better user interface to indicate that we load the previous password profile. And allow the user to clean the password profile.

wdyt?

**Comment by panther2** [comment]
> My answer was to create a better user interface to indicate that we load the previous password profile. And allow the user to clean the password profile.

That is exactly what I am talking about and the reason why I did not close this issue. 
Maybe not "clean" the password profile but "refresh" (if possible)?

**Comment by guillaumevincent** [comment]
Cool
Ok so :+1: for renaming the issue. I let you put what you think is relevant.
Thanks

**Comment by panther2** [comment]
Great, thanks!

**Comment by guillaumevincent** [comment]
related to #109

**Comment by guillaumevincent** [comment]
I created an issue (#242) and close this one because there a lot of info on this one not related to the bug you discover.
Thanks
