### ISSUE TITLE
lesspass-core.exe create cli to generate a password

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#24]
_From @sctfic on October 19, 2016 14:20_

je voudrai coupler LessPass as d'autres outils deja existant afin de remplacer l’interrogation de la base de donné des mdp.

existe t il une API REST (over https) ?

ainsi je pourrai coupler ceci a un fichier excel par exemple
		A			B			C			
1	ClientName	UserLogin0	=lesspass(A1; B1; MasterPass)
2	ClientName	UserLogin1	=lesspass(A2; B2; MasterPass)
3	ClientName	UserLogin2	=lesspass(A3; B3; MasterPass)

_Copied from original issue: lesspass/core#1_

**Comment by guillaumevincent** [comment]
Si je comprends bien la demande, il s'agit d'avoir une API qui permet de retourner un mot de passe à partir d'information passées en paramètre ?

```
POST htttps://lesspass.com/api/passwords/ {
    "login": "38491092",
    "site": "example.org",
    "lowercase": false,
    "uppercase": false,
    "symbols": false,
    "numbers": true,
    "counter": 1,
    "length": 6,
    "masterPassword": "mon master password"
}
```

Ce qui me gène c'est que le masterPassword ne devrait jamais être envoyé null part, même via https.
Le serveur devient intéressant à pirater, car il y a des masters passwords dans les logs.

Un .exe avec la même interface en command line, ne serait-il pas mieux ?

`lesspass-core.exe --login="38491092" --site="example.org" --lowercase=0 --uppercase=0 --symbols=0 --numbers=1 --counter=1 --length=6 --masterPassword="mon master password"`

**Comment by sctfic** [comment]
exact pour le problème de log, même si dans mon cas le serveur serait sur l'intranet.

Du coup l'exe en CLI serait excellent

**Comment by Rudloff** [comment]
Un paquet node lesspass-cli serait parfait pour les cas où on n'a pas de navigateur ouvert sous la main (session SSH par exemple).

**Comment by guillaumevincent** [comment]
@Rudloff quelque chose comme ça ?

    npm install -g lesspass-cli
    lesspass --login="38491092" --site="example.org" --lowercase=0 --uppercase=0 --symbols=0 --numbers=1 --counter=1 --length=6 --masterPassword="mon master password"

**Comment by Rudloff** [comment]
Exactement !

**Comment by guillaumevincent** [comment]
@Rudloff [lesspass-cli](https://www.npmjs.com/package/lesspass-cli)

**Comment by guillaumevincent** [comment]
@sctfic est ce que [lesspass-cli](https://www.npmjs.com/package/lesspass-cli) est suffisant ? Il faut node LTS d'installé sur la machine

**Comment by Rudloff** [comment]
Ça marche nickel, merci :)

**Comment by sctfic** [comment]
parfait pour linux, mais sous Windows ?

**Comment by sctfic** [comment]
je devrai pouvoir l’implémenter en Powershell si tu m'explique le code en detail

**Comment by Rudloff** [comment]
Tu peux tout à fait installer Node et npm sur Windows.

**Comment by guillaumevincent** [comment]
@sctfic il faut installer [node](https://nodejs.org/en/), ouvrir un terminal, installer lesspass :

    npm install --global lesspass-cli

et ensuite dans le terminal tu peux utiliser directement lesspass : 

    lesspass lesspass.com contact@lesspass.com 'my Master Password' --length=14 -s=false

Je cloture du coup. Mes premiers tests pour générer un exe font un bundle de 60Mo.

**Comment by sctfic** [comment]
ok, j'ai fait mon boullet, node.js je pense a linux direct.

je veins de faire le test, install sur un serveur windows.
puis ensuite je peu l'appeler en powershell depuis tous le reseau

    Invoke-Command -ComputerName MonServeur2012R2 -ScriptBlock {lesspass lesspass.com contact@lesspass.com 'myMasterPassword' --length=14 -s=false}
