### ISSUE TITLE
Translate https://lesspass.com/

### ISSUE THREAD

**Issue by JekoTronik** [lesspass/lesspass#240]
Hello LessPass team !

As your website is in english, you may consider translate the "Mot de passe fort" pre-filled sentence in the LessPass view for something more...shakespeare-ish ? Like "Strong password" or even "Your unique strong password"

Cheers !

PS : Very nice software, I like all the ecosystem (firefox, cozy, android,...) Now I have it everywhere!

**Comment by panther2** [comment]
Not sure if I understand what you are talking about; You want to see the word `Master Password` replaced by your suggestions? Or what do you assume being the translation of `Mot de passe fort` ?

Thanks for your clarification :smile:

**Comment by JekoTronik** [comment]
Haha ! Sorry about that.
In the LessPass Gui (or I don't know how it is called) there are 3 input fields : one for the website address, one for the login and the third for the "Mot de passe fort".
As "Mot de passe fort" is french, and all the lesspass.com is in english I was thinking it could be better to have everything in the same language.
While writing this message, I realize it can be applied to all the LessPass GUI (or whatever it is called :) )
Am I more understandable ? x_x

**Comment by panther2** [comment]
Ah, now I see, thank you for the clarification. 
In fact the GUI has been translated to different languages, while the "rest of the website" is always in English.

This is how it appears on German systems:

![lsps](https://user-images.githubusercontent.com/20812775/27769338-c1eb58e4-5f27-11e7-82e2-6351ac30cbb9.PNG)

It appears as `Master Password` on English systems. 

So as you obviously are on a French system, the GUI appears in French, while the "rest of the website" is still in English.

**Comment by JekoTronik** [comment]
Ok, so if I see "Mot de passe fort" (and all other french words) it is because my system is recognized as a french system ? Alright !

So I close this issue.

**Comment by guillaumevincent** [comment]
Hello @JekoTronik,
@panther2 is right, only the component is translated. The site use the same component as the web extension or the Android app. The component detects the language of your browser and loads the corresponding translation.

But the site is not translated. I reopen this one, and change the title.

❤️

**Comment by panther2** [comment]
@guillaumevincent 

Great, I volunteer to do the translation into German again, if wanted/needed.
Are you going to provide sort of an i18n-structure again for this, as you did for the component?

**Comment by guillaumevincent** [comment]
@panther2 

> Are you going to provide sort of an i18n-structure again for this, as you did for the component?

Because it worked well, we are going to do the same thing again. Nevertheless it is not for now. We got some exiting news coming. We will make an announcement during the RMLL next week.

> Also would you extend the translation to the "How does it work" blog on

All contributions are welcome!

**Comment by panther2** [comment]
That sounds interesting and definitely leaves me being curious... :smiley:

**Comment by panther2** [comment]
@guillaumevincent 

I have finished the translation of **"LessPass comment ca marche"/"LessPass How Does It Work?"** into German (LessPass - Wie funktioniert das?) for the blog. 

As the blog is independent from the repo - how can I hand the text over to you?

**Comment by guillaumevincent** [comment]
@panther2 Do you have a medium account? If yes send me your username at `contact@lesspass.com`
I will add you as a writer.

**Comment by panther2** [comment]
@guillaumevincent 

Mail sent, thank you! :smile:

**Comment by guillaumevincent** [comment]
@panther2 nice, you are allowed to write on https://blog.lesspass.com!

**Comment by panther2** [comment]
@guillaumevincent 

So just having a bit of time now I have logged in to Medium. I see the "Write a story" link there, that allows me to start after klicking.
But how do I do it for blog.lesspass.com - when going there, I see nothing that allows me to start writing.
There is nothing indicating a connection to "Medium", though I am logged in there.
So do I write starting from the Medium-Entry-Page or what am I missing?

Also is there a way to copy the layout from your French/English article and to overwrite it with German text?

Sooy for bothering you, but I can't seem to find it out from the Medium-help, as I lack the knwoledge on how "blog.lesspass.com" is actually connected to "Medium".

Thank you.

**Comment by guillaumevincent** [comment]
Hello @panther2,
try to open this copy: https://medium.com/p/2867da611c23/edit
Copy Paste All in another new story

Then you can set the visibility to unlisted and publish your blog post

![screenshot from 2017-07-17 09-36-33](https://user-images.githubusercontent.com/943762/28258822-8e839414-6ad3-11e7-9791-3422d4e1fde3.png)

After I will add your blog post to the LessPass publication with the "Add to publication link", and change the visibility to everyone

![screenshot from 2017-07-17 09-36-44](https://user-images.githubusercontent.com/943762/28258824-8fdf9812-6ad3-11e7-837f-14e2c4e91262.png)

Thanks

**Comment by panther2** [comment]
@guillaumevincent 

Klicking the link opens the article, but not in an editable way. 
The above link is transformed to https://medium.com/@guillaume20100/2867da611c23
and appears to be connected to your personal account, so I have no access to the article's source code and thus can't copy paste the information needed.

Any chance that you could send me the source coded text simply as zipped text file by mail (the address I contacted you 6 days ago), so I could copy paste from there?

Thank you.

**Comment by guillaumevincent** [comment]
Can you retry?
Normally now you can edit also my blog post

**Comment by panther2** [comment]
@guillaumevincent 
No change, still I don't see anything than this:

![lsps](https://user-images.githubusercontent.com/20812775/28328548-37e11cac-6be7-11e7-8afd-d905d250a92b.PNG)

I can't find anything that allows me to enter a sort of edit mode.

**Comment by guillaumevincent** [comment]
in Stories, you can't edit a story?
If you copy paste the html it works?

**Comment by panther2** [comment]
@guillaumevincent 
> do you have the edit button in the menu on https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4 ?

With this link, I finally have the edit button, now:

![lsps](https://user-images.githubusercontent.com/20812775/28336625-fd76f30e-6c02-11e7-80b1-96b8abea447b.PNG)

Thank you :smile:

**Comment by panther2** [comment]
Yes, and copy-paste from this into a new story works.
I can now simply replace the English text with the German text.

**Comment by panther2** [comment]
@guillaumevincent 

OK, I have done everything as instructed above. I will send you the link by email.

**Comment by guillaumevincent** [comment]
close in favor of #https://github.com/lesspass/lesspass/issues/240
