### ISSUE TITLE
lesspass doesn't generate any password on android 4.4.4

### ISSUE THREAD

**Issue by ara11** [lesspass/lesspass#246]
hi, when i try generate V2 password on android 4.4.4 lesspass doesn't work and freez!
v1 work but very slow after 5 second generate password
but v2 doesn't work att all and app will be freeze.

**Comment by guillaumevincent** [comment]
Hum, maybe Android 4.4.4 use an old version of Chrome and doesn't support webcrypto. V1 = 8k iterations, v2 100k iterations -> freeze.

Can you try open web browser, go on https://lesspass.com and try to generate a password?
See if you go the same problem.

I will check this on a simulator next week

**Comment by guillaumevincent** [comment]
Hello @ara11,
one solution is to update your browser on your mobile.

I close this one. 
Feel free to post on this thread to ask for extra help.
