### ISSUE TITLE
Promote blog.lesspass.com

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#247]
@guillaumevincent 
@edouard-lopez 

Maybe I have overseen something, but the existance of `blog.lesspass.com` could be promoted more offensively, IMHO.

Apart from the link to a specific article "How does it work" on the homepage `lesspass.com`, I could not find a hint (or link) that a blog even exists.

Also when on `github.com/lesspass` I do not see a hint to the blog (apart from the said article). 

From an end-user perspective I am not sure how many users might ever visit Github to learn more about lesspass. I assume they would search for more information on the website respectively on the blog. Many/all of the information present in the WIKI could be part of the blog, too.  

Also when you plan to announce news on the blog - who will actually notice it (apart from us Github-users that might be aware of it)?

But maybe you have other ideas regarding the blog, that I am not aware of?

**Comment by guillaumevincent** [comment]
All my communications start from Twitter and I use the blog as an extra way to get new users.
Thanks to the tags on medium. 

We also have a few subscribers on medium, who receive notifications, or see the new posts written.

The wiki is more a living doc. If we put wiki stuff on blog.lesspass.com, we'll have to update both. IMO It's a little time consuming.

My target are Github users, developers. I try to optimize my time and so I try to build a community around Github and Twitter. But maybe you're right and we should try to see if this vector is more effective.

We can try this (= write more blog post) during a few month and see. WDYT ?

cc @edouard-lopez

**Comment by panther2** [comment]
Thank you @guillaumevincent 

I am glad I asked as I did not know all of this.

Personally I came to know LessPass because I was searching for an alternative to masterpasswordapp.com
Only because I have a Github account I was able to find LessPass.
In Germany masterpasswordapp has some attention. But if you google `master password` here you won't find LessPass, at least not on the first 5 result pages, I stopped going on from there.

Twitter is of decreasing popularity here, and I wonder how popular "Medium" is here - you brought me to it yesterday (again I might not be representative). Now I will probably even create a Twitter account to not miss your communication there.

I agree - in case you focus on building a small but fine selected community around LessPass, the blog might not be of that importance.

But in case you plan to "expand" one day by further increasing the popularity of LessPass beyond it's clearly arranged environment, I think as one of the corresponding actions the blog should be either integrated into the website, or the website should point clearly to the blog. That saying I am not really aware of the popularity of the website, of course.

I am not sure that only increasing the articles on the blog would help - again apart from the community you described - who would notice them?

I am a happy user thinking LessPass deserves way more attention. But I am perfectly fine if this is not your aim. I will continue to be a happy user as I will continue to be glad to be a part of the community and contribute whatever I can.

**Comment by guillaumevincent** [comment]
> That saying I am not really aware of the popularity of the website, of course.

We don't know either, there is no third party like google analytic on our site.

I forgot to mention that I sometimes send some news on http://reddit.com/r/opensource/.

Don't create a Twitter account only for that :)
We should increase our communication efforts. 
So let's try to add more content on the blog and see. Personally I love the idea, so

**Comment by guillaumevincent** [comment]
I close this one
