### ISSUE TITLE
`Copied!` tooltip does not appear when you copy the password with the keyboard

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#248]
I have tried not only to generate the password using the keyboard only but to copy the generated password to the clipboard, too.

While it is IMHO intuitive, to hit `enter` to generate the password, I have just found out only by accident that I need to hit `Tab` and then  `space` to copy the generated password to the clipboard.
Also when doing so I don't get a **"copied"** popup as when using the mouse, although the password is definitely copied using the keyboard as described.

Is there a more elegant way to copy only using the keyboard?
Can there be a pop-up confirmation, too?

**Comment by guillaumevincent** [comment]
`enter` > `tab` > `enter`

Copy to clipboard doesn't work with async method. So we need to do the generate with 2 steps.
I'm not sure the pop up is good in term of UI.

Let me try to improve the `copied!` feedback.

**Comment by panther2** [comment]
Thank you! I thought I had tried `enter` `tab` `enter` during my tests without effect, but I can confirm now that it works fine.

**Comment by panther2** [comment]
@guillaumevincent 

It appears that with extension 2.5.0 the process has become more complicated.

Now it is

`enter` `tab` `enter` `tab` `enter` 

instead of `enter` `tab` `enter` before...

**Comment by guillaumevincent** [comment]
@panther2 https://github.com/lesspass/pure/commit/09a878f2538e6a0f965d9ec8393f44c2db2a924f fixes the `enter` `tab` `enter` feature

**Comment by panther2** [comment]
@guillaumevincent 
Tested and works fine! Thank you!
