### ISSUE TITLE
Make LessPass resistant to keylogers

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#25]
_From @sctfic on October 20, 2016 6:58_

serai t il possible de ne pas saisir le Master PassWord au clavier mais plutôt a la sourie (choix possible) ?

ou même cliquer sur les icones pour reconstituer le finger a la sourie, au lieux du masteur PassWord.

ainsi même sur un poste "Pourri" lesspass reste Sûr

------------------------------

Would it be possible to enter the Master Password using the mouse instead of the keyboard?

Or maybe click on the icons to reconstruct the fingerprint with the mouse

so even on a corrupt device [keylogger] LessPass remains safe

------------------------------

_Copied from original issue: lesspass/frontend#4_

**Comment by guillaumevincent** [comment]
@sctfic c'est une excellente idée mais il faut réfléchir à comment ne pas dégrader l'expérience utilisateur.
Pense à poster toutes tes issues ici https://github.com/lesspass/lesspass/issues, pas dans chaque projet. Merci
--------------------------------------
This is a great idea but we must think about how not to degrade the user experience.

**Comment by edouard-lopez** [comment]
## Compromised Machine

> It is far safer to **assume that all functionality in a compromised machine will give you away** rather than assuming that only some functionality has been compromised.
[Bypassing keyloggers - virtual keyboard](http://superuser.com/a/473643/174465) on superuser.com

### Keylogger

L'idée est intéressante, mais cela ne fait pas parti de nos objectifs à court terme.

Pour informations, tous les OS proposent des claviers virtuels, mais il ne sont **pas plus sécure** qu'un clavier physique (quoi qu'en dise Miscrosoft): [Does the Windows Virtual (On-Screen) Keyboard have any protection from Keyloggers/ing?](https://answers.microsoft.com/en-us/windows/forum/windows_7-security/does-the-windows-virtual-on-screen-keyboard-have/ea0c0f6e-edfc-4f8e-9b10-4cd086baa3d1).

### Fingerprint

Le fingerprint visuel est dérivé du master password, donc on peux peux pas le "saisir". Son but est de permettre une détection de l'erreur de saisi, de façon similaire au hash MD5/SHA1 pour les paquets `.deb` ou autres.
