### ISSUE TITLE
[FR] Extension Firefox et Linux Ubuntu

### ISSUE THREAD

**Issue by GuyM-31** [lesspass/lesspass#250]
Bonsoir,
Je ne sais pas si ce sont mes options ou spécifique à Linux/Ubuntu mais l'extension y est difficilement utilisable, l'appui sur une touche "Ctrl" ou "AltGr" ferme la fenêtre de l'extension, impossible de saisir le "@" d'une adresse mail ou bien de coller ("ctrl-v") un login :-( 
En espérant que cela sera utile
Salutations
Guy

**Comment by guillaumevincent** [comment]
Bonjour Guy,
@edouard-lopez et moi utilisons l'extension sur Linux.
Nous n'avons aucun de ces problèmes.

Quelle est la version de votre Firefox?

J'utilise l'extension sur Firefox 54 sur Fedora 26, Fedora 25 et Ubuntu 14.04 sans problème.

**Comment by GuyM-31** [comment]
Bonsoir,
Le problème semble avoir disparu et je ne sais vraiment pas si j'ai fais quelque chose pour que cela disparaisse : j'ai fouillé dans paramètres/clavier/raccourci, j'ai chercher des raccourcis dans Firefox via about:config
Je vous prie de m'excuser du dérangement.
Salutations
Guy
