### ISSUE TITLE
Guide for LetsEncrypt usage with the self-hosted LessPass

### ISSUE THREAD

**Issue by deurk** [lesspass/lesspass#253]
I'm pretty new to docker but have been able to fire-up the self-hosted LessPass. I am now looking for pointers on how to configure it to use LetsEncrypt.

Can anybody point me to a guide or give me the first steps to help? (I am quite familiar with the certbot usage so no need to detail that part much).

Thank you!

**Comment by guillaumevincent** [comment]
Hello @deurk,
there is an issue on this one: https://github.com/lesspass/lesspass/issues/14
We are planning to use LetsEncrypt.
My idea is to start a docker container which  will generate or check the certificate used by nginx.

Feel free to ask for extra help on the other issue, if you try to use LetsEncrypt with LessPass
I close
