### ISSUE TITLE
Unable to view profile and can only delete them

### ISSUE THREAD

**Issue by vishsha9** [lesspass/lesspass#254]
Recently I'm only able to delete profiles after logging in but cannot view the details. There used to be an "eye" button in place of the"delete" button in the image below. Upon clicking the profile, it brings up blank details and cannot edit/overwrite the profile.

Is anyone else facing this issue?

<img width="475" alt="screen shot 2017-07-30 at 12 27 16 pm" src="https://user-images.githubusercontent.com/7733673/28751340-8f9c80aa-7522-11e7-991e-b3304eaed4bf.png">

**Comment by guillaumevincent** [comment]
I updated the frontend yesterday with a new version;
Until I fix this, can you use the extension? It is better to use the extension because the extension is better tested and more stable. In addition it is more secure
Thanks

**Comment by vishsha9** [comment]
Sure, thanks for the information. Along with this, has there been some change around the SSL certificates? I was in progress of creating a personal android app using the LessPass APIs and now I'm getting an exception: 
`Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

**Comment by guillaumevincent** [comment]
Yes the update yesterday introduce LetsEncrypt certificate

**Comment by vishsha9** [comment]
Would it be possible to have the docker yml pointing to the old backend? I had to rebuild my container and facing many issues to self-host this new version.

**Comment by guillaumevincent** [comment]
This is another issue,
The latest nginx container is not compatible with the old one, I will document the upgrade, and fix the container version.

**Comment by guillaumevincent** [comment]
@vishsha9 I will update the site

I revert the nginx container. lesspass/nginx:laster docker container is the old one.
You can run:

    docker-compose down
    docker-compose pull
    docker-compose up -d

> I had to rebuild my container and facing many issues to self-host this new version.
You never need to "rebuild" with `docker-compose build` LessPass.
