### ISSUE TITLE
Logging in on android does nothing.

### ISSUE THREAD

**Issue by weedy** [lesspass/lesspass#256]
So on my phone both 2.0.7 and 2.0.8 don't do anything when I hit sign-in or register buttons. Enter key on a bluetooth or usb keyboard fails too.

Latest security patch Marshmellow.

**Comment by guillaumevincent** [comment]
probably related to https://github.com/lesspass/lesspass/issues/255
I'm fixing this right now

**Comment by guillaumevincent** [comment]
Can you try again @weedy ?

**Comment by weedy** [comment]
Hello from insomnia land.
Works fine now, thank you. 


There should really be some kind of feedback that you hit the button, colour change? vibration? something. I thought the beta version was broke at first. I can't find the article now but there was some company (an Amazon/FaceButt/Google) that changed there search function to insert an artificial delay if the results were returned too fast.
That was the spinner has time to animate and people PERCEIVED that the computer was doing something vs. instantly getting results and thinking "wtf, you didn't even try"

**Comment by weedy** [comment]
Also maybe spit out errors to logcat. I had no idea what was going on, lesspass is silient in logcat.

**Comment by guillaumevincent** [comment]
@weedy yesterday I fixed the other issue when there is a network issue in the http request (https://github.com/lesspass/pure/commit/2aee8461f233d82f01584463b45e52a3b09efb64#diff-a69f15f574ed3e711fef31c26c24bd90L105)  

When there is a network error (SSL handshake failing) and no response in the error cached, the component will display an error now.

**Comment by weedy** [comment]
Gimme that fat 2.0.9 beta plz
plz
