### ISSUE TITLE
Ability to backup configuration database with cipher password

### ISSUE THREAD

**Issue by ctaverne** [lesspass/lesspass#257]
Hi
I tried the following script to backup configuration database from https://lesspass.com but it doesn't work because I used front-end feature to cipher my password I think

I'm using the following python script: https://github.com/lesspass/lesspass/wiki/password-profiles-manipulation-scripts

How can I process ?

Thanks

**Comment by guillaumevincent** [comment]
Hello @ctaverne 
what do you want to achieve?
you want to save your password profiles?
there is no `configuration database`, what do you mean by `configuration database`?

**Comment by ctaverne** [comment]
Hi,

Thanks for your answer.
Yes, sorry, I  meant password profile..

I would like to bakup all my profiles locally in case of unavailability of lesspass website.

But I didn't succeed with the script given previously. I think it is because my lesspass.net password is cipher.

**Comment by guillaumevincent** [comment]
@ctaverne if by cipher you mean `Encrypt my master password` feature, what you need is to generate your encrypted password before.

`Encrypt my master password` use default password profile: https://github.com/lesspass/lesspass/wiki/FAQ#you-should-never-save-your-master-password

So go on https://lesspass.com/ or open LessPass web extension, and generate a password for Site: `lesspass.com` with your email and your master password.

**Comment by ctaverne** [comment]
Ok thanks for your answer.
Yes I used : "Encrypt my master password" feature. In consequence, I can't get its encrypted value to use with python script.

Ok. If I understand I need to generate password manually and re create my profiles database.

regards

**Comment by guillaumevincent** [comment]
> I can't get its encrypted value to use with python script.

Yes you can with site `lesspass.com` your email and your master password.
I close
Feel free to post on this thread to ask for extra help.
