### ISSUE TITLE
[Android] set minimum version to Android 5 and display error if webcrypto not available

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#259]
Hello,
I'm trying to use Lesspass 2.0.7 on an old ASUS tablet with Android 4.2.1 and the app displays the splashscreen and then a blank screen.
Unfortunately, my USB cord seems to be buggy so I can't run logcat on ths tablet, so I'm not sure what other info I can provide.

**Comment by guillaumevincent** [comment]
Android 4.2.1 is an old version of Android.
I'm not sure of the version of chrome running on this one, but I think there is no webcrypto.

What is the version of Chrome running on your system?

**Comment by Rudloff** [comment]
Chrome 59 is installed.
But I think on Android 4.2, the webview still uses the old internal Android Browser.
Here is the user agent:
```
Mozilla/5.0 (Linux; U; Android 4.2.1; fr-fr; ASUS Transformer Pad TF300T Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by Rudloff** [comment]
I reproduced the issue in the Android emulator's browser and here is the error I got in the console:
```
E/browser ( 2156): Console: Uncaught Error: [vuex] vuex requires a Promise polyfill in this browser. http://dev.rudloff.pro/lesspass/dist/lesspass.min.js:7
```

**Comment by guillaumevincent** [comment]
Thanks for the update, so not related to webcrypto but Promise support

**Comment by Rudloff** [comment]
Yes but it seems the 4.2 webview also doesn't support crypto.
Crypto was added in Android 5 and this version also support promises. So I don't think it's worth adding a Promise polyfill.

However I think you could either:
* Make lesspass/cordova require Android >= 5.0 (just add `<preference name="android-minSdkVersion" value="19" />` in `config.xml`)
* Make lesspass/pure display an error message if the browser does not support promises or crypto.

**Comment by guillaumevincent** [comment]
Good idea, let me do this
