### ISSUE TITLE
No new webextension reflecting the latest updates?

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#260]
Back from vacation I just realized the update of almost all modules about nine days ago.
#238 / #242 has been fixed, thank you!

But the Chrome extension is still version 2.4.10 of May 26th, 2017.
Any reason why this has not been updated?

**Comment by guillaumevincent** [comment]
Sorry, I catch a bug on the web extension that delay the update.
I'm in Boston this week and I don't have any time this week.
I promise I will update the web extension next week.
Sorry for that

**Comment by guillaumevincent** [comment]
@panther2 Chrome extension is on production, Firefox extension is waiting for validation
check version 2.5.0

Thanks for your patience

**Comment by panther2** [comment]
@guillaumevincent 

Thanks a lot, but please see #265
