### ISSUE TITLE
iOS App?

### ISSUE THREAD

**Issue by aurimasmb** [lesspass/lesspass#261]
Hi, 

Do you have a timeline for creating an iOS app?

Thanks!

**Comment by guillaumevincent** [comment]
I'm working on a React Native implementation.
When the new Android version will be online, we will probably create the iOS app

**Comment by aurimasmb** [comment]
Great! Are you developing that publicly? Would love to see the progress / potentially get involved. This seems like a great project.

**Comment by guillaumevincent** [comment]
Yes I will update native sub repo when starting this

**Comment by guillaumevincent** [comment]
Hello, we are going to buy a mac and the Apple Developer Program subscription soon. Stay tuned

**Comment by guillaumevincent** [comment]
Hello,
I bought a mac mini today, I start development on IOS next week

![img_20171016_223526](https://user-images.githubusercontent.com/943762/31635135-109555d4-b2c6-11e7-8b5f-2e62bb6404d9.jpg)

**Comment by benhamill** [comment]
FWIW, I'd be happy to help test once it gets to that stage.

**Comment by guillaumevincent** [comment]
I have a question regarding the license of LessPass and itunes. Due to the anti tivoization clause in the GPLv3, is it illegal to distribute programs on iTunes?

**Comment by RomainQuidet** [comment]
I missed this thread last night when I ported the core lib into native iOS framework.
check https://github.com/RomainQuidet/LessPassCore
It might help for iOS integrations !

**Comment by RomainQuidet** [comment]
About the GPL issue, several open sources apps are in the AppStore. Did you check issues VLC had for example?

**Comment by o-be-one** [comment]
How Master Password handle this? And other under GPL apps?

**Comment by guillaumevincent** [comment]
@o-be-one there double license the code
I'm going to do the same: https://github.com/lesspass/entropy-ios/blob/master/LICENSE

**Comment by failshell** [comment]
Any progress on the iOS app?

**Comment by guillaumevincent** [comment]
Hello @failshell,
I don't have a lot of time for LessPass right now. 
I'm working on new features, the new design and the iOS app.
I will update this issue when I will have some update.

**Comment by vuleetu** [comment]
Any updates?

**Comment by RomainQuidet** [comment]
Hi

I’ve created a native app based on my port of the algorithm in swift. I need some time to test it and release it. I’ll keep you informed of the evolution.

Romain

**Comment by beli3ver** [comment]
@RomainQuidet could you put your app at TestFlight than all can test it.

**Comment by RomainQuidet** [comment]
Hi @beli3ver public beta on TestFlight is not so easy, I need to pass Apple's review. For that I need to finish a v1 of my app.

**Comment by Unkn0wn-MDCLXIV** [comment]
@RomainQuidet
Any news on that app?

**Comment by RomainQuidet** [comment]
Sorry no time yet to work on this project...

**Comment by exislow** [comment]
+1 would be amazing having an iOS app! Thanks in advance.

**Comment by e-moe** [comment]
looking forward for ios app

**Comment by yonyonson** [comment]
That would be great to have an iOS app for lessPass

**Comment by guillaumevincent** [comment]
I implemented iOS native module for fingerprint and entropy functions
Looks like iOS app is working

If you are an iOS developper, feel free to test it
I will start doing some tests, and try to push the application to the app store

![Simulator Screen Shot - iPhone 11 - 2020-07-25 at 23 28 34](https://user-images.githubusercontent.com/943762/88466629-9e248600-cece-11ea-9e39-03cdf69ef635.png | width=320)

**Comment by MalteKiefer** [comment]
Could you put it on testflight, so I can test it for you?

**Comment by guillaumevincent** [comment]
Excellent idea, I will push this on testflight

**Comment by MalteKiefer** [comment]
When you done, could you give me the link?

**Comment by guillaumevincent** [comment]
Today I tried to publish LessPass app on the App Store. Apparently someone already publish the application before me. 😕 What should I do ?

Any help here?

**Comment by MalteKiefer** [comment]
Contact to Apple.
Maybe tell them who you are.
Do you have a link to the app?

**Comment by guillaumevincent** [comment]
Nope I can't find it.
I sent Apple an email, will see.
I will use "LessPass Password Manager"
Thanks

**Comment by MalteKiefer** [comment]
Thank you, when will you release it to TestFlight, can not wait to test it

**Comment by guillaumevincent** [comment]
Beta team should validate the app, upload is done.
As soon as I have a link, I will share it here

**Comment by MalteKiefer** [comment]
Can I join the beta team, please?

**Comment by guillaumevincent** [comment]
Beta App review team is a team at Apple, validating the app before we can publish an app on Testflight.
Send me an email at contact(at)lesspass.com and I will put you in the testers. Thank you

**Comment by guillaumevincent** [comment]
Let's go 

https://testflight.apple.com/join/Wf2wb7e2

**Comment by vuleetu** [comment]
finally, cool @guillaumevincent

**Comment by guillaumevincent** [comment]
In order to be able to name the application LessPass, I was forced to create a new app (rename with a new version wasn't working on the US). I deleted "LessPass Password Manager" from the testflight program.

Review is being done for "LessPass", we will be on the app store probably tomorrow or on friday
I will close this issue soon

Thank you for your patience, support, help, money, etc 😍 
The community pay for the 99$ apple developper program trough Open Collective (see Budget [here](https://opencollective.com/lesspass/))

**Comment by guillaumevincent** [comment]
The new testflight link: https://testflight.apple.com/join/grzBe7bN

**Comment by MalteKiefer** [comment]
Thanks for your work

**Comment by guillaumevincent** [comment]
We can close this one: https://apps.apple.com/app/id1531215924
