### ISSUE TITLE
password generation is very slow on safari in IOS 

### ISSUE THREAD

**Issue by aurimasmb** [lesspass/lesspass#262]
Trying to generate a password on the web interface through a mobile browser on iOS:

* iPhone 5
* Safari Browser
* 16 character password

Very slow to generate password - only completed once out of 5+ tries.

**Comment by guillaumevincent** [comment]
Can you give me the safari version Iphone 5 is running ?
I think there is no webcrypto on your Safari.

Will be fix by https://github.com/lesspass/lesspass/issues/261

**Comment by aurimasmb** [comment]
`user-agent Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1`

**Comment by guillaumevincent** [comment]
@aurimasmb yes webcrypto is not implemented on Safari browser
See https://github.com/lesspass/lesspass/issues/127 for a more technical explanation
