### ISSUE TITLE
Unable to reset my password on lesspass.com

### ISSUE THREAD

**Issue by thomaschampagne** [lesspass/lesspass#263]
Dear team,

Thanks for this tool !

I tried to reset my password on your site.

- I entered my email and clicked "Reset my password"
- Clicked on the link given in the email i received (https://lesspass.com/#/password/reset/confirm/xxxxxxxxxxxxxx)
- I entered my email with the new password i wanted.
- I clicked the "Reset my password" button and got this:

![image](https://user-images.githubusercontent.com/151973/29223058-6ebf8c72-7ec5-11e7-9591-4783fac0ef45.png)

The new password is not changed on your site i try to login next to upper steps.

Thanks for ur help,

Cheers,

Thomas

**Comment by Charles-Neil** [comment]
I ran into this issue, too. Thanks for the team, this is a really great tool!

**Comment by guillaumevincent** [comment]
problem solve in production

**Comment by thomaschampagne** [comment]
Thanks for the tool & support !!  👍
