### ISSUE TITLE
Web extension 2.5.0 profile update issues

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#265]
This is a follow-up to #238 and #242 after the recent Webextension update (2.5.0)

First of all: Thank you for updating.

But I am afraid the process is buggy now.

This is what I am experiencing (Steps to reproduce):

1. Go to `accounts.google.com`
2. Log in using your google user account and the webextension
3. Move on to `github.com` then
4. When starting the webextension here, it is filled with `github.com` **and** the **google** user name
5. When hitting "Lesspass" on top of the extension's window, `github.com` is replaced by `accounts.google.com`  (though still on `github.com`), **keeping the google user name**.

Restarting the extension on github.com brings back `github.com` as site name but with the prefilled **google account name** used before.

I need to manually remove/overwrite the old data with the required new data.

I am not posting an animation this time, because it appears too complicated to remove my personal data from the images. 

Edit to add:
It appears that I do always have the "User name" that I used on the **previous** website, when opening the webextension on a **new** site. Hitting "LessPass" then restores the **previous** website as site name.

**Comment by guillaumevincent** [comment]
@panther2 maybe you hit the `save options` button before
Can you try to clean site and login and hit `save options` button ? Now every time you open the webextension login and site will be empty.

**Comment by guillaumevincent** [comment]
> 1. Go to `accounts.google.com`
> 2. Log in using your google user account and the webextension
> 3. Move on to `github.com` then
> 4. When starting the webextension here, it is filled with `github.com` **and** the **google** user name
> 5. When hitting "Lesspass" on top of the extension's window, `github.com` is replaced by `accounts.google.com`  (though still on `github.com`), **keeping the google user name**.

When you generate a password, extension save the profile in localstorage. If you reopen the extension 1 minute before the generation, extension load the previous profile. (interesting when you want to change an option)
This is an expected behaviour.

What was your idea? Load the previous profile only if we are on the same domain?

**Comment by panther2** [comment]
@guillaumevincent 

> ... maybe you hit the save options button before

I never hit and use the save button, actually. I am always going with the default options. Even in the rare cases where I can't use default I never save anything.

> Can you try to clean site and login and hit save options button ? Now every time you open the webextension login and site will be empty.

I have tried that- it worked for the first site, but from that time on I always get the previous user name again, without hitting save options. The only difference I notice is that now when hitting "Lesspass" on the top of the extension, all fields are cleared.

**Comment by panther2** [comment]
@guillaumevincent 

>When you generate a password, extension save the profile in localstorage. If you reopen the extension 1 minute before the generation, extension load the previous profile. (interesting when you want to change an option)

Once my passwords are set, I would not need to change an option. So in my usecase, where I quickly change sites to grasp some information and move on then, So the prevoius profile is an obstacle here.

>This is an expected behaviour.
Ouch!

>What was your idea? Load the previous profile only if we are on the same domain?

My idea would be to never load a previous profile (here: site and user name) when going to a new domain.
Also, my idea would be not to restore the previous domain when trying to clean the previous user name from the actual domain.

Thank you for taking care of my issues :smile:

**Comment by guillaumevincent** [comment]
If you have some time during the day, feel free to come to #lesspass on freenode to discuss about this.

Here the workflow I want to achieve:

![screenshot from 2017-08-17 19-11-29](https://user-images.githubusercontent.com/943762/29424494-405501fe-8380-11e7-87ba-66ab49100fcb.png)

When I look at my tests, I'm not sure this is the actual behavior.

 * What do you want to say by `Once my passwords are set` ?
When you password is saved on LessPass Database or when the password on the site is a LessPass password? 

 * Are you using LessPass Database?

Maybe with #245 feature, we can simplify the workflow loading only profile if site match password profiles in LessPass Database. 

And remove password profile loading if last use < 1min

wdyt ?

**Comment by guillaumevincent** [comment]
> I have tried that- it worked for the first site, but from that time on I always get the previous user name again, without hitting save options. The only difference I notice is that now when hitting "Lesspass" on the top of the extension, all fields are cleared.

When you hit LessPass button, it loads your default password profile. Default password profile is set when you hit `save options`.

**Comment by guillaumevincent** [comment]
thank you @panther2 for your time ❤️

**Comment by panther2** [comment]
@guillaumevincent 

>When you hit LessPass title, it loads your default password profile. Default password profile is set when you hit save options.

Has that changed? Please see https://github.com/lesspass/lesspass/issues/238#issuecomment-309895545 (nearly at the end of the comment) .

**Comment by guillaumevincent** [comment]
> Has that changed? Please see #238 (comment) (nearly at the end of the comment) .

No, always be like this.
But because you never it `save options` button, for you it cleaned login and site.

Lets try to remove the last used feature because it's add more trouble than useful use case.
Let's see if you prefer the next version.

**Comment by panther2** [comment]
@guillaumevincent 
Much better, thanks a lot :+1:

**Comment by nshtg** [comment]
@guillaumevincent 
I actually used the feature, now every time I open a site I have to manually increase the length to 30, which is really exhausting.

Have you considered adding an option to increase only the password length by default?

**Comment by guillaumevincent** [comment]
@nshtg I will add an options page that allows you to set up your default behaviour of yours app.

**Comment by nshtg** [comment]
That sounds perfect thank you!
