### ISSUE TITLE
Android App worth an update?

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#268]
The latest update of Cordova occurred 14 days ago.
The latest tagged version is 2.1.0 of May, 30th.

However in the Google play store the latest version is 2.0.7 of May, 11th.

**Comment by guillaumevincent** [comment]
The last version use latest Cordova version and double in size. From 2.5mo to 5mo.
I want to check if everything is ok. 
And because I'm rewriting it, I would like to wait a little

**Comment by panther2** [comment]
Thanks for the insight,
