### ISSUE TITLE
[lesspass-cli] password prompt

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#27]
(J'ouvre un autre ticket pour ne pas polluer #24.)
En fait ça m'embête de devoir mettre le master password en clair comme argument.
Ça serait pas mal d'avoir un prompt avec texte invisible comme le fait par exemple sudo.

**Comment by guillaumevincent** [comment]
Si :

    lesspass input1 input2 input3

alors `input3` est égal à master password ?

Si :

    lesspass input1 input2

alors demander le mot de passe ?

**Comment by Rudloff** [comment]
Oui, ça me parait pas mal.

**Comment by guillaumevincent** [comment]
fix en version 0.2.0 de lesspass-cli

**Comment by Rudloff** [comment]
Parfait, merci !
