### ISSUE TITLE
Feature Request: Add release tag to desktop version

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#270]
I would like to suggest adding a release tag to the desktop version.
We already have release tags for many lesspass-versions, but apparently not for the desktop version.

It would be easier to identify new releases by the tag instead of comparing dates of commits.

**Comment by panther2** [comment]
@guillaumevincent  Not a good idea?

**Comment by guillaumevincent** [comment]
@panther2 yes sorry
I will add a tag soon
nice catch
