### ISSUE TITLE
BUG: website domains are not filtered correctly 

### ISSUE THREAD

**Issue by darkworks** [lesspass/lesspass#272]
when i add http://github.com   or  github.com  or www.github.com
 
for all three different passwords are generated 

so it will be good if domains are trim to lets use enter domain : http://www.github.com   it should be trim to github.com  and then password should be computed , because if today user copied domain www.github.com  and generated password and tomorrow it copied github.com  or http://github.com  then generated password will be different.
 

thanks

**Comment by guillaumevincent** [comment]
Hello @darkworks,
there is no easy solution to get only the `github.com` from the url:
See the discussion https://github.com/lesspass/lesspass/issues/199

Removing the `www.` to the actual code will break a lot of passwords for current users.
So we will introduce this breaking change in a next version.
But this change is not enough to create a new version.

My advice: let the www.github.com given by the web extension.

Duplicates https://github.com/lesspass/lesspass/issues/199
