### ISSUE TITLE
This vs PasswordMaker?

### ISSUE THREAD

**Issue by RoseTheFlower** [lesspass/lesspass#273]
What's the difference between LessPass and [PasswordMaker](https://passwordmaker.org/Introduction) and its extensions that have been around for about a decade?

**Comment by guillaumevincent** [comment]
Hello @RoseTheFlower,

here the main difference:

 * PasswordMaker [interface](https://passwordmaker.org/Screenshots) is too complex: 
 * PasswordMaker has a lot of [algorithms](https://passwordmaker.org/FAQ#Which_hash_algorithms_are_supported.3F) 
 * None of the algorithms are robust against brute force
 * I'm not sure it's still developed? last news 2009

**Comment by RoseTheFlower** [comment]
There are browser extensions based on the code that are still maintained and updated, such as [this one](https://github.com/emersion/passwordmaker). You can also see the UI there.

I had hoped to get a more technically detailed response without getting into the code.

**Comment by guillaumevincent** [comment]
@RoseTheFlower technically the generated password is weak.
There is no salt (no login) and the generation of a password is ultra fast ( the most robust algorithm is HMAC-sha-256). So PasswordMaker is not robust against brute force.

We use pbkdf2 with 100k iterations to generate a password on LessPass.
