### ISSUE TITLE
LessPass v1

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#274]
Hello,
I'm going to remove v1 from the current pure component and core.
I created a [v1.lesspass.com](http://v1.lesspass.com) site, hosted on GitHub page, as an archive.
Remember than v1 is deprecated.
Cheers

**Comment by edouard-lopez** [comment]
Good news :)

Should we add a small link at the bottom of the website?

**Comment by guillaumevincent** [comment]
We should display a warning maybe,

The new version will be pushed soon.

![screenshot-2017-10-10 lesspass](https://user-images.githubusercontent.com/943762/31395024-0f96cb94-ade0-11e7-9dd9-a9f04a37ca6f.png)

https://github.com/lesspass/pure/commit/aea154026eae8732965cc5b9fb9357e4efa86529
