### ISSUE TITLE
Some thoughts to make lazy users happy

### ISSUE THREAD

**Issue by roipoussiere** [lesspass/lesspass#275]
I use lesspass with the web extension (without database) and I find that the process to get the generated password could be faster.

Currently the steps I do to generate a pw are:
- I select the username previously entered in the current website (because my browser or a cookie remember it), and I copy it;
- I click on the LessPass icon;
- I paste the username on the login field;
- eventually I strip the domain (but I hear that could be improved in a future version);
- I click on the pw field and I type my password;
- I click on generate, then copy;
- then I click on the website pw field and pastle the generated pw.

I think about several ways to improve this:
1. Add a keyboard shortcut to open LessPass;
2. If I select the site username field then open LessPass, the LessPass username field could be automatically filled (and pw field focused);
3. If page have only one password field, LessPass could try to paste the password in this field after it's generated.

What is your opinion? :)

**Comment by panther2** [comment]
There is a keyboard-shortcut to open LessPass: `Ctrl+Shift+L` .

**Comment by kidburglar** [comment]
@roipoussiere 
About the autofill feature it will never be done.
It is explained =>https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension

**Comment by roipoussiere** [comment]
Thank you for the keyboard shortcut! Very useful, you should write it somewhere, for example in the LessPass tooltip.

Ok about the autofill feature.

I have just tried the connected version and saved several passwords, and I fact it's all I want: I have just to type my pw. Closing this, so, thank you again. :)

**Comment by roipoussiere** [comment]
Oh, just one last thing, why the generated password is not automatically copied ? I try to generate my pw only with the keyboard but I can't...

**Comment by panther2** [comment]
@roipoussiere 

You can, after typing the masterpassword hit `enter` `tab` `enter` and the generated password is copied.
There is just no tooltip, see #248

**Comment by guillaumevincent** [comment]
@roipoussiere when you install the extension, the first time, there is a pop-up with the shortcut. Maybe we can update the web extension description to add the shortcut. wdyt?
