### ISSUE TITLE
Documentation of the keyboard shortcut

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#277]
Is the keyboard shortcut `Ctrl+Shift+L` documented?

As discussed in #275 the keyboard shortcut  to open the web extension could be documented more obvious.

**Comment by guillaumevincent** [comment]
+1 web extension popup is not sufficient

**Comment by panther2** [comment]
Some ideas:

- on Github in the readme.md
- on Github / WIKI as part of the FAQ
- in the Chrome WebStore description of the extension

**Comment by guillaumevincent** [comment]
sounds good, let's do this

**Comment by roipoussiere** [comment]
I though to something like this:

![](https://i.imgur.com/GsRCwPU.png)

**Comment by edouard-lopez** [comment]
added to:
* [x] wiki [Home](https://github.com/lesspass/lesspass/wiki) page ;
* [x] [FAQ](https://github.com/lesspass/lesspass/wiki) page.

Also like @roipoussiere suggestion.
