### ISSUE TITLE
[lesspass-cli] certain caractere dans le parametre retourne une erreur au lieu du MDP

### ISSUE THREAD

**Issue by sctfic** [lesspass/lesspass#28]
ces exemple ne passe pas

```
lesspass '<site>' '<login>' '<masterPassword>'
```

La syntaxe de la commande n'est pas correcte.

```
lesspass 'site' 'login' 'masterPasswo>rd'
lesspass 'site' 'login' 'masterPa$$word'
```

**Comment by edouard-lopez** [comment]
Tu es dans quel environnement? 

```
$ lesspass --version
0.2.0
``` 
J'ai le même résultat pour:

1. l'extension Firefox
1. la commande complète

        $ lesspass 'site' 'login' 'masterPa$$word'      
        obAD1&acUP1,

1. la commande avec prompt du mot de passe

        $ lesspass 'site' 'login'
        master password:  # je tape masterPa$$word
        obAD1&acUP1,

J'ai testé avec:
* Bash `4.3.42` ;
* zsh `5.1.1` ;

**Comment by sctfic** [comment]
Sous Windows Powershell 3.0

    PS C:\Users\alopez> lesspass --version
    0.2.0


```
PS C:\Users\alopez> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18449
BuildVersion                   6.2.9200.17065
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by guillaumevincent** [comment]
@sctfic tu peux nous donner le résultat de : 

    lesspass 'site' 'login' 'masterPa$$word'

**Comment by edouard-lopez** [comment]
@guillaumevincent ce n'est pas dans un environnement `bash`, t'as réussi à reproduire sur **`powershell`**?

**Comment by guillaumevincent** [comment]
je teste mercredi prochain

**Comment by guillaumevincent** [comment]
@sctfic pour moi ça fonctionne :

![2016-11-02 09_12_18-administrator_ command prompt](https://cloud.githubusercontent.com/assets/943762/19921059/7d773066-a0dc-11e6-9ed8-a7d1a82c9e95.png)

![2016-11-02 09_09_42-administrator_ windows powershell](https://cloud.githubusercontent.com/assets/943762/19921016/337a7b58-a0dc-11e6-8758-e603ac8a3a43.png)

@sctfic pour tester tu peux utiliser l'extension ou le site (c'est l'implémentation qui fait foi) et ensuite tester en ligne de commande.

Je ferme et tu réouvres le bug si tu trouves une incohérence entre le site et PS
![2016-11-02 09_15_49-lesspass](https://cloud.githubusercontent.com/assets/943762/19921172/fe59196a-a0dc-11e6-85b4-0c331876bc45.png)

**Comment by sctfic** [comment]
le probleme semble venir de Powershell, car en mode DOS ca fonctionne

PS C:\Users\alopez> cmd /c 'lesspass "site" "log$^^in" "fs<x"'
onAL9:edOP9=

**Comment by guillaumevincent** [comment]
@sctfic tu dois echaper le caractère `<`

```
PS C:\> lesspass "site" `"log`$^^in`" `"fs<x`"
aqYW2=axUS0@
PS C:\> cmd /c 'lesspass site "log$^^in" "fs<x"'
aqYW2=axUS0@
```

![2016-11-02 11_27_17-](https://cloud.githubusercontent.com/assets/943762/19925268/86721498-a0ef-11e6-9a60-9afff103d016.png)

**Comment by edouard-lopez** [comment]
Référence obligatoire.

* [936: Password Strength](https://www.explainxkcd.com/wiki/index.php/936:_Password_Strength)
* [XKCD #936: Short complex password, or long dictionary passphrase?](http://security.stackexchange.com/a/6116/30496)

> > AviD's Rule of Usability:
> >
> > **Security at the expense of usability comes at the expense of security.**

### XKCD 936
![password_strength](https://cloud.githubusercontent.com/assets/1212392/19929700/ebc3aff4-a104-11e6-9076-f722865e83bd.png)
