### ISSUE TITLE
Display a profile when you click on it

### ISSUE THREAD

**Issue by Romathonat** [lesspass/lesspass#285]
When I use the firefox extenstion, I go to a webmail (like [laposte.net](laposte.net)), I change my password. The URL is now [compte.laposte.net](compte.laposte.net), so I save my profile with this URL.

When I want to login to laposte.net, I click on the "key", and **I expect the application to display the profile I selected**, but it won't display anything else than the current url (wich is [laposte.net](), and not [compte.laposte.net](), I think this "bug" comes from here). I can open another tab and it will work (because there is no conflict between the current URL and the one of the selected profile), but it's kinda annoying.

Thank you for this innovative project !

**Comment by guillaumevincent** [comment]
Hello normally with the latest web extension, this is fixed. Can you check your version?

**Comment by Romathonat** [comment]
Using firefox 56.0.1 (64bits), and lesspass 2.5.1 ([here](https://addons.mozilla.org/fr/firefox/addon/lesspass/)), it does not work.

**Comment by panther2** [comment]
@guillaumevincent 
The web extension is still on 2.5.1 of August, 17, 2017.

All the latest updates have not bumped any version number of any LessPass-distribution.

**Comment by guillaumevincent** [comment]
Hello @Romathonat,
so if you save `compte.laposte.net ` and go to `lasposte.net`, the site becomes `www.laposte.net`.
So there is a bug because LessPass don't check if domains are identical.

I will fix this by checking if site match domain exactly or if site without www. match one password profile.

**Comment by Romathonat** [comment]
Well, It is not exactly what I meant. The user experience is a bit weird IMHO. When you click on profile, you want it to be displayed, whatever the website you are currently on. With the current version, it depends on the current URL. With your fix, you let the plugin display a profile if the current URL is the one on the profile, or if the URL begins with "www"+URL. It will not solve my use case, when profile's URL = "compte.laposte.net" and the current URL is "laposte.net". I don't understand why you want those two URLs to be the same. It would be easier to not have such a restriction no ?

**Comment by guillaumevincent** [comment]
> When you click on profile, you want it to be displayed, whatever the website you are currently on.

@Romathonat  that is the case
