### ISSUE TITLE
lesspass not work on android 4.4.4

### ISSUE THREAD

**Issue by auriii** [lesspass/lesspass#287]
hello, lesspass app not work on android 4.4.4 
i have test on higher version and work correctly
but on version 4.4.4 when tap on generate button app will be crash

please fix this issue.

**Comment by guillaumevincent** [comment]
Hello @auriii 
it duplicates https://github.com/lesspass/lesspass/issues/246
Cordova App requires a recent browser with crypto support.
For now the minimum version of Android is version 5.

**Comment by edouard-lopez** [comment]
@guillaumevincent I guess we should specify the minimal version on the `config.xml`

     <preference name="android-targetSdkVersion" value="21"/> //android 5.0

More
* [How can I specify the minimum SDK in phonegap? It is ignoring android-minsdkversion in config.xml](https://stackoverflow.com/a/27137393/802365)
*  [Android version history](https://www.wikiwand.com/en/Android_version_history)

**Comment by edouard-lopez** [comment]
It's already there
