### ISSUE TITLE
fingerprint support on mobile

### ISSUE THREAD

**Issue by jeroen7s** [lesspass/lesspass#288]
would be easy to login using fingerprint where the fingerprint chip stores your masterpassword, would make it much more appealing to use on mobile

**Comment by guillaumevincent** [comment]
I like the idea, it would improve usability on mobile.

**Comment by guillaumevincent** [comment]
I did some experimentation yesterday on this feature: 
![fingerprint](https://user-images.githubusercontent.com/943762/45537043-84f71c80-b803-11e8-843e-8bdfe6d0c888.gif)

**Comment by guillaumevincent** [comment]
This feature is on production!
Download LessPass version 3.0.2 on Android store
