### ISSUE TITLE
autofill on mobile

### ISSUE THREAD

**Issue by jeroen7s** [lesspass/lesspass#289]
many password managers can detect login fields and ask to login with an overlay (see things like lastpass, which do this very nicely)\
would be very conventient to have similar functionality in lesspass

**Comment by guillaumevincent** [comment]
Yeah, the mobile integration/usability should be improved
There is an open discussion in this one: https://github.com/lesspass/lesspass/issues/239
I close this one.
The idea is how do we connect the app with other apps to share context.
