### ISSUE TITLE
Threat model improvements

### ISSUE THREAD

**Issue by n2liquid** [lesspass/lesspass#291]
Hi! I'm really excited about LessPass, since I've never liked the idea of storing all my passwords in a server, even if encrypted.

But as it stands, at the end of the day I believe stateful password managers offer very similar kind of protections / threat models.

In my understanding, the stateful password managers threat model is that you have to trust the clients to:

1. Always encrypt your passwords before storing them on the server.
2. Never use weak crypto or encryption algorithms with "backdoors."
3. Never leak plain-text passwords.
4. Be free software so we can read the code and check the previous points.

Additionally, we have to:

5. Re-check the source code with every update.

For LessPass, # 1 is irrelevant, # 2 is even more of a concern since we're doing things differently and crypto is hard, # 3 is still a concern, # 4 is OK, and # 5 is still a concern, too.

I think we could drastically improve # 3 by making LessPass clients unable to connect to the Internet. Stateful password managers can't do that because they need to fetch and upload passwords, but LessPass can work "airgapped," so I think it really should.

If Chromium / Firefox offered an airgapping configuration for extensions, that would make problem # 5 less of a concern, since even compromised software wouldn't be able to leak any data.

Without this, not only we're doing handcrafted crypto (-1), client updates could still be compromised, so we'd still have to re-check the source code on every update (=). Yes, we aren't storing data on any server (+1), but that leaves us with the same score as state-of-the-art stateful password managers in my mind.

Do you have any plans or ideas to improve this situation in the future? What do you think?

**Comment by monolifed** [comment]
Issue **1** might not be totally irrelevant.  
From #185 I assume password profiles are encrypted.  
But they are encrypted server side as far as I can tell from this script: https://github.com/lesspass/lesspass/wiki/password-profiles-manipulation-scripts  
My understanding is that you send the server your master password and email (this is sent through https so it should be safe)  
The server decrypts your profile data and sends it to you (again through https)  
Although quite unlikely, If someone tricks you with a fake site or gains access to the server. They can get your master password and profiles.

It would be nicer if server password was different from the master password and profiles were encrypted on the client then sent to the server. 

About issue **2** both AES (depending on the block mode) and SHA256 are supposedly safe.

Singed commits might help about **4** and **5**.

**3** sounds like an issue on the user side, e.g. Logging into lesspass site from a public computer can be quite bad.

**Comment by n2liquid** [comment]
> My understanding is that you send the server your master password and email (this is sent through https so it should be safe)

If this is true, it's absolutely unsafe. It means the project / server maintainers can get people's master password and derive their passwords for common websites. I'd be shocked if that was the case.

Apparently there are mechanisms that prevent our master password from reaching the server, at least that's what this section says, I think: https://github.com/lesspass/lesspass/wiki/FAQ#you-should-never-save-your-master-password

Regarding server-side encryption of password profiles, if that's really what happens, I think it also needs to change. Even if password profiles don't contain any passwords, they can be used to make brute force attacks a bit easier by telling attackers the exact password format to brute force... I'm not sure that's a big issue, but ideally we'd better avoid giving out hints like these.

> About issue 2 both AES (depending on the block mode) and SHA256 are supposedly safe.

Even if we're using AES / SHA256, I think it's possible to combine them in ways that could make the resulting algorithm unsafe. I think LessPass V1 also used strong crypto, but used it in a way that produced weak passwords...

But anyway, not much we can do about this besides hoping project maintainers research a lot and implement sound algorithms. I think the fact that V1 was harshly criticized and we got an improved V2 is a sign we're in the right path.

> Singed commits might help about 4 and 5.

> 3 sounds like an issue on the user side, e.g. Logging into lesspass site from a public computer can be quite bad.

Sure, we can't protect against that. What I meant is that the LessPass software could contain malicious code that sends plain-text passwords to a server.

Signed commits help, but not much. Ideally, we shouldn't have to trust the source not to do that; we should just make it impossible. Complete distrust is an unbeatable trust model :)

Even if Chromium / Firefox don't implement that right now, I think it could be a useful feature for other extensions as well. Maybe someone would be interested in implementing that.

**Comment by guillaumevincent** [comment]
Hello @n2liquid,
> * 2 is even more of a concern since we're doing things differently and crypto is hard

I don't understand what you mean by we are doing things differently. Can you add more details?

> 3 Never leak plain-text passwords.

For LessPass you mean never leak password profiles? If you use LessPass Offline, there is no leak possible, right?

> I think we could drastically improve # 3 by making LessPass clients unable to connect to the Internet. Stateful password managers can't do that because they need to fetch and upload passwords, but LessPass can work "airgapped," so I think it really should.

The default behaviour of LessPass is the offline mode. What do you mean by unable to connect to the internet?

> 5 Re-check the source code with every update.

Another solution for this use-case, you can also disable auto-update for your extension, and use a version you audited.

**Comment by guillaumevincent** [comment]
Hello @monolifed,

so to start **LessPass does not (yet) encrypt password profiles on LessPass Database**.
This is something we need to do.

> My understanding is that you send the server your master password and email (this is sent through https so it should be safe)

Don't send you master password through the wire, even encrypted. Encrypt you master password on the login page. There is a feature for this:

![img](https://camo.githubusercontent.com/26eea775b6786856e496f6ccd5419dfbb346d9a9/687474703a2f2f692e696d6775722e636f6d2f6a77566f6f53732e706e67)

See https://github.com/lesspass/lesspass/wiki/FAQ#you-should-never-save-your-master-password

**Comment by monolifed** [comment]
Nice feature, with this attackers shouldn't be able to find out your real master password easily. They might still somehow get your profiles but without the master password they are not very useful.
