### ISSUE TITLE
Domain names should be case-insensitve

### ISSUE THREAD

**Issue by devsnd** [lesspass/lesspass#294]
Hi! First of thanks for this really cool idea, I'm immediatly hooked by it!

I just tried the lesspass.com and the android app implementation of lesspass and both show the same problem:

Passwords generated for `google.com` and `Google.com` are different even thought this is just an [alias for the same domain](https://tools.ietf.org/rfc/rfc4343.txt).

Domain names are case insensitive and so should it be handled in lesspass.

**Comment by guillaumevincent** [comment]
Hello @devsnd,
it should be the case :) see https://github.com/lesspass/pure/blob/master/src/views/PasswordGenerator.vue#L24-L25
But Android web view doesn't respect some HTML parameter. This is a known Android bug.

On my Android 7 or Android 8 I don't have this bug.

I'm rewriting the Android App, so I keep this one open to be sure this problem is fixed in the next version of the application. It will be a native Android App, so it will not depend on the web view version.

Thanks

**Comment by devsnd** [comment]
Hey @guillaumevincent 

I can reproduce this issue in both chrome 61 and firefox 56 using the input on lesspass.com.

Just to make it clear: The issue is not with android capitalizing my input, but with me as a user inputting a capitalized domain name (which is completely valid as by the RFC linked in the OP).

For example, i think the owners of `PenIsland.net` will always want to capitalize the `I` in their domain.

**Comment by guillaumevincent** [comment]
If I understand properly, you are asking to force lowercase for the site? when typing or when generating the password? because the uppercase site is an alias for the lowercase site?

**Comment by edouard-lopez** [comment]
@devsnd thanks for the cross-platform testing.

However this feature would break existing password generation and I don't really see why we should abide to the same behavior as DNS resolution, that's not the goal of the app.

**Comment by devsnd** [comment]
> I don't really see why we should abide to the same behavior as DNS resolution, that's not the goal of the app.

Okay, then I'm missing the goal of this app. But why is the field called "site" and not something more generic, if lesspass is meant for more than websites? That is what left me to write this report in the first place.

Actually the issue is practically the same as #295, but this time its about domains, and not protocols.

**Comment by edouard-lopez** [comment]
First mock-ups where actually using a more generic wording such as 
* site → _where do you go?_
* login → _who are you?_
* master password → _what is your secret?_
That didn't last as too confusing

**Comment by guillaumevincent** [comment]
@edouard-lopez like for #295 we could introduce a suggestion feature, to help users to use the web extension in the "right way". Like this, it will no break the actual behaviour > so no password break.

And we will discuss the "right way" to see what transformation LessPass should propose.
