### ISSUE TITLE
The lesspass site input field should allow inputting the URL protocol

### ISSUE THREAD

**Issue by devsnd** [lesspass/lesspass#295]
The UI should allow me to enter either `http://google.com` or `https://google.com` (as it might be copy-pasted from the url bar of a browser) to get the same site. Those should both yield the same site.

Currently I get an error instead:

![image](https://user-images.githubusercontent.com/1980794/32101983-f0b1a366-bb09-11e7-819b-c34f2fe794c6.png)

**Comment by guillaumevincent** [comment]
Hi @devsnd,
LessPass doesn't touch to the site field.
If you use the web extension, it auto-fill for you the site field and HTTP protocol is removed.

Can you try to explain again your problem?

**Comment by devsnd** [comment]
ah sorry, the error was actually my error! I made a mistake when recreating the bug.

But what remains the case is that `https://google.com` and `http://google.com` yield different passwords.

(I know that the server might not return the same content for port 80 and 443, but as a user I want to generate a password for `google.com`)

**Comment by guillaumevincent** [comment]
> But what remains the case is that `https://google.com` and `http://google.com` yield different passwords.

It's not a bug, it's a feature. Information should be identical to generate the same password.

So your question is maybe: does the site could remove the HTTP(S) when you paste an url in the site field? If yes, my question is why do you copy the url, and don't use the auto-fill feature?

**Comment by devsnd** [comment]
It's about usability. I copy and paste the url from somewhere and I want my login for the site of this url. This url can be from written by someone else, copy pasted from an email, written in IRC, in a word document, you name it.

**Comment by panther2** [comment]
@devsnd 
So do you ask for the site input field to accept
as well 

`http://abc.def.gh`
as
`https://abc.def.gh`

but for password generation LessPass should ignore the charakter `s` in `https` ?

Have I understood that correctly?

**Comment by guillaumevincent** [comment]
> Currently I get an error instead:

@devsnd if you add https or http in the site field. Generation works:

![screen shot 2017-10-27 at 17 11 04](https://user-images.githubusercontent.com/943762/32111143-eeae92e2-bb39-11e7-8c70-9f4b5a41ae0c.png)
![screen shot 2017-10-27 at 17 10 52](https://user-images.githubusercontent.com/943762/32111145-f0630ef6-bb39-11e7-857f-a06302665308.png)

You can also share a password in your document (with the share icon). It allows you to click and generate your password instantaneously:

`https://lesspass.com/#/?login=a&site=https://lesspass.com/#/a&uppercase=true&lowercase=true&numbers=true&symbols=true&length=16&counter=1&version=2`

This feature is similar to https://github.com/lesspass/lesspass/issues/294

The most difficult thing with those changes is: how do we handle the migration? Does it break a lot of actual user's passwords?

**Comment by panther2** [comment]
> Does it break a lot of actual user's passwords?

Also please consider that LessPass is not limited to website-password creation.

My usecases include password generation for purposes unrelated to Web-Addresses, too.

I welcome very much the opportunity to enter any character into the site field.
That makes LessPass a universal password tool.

Let's not limit that.

**Comment by devsnd** [comment]
@panther2 
> I welcome very much the opportunity to enter any character into the site field.
> That makes LessPass a universal password tool.
> Let's not limit that.

I didn't want to open that can of worms.

> @devsnd if you add https or http in the site field. Generation works:
Yes, it does work, but creates different passwords;

To keep it short: As a user I expect that the password generated for:

`google.com`
`http://google.com`
`https://google.com`

are all the same.

How this is then done internally, is not of interest to the user. I guess that it should be done so that it does not break existing passwords, which probably boils down to removing the protocol entirely, meaning the `http://` and `https://` parts of the `site` are removed before the password is calculated.

**Comment by panther2** [comment]
> To keep it short: As a user I expect that the password generated for:
> 
> google.com
> http://google.com
> https://google.com
> 
> are all the same.
> 
> How this is then done internally, is not of interest to the user.

Sorry, I strongly disagree.
As a user I expect that - following the concept of LessPass - I get three different passwords!
And personally, I am very interested how it is done internally. And I am a user, too.

So don't claim to know what "the user" wants or not.
Your are not "the user", you are one among many.

**Comment by monolifed** [comment]
What @devsnd wants sounds like feature for the autofill part of the browser extension to filter out the protocol part of the website (forgive my ignorance if it already supports it).

For lesspass site and login are not necessarily the site and the login info for the site you are visiting (but using it that way makes remembering them easier).
Someone might want to enter "google dot dot dot com" for site, "my google account" for account and "900913" as counter

**Comment by devsnd** [comment]
>  So please don't claim to know what "the user" is interested in or not.

Hello, it's me, the user. :wave: I tried out lesspass and this was a problem for me, so I wrote this report. There are many users that will not write such a report, here we are having a sample-size of one for this problem. If that's significant or not, is up to you.

> And personally, I am very interested how it is done internally.

Okay, then let me suggest how to do it: A nice solution to me, would be to change the input field so that typing in an address `http://google.com` will yield a suggestion box: `did you mean "google.com"? YES/NO` so its easy for users to type in or copy paste URLs without making a mistake (or correcting that mistake easily).

And when I said
> How this is then done internally, is not of interest to the user.
I meant that this issue has many different solutions and I did not want to steer the discussion in this direction before finding out if this feature is wanted or not in general. Most of the time the suggested solution of a user will be much to specific, because it will only involve the solution to a single problem, while there might be a solution that will solve multiple problems at once.

**Comment by guillaumevincent** [comment]
I will allow users to choose those options in an options panel.
I keep issues open when they make sense, and this one is an option that makes sense.
To be valid an option should help the user to do something quicker, faster or easier.

You just need to keep in mind that it's difficult to change the default behaviour of LessPass. A change like removing `http(s)` by default will break some generated passwords for some users.

> suggestion box: did you mean "google.com"? 

I like the idea of a helper that let the user choosing a "good" alternative
❤️

**Comment by edouard-lopez** [comment]
@devsnd are you aware of the suggest feature of the [connected mode](https://github.com/lesspass/lesspass/wiki/Private-vs.-connected-mode), it might solve _parts_ of your problem.
![connected mode suggestion in LessPass](https://user-images.githubusercontent.com/1212392/32249520-989c2506-be89-11e7-98bd-24757bef6de6.png)

**Comment by guillaumevincent** [comment]
@edouard-lopez the suggestion should appear after a paste and should work in offline mode.

**Comment by guillaumevincent** [comment]
maybe we can add suggestion in offline mode with auto completion?

**Comment by edouard-lopez** [comment]
@guillaumevincent Do you mean to suggest `http://google.com` when user paste `https://google.com` and vice versa?

**Comment by guillaumevincent** [comment]
suggest `google.com` when user enter `http://google.com` or `https://google.com` or `https://www.google.com`
