### ISSUE TITLE
Android layout too small for generated password field

### ISSUE THREAD

**Issue by devsnd** [lesspass/lesspass#296]
When I generate a password on android the generated password does not fit on the screen:

![screenshot_20171027-113026](https://user-images.githubusercontent.com/1980794/32102129-8d5cf508-bb0a-11e7-933d-b41cd1f73c1c.png)

This is annoying if you want to login on another computer which you don't trust with your master password, but you are willing to risk typing in the password of a particular service.

**Comment by monolifed** [comment]
Does rotating the screen (to landscape) help?

**Comment by devsnd** [comment]
Yes, in landscape mode it does show, but to me thats still a usability bug.

**Comment by guillaumevincent** [comment]
It's fixed in the new version of LessPass 3.0.2
