### ISSUE TITLE
Opera extension

### ISSUE THREAD

**Issue by alainrouet** [lesspass/lesspass#297]
Hello,

I'd love to see LessPass on the Opera add-ons website ( https://addons.opera.com/extensions/ ). The Chrome extension works perfectly fine, but it requires the use of another extension ( https://addons.opera.com/extensions/details/download-chrome-extension-9/ ).

Do you think it might be possible in the future, or would it be too much work?

**Comment by guillaumevincent** [comment]
Hello @alainrouet,
I don't know how opera addon works. Is it possible for you to retrieve information on how to migrate a Chrome extension into an Opera extension? Thank you

**Comment by alainrouet** [comment]
Hi @guillaumevincent,

Disclaimer: I'm not a developer, just an enthusiast.

Since Opera is a Chromium based browser, extensions should, in theory, work without any changes. I only had to extract the CRX file, and follow the instructions here: https://dev.opera.com/extensions/basics/ to create a NEX file.

I don't really know where I should be looking at to provide you with an easy method, or if I can be of any help on this matter, but I'll gladly help you if I can.

**Comment by edouard-lopez** [comment]
@alainrouet isn't renaming the file from `.crx` to `.nex` enough?

**Comment by alainrouet** [comment]
Hi @edouard-lopez,

It seems to be working. It's a shame that I didn't even think about renaming the file extension…

**Comment by edouard-lopez** [comment]
Publishing procedure is described on the [Publishing Guidelines](https://dev.opera.com/extensions/publishing-guidelines/#submit) page. 

Not sure if we can automate publication.

**Comment by guillaumevincent** [comment]
Hello @alainrouet,
it looks like there is no automated way to publish the extension. Can you confirm that?
If so I propose you to close this one until they provide an automated way
Thanks

**Comment by alainrouet** [comment]
Hi @guillaumevincent,

You're right. I couldn't find a way to automatize the process or, at least, not at this time.

I'll close this issue for now. Thanks for looking into it.
