### ISSUE TITLE
Can't delete password profile

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#299]
Hi,

### Step to reproduce

I'm trying to delete a password profile when in connected mode. 

* Click the key icon
* Search for my password profile
* Click the trash icon, got the notification _Password profile deleted UNDO_

However if I reopen lesspass extension and search for the "deleted" profile it's still present.

### Env

* Firefox (Linux) `57.0b14 (64-bit)` and Chromium `62.0.3202.75`
* Lesspass extension `3.0.1` (on both browser)

**Comment by guillaumevincent** [comment]
Yeah, delete password is only done after 10s.
I will simplify this one.

**Comment by edouard-lopez** [comment]
Tried to remove the same entry several time and still had it today in my profiles.

Went to the website to reproduce in a clean context:
* delete profile
* saw the network request 
* finally deleted!

Does closing the extension's pop-up abort the request?

**Comment by guillaumevincent** [comment]
Yes, and if you change the view (going into the password generator view for example) reset the deletion too.
