### ISSUE TITLE
Email overflows when to long on mobile

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#30]
When email is too long it overflow and "break" the layout (see page 2). 

![tmp_29277-screenshot_20161027-071629-1039461401](https://cloud.githubusercontent.com/assets/1212392/19761758/7cd5a592-9c37-11e6-9ecc-b756008808fd.png)

![tmp_29277-screenshot_20161027-1122422017922145](https://cloud.githubusercontent.com/assets/1212392/19761852/d263406e-9c37-11e6-8062-c4ff7b8e7508.png)

**Comment by edouard-lopez** [comment]
Why not just replace the email by "You"?

**Comment by guillaumevincent** [comment]
I remove bootstrap js and jquery and use icon now 
It will be fixed by https://github.com/lesspass/pure/commit/1f413d97e9d17f7c14a553c53d96f053285fc01a

**Comment by guillaumevincent** [comment]
![screen shot 2016-10-27 at 14 29 50](https://cloud.githubusercontent.com/assets/943762/19771945/e7ec6a32-9c64-11e6-850a-e230ded87550.png)

**Comment by edouard-lopez** [comment]
Sweet, this icons need tooltips especially the `key` icon.
