### ISSUE TITLE
Not logging into database after browser restart

### ISSUE THREAD

**Issue by HUg0005** [lesspass/lesspass#300]
When ever I restart my browser (Firefox 57.0 on Windows 10), I have to log into my lesspass database. Where as I'm automatically logged back in on my Ubuntu 17.10 machine on Firefox 57.0. Can this be fixed?

**Comment by guillaumevincent** [comment]
Hello @HUg0005,
looks like a Firefox issue with local storage no?

**Comment by HUg0005** [comment]
I have done some testing and the problem seems to be caused by Firefox clearing it's cookies when it closes. Turning that off in the settings has fixed the issue. Thanks
