### ISSUE TITLE
Caching of master password

### ISSUE THREAD

**Issue by apopiak** [lesspass/lesspass#301]
From time to time I need to generate multiple passwords in short succession. (Sometimes this is caused by the generated password disappearing too quickly btw.) Because I use the same master pass phrase that is also fairly long (security...) it can start feeling repetitive.
Suggestion: cache a hash of the master password and offer a toggle that says something like "reuse master password for repeated password generation" so that it is closer in behaviour to `sudo` on Linux systems.

**Comment by yannicka** [comment]
A configurable lifetime would be very interesting (for example 5 minutes, 30 minutes, 1 hour, 4 hours, 1 day, etc.)

**Comment by jliebrand** [comment]
+1 especially with a configurable lifetime... (plus 'clear cache when screensaver comes on / device locks')

**Comment by guillaumevincent** [comment]
The Android version can save your master password locally with your fingerprint. It's not a caching method but similar.
I close this one

**Comment by apopiak** [comment]
sorry for re-opening, but:
@guillaumevincent would you be open to a PR adding this?

**Comment by guillaumevincent** [comment]
I am divided for this issue. At the same time I like the idea as sudo to save the password temporarily to reuse it right after. But I know that there is no way to save securely the master password accessible only by the web extension on the browser. 

How do you plan to save the master password from the web extension?

**Comment by apopiak** [comment]
What about hashing it with (part of) the settings? You'd have to prompt again on settings change, but that's uncommon so you'd get about 80% there.

**Comment by guillaumevincent** [comment]
I mean, where do you want to save the master password? Localstorage ? Cookie? All those data are not safe
