### ISSUE TITLE
Feature request: multiple domain support per profile.

### ISSUE THREAD

**Issue by batonac** [lesspass/lesspass#302]
I use some services which spread themselves across domains, and allow you to login with the same account on any of them. Please allow for adding multiple axillary domains to one profile so the master domain and configured options will be queried on any associated domain.

**Comment by guillaumevincent** [comment]
Hello @batonac 
is it the same as https://github.com/lesspass/lesspass/issues/278 ?
if so can you +1 the issue to show your interest in this enhancement?

**Comment by guillaumevincent** [comment]
I close this one, because it dupplicates #278 
Feel free to comment on this one if not
