### ISSUE TITLE
Can't delete saved profiles 

### ISSUE THREAD

**Issue by theblackking** [lesspass/lesspass#307]
For some reason there is no trash can icon next to my saved profiles when signing with my account.

The same applies for using the website & the add on for chrome and firefox.
<img width="448" alt="screen shot 2017-12-22 at 13 02 38" src="https://user-images.githubusercontent.com/34771302/34299113-1c2bf98e-e719-11e7-8ad7-401ccbf72ac9.png">

**Comment by guillaumevincent** [comment]
Hello,
click on the icon to select the password profile you want to delete, then click on the delete icon.
I will make the icon more visible.

**Comment by theblackking** [comment]
Thanks it worked :)

**Comment by guillaumevincent** [comment]
I reopen the issue because you raise an issue finding a way to delete the password profile.
Apparently it's not obvious. 
We need to improve this

**Comment by guillaumevincent** [comment]
It's fixed in the last version of LessPass in production
