### ISSUE TITLE
frontend: Not Generating Passwords Using Microsoft Edge

### ISSUE THREAD

**Issue by seamlik** [lesspass/lesspass#309]
When using Microsoft Edge 41.16299.15.0 (with EdgeHTML 16.16299) on [the frontend](https://lesspass.com), clicking the `Generate` button yields nothing.

**Comment by guillaumevincent** [comment]
Hello @seamlik,
probably a web crypto non working implementation.
can you look at the pbkdf2 line [here](https://diafygi.github.io/webcrypto-examples/)
What do you see?
Thank you

**Comment by seamlik** [comment]
You are right, 4 ❌ for PBKDF2. Looks like this can't be solved unless Microsoft makes improvements on it?

**Comment by guillaumevincent** [comment]
You are right, I will fix this with a warning and encouraging people to use Firefox. Thanks for the feedback. I don't have a single computer on Windows.

**Comment by guillaumevincent** [comment]
I close, Edge will use chrome engine so it will work in the future!
