### ISSUE TITLE
Une autre approche pour les règles spécifique aux sites

### ISSUE THREAD

**Issue by GammaNu** [lesspass/lesspass#31]
Plutôt que de proposer un compte aux utilisateurs pour qu'ils puisse mémoriser leurs règles de password pour leur site, une autre approche serai de **proposer une liste de règles alimentée par la communauté**, pour proposer des règles par défaut pour chaque site (tout du moins pour les plus répandu, par la même probablement plus susceptible d'avoir des règles spécifiques).

Avantage : plus besoin de stocker quoi que ce soit lié aux utilisateurs (s'ils veulent savoir sur quels site ils ont un compte, d'autres outils comme des marques pages peuvent faire l'affaire)

Inconvénient : En cas de mise à jour des règles par défaut pour un site, les mots de passes généré serons différents pour tout les utilisateurs existant, ce qui peux poser problème pour se reconnecter.

**Comment by guillaumevincent** [comment]
Oui cela a du sens pour un site de banque où tous les codes sont par exemple des nombres de taille unique. Cela n'en a pas pour les sites où les paramètres sont modifiables par l'utilisateur.

**Comment by edouard-lopez** [comment]
C'est une bonne idée, pour mitiger le problème de migrations on peut utiliser la version du fichier de config et si jamais elle change proposer aux utilisateur de changer de version. Et tout ça à faible coût puisque l'on se baserai sur git.

**Comment by guillaumevincent** [comment]
@GammaNu les règles spécifiques réduisent l'entropie du système et donc la sécurité du mot de passe fort. 
A cause de l'implémentation de la V2, nous nous contenterons des règles proposées simples.
Je ferme

Discussion en anglais ici: https://github.com/lesspass/lesspass/issues/89
