### ISSUE TITLE
CLI ignores initial zeros if the username is a number

### ISSUE THREAD

**Issue by onagano-rh** [lesspass/lesspass#310]
For example, all the followings generate the same password.
~~~
lesspass example.com 0123 masterpassword 
lesspass example.com "0123" masterpassword
lesspass example.com "00123" masterpassword
lesspass example.com 123 masterpassword 
~~~
It seems JavaScript converts such an argument to a number automatically, where we want the string we typed. This behaviour is different from the web extensions of Firefox and Chrome those treat the argument as a string.

**Comment by monolifed** [comment]
From https://github.com/substack/minimist readme.markdown:  
`Numeric-looking arguments will be returned as numbers unless opts.string or opts.boolean is set for that argument name.`

**Comment by guillaumevincent** [comment]
Fixed with the latest version of lesspass-cli

    npm install -g lesspass-cli

Thank you for your report
