### ISSUE TITLE
Encode parameter before sharing it using the url?

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#311]
Hello
I have a bug when using this feature: https://github.com/lesspass/lesspass/issues/142

Some of my login are emails, and my emails can contain specials characters like `+`.
For example in the website lesspass.com:
 - site: test
 - login: test+test@test.test
 - master password: test

(We generate the password, else we can't have the share button) `ky2@z=y6?iwE*3D\`

URL to share is: https://lesspass.com/#/?login=test+test@test.test&site=test&uppercase=true&lowercase=true&numbers=true&symbols=true&length=16&counter=1&version=2

I go to this URL, I saw login is now `test test@test.test` instead of `test+test@test.test`
Using the same master password (test), I have a completely different password `x@96W03)!K!oc[Kq` because of this login.

→ Having this different password is normal in this case, but having a different login when using the sharing URL is not.

Thank you

**Comment by Kcchouette** [comment]
By doing some more test, we should encode (using _encodeURIComponent_) login (and site): for example `test+test@test.test` should be `test%2Btest%40test.test`, and it's yet `test+test%40test.test`

**Comment by guillaumevincent** [comment]
yes this is a good idea
