### ISSUE TITLE
Setup issues. Can't create super user. 

### ISSUE THREAD

**Issue by folusomaine** [lesspass/lesspass#314]
Running the setup on Ubuntu installed in virtualbox. First command to install LessPass works and there's confirmation "LessPass database is running". But the command to create superuser is not working and returns "Error, No such container" 
Need assistance to finish this setup, please.

**Comment by edouard-lopez** [comment]
@folusomaine could you provide more context:
* commands 
* docker version
* outputs

**Comment by folusomaine** [comment]
command:
<docker exec -it lesspass_backend_1 sh>
outputs: 
no such container found

docker version 17.12 ce

I also pulled the lesspass/backend from the hub and then i try to run the lesspass/backend image but it outputs: nc: getaddrinfo: name cannot be resolve

**Comment by guillaumevincent** [comment]
Did you solve your problem?
Can you run

    docker-compose ps

Look like your container is not running

    docker-compose logs

**Comment by folusomaine** [comment]
i haven't solved the problem. I mistakenly closed the issue. 
I've run **docker-compose ps**
It doesn't show any running container.
it returns this output continuously **nc: getaddrinfo: name cannot be resolve**
so i opened another terminal and run **docker-composer ps**
its shows the container is running.
but afterwards the next command doesnt work **docker exec -it lesspass_backend_1 sh**

**Comment by folusomaine** [comment]
I think the installation is complete but its not running correctly. 
it still returns this output **nc: getaddrinfo: name cannot be resolve**
Im able to enter backend with this command **docker exec -it [container ID] sh**
**python manage.py createsuperuser**
**python manage.py migrate**
all migrations OK
but i cant access https://[DOMAIN]/admin

this output still running continuously in one terminal
**nc: getaddrinfo: name cannot be resolve**

please help

**Comment by folusomaine** [comment]
output when i run

**docker-compose logs**

**docker-compose ps**

**docker ps**

![docker-compose-ps-logs](https://user-images.githubusercontent.com/29386389/36148988-3a3a65a4-10be-11e8-853e-51fa742e50ef.JPG)
**

**Comment by guillaumevincent** [comment]
you are not on the good folder. You need to run `docker-compose` in LessPass folder where ` 	docker-compose.yml` is located.

Did you run `bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/lesspass.sh) [DOMAIN] [EMAIL]` ?

**Comment by folusomaine** [comment]
I'm able to resolve by doing some troubleshooting and tweaking. 
I can finally access the application via the browser using the container ip address 172.17.0.2/admin
but once i login it returns this output
![login output](https://user-images.githubusercontent.com/29386389/36160140-c08ad090-10e0-11e8-8f03-09dace9ba31e.JPG)

should i still go ahead and run docker-compose in lesspass folder to fix, and yes i already ran the bash. It ran ok

**Comment by guillaumevincent** [comment]
`[DOMAIN]` should be replaced by your domain name pointing to your server (i.e. example.org)
We are agree that your `[DOMAIN]` DNS is pointing to your server?

Your `docker ps` is not good. It should returns something like:

```
xxxxxxxxxx        lesspass/nginx:letsencrypt   "/entrypoint.sh ngin…"   2 months ago        Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   lesspass_nginx_1
xxxxxxxxxx        lesspass/backend:latest      "/entrypoint.sh /usr…"   2 months ago        Up 2 minutes        8000/tcp                                   lesspass_backend_1
xxxxxxxxxx        lesspass/frontend:latest     "npm start"              2 months ago        Up 2 minutes        8080/tcp                                   lesspass_frontend_1
xxxxxxxxxx        postgres:9.5                 "docker-entrypoint.s…"   2 months ago        Up 2 minutes        5432/tcp                                   lesspass_db_1
```

After running `bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/lesspass.sh) [DOMAIN] [EMAIL]` you should go to `[DOMAIN]/admin`.

**Comment by guillaumevincent** [comment]
Look like you are running it on a VM on your computer.
If you want to test LessPass on a VM you should look at this [docker-compose.yml file](https://github.com/lesspass/lesspass/blob/master/docker-compose.yml)

Care this is a dev version. Not valid for production.

**Comment by guillaumevincent** [comment]
I close this one. 
Feel free to post on this thread to ask for extra help.
