### ISSUE TITLE
Use case for regular user to keep track of counter?

### ISSUE THREAD

**Issue by stevenandres** [lesspass/lesspass#315]
Trying to understand the use case for a non-IT non-admin regular user: If we train people to use lesspass to setup all their complex passwords, and they need to rotate every year or quarter, how is that regular user supposed to remember what the counter was set at last time? If they need to store that somewhere else, that means two areas to maintain password-ish information. Maybe I'm misunderstanding the counter?

**Comment by panther2** [comment]
In case you need to change the Password every year you could set the counter for example to "18" for "2018".
Changing on a monthly base set it for example to "5" for "May" ...
... just some ideas.

**Comment by guillaumevincent** [comment]
Hello @stevenandres,
@panther2 answer is one solution.
Another solution is to use LessPass Database, the connected version that allow users to save their password's profiles.

**Comment by panther2** [comment]
@guillaumevincent 
What is the maximum allowed value for the counter?

**Comment by guillaumevincent** [comment]
@panther2 there is no maximum.
there is surely a technical limitation on a very very large number. I don't know it

**Comment by edouard-lopez** [comment]
@stevenandres nice to hear you want to use lesspass on a larger scale. 

Could you tell us more about the context you're talking about so we can give some feedback? Is it for enterprise/NGO/Open-source community

**Comment by panther2** [comment]
@guillaumevincent 

> there is no maximum.

Thanks. That is good to know, as it gives a high flexibility for use cases such as the one @stevenandres brought up. :smile:

**Comment by stevenandres** [comment]
Thanks -- if there is no upper limit I can instruct people on using the year as the counter value

**Comment by guillaumevincent** [comment]
@stevenandres send NIST password guidelines to the guy who set the rule https://pages.nist.gov/800-63-3/sp800-63b.html

this is not a good rule at all

**Comment by panther2** [comment]
@guillaumevincent 
Not good, you are right for sure, but unfortunately very common in many professional (enterprise) environments. I had to change passwords for up to 10 applications (as well web based as not web based / stand alone or server based) every three months. 

There is no single "guy" behind it but often regulatoric requirements that lead to these consequences.

It was a pain - but LessPass is a great aid for tasks like these. So thanks again to you and @edouard-lopez for this great tool.

**Comment by guillaumevincent** [comment]
More often they follow some rules without any idea if the idea is good or not. Sometimes it's good to point them to the good rules.
