### ISSUE TITLE
Save default options for offline mode

### ISSUE THREAD

**Issue by ldanicel** [lesspass/lesspass#316]
Advanced options like password length are not saved and need to be reconfigured everytime I generate myself the password

**Comment by guillaumevincent** [comment]
Hello @ldanicel,
I don't understand the issue. Are you using the connected mode or the offline mode?

**Comment by ldanicel** [comment]
this was quick... offline mode - i go to my website for example and generate myself a new password by setting for example 29 as password length. I copy the password , change my password or even login. Second time I go in the extension I have to set again 29 as the length because it resets back to the default of 16 chars.

**Comment by guillaumevincent** [comment]
@ldanicel nop your are right.
I will implement this soon, a page to save default options for offline mode.

**Comment by guillaumevincent** [comment]
The feature is present in the Android version
I close, I will implement it in the web extension soon
