### ISSUE TITLE
[Question] Is master password reset useless?

### ISSUE THREAD

**Issue by tiaod** [lesspass/lesspass#317]
If I had forgot my master password, I can't generate the correct password for other websites anymore, isn't it? 🤔

**Comment by guillaumevincent** [comment]
@tiaod the answer is yes, without your master password, you can't generate the correct password.

**Comment by edouard-lopez** [comment]
Hello @tiaod, indeed as your master password is one parameter we use to create unique password:

> lesspass(`site`, `login`, `master password`, `options…`) → unique password 

If you want to know more, you can read our [blog post: LessPass How Does It Works?](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4) and a short 
[Technical Overview of Password Generation](https://github.com/lesspass/lesspass/wiki/Overview-of-Password-Generation)

If you are locked out of some of your accounts (facebook, google, etc.) you can use their `forgot password?` feature

**Comment by tiaod** [comment]
Maybe Couchdb + Lesspass is a good idea! Because password reset is not necessary, I can use only the original Couchdb as my backend, and I don‘t need to change anything! 😃
