### ISSUE TITLE
nginx-less docker configuration

### ISSUE THREAD

**Issue by HeapUnderfl0w** [lesspass/lesspass#319]
While i was installing the docker image through the [command](https://github.com/lesspass/lesspass/#self-host-your-lesspass-database) from the README.md, i ran into the following problem:

I have a running instance of NGINX on the host-system which serves as the reverse proxy for all of the web-services running on the system (it is secured with HTTPS).  
This creates a problem as the nginx-container wants to bind to the port 443, which is already in use.
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint angry_panini (bc8f311174f0fe6b4cd298cc3bb0350faf2b631e589de2a54f6c2beda942bf45): Error starting user land proxy: listen tcp 0.0.0.0:443: bin
d: address already in use.
```

Is there a easy way to forego the nginx server and just use the one already running on the host ?

**Comment by HeapUnderfl0w** [comment]
this has already been answered in #304

**Comment by HeapUnderfl0w** [comment]
Reopening as i could not get anything to work with the "solution" in #304 

What i am trying to do is  
i have the sub-url `/lp/` on my existing nginx-server over which i want to serve the lesspass page.

This is the modified `docker-compose.prod.yml` and `nginx.conf` i came up with.:
https://gist.github.com/HeapUnderfl0w/2b506a156c8e1ec7f0d74c6acd1152b1

It works up to the moment of me trying to access it through the nginx-server, as it then complains with `Cannot GET /lp/`

**Comment by guillaumevincent** [comment]
Hello @HeapUnderfl0w,
sorry I miss your issue

What is the issue you encounter?
Can you print here the `docker-compose logs` output?

**Comment by HeapUnderfl0w** [comment]
On the system there is currently an nginx-reverse-proxy already running.  
Due to that i tried to create a docker-configuration, that did not include the nginx image.

This is the log when i start the docker-file
https://gist.github.com/HeapUnderfl0w/76ca3b24a17131db881b145a427a9cb4

But when i then access the page `/lp/` on my reverse proxy that is configured like [this](https://gist.github.com/HeapUnderfl0w/2b506a156c8e1ec7f0d74c6acd1152b1#file-nginx-conf)
I just get this html page: 
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /lp/</pre>
</body>
</html>
```

**Comment by guillaumevincent** [comment]
@HeapUnderfl0w so the frontend is properly listening on http://localhost:8080 ?
What is the output of `curl http://localhost:8080`?

Look like a nginx misconfiguration.

**Comment by HeapUnderfl0w** [comment]
Ok, i will look into it. (curl returns the desired content)
