### ISSUE TITLE
Règles avancées

### ISSUE THREAD

**Issue by GammaNu** [lesspass/lesspass#32]
Certains sites ont des contraintes comme :
au moins 2 chiffres, non consécutif
Au moins deux majuscules, non consécutif
Et parfois un nombre de caractères spécifique imposé (genre 8)
Dans ce genre de situation, en l'état actuel, il n'est si je ne me trompe pas possible de garantir ces règles pour un mot de passe généré ?

**Comment by guillaumevincent** [comment]
En effet, il sera possible dans une future version de changer pour chaque mot de passe le pattern utilisé. Pour l'instant je ne veux pas complexifier l'UX. Sinon ce genre de site ne comprennent pas qu'un chiffre ou un caratère spécial c'est la même chose pour un programme malveillant.

**Comment by guillaumevincent** [comment]
Je ferme car c'est la même chose que https://github.com/lesspass/lesspass/issues/37
Cela semble être souhaité par plus d'une personne.
