### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#320]
Hello LessPass Community,
I'm working on a LessPass Redesign. There is still a lot of work to be done but you can see a preview on this [codepen](https://codepen.io/guillaumevincent/full/PRwamO/).

If you have any feedback on the new interface, feel free to add a comment here.
I will update this issue after any update.

![screenshot from 2018-03-23 10-59-23](https://user-images.githubusercontent.com/943762/37823273-4db5fe98-2e89-11e8-8a83-cdec8dcbfc43.png)

**Comment by panther2** [comment]
@guillaumevincent 

Looks nice. 
What will be behind the 
![lp](https://user-images.githubusercontent.com/20812775/37834403-e93df69e-2ead-11e8-8d06-66e06729b189.PNG)
image?

The site default in this case would be "lesspass.com" - so I hope you won't change today's defaults...

**Comment by guillaumevincent** [comment]
@panther2 behind the hamburger, we will have the menu, with settings for LessPass, Login, etc. The menu is in the todo list.

The default will not change, but we will add a new feature :)
An auto complete suggestion:

```
site: www.subdomain.example.org
|example|
|example.org|
|subdomain.example.org|
```

**Comment by edouard-lopez** [comment]
### Icons

I'm a bit confused by the use of the hamburger and the cog icons.

The ![selection_007](https://user-images.githubusercontent.com/1212392/38022486-f201c654-327f-11e8-874a-81a6d63fc73c.png) (cog icon) is often associated with settings, I would suggest to use the [![selection_008](https://user-images.githubusercontent.com/1212392/38022677-72146856-3280-11e8-942a-9482d7c68892.png) _slider_ icon](https://fontawesome.com/icons/sliders-h?style=light) for the password configuragtion.

### Toggle button
I feel like something is amiss with the toggle button, either the unnecessary shadow or a missing tiny radius

### Panel's handle position
Why force user to move there mouse when they just want to check the password config? Imagine if clicking the lesspass icon in the browser toolbard move the icon to another place.
![selection_009](https://user-images.githubusercontent.com/1212392/38022907-1fbd77b8-3281-11e8-8914-a3e4c605b64a.png)

**Comment by edouard-lopez** [comment]
A quick look at my phone apps shows a recurring design pattern for a panel: 
1. a hamburger icon in the top/bottom navbar.
1. clicking it slide the panel from the border to the center
1. take full height
1. contains action entries 

This is used by Google Keep/Maps/Calendar, Wikipedia, Pleco, etc. A similar pattern is based on the slide gesture without icon but that won't fit on a desktop.

| App | closed panel | open panel |
| --- | --- | ---
google keep | ![keep close](https://user-images.githubusercontent.com/1212392/38024497-7917bb4e-3285-11e8-9036-8ad66360c6a0.png) | ![google keep](https://user-images.githubusercontent.com/1212392/38024196-92c08b08-3284-11e8-8c2f-18e27e266050.png)
pleco | ![pleco close](https://user-images.githubusercontent.com/1212392/38024551-afb2bfc8-3285-11e8-92e4-963fa9a05933.png) | ![pleco](https://user-images.githubusercontent.com/1212392/38024207-98f61e20-3284-11e8-919c-86cce7f7a669.png)
wikipedia beta | ![screenshot_20180328-124440](https://user-images.githubusercontent.com/1212392/38024652-efb878c4-3285-11e8-8f74-7d55f3fe2fb9.png) | ![wikipedia beta](https://user-images.githubusercontent.com/1212392/38024216-9f2276b8-3284-11e8-9afc-4358f20a9bd5.png)

We could try one with the following entry:
* settings
* length
* counter
* lowercase
* upercase
* digits
* symbols

**Comment by edouard-lopez** [comment]
Here is a [codepen proposal based on above feedback](https://codepen.io/edouard-lopez/pen/QmaxvW). There are some rough edges that need improvement but you get the idea.

![selection_002](https://user-images.githubusercontent.com/1212392/38028189-6c04b94a-3292-11e8-9db0-db63b56c9fab.png)

### Panel focus
![proposal-new-design-panel](https://user-images.githubusercontent.com/1212392/38028433-3462e5e2-3293-11e8-8ab5-f3358a22fe92.png)

**Comment by guillaumevincent** [comment]
I love it!
The only problem I see is that the hamburger menu should contain also the login button and the global settings button.
Maybe we should move the password settings button on the bottom right.
@edouard-lopez where do you see the sliders icon?

**Comment by edouard-lopez** [comment]
Global _settings_ button is present at the top when open, otherwise there is only the hamburger menu visible.

There is a strong constraint on available space, we have several action point to mitigate this:
* inline the spinner next to their labels
* remove section header
* tweak margin/padding

I will give it a shot.


the slider icons remark was related to your first proposal.

**Comment by edouard-lopez** [comment]
preview

| Fit in Panel and Sign-in | [_Settings_ at the bottom](https://codepen.io/edouard-lopez/pen/QmaxvW) |
| --- | --- |
![proposal-panel-sign-in](https://user-images.githubusercontent.com/1212392/38038849-402a4834-32ac-11e8-9215-9e0c6871d72c.png) | ![proposal-panel-settings-bottom](https://user-images.githubusercontent.com/1212392/38038959-735b838a-32ac-11e8-81a7-498faace484b.png)

**Comment by guillaumevincent** [comment]
Login and Global settings are different from password generation settings.
Maybe we can try to keep the current structure but use the settings panel.

![screen shot 2018-03-29 at 09 53 28](https://user-images.githubusercontent.com/943762/38076806-0ca0f086-3337-11e8-9ff2-f46be2de15d3.png)

**Comment by buoyantair** [comment]
Woah :O
