### ISSUE TITLE
How to find the original password？

### ISSUE THREAD

**Issue by theratlesnake** [lesspass/lesspass#321]
I registered for Lesspass（Chrome）， then entered my email address and password at google.com, then clicked the Generate button, and then what should I do? Even if I saved the generated password,  how can I see the original password I entered? what's the use? Can someone tell me how to use this software? Thank you! (I'm sorry, my English is not very good)

**Comment by guillaumevincent** [comment]
Hello @theratlesnake,
did you see the "How does it work?" section on the readme?

    🇫🇷 LessPass comment ça marche?
    🇬🇧 LessPass How Does It Work?
    🇩🇪 LessPass - Wie funktioniert das?

LessPass is different from other password managers. Read the How does it work section, then come back here for more details

**Comment by theratlesnake** [comment]
@guillaumevincent  Hello, I have already seen the readme.  But still don’t quite understand how to use it, and in my country, I can’t find any ways to use. It may be that there are not many people who use it. So thank you again!
