### ISSUE TITLE
Professional Copywriter Willing to Contribute...

### ISSUE THREAD

**Issue by order4adwriter** [lesspass/lesspass#323]
I've seen and used the demo of your online password manager  app Lesspass at your website...and I must say that it looks pretty cool!

I am a professional copywriter and I 'd like to contribute to your repository by writing an About Lesspass/ About Us page content, Privacy Policy, Help/FAQ, Terms Of Use, Case Studies, Blog posts ... and other necessary marketing content for your app website.

My question is .... would you merge it into your repository when it is done? 

Please let me know so I can get started as soon as possible.

Thanks.

**Comment by guillaumevincent** [comment]
Hello @order4adwriter,
I see that you opened a lot of similar requests in a lot of different projects with the same message.
We have already some of your suggestions.

Is this request for disguised advertising? order4adwriter > order for advertising writer ?
I close this one, LessPass is an open source repository, you don't need an approval for pull request. 
Thanks

**Comment by order4adwriter** [comment]
Hi @guillaumevincent,
Yes I did send similar requests to other projects because I still believe in getting permission form such project owners before creating any content / copy for the pages.

Lol!.... No it is not a marketing gimmick...Order4adwriter is indeed my moniker on a lot of freelance websites I work on including fiverr, freelancer, peoplerperhour, upwork etc.

At times when I feel bored or just wanna keep my brain busy, I assist some open source app repos such as yours here on github with any kind of content/ copy writing.

Look I get it, you probably don't need any thing from me...That's ok.

But  I am assuring  you now of my sincere intentions. I know a pull request approval is not necessary... but I just feel personally that contacting you first before writing anything and submitting i as a pull request is indeed the right thing to do.

Anyway...let me know if you do change your mind.. and if there's any content you''d like me to contribute to.

Thanks for taking the time to read this.

**Comment by guillaumevincent** [comment]
Hello @order4adwriter,
thank you for the clarification.
Feel free to contribute, check the [contributing file](https://github.com/lesspass/lesspass/blob/master/CONTRIBUTING.md) to see what kind of help we are looking for.
