### ISSUE TITLE
The maximum length of a password is 35 characters.

### ISSUE THREAD

**Issue by FranzSkuffka** [lesspass/lesspass#326]
`The maximum length of a password is 35 characters.`

This effectively locks this out of generating any hashes / keys :( (IOTA in my case)

**Comment by guillaumevincent** [comment]
Hello, 
the entropy used to generate a password limit us to 35 chars. Without changing the algorithm it will be impossible to modify the max length.

**Comment by FranzSkuffka** [comment]
I understand - thank you for the insight.

**Comment by FranzSkuffka** [comment]
Just wanted to add this to the wiki. It is not writable is it?
