### ISSUE TITLE
LessPass for teams

### ISSUE THREAD

**Issue by oncletom** [lesspass/lesspass#327]
Hello folks 🙂 

I get LessPass is about choosing a master password.
How does it work if passwords are meant to be shared amongst different people, who could be joining and leaving an organization?

I can imagine this being used in combination of personal passwords (not shared with the team).

Is it already possible? Is it something you've been thinking about?

Thanks a bunch for this project :-)

**Comment by guillaumevincent** [comment]
Hello @oncletom,
Happy to see you there.
I think @Krilivye use LessPass in his team. He told me they share a master password. They consider that changing master password when somebody leave is a feature.

I imagined at the beginning using LessPass Database to saved team info and some GPG encryption "like pass" to share a master password across team.

But this is a complex evolution (interesting also) and LessPass will probably need some help from the crypto experts

**Comment by oncletom** [comment]
Thank you @guillaumevincent :-)

Good to see all the nice work you've put into LessPass too!
I'll think about it and see what's the most convenient for our team between a shared password and NextCloud password manager.

**Comment by Krilivye** [comment]
Hi folks!
Some of us in the team use LessPass for every bare-metal server we have (1 password/server). 
Most of us use a personal KeyPass.
For collective datas we use a shared KeyPass Base on a private cloud service with 2 Factors auth.

My main +++ for LessPass is the CLI and so it's ability to be combined in automated script (ansible/ssh... )
and it's "simple" open source implementation.

Kudo's to @guillaumevincent ;)
