### ISSUE TITLE
Non-matching password on counters >= 10 with different versions of lesspass-cli

### ISSUE THREAD

**Issue by D-Nice** [lesspass/lesspass#328]
Using the npm package lesspass-cli on Void GNU/Linux Kernel 4.12.x - 4.16.x  with musl libc, when a counter of 10 or higher is set, it renders passwords that do not match with those generated on other OS, including other Linux distributions just using glibc and Windows. The above is not an exhaustive list, I have a feeling it may have to do something with musl, so if someone is using Alpine Linux with musl or another distro that comes with musl, it would be helpful to confirm that it's related to musl in fact.

Example: 

Windows/Debian 9:
```
$ lesspass site login test -c 9
vvqNx4/AOBLx;d]s

$ lesspass site login test -c 10
XFt0F*,r619:+}[.
```

Void Linux + musl
```
$ lesspass site login test -c 9
vvqNx4/AOBLx;d]s

$ lesspass site login test -c 10
l:`nzj>S7+0#uL_d
```

Using the browser-plugin, renders results consistent with those on other distros.

**Comment by guillaumevincent** [comment]
Hello @D-Nice,
Nice catch. I will look at this issue after my paternity leave.
Feel free to update the issue if you find anything else

**Comment by D-Nice** [comment]
Did try on clean installation of Void Linux using glibc and the same issue, so it doesn't appear that muslc is the culprit as I had expected.

**Comment by D-Nice** [comment]
Just tried this on a Windows 10 PC and same issue occurred. Appears to have nothing to do with the distro as I initially seemed to assume. Instead it has to do with the version of lesspass-cli (although I swore I tried diff versions earlier). 

I haven't had the time to check exactly at which version the difference starts occurring, but the previously mentioned Windows/Debian 9 results are with lesspass-cli@5.0.1 and the Void Linux + musl result I mentioned occurs with lesspass-cli@5.1.1

For now I'm reverting to 5.0.1 until I'm told which one is not working correctly with 10+ higher counters.

**Comment by guillaumevincent** [comment]
LessPass cli move on pypi and this bug is fixed:

    npm -g uninstall lesspass-cli
    python3 -m pip install --user lesspass

:warning:  breaking changes:

 * -c is associated with --copy flag to copy the password
 * -C is associated with the counter (previously -c)
