### ISSUE TITLE
Ubuntu 18.04 and LessPass Web Extension issue on Firefox

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#329]
Hello LessPass users,
there is an issue with Firefox 60 on Ubuntu 18.04 due to a broken ibus package.
See https://github.com/ibus/ibus/issues/2002

It's not related to LessPass and we are waiting for a fix from ibus

Thanks to [jfietkau](https://www.reddit.com/user/jfietkau) for the research

See next post for a temporary workaround
Thanks @subdavis

**Comment by lolozere** [comment]
After reading all issues from mozilla, ibus and gnome-shell, I try and fix the problem by applying this package: https://bugzilla.mozilla.org/attachment.cgi?id=8974077

Run:

```
dpkg -i ibus-gtk3_1.5.17-3ubuntu4_amd64.deb
```

And restart Firefox. It should be worked.

**Comment by mihira** [comment]
> If you use Ubuntu 18.04, after reading all issues from mozilla, ibus and gnome-shell, I try and fix the problem by applying this package: https://bugzilla.mozilla.org/attachment.cgi?id=8974077
> 
> Run:
> 
> ```
> dpkg -i ibus-gtk3_1.5.17-3ubuntu4_amd64.deb
> ```
> 
> And restart Firefox. It should be worked.

Thanks @lolozere, this worked for me :)

**Comment by guillaumevincent** [comment]
I close, this is a bug related to a broken package on Ubuntu. Feel free to comment the ibus issue
