### ISSUE TITLE
LessPass installation fails when generating LE certificate.

### ISSUE THREAD

**Issue by r4nd0m9uy** [lesspass/lesspass#331]
Hi everyone

I just installed LessPass, but during the installation, I got this message when the Let'sEncrypt certificate generates:
`Create LetsEncrypt certificate...
Unable to register an account with ACME server`

After which the installation process just stops.

I tried running the following steps manually and ignoring the certificate problem by calling following commands:

`root@less:~# curl -s -o update.sh https://raw.githubusercontent.com/lesspass/lesspass/master/scripts/update.sh
root@less:~# chmod u+x update.sh
root@less:~# docker-compose up -d`

The frontend is accessible, but I can't create the backend user:

[//snippeter.krizdelogi.be/public.php?id=181
](//snippeter.krizdelogi.be/public.php?id=181)

What am i doing wrong?

Thanks in advance everyone

**Comment by guillaumevincent** [comment]
@r4nd0m9uy can you copy paste the info from `/var/log/letsencrypt` ?

See https://github.com/certbot/certbot/issues/3671
`The ACME server believes xxx@yyy.com is an invalid email address. Please ensure it is a valid email and attempt registration again`

**Comment by r4nd0m9uy** [comment]
Hi @guillaumevincent 

There is no log at /var/log/letsencrypt

The emailaddress is a valid mail address, so this shouldn't be a problem

This is the full output of `root@less:~# bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/lesspass.sh) [less.dlds.be] [me@dlds.be]`:

`Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
Pulling frontend (lesspass/frontend:latest)...
latest: Pulling from lesspass/frontend
Digest: sha256:5554cddd1ae08c77b1099b138a0cf8c533b0e88582abe6084f914fc23f172710
Status: Image is up to date for lesspass/frontend:latest
Pulling db (postgres:9.5)...
9.5: Pulling from library/postgres
Digest: sha256:0d94b9517961ef1d09f6db201375fc2d68e169256fc29d911ca60a3d11b040c5
Status: Image is up to date for postgres:9.5
Pulling backend (lesspass/backend:latest)...
latest: Pulling from lesspass/backend
Digest: sha256:471e26ddbc2edcf7cff6919bcf17501d46862241a34f1d6574641ee79c186c2e
Status: Image is up to date for lesspass/backend:latest
Pulling nginx (lesspass/nginx:letsencrypt)...
letsencrypt: Pulling from lesspass/nginx
Digest: sha256:4de7869fe0a126683ee5cdbfa2d26e58e584363a3c851a902e175b2c1f86c2bc
Status: Image is up to date for lesspass/nginx:letsencrypt
Removing network lesspass_default
WARNING: Network lesspass_default not found.
Create LetsEncrypt certificate...
Unable to register an account with ACME server
root@less:~# 

`

**Comment by guillaumevincent** [comment]
@r4nd0m9uy I tested and it works for me

Certbot needs to answer a cryptographic challenge issued by the Let's Encrypt API in order to prove you control your domain. It uses ports 80 or 443 to do so

Can you look if you don't have a firewall rule for port 80 and 443?

Other test you can do is to run manually the command with more log
```
docker run -it --rm -p 443:443 -p 80:80 -v $PWD/letsencrypt:/etc/letsencrypt/ certbot/certbot certonly --standalone --noninteractive --quiet --email "me@dlds.be" --agree-tos -d "less.dlds.be" -vvvvv
```

**Comment by r4nd0m9uy** [comment]
Okay now the LE certificate gets installed w/o error. I don't know what the reason was, unfortunately.
I have another issue that came up now, but I'll open a new issue for that.
