### ISSUE TITLE
createsuperuser command gives error when connecting to db

### ISSUE THREAD

**Issue by r4nd0m9uy** [lesspass/lesspass#332]
Hi again to all! :)

When I'm trying to create the superuser, the command gives `django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"` as a result.
I tried to find out where the password was stored in the lesspass folder, but I couldn't find it.

What are the things I should check?

Thanks in advance

Kriz

**Comment by guillaumevincent** [comment]
Hello,
The postgres database use the [env variable DATABASE_PASSWORD](https://github.com/lesspass/lesspass/blob/master/docker-compose.prod.yml#L11).
The DATABASE_PASSWORD is generated during the [lesspass.sh](https://github.com/lesspass/lesspass/blob/master/lesspass.sh#L39) run and saved in a .env file.
The DATABASE_PASSWORD is then used by the [django backend](https://github.com/lesspass/backend/blob/670e4b39c06416a1f3946a7d97074dc6f42751b7/lesspass/settings.py#L76)

Normally when you connect on the backend (`docker exec -it lesspass_backend_1 sh`) you are connected as root user. You can do a `echo $DATABASE_PASSWORD` to see the database password. 
Inside the db (`docker exec -it lesspass_db_1 sh`) you can see the database password: `echo $POSTGRES_PASSWORD`

Check the .env file is correctly generated (do not paste it here) with the good DATABASE_PASSWORD.
Run an `./update.sh` to see if there is any error.

**Comment by r4nd0m9uy** [comment]
both passwords are the same. Running update.sh doesn't give any error messages.  I do see a hostname with some numbers and letters, is this correct?

**Comment by guillaumevincent** [comment]
`docker-compose logs -f` can give us more information about why is not working when you try to create the super user.

**Comment by r4nd0m9uy** [comment]
https://snippeter.krizdelogi.be/public.php?id=182
There isn't much to see about the backend section.

**Comment by guillaumevincent** [comment]
@r4nd0m9uy database docker container is not running: `LOG:  database system is shut down`

`docker ps` can confirm this.

Maybe you have already a service listening on 5432 port on your host?

What is your OS?

**Comment by guillaumevincent** [comment]
fyi the production is running on the same OS

**Comment by guillaumevincent** [comment]
@r4nd0m9uy I close this issue
Feel free to reopen the issue with some extra info for more help

**Comment by skjorrface** [comment]
I'm having the same problem as well under archlinux trying to create superuser, with .env password matching $DATABASE_PASSWORD, the following docker-compose logs -f output when issueing the createsuperuser command:

`db_1        | FATAL:  password authentication failed for user "postgres"
 db_1        | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"`

docker ps output:

`
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                      NAMES                           
44d52891ba4a        lesspass/nginx:letsencrypt   "/entrypoint.sh ngin…"   About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   lesspass_nginx_1                
89b94a7b747a        lesspass/backend:latest      "/entrypoint.sh /usr…"   About an hour ago   Up About an hour    8000/tcp                                   lesspass_backend_1              
ceb0fe1674ca        postgres:9.5                 "docker-entrypoint.s…"   About an hour ago   Up About an hour    5432/tcp                                   lesspass_db_1                   
30d6b84f788b        lesspass/frontend:latest     "npm start"              About an hour ago   Up About an hour    8080/tcp                                   lesspass_frontend_1 
`
and weirdest thing:

"404: Not found" as the content of update.sh file!

I'm not receiving any particular error message during installation procedure! Thanks for any help!

**Comment by guillaumevincent** [comment]
@skjorrface what code are you using?

**Comment by skjorrface** [comment]
@guillaumevincent I just cloned the repo and executed ./install-lesspass.sh 

I also tried with latest release of just "web-extension" but same results. What may I be doing wrong?

**Comment by guillaumevincent** [comment]
Hello,
this is a work in progress: https://github.com/lesspass/lesspass#wip
Do no try to install it right now, it wont work
Sorry for this
