### ISSUE TITLE
Autocomplete on site field for multiple login return only one entry

### ISSUE THREAD

**Issue by jeromecst** [lesspass/lesspass#333]
For example I have many accounts on twitter, all with differents login and password on lesspass.
Is it possible to have to autocomplete box for login field so I can directly choose my different account from the same website

**Comment by guillaumevincent** [comment]
Hello @owazae,
it's a bug, if we have two accounts on the same site, the auto completion on the site field should return two entries:

 * twitter.com 1@example.org
 * twitter.com 2@example.org

Actually it only returns

 * twitter.com

I will fix this

**Comment by owazae** [comment]
Got it, I didn't know I was a bug.
Thank you

**Comment by guillaumevincent** [comment]
It's fixed on mobile
Will be fixed soon on web extension

**Comment by pbaity** [comment]
Has this bug re-appeared (or the design changed)? If the expected behavior when opening the lesspass web extension on a site with multiple logins is: 
>    twitter.com 1@example.org
>    twitter.com 2@example.org
It's not working for me anywhere I've tested (on Firefox 67 and Chrome 75, Windows 10 and Mac). The extension seems to pick one (whichever is at "the top of the list," I guess?) and always display it, so I have to replace the login manually.

(PS thanks for an awesome password manager)

**Comment by guillaumevincent** [comment]
It's not fixed on the web extension

**Comment by FaustXVI** [comment]
I would be happy to try to fix this.
Also, there is no way to distinguish between two accounts. What do you think of adding some info in the auto-complete (like the login or the index if the order guaranteed to be always the same) ?

**Comment by guillaumevincent** [comment]
@FaustXVI the distinction can be done with site + login no?

**Comment by FaustXVI** [comment]
Yep, totally! Sorry if that wasn't clear in my previous message.

Xavier Detant

**Comment by FaustXVI** [comment]
@guillaumevincent, I think I spotted the faulty line : https://github.com/lesspass/lesspass/blob/bf89ce2c7ab3a1d8158754e884c7428515273e0d/packages/lesspass-pure/src/components/InputSite.vue#L64
I am able to run the unit tests using `yarn test`, but can't run the e2e test :( When I run `yarn test:e2e` in the lesspass-pure package, I got : 
```
yarn run v1.17.0
$ node test/e2e/runner.js
frontend listening on port 8080
   Error: An error occurred while trying to start the Nightwatch Runner: Error reading external global file using "test/e2e/globals.js"
   Error: Cannot find module '/home/xadet/projects/lesspass/packages/lesspass-pure/test/e2e/test/e2e/globals.js'
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
       at Function.Module._load (internal/modules/cjs/loader.js:562:25)
       at Module.require (internal/modules/cjs/loader.js:690:17)
       at require (internal/modules/cjs/helpers.js:25:18)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
and I can't find a command that runs the e2e tests in the `.travis.yml` file.
Could you help me ?
Another option (wish I like) could be to unit test components using shallow mounts (https://vuejs.org/v2/cookbook/unit-testing-vue-components.html). It seems it's not the way testing is done so far. Am I right ? What do you think of that way of testing ?

Thanks

**Comment by guillaumevincent** [comment]
@FaustXVI can you create a pull request to fix this?
Feel free to add some tests that works for you
If e2e tests are failing, I need to fix this
Thank you
