### ISSUE TITLE
How to login into "connected" version on LessPass website?

### ISSUE THREAD

**Issue by MurzNN** [lesspass/lesspass#334]
At https://lesspass.com/ website there are described:

> Use LessPass Database for complex passwords
We all know sites with stupid password rules. For this kind of site, we created a "connected" version to memorize the options. Sign in, load or save complex password profiles on LessPass Database.

But I can't find at website this login form for sign in:
![](https://lesspass.com/dist/LessPassDatabase.png)

Where is this form located?

**Comment by guillaumevincent** [comment]
Hello @MurzNN,

the source code? or the form?

Source code is here: https://github.com/lesspass/pure/blob/master/src/views/Login.vue
To access this form, you should click on the login icon (top right in the black header) in the application.

![t](https://user-images.githubusercontent.com/943762/41460474-350fc32e-708d-11e8-916d-21d3704771e1.png)

**Comment by MurzNN** [comment]
Wow, thanks! This button have too bad visibility. Will be good to duplicate this via some menu item or text with "Login" and Register" words.

**Comment by guillaumevincent** [comment]
@MurzNN you are right, and we are working on a complete redesign here #249 

![proposal-panel-sign-in](https://user-images.githubusercontent.com/1212392/38038849-402a4834-32ac-11e8-9215-9e0c6871d72c.png)

Sign In will be more accessible and simpler to find
Thank you for the report

Feel free to add a comment in #249 for other early feedback
Thanks

**Comment by edouard-lopez** [comment]
Addon redesign conversation is #320
