### ISSUE TITLE
Same credentials give different passwords on different platforms

### ISSUE THREAD

**Issue by rphlypo** [lesspass/lesspass#335]
Used LessPass Android app and Firefox (61, Quantum) browser extension as well as web page lesspass.com to generate password with the exact same settings (tried version 1 and 2 on android app, not available on the other modalities). The final generated password is different on Android than it is on my Linux 64bit (Ubuntu 18.04), and this independently of which modality is used (web based, browser extension or app). Is that a bug, is it because different libraries are used for the encoding?

**Comment by guillaumevincent** [comment]
Hello @rphlypo,
this is strange. Do you use some non ASCII char in the login, site or master password?
Can you generate an example with different password on different platforms?

**Comment by edouard-lopez** [comment]
Can you try to generate using following credentials?
* site: `github.com`
* login: `lesspass`
* master password: `debug`

I get the same result via the web-extension, website and mobile app.

> itTg,UZezLdy&4K2

You should get it too.

:warning: On mobile some fields are capitalized.

**Comment by rphlypo** [comment]
This is doing fine, no longer able to reproduce the issue. Both your proposed site/crendentials and mine now give the same result on different platforms.
