### ISSUE TITLE
Run LessPass with BYOC?

### ISSUE THREAD

**Issue by thebetterjort** [lesspass/lesspass#337]
I want to pass LessPass my cert that I have from my organization and not use LetsEncrypt. Is this possible?

**Comment by guillaumevincent** [comment]
I don't know. You can try to create a folder `./letsencrypt/live/{{ domain }}` in the root directory and add the ssl certificate with name `fullchain.pem` and ssl certificate key with name `privkey.pem`.
Then restart the container.

Let me know if it works
