### ISSUE TITLE
Possibility to have a default setting for the domain / FQDN option

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#338]
Hello,
Sorry to come back with that I took some time to check how lesspass was going.

Related to https://github.com/lesspass/lesspass/issues/199

I see that now there is a suggestion box and that is a nice feature but I saw an little issue.
The suggestion box is only displayed when you type the site and not automatically.

What would be very nice too it's an option to ask which is the default value of the suggestion box.

Example:
Actually if I go to lesspass and edit the site textbox I see this.
```
github
github.com
```

It would be nice to have an option to select automaticaly a default value (example the second one).

Cheers.

**Comment by guillaumevincent** [comment]
A new feature will make this issue obsolete
I close

**Comment by kidburglar** [comment]
Hello @guillaumevincent 

Which feature will help for this issue ?
There is already an issue for the new feature ?

Cheers.

**Comment by guillaumevincent** [comment]
I'm working on the beta for the issue
It's will be available in early 2019

**Comment by kidburglar** [comment]
Hello @guillaumevincent 

There are updates about the new feature ?
Maybe I could try it and tested it ?

Cheers.

**Comment by guillaumevincent** [comment]
A blog post is coming and will explain the future of LessPass with the new feature

**Comment by kidburglar** [comment]
Hello @guillaumevincent 

Do you have an ETA about it ?
I don't want push you, but I must say that I'm really curious about this new mysterious feature.

Cheers.

**Comment by guillaumevincent** [comment]
Here we are https://blog.lesspass.com/lesspass-default-password-profiles-99e4d01dec5
