### ISSUE TITLE
Store encrypted metadata locally and allow autofill after entering master password

### ISSUE THREAD

**Issue by contactlp** [lesspass/lesspass#339]
I would like to propose new feature which stores encrypted metadata locally and allow auto fill after entering master password.

1. Store metadata locally encrypted/hashed.:  
1.a. Metadata will include: URL, login, length, counter,lower character ,upper character ,special character 
1.b. each field will be encrypted interdependently, except url and it will be hashed instead of encrypted. 
1.c. encryption password be the same as master password.

2. When user go to a site, (eg gmail.com) sign in page (where username/password field exists), lesspass will hash URL compare with stored metadata. if it founds the URL, lesspass will create popup and ask user to enter master password, if master password is right (hence encryption password), lesspass will lookup metadata based on hash one more time, and only decrypt metadata for that URL and  auto fill(auto generate) username and password. 

This will help user as they don't have to copy ad paste password and also more secure then manually copying and pasting since lesspass can make sure password is given to correct site(at least, where users have used that password before). Locally stroe metadata will be safe as it will be hashed/encrypted, and it will be decrypted one record at time.

**Comment by guillaumevincent** [comment]
Hello,
yes this is a good idea to help users with autoload feature based on the website you are visiting. 
There is already this feature with LessPass extension.
Password profiles (metadata) are not encrypted yet.

I will probably split this issue in two issues in the future. But I let it open for further discussion

**Comment by bag-man** [comment]
@guillaumevincent Any updates on this? Autofilling and encryption would definitely win over a lot more users. They are the things holding me back.

**Comment by guillaumevincent** [comment]
I close this one,
A new feature with autocomplete on password profiles will be implemented and will make this issue obsolete
