### ISSUE TITLE
Connected LessPass with file system

### ISSUE THREAD

**Issue by roguh** [lesspass/lesspass#340]
I noticed the deterministic password manager [Pain-free Passwords](https://pfp.works/) lets you upload site-specific password settings (like length, revocation counter, and character requirements) to Dropbox. In this way it is possible to use the extension from multiple devices without memorizing every setting. It makes password changes much easier too.

Is it possible for LessPass to upload/read its small amount of settings to/from a JSON file to Dropbox (perhaps encrypted)?

Thanks

**Comment by guillaumevincent** [comment]
This is an interesting idea. I will transform the backend mechanism to allow different type of storage (local storage, API HTTP, or FS)

**Comment by roguh** [comment]
Thank you! This would be very helpful. 

I also envision using such a feature for *printing* a list of password metadata so I could physically store the data somewhere safe.

**Comment by panther2** [comment]
Sounds great, indeed.

**Comment by edouard-lopez** [comment]
Worth mentioning we have:
* a FAQ about [What information are saved in LessPass Database?](https://github.com/lesspass/lesspass/wiki/FAQ#what-information-are-saved-in-lesspass-database)
* A [connected mode](https://github.com/lesspass/lesspass/wiki/Private-vs.-connected-mode)
* a manual way to retrieve your profiles is to use lesspass.com and inspect the page Network requests

**Comment by betsythefc** [comment]
I would recommend using git or something similar when storing in any filesystem like backend for version control. It would be cool, though I'm not sure of the usefulness.

**Comment by guillaumevincent** [comment]
Hello,
I close this one because it's similar to https://github.com/lesspass/lesspass/issues/396
File system is only relevant for the cli not for the backend.
