### ISSUE TITLE
[webextension] firefox: hotkey doesn't work when toolbar button removed

### ISSUE THREAD

**Issue by aeosynth** [lesspass/lesspass#343]
Hi, when I remove the lesspass toolbar button from Firefox, the ctrl+shift+l hotkey doesn't work; maybe it's a browser restriction, I don't know.

When I put it in the overflow menu, it shows with scroll bars:

![scrollbars](https://user-images.githubusercontent.com/75317/46270370-02a57280-c4fc-11e8-9c2c-44bf79678034.png)

using Solus Linux

**Comment by guillaumevincent** [comment]
I don't have the bug on Firefox 56
Can you try again?
It's a Firefox issue no? Do you have the bug with another extension?
