### ISSUE TITLE
Wrong URL on blog

### ISSUE THREAD

**Issue by fauust** [lesspass/lesspass#344]
Hi,
sorry if this is not the right place to report this but URL is not OK on:
https://blog.lesspass.com/lesspass-comment-%C3%A7a-marche-9f1201fffda5

https://github.com/lesspass/core -> 404 

Regards,
Faustin

**Comment by guillaumevincent** [comment]
Fixed
Thank you @fauust

**Comment by fauust** [comment]
de rien :-)
