### ISSUE TITLE
Add LessPass android app to F-Droid

### ISSUE THREAD

**Issue by betsythefc** [lesspass/lesspass#345]
**related:** #252 #177

---

F-Droid is an open source app store for Android.

From F-Droid's website: https://f-droid.org/en/contribute/

## Submit Applications

If you see an application missing from the repository (after reading the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy)), please feel free to submit it via the dedicated [Requests For Packaging](https://gitlab.com/fdroid/rfp/issues) issue tracker.

If you have the technical skills required, you can also put together the relevant metadata and [submit that via the F-Droid Data repository](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md), which will drastically speed up the inclusion of the application.

The same applies for helping to build newer versions of applications.

Further information can be found in [the documentation](https://f-droid.org/en/docs), or by asking [on IRC](https://webchat.freenode.net/?channels=%23fdroid) (#fdroid on freenode).

**Comment by betsythefc** [comment]
That works for me! Can't wait to see the new app.

**Comment by guillaumevincent** [comment]
The version is live, can you guide me on how to push LessPass on FDroid?

**Comment by Rudloff** [comment]
I can take care of writing the F-Droid build recipe.
However, I see the code is now [included in the main repository](https://github.com/lesspass/lesspass/tree/master/packages/mobile). F-Droid usually looks for Git tags to see if a new stable version was released but I suppose this will not be possible here.

**Comment by guillaumevincent** [comment]
@Rudloff we can add some tag like `mobile-v3.0.2`
is it enough?

thank you for taking care of this

**Comment by Rudloff** [comment]
It would be very helpful, yes.

**Comment by guillaumevincent** [comment]
done https://github.com/lesspass/lesspass/releases/tag/mobile-v3.0.2

**Comment by edouard-lopez** [comment]
It has been [merged on F-droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/4086) waiting to be published, thanks @Rudloff :heart:

**Comment by guillaumevincent** [comment]
thank you @Rudloff 
 * just for your information package/cli has been removed

We can probably save the file metadata/com.lesspass.android.yml in the source code no?

**Comment by Rudloff** [comment]
> just for your information packages/cli has been removed

Don't worry, I just removed this folder from the F-Droid build because it contains some binary files and it triggered a warning (and it is not used for building the Android app anyway).

> We can probably save the file metadata/com.lesspass.android.yml in the source code no?

Build recipes always need to be stored in the fdroiddata repository, they are never fetched from upstream.
However, you can host additionnal metada (screenshots, changelog, etc.) in your repository if you want: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository

**Comment by licaon-kter** [comment]
This can be closed

**Comment by edouard-lopez** [comment]
@licaon-kter the app isn't available yet.

See https://search.f-droid.org/?q=lesspass

**Comment by Rudloff** [comment]
It is available in the F-Droid client.
I guess the website has not been updated yet.

**Comment by licaon-kter** [comment]
@edouard-lopez why aren't you using the client? You're missing out app updates...

**Comment by guillaumevincent** [comment]
Thank you all of you
thank you @Rudloff for your patience and reactivity
:heart:
