### ISSUE TITLE
Storing custom passwords

### ISSUE THREAD

**Issue by virtuallyvlad** [lesspass/lesspass#347]
Sometimes a service or application will simply provide a password for you to use, without allowing you to generate your own.

Other times a custom password may not be changed, for example if a service or application no longer exists or prevents the change for some other reason.

Is there a way to handle either of these cases assuming you want or need to store these passwords?

**Comment by edouard-lopez** [comment]
Hello @virtuallyvlad,
This is behing Lesspass scope. Indeed Lesspass is stateless, _i.e._ we don't store password. 

For more information, refer to the [FAQ: How does this compare with KeePass?](https://github.com/lesspass/lesspass/wiki/FAQ#how-does-this-compare-with-keepass) or the [blog post](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4).
