### ISSUE TITLE
installation requirement

### ISSUE THREAD

**Issue by doc-jay** [lesspass/lesspass#35]
Is there a way to self host this without docker?

thanks

**Comment by guillaumevincent** [comment]
@doc-jay there is no documentation to install LessPass without docker. But for every part of the application there is a Dockerfile describing the installation. For example if you look at the [backend Dockerfile](https://github.com/lesspass/backend/blob/b4f557ddd5b502d7f7370e327ed3efe1b520ffbf/Dockerfile) you can see the different task Docker run to build the container. 

Docker configure for you nginx for the `https` for your domain, the postgresql database to save passwords' profiles and the API with Django Rest Framework.

**Comment by edouard-lopez** [comment]
@doc-jay you can read the different `Dockerfile` to see what are the requirements and steps to install each part but then you will pollute your environment. That's one reason why using Docker is better, everything related to the serices is inside a containers you can easily build/start/stop/destroy.

The oneliner installer assume you have **[`docker-engine`](https://docs.docker.com/engine/installation/) and [`docker-compose`](https://docs.docker.com/compose/install/) installed**.

**Comment by guillaumevincent** [comment]
@doc-jay I close. 
Feel free to post on this thread to ask for extra help.
