### ISSUE TITLE
Multiple passwords within a site

### ISSUE THREAD

**Issue by kishaningithub** [lesspass/lesspass#350]
In India, we have banks which have 3 passwords within the same site

1.  Internet banking password
2. Profile password
3. Transaction password

So i wish to be able to use multiple passwords inside the same website. I am very much open to discussions around this and i really ❤️ the idea behind lesspass.

**Comment by panther2** [comment]
In case the website does not have different URL for different tasks, you can simply modify your "Login" information for LessPass, such as

1. Kishan Banking
2. Kishan Profile
3. Kishan Transaction

Actually you can enter whatever you want there. Different content creates different passwords.
In case you want don't want to use different "Login-information", just use different counters for different tasks.

**Comment by guillaumevincent** [comment]
If you are on the same site, you use 3 different logins no?
@panther2 is right use different login
