### ISSUE TITLE
docker install script don't work

### ISSUE THREAD

**Issue by Enderdead** [lesspass/lesspass#351]
In your docker install script, you use this url : **https://raw.githubusercontent.com/lesspass/lesspass/master/docker-compose.prod.yml**

But this link is broken (error404). Can you update it ?

**Comment by Enderdead** [comment]
I did a Pull request.

**Comment by guillaumevincent** [comment]
Hello,
I'm working on a new version right now
The breaking change is normal
See https://github.com/lesspass/lesspass/issues/349

**Comment by guillaumevincent** [comment]
I will merge the PR, I close
