### ISSUE TITLE
Firefox extension issues

### ISSUE THREAD

**Issue by durksi** [lesspass/lesspass#353]
Hi,
I am currently finding that the firefox extension will not accept my password or my email. App works fine. First the desktop version was working  but the mobile Firefox extension was not accepting my information and telling me it doesn't recognise the username and email. Now the desktop extention is not working either.
please help.

**Comment by guillaumevincent** [comment]
Hello @durksi,
the firefox extension on Firefox or on Firefox mobile works.
Be sure your email and password are correct and check (on mobile) that the first letter for your email is not capitalized.
This is a bug somebody raise by email, and I will address this in the next version

**Comment by edouard-lopez** [comment]
@durksi Please check the version you are using on mobile (as of 2018-dec-05 it's `2.0.7`) and `3.1.2` on Firefox desktop.

If you encrypt your master passowrd before sign-in you should do it again:

![lesspassdatabase](https://user-images.githubusercontent.com/1212392/49547557-4b561f00-f8e3-11e8-9fe0-e58c59d71e57.png)

**Comment by durksi** [comment]
Yes, you're right. Thanks for engaging with my concern and love the app.
