### ISSUE TITLE
Login to cloud database in Android app v3.0.2 does not support encrypted password

### ISSUE THREAD

**Issue by danielrozenberg** [lesspass/lesspass#356]
This feature is missing from the new Android app:
![image](https://user-images.githubusercontent.com/1839738/49900790-91543b00-fe2d-11e8-995e-4145601ad6d3.png)

**Comment by guillaumevincent** [comment]
The feature is by default on the sign in form
The option is available in the settings

**Comment by danielrozenberg** [comment]
Oops, that wasn't clear to me from the sign-in form due to the different UX between the browser extension and the Android app. Might be worth clarifying that this is happening in the login form, but not that important. Thanks!

**Comment by guillaumevincent** [comment]
Yes definitively, I need to update the web extension and the wiki.
Sorry for this.

I tried to describe it in the help page, and the error message if your sign in fails.

**Comment by danielrozenberg** [comment]
Admittedly I didn't even try to sign in, because the emojis looked like my unencrypted password and I just assumed it wouldn't work 😇
