### ISSUE TITLE
[mobile] Can't find lesspass-fingerprint

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#357]
Hello,

When trying to build the new mobile app (6133a19109a36905d0982ab1d2b9894c783f83ec), I get the following Yarn error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/lesspass-fingerprint: Not found".
```
It seems that `lesspass-fingerprint` indeed does not exist as a published NPM package.

Am I missing something?

**Comment by guillaumevincent** [comment]
yes until I cleaned everything you need to bootstrap the mono repo

    yarn install && yarn run bootstrap

**Comment by Rudloff** [comment]
It works, thanks!
