### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ghost** [lesspass/lesspass#358]
My issue is a simple feature request. I'm loving the new React native Android app, but I think it would be really swell if there was an option in the settings for a darker background and UI elements with white text. Also, for devices with OLED displays, the background and as many UI elements as possible should be pure black (#000000) so that those sections of the display are turned off to conserve battery life. I've seen this implemented as a third theme option or an automatic detection when the dark theme is selected on an OLED device.

**Comment by guillaumevincent** [comment]
This is implemented in the latest version. Closing
