### ISSUE TITLE
Game to change its master password

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#36]
@edouard-lopez Imagine if we can offer a game to change its master password.
I want to change my master password :

1/ backup your internet history : bookmarks-2016-10-31.json
2/ load your internet history in the game
3/ change password one by one on your sites (I can see my progression) 

It can be a complete different software

**Comment by edouard-lopez** [comment]
There is different scenario for the user to update its password:

1. using LessPass in it's _amnesic_ form (default) ;
2. using it as a connected user ;
1. mix of both.

The first scenario require explicit action from the user to provide a list of sites to update. On the second scenario we can divide password's profiles in 2 categories and suggest update by various mechanism (notification when service is used, goal to reach, etc.)

**Comment by guillaumevincent** [comment]
After a little survey people don't migrate a lot of password to LessPass. And actual users use version 2.
For now I pause this issue.
See if it still relevant when we will do #60

**Comment by guillaumevincent** [comment]
I close this one, sort of #60 duplicate

**Comment by ChristopherKing42** [comment]
What if lesspass just changed the passwords automatically? (Since it knows all of your old passwords, it should be able to do this.)
