### ISSUE TITLE
Fingerprint doesn't toggle password visibility 

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#360]
On the mobile beta `3.0.2` when I type a master password the fingerprint help me detect any typo I might have done. However, on old version and other platforms touching the visual fingerprint toggle the password visibility.
This is not the case in this version , so every time I make a typo I have to erase everything and start again

**Comment by guillaumevincent** [comment]
This is expected for security reason. If you can save the master password locally, you should not have some way to get it from a user.

**Comment by edouard-lopez** [comment]
This make sense when you store your master password, but it does happen even if it's not stored.

**Comment by guillaumevincent** [comment]
So we will introduce different behavior depending on an option. But the relationship between the option and the fingerprint behavior is not easy to understand.
I will try to do some experiments

**Comment by edouard-lopez** [comment]
I agree changing the behaviour based on a configuration hidden in the Settings tab will make things hard to understand.

Right now behaviour are inconsistent between webExtension/site vs. mobile app. The former allow access to master password for a limited amount of time since we have a timeout mechanism, the latter doesn't have the same timeout mechanism to clear the master password.

If we restore this mechanism we can keep a consistent behaviour on the fingerprint component and still maintain good security. What do you think?

**Comment by guillaumevincent** [comment]
For me we should always hide the master password.
Because for simplicity and consistent behavior with and without the fingerprint feature.

Consistency between app will be soon the same, as soon as the react version will replace the web extension

**Comment by guillaumevincent** [comment]
I close for now, I don't like the inconsistent behavior depending on an option
