### ISSUE TITLE
Field to store master password locally should behave like on main form

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#361]
On mobile beta `3.0.2`, when I want to store my master password locally, I'm presented with a simple form field. I can toggle the field visibility and there is no fingerprint to help me verify is what I type is correct or not.

Expectations are the same as the field in the main form.
![img_20181215_081218](https://user-images.githubusercontent.com/1212392/50040307-27ac7a80-0041-11e9-839b-818364f7f470.jpg)

**Comment by guillaumevincent** [comment]
👍 
PS the version is on production
