### ISSUE TITLE
Make lesspass.com a PWA

### ISSUE THREAD

**Issue by 71** [lesspass/lesspass#369]
Making https://lesspass.com a PWA would allow anyone to generate passwords without installing an application, even offline. Since there already is a `manifest.json` file, I think the only step left is adding a service worker to cache scripts / images / pages.

**Comment by edouard-lopez** [comment]
@71 You can already do it [with the website](http://lesspass.com/)

**Comment by guillaumevincent** [comment]
Hello,
yes the manifest is not present.
I will see when I will work on the site to add the manifest. 
However keep in mind that you should use the web extension instead of the site to generate your password.

**Comment by edouard-lopez** [comment]
@guillaumevincent on the website we do have a [_manifest.json_](https://lesspass.com/dist/manifest.json). It look like it's being [created by a `gulp` task](https://github.com/lesspass/lesspass/blob/4280872d3cc1e9371b4b6f216380f267a268665a/containers/website/gulpfile.js):

```json
{
  "name": "LessPass",
  "short_name": "LessPass",
  "description": "Next-Gen Open Source Password Manager",
  "dir": "auto",
  "lang": "en-US",
  "display": "standalone",
  "orientation": "portrait",
  "start_url": "/?homescreen=1",
  "background_color": "#555555",
  "icons": [
    {
      "src": "dist/android-chrome-36x36.png",
      "sizes": "36x36",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-48x48.png",
      "sizes": "48x48",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-256x256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "dist/android-chrome-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

For the offline part that something different, we could go with [GoogleChrome/workbox](https://github.com/GoogleChrome/workbox).

**Comment by tripurari001** [comment]
Hi

I would like to work on this 
is anyone already working on this one ??

**Comment by guillaumevincent** [comment]
Hello @tripurari001 
I plan to transform the web site and use gatsby. Maybe it will be fixed when making the new site?
I haven't started the migration yet. But you can work on this if you want

**Comment by guillaumevincent** [comment]
I close this one, because I have no plan doing it right now.
Feel free to create a PR if this is important to you
