### ISSUE TITLE
Other password rules?

### ISSUE THREAD

**Issue by edent** [lesspass/lesspass#37]
Thinking about switching, but I have a few questions about *annoying* password rules.

* No recurring characters. I work with a system that won't allow two or more consecutive characters. So `abc%%123` won't be accepted.
* No sequential characters. Similarly, I have a system which will reject `23`, `xyz`, and so on.
* Password can't contain the username.
* Passwords *must* start with a letter

I appreciate that some of these passwords are *unlikely* to be generated by LessPass - but is there any way to **ensure** that they won't be? Or do I have to rely on incrementing the password?

**Comment by edouard-lopez** [comment]
Hi @edent, thanks for the use cases.

You can toggle the different options (lowercase, uppercase, counter etc.) depending on your requirements but custom rules are not implemented yet. 

You can use the [connected version to remember your complex password rules](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4#ffbc).

**Comment by guillaumevincent** [comment]
* [ ] No recurring characters. I work with a system that won't allow two or more consecutive characters. So `abc%%123` won't be accepted.
* [ ] No sequential characters. Similarly, I have a system which will reject `23`, `xyz`, and so on.
* [x] Password can't contain the username.
* [x] Passwords *must* start with a letter

The last two are already done. The first two will be possible when user can customize patterns

**Comment by guillaumevincent** [comment]
@edent specific password rules reduce entropy, so security of the master password.
We should encourage site to allow complex password. 
I close this one because of the V2 algorithm. For now we will start with a simple secure implementation.

See discussion https://github.com/lesspass/lesspass/issues/89
