### ISSUE TITLE
[Feature Request] Built-in text editor for notes

### ISSUE THREAD

**Issue by esmoak** [lesspass/lesspass#370]
It would be great to have a way to take notes within the app to list authentication reminders.

Example: I want to remember that site "blahblahdotcom" is using counter 2 in the app, I could notate it in the built in editor. Or if I want to note that I enter "blahblah" without "dot com" when generating a password.

This would be a use at your own risk function, but could greatly improve the usability of the app so one doesn't have to keep notes in a separate text editor, or rely on memory.

Possibly related to #340

Edit: I envision a separate icon near settings and help icons on bottom.

**Comment by edouard-lopez** [comment]
@esmoak thanks for the interest in contributing.

What you describe, special ruleset, sounds like a use case for the [connected mode](https://github.com/lesspass/lesspass/wiki/Private-vs.-connected-mode). We have a wiki page detailing [what is store](https://github.com/lesspass/lesspass/wiki/FAQ#what-information-are-saved-in-lesspass-database) on the connected mode

**Comment by guillaumevincent** [comment]
Hello,
yes this is what the connected mode is for.
See the wiki for more information, or ask your question here, we will be happy to answer it
thanks

**Comment by esmoak** [comment]
Thanks to both of you for your work and input.
