### ISSUE TITLE
Building for ARM(rpi) & Docker fails

### ISSUE THREAD

**Issue by eratio08** [lesspass/lesspass#371]
Hello,

I wanted to run lesspass with docker on my rpi but sadly the building fails at Step 5
```Shell
$ docker-compose up
Creating network "containers_default" with the default driver
Creating volume "containers_www" with default driver
Creating volume "containers_postgresql" with default driver
Creating volume "containers_profiles" with default driver
Building webserver
Step 1/11 : FROM centos:7
7: Pulling from library/centos
848bc3b64aca: Pull complete
Digest: sha256:184e5f35598e333bfa7de10d8fb1cebb5ee4df5bc0f970bf2b1e7c7345136426
Status: Downloaded newer image for centos:7
 ---> 696a2a326214
Step 2/11 : LABEL name="LessPass Web Server"
 ---> Running in 98590ebd349a
Removing intermediate container 98590ebd349a
 ---> ba5ccac38e02
Step 3/11 : LABEL maintainer="LessPass <contact@lesspass.com>"
 ---> Running in e95b09055b2a
Removing intermediate container e95b09055b2a
 ---> a37ceecec8dc
Step 4/11 : ENV LANG en_US.UTF-8
 ---> Running in 8375716a3618
Removing intermediate container 8375716a3618
 ---> e5cd7c6afd84
Step 5/11 : RUN yum -y install epel-release &&     yum -y install httpd openssl mod_ssl proxy_http python34 python34-pip &&     yum clean all
 ---> Running in 242a900d8150
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror1.hs-esslingen.de
 * centos-kernel: mirror1.hs-esslingen.de
 * extras: mirror1.hs-esslingen.de
 * updates: mirror1.hs-esslingen.de
No package epel-release available.
Error: Nothing to do
ERROR: Service 'webserver' failed to build: The command '/bin/sh -c yum -y install epel-release &&     yum -y install httpd openssl mod_ssl proxy_http python34 python34-pip &&     yum clean all' returned a non-zero code: 1
```
The images wont run that easy like said in #215
> We can close this now, it should work on raspberry pi too 

Seems like the package `epel-release` could not be found. Some googleing showed that the repo of that package must be explicitly added for ARMv7 like showed here [https://stackoverflow.com/questions/35925066/epel-repository-for-arm7](https://stackoverflow.com/questions/35925066/epel-repository-for-arm7) because the is no offical repo for armhf.

I have no centos knowledge so maybe some one can fix this. 
Thanks :)

**Comment by edouard-lopez** [comment]
Thanks for the feedback and the time you took to find a solution. 

However, building a security software on unsigned, _i.e._ possibly altered, packages don't sound like a good idea.

cc @guillaumevincent

**Comment by guillaumevincent** [comment]
No this is a bug, let me check with my teammates at Red Hat. I think the solution is to drop epel.

I need to find the appropriate repository with python3. I will reach some devs from the Openshift team.

Thanks for reporting this

**Comment by guillaumevincent** [comment]
@eratio08 I will test this when I will get back a rpi

Can you test https://hub.docker.com/r/centos/python-35-centos7/ and see if you can run python-35-centos7 container?

**Comment by earlcray** [comment]
any updates with this issue?

**Comment by guillaumevincent** [comment]
For now there is no centos7 ARM image on dockerhub, so maybe we need to choose another base image for LessPass containers
