### ISSUE TITLE
Make Firefox add-on properly responsive

### ISSUE THREAD

**Issue by salim-b** [lesspass/lesspass#373]
On Firefox for Android, the browser extension is not properly fit to the screen size (horizontal scroll bars):

![screenshot_20190112-225700](https://user-images.githubusercontent.com/20040931/51078997-3ecd9f00-16b7-11e9-89d5-16f5d13798f1.png)
![screenshot_20190112-225654](https://user-images.githubusercontent.com/20040931/51079004-442ae980-16b7-11e9-99f4-39608bf4e8d7.png)

I'm on Android 7.1.2 (LineageOS), 1080x1920 screen.

**Comment by edouard-lopez** [comment]
We have a native android app available [on F-droid](https://f-droid.org/app/com.lesspass.android) and the [Play store](https://play.google.com/store/apps/details?id=com.lesspass.android).
You will have a better experience using it.

**Comment by salim-b** [comment]
> We have a native android app available [on F-droid](https://f-droid.org/app/com.lesspass.android) and the [Play store](https://play.google.com/store/apps/details?id=com.lesspass.android).
> You will have a better experience using it.

I know, thanks. But I think the browser add-on is more convenient since one
1. doesn't have to switch apps while browsing,
2. the domain is auto-filled.

**Comment by edouard-lopez** [comment]
Thanks @salim-b, last time I check Firefox mobile integration was a looong time ago (`v1`) and autocomplete wasn't working.

**Comment by tripurari001** [comment]
I think the scrollbar is because 

`    body {
      width: 420px;
      height: 460px;
    }`

present in popup.html 

to fix this we can add another property 
`max-width: 100%`

**Comment by tripurari001** [comment]
but I am not sure how to setup the repository and test it ( can't find any docs related to that )

**Comment by edouard-lopez** [comment]
Have a look at _.travis.yml_ to see [how to run the tests](https://github.com/lesspass/lesspass/blob/master/.travis.yml#L45-L59).

We will be happy to review your PR :+1:

**Comment by guillaumevincent** [comment]
Hello,
this will be fixed in the future, I close this one because it's already fixed in the WIP [here](https://github.com/lesspass/lesspass/blob/master/packages/lesspass-web-component/src/LessPass.js#L39)
