### ISSUE TITLE
Android app generates different passwords than website

### ISSUE THREAD

**Issue by 3bagr** [lesspass/lesspass#374]
I like the idea here but the android app generates different emoji and passwords than the firefox plugin and website.

**Comment by edouard-lopez** [comment]
@guillaumevincent I replicate with:
* webextension: `3.1.2` (site as same fingerprint)
* Android `3.1.0`

**Comment by edouard-lopez** [comment]
@3bagr upgrading to `3.1.1` on android solve the issue, it's available PlayStore (seems  F-droid take some time to build new version).

**Comment by guillaumevincent** [comment]
Yeah, I will add some tests to avoid that in the future

**Comment by 3bagr** [comment]
I downloaded 3.1.1 and the problem persists. I am using spaces in my master password.

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Jan 14, 2019, 2:47 AM by notifications@github.com:

**Comment by guillaumevincent** [comment]
@3bagr space in master password works properly
can you give us an example with **faked data**?
You can send an email at contact(at)lesspass.com if you don't want to send it here
