### ISSUE TITLE
Unified Naming rules

### ISSUE THREAD

**Issue by djerrystyle** [lesspass/lesspass#375]
In "Site" column:
`<auth method>/(<service>)/<target>/<(c-company,h-home)>/<encrypt salt>`

**eg:
ssh/1.1.1.1/c/this is linux
rdp/1.1.1.1:3389/c/this is my windows
sso/google/h/none
sso/cloud/google/h/none
sso/driver/google/none
web/youtube/h/use in home
ldap/company_A/c/none**

ALL IN ONE:(create password policy)

web/jumpserver/c/nice_|username123|password123|a-z/A-Z/0-9/%!@|20/10
-> mapping function("Lesspass")-> strong password string

web/jumpserver/c/nice_         -> information we know
username123|password123    -> easy to remember
a-z/A-Z/0-9/%!@|20/10          -> default policy

**Comment by guillaumevincent** [comment]
Hello,
I don't understand what your are trying to report;

Can you give us more context?

Look like you want a cli in the web component?

**Comment by edouard-lopez** [comment]
@djerrystyle 

Once you have generated a password, you can share the profile/settings used to create it. You will get a link with all the settings preset like
> https://lesspass.com/#/?passwordProfileEncoded=eyJsb2dpbiI6IjEyMyIsInNpdGUiOiIxMjMiLCJ1cHBlcmNhc2UiOnRydWUsImxvd2VyY2FzZSI6dHJ1ZSwibnVtYmVycyI6dHJ1ZSwic3ltYm9scyI6dHJ1ZSwibGVuZ3RoIjoxNiwiY291bnRlciI6MSwidmVyc2lvbiI6Mn0%3D

![share your password with lesspass](https://user-images.githubusercontent.com/1212392/51209994-e514e100-1911-11e9-8f54-6115948468ee.png)

**Comment by guillaumevincent** [comment]
No input from OP
I close
