### ISSUE TITLE
Provide a truly offline independent app

### ISSUE THREAD

**Issue by zorbakus** [lesspass/lesspass#381]
Currently you can only install a CLI, install an Android app, install a Firefox addon... but these are all dependent on their presence in the cloud and once installed, are tied to one specific device. I would like to have a truly standalone version of LessPass that I can copy to external drive and launch in whatever environment because I would feel more secure that way .What if website gets taken down, addon removed from Mozilla store, app removed from Google Play or F-Droid, and CLI removed from repository? Probably unlikely but possible, if for example the developer goes bankrupt - sorry no offense here, just genuine concern about being able to access my passwords.

**Comment by zorbakus** [comment]
Oh, I didn't realize you can download .apk itself from F-Droid. Also thank you for your other inputs.
#Closed

**Comment by guillaumevincent** [comment]
Save it with Firefox,
Yes the icon are not working because your browser expect font to be statically rendered
So you need a web server
