### ISSUE TITLE
cannot reset password

### ISSUE THREAD

**Issue by earlcray** [lesspass/lesspass#383]
https://github.com/lesspass/lesspass/issues/318

Am receiving the same issue as above, I am a protonmail user also.

**Comment by guillaumevincent** [comment]
@earlcray I will look in detail at this issue soon. I don't know why protonmail don't like emails coming from [AWS SES](https://aws.amazon.com/ses/)

I need to check if DMARC is correctly configured

**Comment by betsythefc** [comment]
Hey, I also have protonmail and haven't been able to change my password as well. Just a heads up that it affects other protonmail users too.

**Comment by guillaumevincent** [comment]
@soleera yes this is definitively an issue with LessPass configuration.
I checked the SPF and DKIM configuration.

I'm using the default FROM email from AWS. I will need to configure it correctly using contact@lesspass.com as default FROM email

**Comment by guillaumevincent** [comment]
It should be fixed now, the came from the mail from `'LessPass <contact@lesspass.com>'` doesn't work because of the simple quote. Remove the simple quotes and LessPass can send some emails now.
