### ISSUE TITLE
Master password is auto-capitalized

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#384]
Hello,

When entering my master password on the Android app (version 3.1.1), the keyboard wants to start with a capital letter, which is annoying.

I think `autoCapitalize="none"` is missing here: https://github.com/lesspass/lesspass/blob/e526584d690e92beef8eb59006b5b33031f21533/packages/mobile/src/password/MasterPassword.js#L54

**Comment by edouard-lopez** [comment]
Hi @Rudloff 
Are you sure of the version, I can't reproduce on `3.1.1` on Android `8.1.0`.

* Can you check version from in-app `settings` **and** Android app information ?
* Did the behaviour change after an update or something?

**Comment by Rudloff** [comment]
I confirm I am using 3.1.1 (from F-Droid) on Android 7.1.2.
I always had this behavior since I started using the React Native app (with 3.0.2 I think).

**Comment by edouard-lopez** [comment]
@Rudloff my bad, you are correct, I **reproduce with Android native keyboard**, SwiftKey Beta Keyboard behave differently.

**Comment by guillaumevincent** [comment]
It should be testable in 15 min in LessPass 3.1.2 beta
