### ISSUE TITLE
Android application allows generating a password without filling the site and login fields

### ISSUE THREAD

**Issue by 0x2b3bfa0** [lesspass/lesspass#388]
The Android application allows generating a password without filling the site and login fields. I don't know if this behavior is a bug or a feature, but should be consistent across all the implementations.

**Comment by guillaumevincent** [comment]
It's a feature and only the web extension need to be fixed no?

**Comment by 0x2b3bfa0** [comment]
🐛 I don't know if it's a bug or a feature. What do you think?

**Comment by guillaumevincent** [comment]
We are going to be consistent everywhere and enforce at least the site field. Login field can be empty.

So it's a bug, I will fix that
