### ISSUE TITLE
[cli] adding password length cap to help output

### ISSUE THREAD

**Issue by Komish** [lesspass/lesspass#390]
Given #326 - It might be helpful to new users to add information as to the cap on password length as it was a bit confusing on my first use of the tool.

From:

```
  -L, --length         int (default 16)
```

To something like:

```
  -L, --length         int (default 16, max 35)
```

I'm not sure what kind of impact a change like this would have on the other lesspass use cases, but figured it would save some new users a few clicks.

In addition, would it be beneficial to print out a message to STDERR whenever a length greater than 35 is requested AND force only 35 to return? Currently I'm seeing `a` characters appended.

```shell
$ python --version
Python 3.7.2

$ lesspass --version
6.1.0

$ lesspass somewebsite someusername -L 100
!0Aach\Kn/)E}.owwJARpc)/05UA>ExCn9tweY*':z}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

$ lesspass somewebsite someusername -L 100 --lowercase
auexemqcmmycrzjbtjblvjoxyqexroibalsrtrvviandfboipkqrdfldaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Comment by edouard-lopez** [comment]
Thanks @Komish 

In the web extension UI, the `length` is already capped at `35` characters.

Feel free to [submit a PR](https://github.com/lesspass/lesspass/blob/60dfaa8ba3f3a12526b296200c8f2e5b2a7f9b9d/cli/lesspass/help.py#L34) we would be happy to review it.

**Comment by Komish** [comment]
@edouard-lopez understood, I'lll take a look as time allows!
