### ISSUE TITLE
[cli] Making use of ArgParse to handle Validator and Help Output

### ISSUE THREAD

**Issue by Komish** [lesspass/lesspass#392]
While working on #390 / #391 I noticed that the help output is produced statically [here](https://github.com/lesspass/lesspass/blob/master/cli/lesspass/help.py). The [validator](https://github.com/lesspass/lesspass/blob/master/cli/lesspass/validator.py) is (for the most part) also handling mutually exclusive options at the command line.

ArgParse should be able to handle both of these bits without needing the extra functions. It would take some adjustment to a few files outside of just [cli.py](https://github.com/lesspass/lesspass/blob/master/cli/lesspass/cli.py), but it should be pretty straightforward to implement.

Is there any interest in collapsing this down in this manner?

**Comment by Komish** [comment]
I've got some code staged that I think accomplishes this [here](https://github.com/Komish/lesspass/commit/53226800779bcbc8803b3e04f70657a242d49264). I'm holding the PR for now to make sure there is interest for this kind of change. 

If you prefer I just submit the PR (or PR draft) and submit a text changelog/summary to evaluate if this is something you'd want to do, let me know and I'll submit the PR. 

Thanks!

**Comment by guillaumevincent** [comment]
Thank you Komish for the work on the cli.
You can submit the PR.

With a quick look at the code I see some issue:

 * clipboard option is for retro compatibility but I want to hide this option from the help.
 * code multually exclusive group should be together. add arguments right after the group creation.
 * Use description from __initi__.py in cli.py

**Comment by Komish** [comment]
Will do, PR coming shortly.
