### ISSUE TITLE
[cli] site field allowed to be blank string when using --prompt

### ISSUE THREAD

**Issue by Komish** [lesspass/lesspass#393]
While playing around with what I would need to do to implement #392, I noticed that utilizing `--prompt` will allow for an empty string to make it to the profile. 

Version information for reference:

```shell
$ lesspass --version
6.1.0
```

Confirming SITE is otherwise a required argument:

```shell
$ lesspass
Usage: lesspass SITE [LOGIN] [MASTER_PASSWORD] [OPTIONS]
Errors:
 * SITE is a required argument (unless in interactive mode with --prompt)

Try 'lesspass --help' for more information.
```

Reproduction just requires leaving the `Site: ` prompt empty by hitting Enter.

I added some printlines debugging to test, so you'll see the Argument namespace as well as the profile (adding comments to the shell output for clarity):

```shell
$ lesspass --prompt
# these are the arguments provided as input (i.e. none, so we're getting default values)
Namespace(clipboard=False, counter=1, d=False, help=False, l=False, length=16, login=None, master_password=None, nd=False, nl=False, ns=False, nu=False, prompt=True, s=False, site=None, u=False, version=False)
Site:            # to reproduce, leave this blank - just hit Enter
Login:
# This is the stat eof the profile after that input, notice that site went from Nonetype to an empty string
{'lowercase': True, 'uppercase': True, 'digits': True, 'symbols': True, 'length': 16, 'counter': 1, 'site': '', 'login': 'testing'}
Master Password:
# This is the profile after the Master Password prompt - just before we intend using it, site is still an empty string
{'lowercase': True, 'uppercase': True, 'digits': True, 'symbols': True, 'length': 16, 'counter': 1, 'site': '', 'login': 'testing'}
PasswordRenderedHereRedacted
```

The code I have staged to resolve #392 should handle this bug as well - but as the discussion on whether that issue is worth pursuing is still taking place, I figured it best to report this bug separately in case the decision is made to keep leave the argument parsing as is.

Including a diff here for how I'm printing the debug output (not for a fix, or otherwise).

```diff
$ git diff
diff --git a/cli/lesspass/core.py b/cli/lesspass/core.py
index 68290a4..c418291 100644
--- a/cli/lesspass/core.py
+++ b/cli/lesspass/core.py
@@ -26,15 +26,18 @@ def main(args=sys.argv[1:]):
     if error:
         print_help(help_message)
         sys.exit(0)
+    print(args)  # debug
     profile, master_password = create_profile(args)

     if args.prompt:
         profile["site"] = getpass.getpass("Site: ")
         profile["login"] = getpass.getpass("Login: ")

+    print(profile) #debug
     if not master_password:
         master_password = getpass.getpass("Master Password: ")

+    print(profile) # debug
     generated_password = generate_password(profile, master_password)

     if args.clipboard:
```

Let me know if I can provide further information.

**Comment by guillaumevincent** [comment]
We should decide if empty site is a bug or a feature.
Because LessPass is better than the same password everywhere, you should enforce at least a non empty string in the site field.

Wdyt?
Makes sense?

**Comment by guillaumevincent** [comment]
See https://github.com/lesspass/lesspass/issues/388#issuecomment-465027271

**Comment by Komish** [comment]
I'm in agreement. I'm of the opinion that **none** of the fields should be left blank - but I believe I read an earlier bug that was reported indicating that the LOGIN field could be left blank and that was by design. At the very least, a site and a master password should be required.

That said, I'm noticing that `--prompt` also allows for an empty master password, I'm not sure if this is intended. Testing with printline debugging.

```shell
# testing with a master password being provided
$ lesspass --prompt
Site:
Login:
Master Password:
#  print("DEBUG master password: ", master_password, type(master_password))
DEBUG master password:  testing <class 'str'>
PasswordOutputRedacted

# testing by leaving the master password blank
$ lesspass --prompt
Site:
Login:
Master Password:        # just hit enter here to give the key an empty string
#  print("DEBUG master password: ", master_password, type(master_password))
DEBUG master password:   <class 'str'>
PasswordOutputRedacted
```

A diff to reproduce what you see here:

```diff
$ git diff
diff --git a/cli/lesspass/core.py b/cli/lesspass/core.py
index 68290a4..df07753 100644
--- a/cli/lesspass/core.py
+++ b/cli/lesspass/core.py
@@ -34,7 +34,7 @@ def main(args=sys.argv[1:]):

     if not master_password:
         master_password = getpass.getpass("Master Password: ")
-
+    print("DEBUG master password: ", master_password, type(master_password))
     generated_password = generate_password(profile, master_password)

     if args.clipboard:
```

I'll also address this in the PR associated with #392, requiring a master password.
