### ISSUE TITLE
Profiles and CLI

### ISSUE THREAD

**Issue by davidbgk** [lesspass/lesspass#396]
Hey there,

I plan to use it within my team of trusted coworkers. But we don't want to use a web interface for this so my plan would be to add a way to export profiles from CLI as JSON files, share them using a private git repository and be able to import it when asking for a password from another machine with the same rules.

If I understand correctly, it would add two options to the CLI like `-P, --profile` and `--from-profile`. The [create_profile](https://github.com/lesspass/lesspass/blob/4280872d3cc1e9371b4b6f216380f267a268665a/cli/lesspass/profile.py) might be useful on one hand and then [args](https://github.com/lesspass/lesspass/blob/7efcb83940cb07ba4cf3cb248acfa7f831791f70/cli/lesspass/core.py#L18) could be overridden by the optional profile.

I can propose a PR but I'm not sure that's the direction of the project. Let me know what you think about all that 🤗

**Comment by edouard-lopez** [comment]
@davidbgk , that sounds like a nice feature addition. 

However, did you explore the possibility of self-hosting the backend/db on your network? This will let you use web or mobile application without the need to manage syncing.

**Comment by davidbgk** [comment]
@edouard-lopez thanks for your answer! I'm always a bit reluctant to let that kind of information transiting across the network, maybe at some point we will host it somehow but I'll let the need grow first :)

**Comment by kidburglar** [comment]
Good idea, I only know "pass" for sharing password between a team.
It a mix of GPG and git, but it work as "storing information" so it not really work when we want use password generation based on website like "lesspass" or "passwordmaker".

Maybe it could be also a good idea to add the possibility to encrypt the information with GPG (or password) so that only some people can access it ?

**Comment by guillaumevincent** [comment]
@kidburglar we can start with a default big json file passed as parameter of the cli?
If you want to encrypt it, you can use the cli to decrypt it on the fly and use it automatically no?

**Comment by kidburglar** [comment]
@guillaumevincent 
It was more like "that could be a good idea". I never tried actually.

You mean something lilke that "decryp myfile | lesspass-cli --profile -" ?
It's true that it could be a good enough and so we can use any encryption method that we want.

**Comment by guillaumevincent** [comment]
yes exactly

**Comment by guillaumevincent** [comment]
Hello,
I'm closing this one, I will probably never have time to work on it.
Also it's not going in the right direction: "Remove LessPass Database".
Thanks
