### ISSUE TITLE
Provide a <datalist> for the "Où allez-vous part"

### ISSUE THREAD

**Issue by DavidBruant** [lesspass/lesspass#4]
People can easily type "facebook" or "Facebook" which'd lead to a different password being generated. A <datalist> would provide some autocompletion help for most used websites.

**Comment by guillaumevincent** [comment]
nice feature, 
and text input on mobile always starts with an Uppercase letter. That will fix this issue as well

need to find an existing list for most used sites

**Comment by guillaumevincent** [comment]
I need to include the modification in lesspass pure

**Comment by guillaumevincent** [comment]
fixed in lesspass-pure 1.2.1 by https://github.com/lesspass/pure/commit/775c7d227b31df6fa0b0fe408c7ada13274cb68a
