### ISSUE TITLE
[Feature Request] Add tags to LessPass saved profiles

### ISSUE THREAD

**Issue by egara** [lesspass/lesspass#400]
Hi!

First of all, I'm impressed about LessPass. It is amazing a the concept is a great idea. Thank you very much for your time to develop such a nice tool.

I would like to propose a feature request. I have several gmail accounts and I have saved a profile for every one of them. It would be very useful to have the possibility to tag every profile, i.e. you can tag **Personal Gmail** for my gmail account 1 and **Work Gmail** for my gmail account 2. Doing so, I would be able to search for tags directly within my stored profiles which would have more sense to me. It would be very helpful in the browser extensions, but it would be even more helpful within the Android application for example.

Thank you very much and keep up the amazing job!!!

Best,

Eloy

**Comment by edouard-lopez** [comment]
Hello @egara,
You can use `Personal Gmail` or `Work Gmail` as your _login_ value instead of an email or username. I do this myself for _personal_ versus _family_ account. 

You're free to use whatever you want in the _login_ field, not necessarily and email, _e.g._ `work:foo@bar.org`, `foo@bar.org`, `me`, `Édouard Lopez`, etc.

**Comment by egara** [comment]
Hi @edouard-lopez and thank you for your response! :)

It is a kind of work around but still, I think it would be great to have a specific field for adding a tag. This field could be searchable (right now, I think the only searchable field in the Android application is site) and would help to find the specific entry easily if you have a lot of profiles stored.

Best,

Eloy

**Comment by guillaumevincent** [comment]
Hello @egara,
we need to keep in mind that I try to encourage every features that increase the stateless form of LessPass. Saving some tags is great and will improve the user experience.
I like the idea. Will see if we can include this in the roadmap.

**Comment by egara** [comment]
Hi @guillaumevincent 

Thank you very much :) 

And again, I think this project is amazing. I discovered it in the interview you had in The Ask Noah Show a few weeks ago.

Keep up the good work and thanks for the time all you are investing in the project.

Best,

Eloy

**Comment by guillaumevincent** [comment]
Hello,
I close in favor of #278. Keep in mind I don't know if I will do #278.
I would like to abandon the database and focus LessPass on his stateless strength.
