### ISSUE TITLE
Not able to input master password in desktop FF extension (Fedora)

### ISSUE THREAD

**Issue by heuzef** [lesspass/lesspass#401]
Hello guys :smiley_cat: 

I follow the #368 because i have the same.

But i use Firefox 63.0.3 (64 bits) on Fedora and my ibus package is up to date : ibus-1.5.17-6.fc27.x86_64

What can i do for fix this ?

Thanks for this amazing project & support ! :+1:

**Comment by guillaumevincent** [comment]
I don't have the issue on Fedora 29
Let me check

**Comment by heuzef** [comment]
Thanks :) (I'm on Fedora 27).

`
Linux x240 4.18.19-100.fc27.x86_64 #1 SMP Wed Nov 14 22:04:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by guillaumevincent** [comment]
My guess is that you are using X server instead of Wayland right?

**Comment by heuzef** [comment]
Hmmm ... right :wink: 

`
loginctl show-session 1 -p Type
Type=x11
`

**Comment by guillaumevincent** [comment]
I think the patch is fixed upstream. So I don't know why you got this error (maybe upgrade are not on Fedora 27). I'm on PTO right now. I can check with my teammates at the end of this week.
You can use the workaround in #368 or use Wayland.

**Comment by guillaumevincent** [comment]
I close.
The issue is in another upstream project.
The only workarounds I see are listed in #368 or here

I think there is no backport for older fedora release. So feel free to update to the latest release and see if ibus is version 1.5.19 (latest one)
