### ISSUE TITLE
Visual fingerprint in the CLI app

### ISSUE THREAD

**Issue by Bannerets** [lesspass/lesspass#402]
Visual fingerprint is a very useful feature to me. Currently CLI app doesn't show a fingerprint.

i'd be happy if the app would show emoji as you type, something like this:

```console
$ lesspass google.com
Master Password [😀👤👁]: **

$ lesspass google.com
Master Password [👾🙆‍♂️👣]: ***
```

Probably there should be a cli option to disable/enable fingerprint.

**Comment by guillaumevincent** [comment]
ahah it would be awesome, but not easy to do. 
We need to find a way to update cli on the fly and find a way to get font awesome icon in cli.

**Comment by edouard-lopez** [comment]
Love the challenge it poses 👍

Updating the CLI means rewriting it, that's doable with `printf` and `\b` (backspace) or `\r` (carriage return).

There is Web service to create your own font out there (e. g. Font moon or something like that), we can create one with just fontawesone set then ship it with the code. However I don't know if and how we can use this just for our output or is it global to our tty application. The latter will require user to change their applications font and that a major bummer as many already use another (e. g. Powerline)

**Comment by edouard-lopez** [comment]
This [can I change default fonts for a shell?](https://superuser.com/q/72950) indicates there is no font in shell outside the one from the terminal app they run in.

**Comment by ElieKadoche** [comment]
Instead of updating the visual fingerprint as we type, could it be simplest to just display the visual fingerprint at the end? If We are wrong we just need to do it again.

**Comment by Bannerets** [comment]
Updating the fingerprint as we type isn't a problem, one should just output `\r`. However with it usage of `getpass.getpass` shouldn't be possible, and because of this the fingerprint should be optional.

I didn't think about font-awesome. As far as I know, there is no portable way to render custom fonts.
One possible solution is to print ASCII-art of an emoji, but it is far from ideal.
