### ISSUE TITLE
Lesspass app : can't save password options

### ISSUE THREAD

**Issue by laurentriffard** [lesspass/lesspass#403]
Hi,
it seems that the lesspass app can't save the password options…

Test case : 

- install Lesspass app on your smartphone
- in the app, sign in into your Lesspass account 
- use the app to generate a password
  - fill "Site", "Login", "Master Password" fields
  - set some password options. For example : uncheck "Symbols" checkbox, set a specific length
  - touch the "Generate" button, then touch the "Save" button 

At this point, one can notice that the options are reset to their default option. 

- stop the app, and restart it
- try to use the Site defined above. You can notice that the specific option are not retained.

Moreover, if you try to replay the testcase, you can save many instance of the site options, none with the specific parameters.

Lesspass app version : 3.1.1 from F-Droid.

Note that the Lesspass extension for Firefox work as expected (correctly save the password option).

**Comment by edouard-lopez** [comment]
@laurentriffard thanks for the feedback 

@guillaume20100 I reproduce on `3.1.2`

**Comment by guillaumevincent** [comment]
It will be fixed on LessPass 3.1.4
ping @Rudloff how we can update the FDroid app to the latest version?
Thanks and sorry for this bug

**Comment by Rudloff** [comment]
Someone needs to add a new section to the metadata. For example: https://gitlab.com/fdroid/fdroiddata/merge_requests/4596

We also have an auto update system but it does not work when the version code/name is dynamic: https://github.com/lesspass/lesspass/blob/83ddc2e4ce0d5396171a194ff754147996463aeb/mobile/android/app/build.gradle#L106

**Comment by laurentriffard** [comment]
Hi,
Got Lesspass 3.1.3  from FDroid yesterday.
I’ll wait for version 3.1.4…
