### ISSUE TITLE
AMO LessPass Web Extension issue on Firefox

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#406]
Hello,
I have some trouble with the review process done by Mozilla. One reviewer try to understand the source code, ask irrelevant questions. Because I don't have any time at the moment (I'm finishing to build my new house) the addons was disabled from AMO.

I need to do some extra work to have the addon published again.
If you have some error in the password generation check that you use a web extension version 3.x.x. Or use Chrome

Really

**Comment by edouard-lopez** [comment]
You could also use the website: https://lesspass.com/

**Comment by guillaumevincent** [comment]
I submitted a version 3.1.5 with a new policy

Mozilla you need to understand that your review process is so bad!
