### ISSUE TITLE
Merge powershell implementation into main repository

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#407]
**related:** https://github.com/edouard-lopez/lesspass-powershell/issues/15

---

### Goal?

Merge `PowerShell` implementation into main repository.

### What?

* Source code: https://github.com/edouard-lopez/lesspass-powershell/
* Module: https://www.powershellgallery.com/packages/Lesspass/

### Why?

* make powershell implementation officially part of the project
* have a simple place to declare bugs

### How?
PR should:
* [ ] create a directory for powershell implement at root level as `./powershell/`
* [ ] perserve commits authorship (cc @sctfic)
* [ ] merge travis.yml so powershell tests are run by CI
* [ ] (optional) publish module with CI/CD (remember publish module `foo` from directory `foo/`)

### When?

As time allow :)

**Comment by guillaumevincent** [comment]
:+1:

**Comment by guillaumevincent** [comment]
I close this one, reopen when you will start the work
