### ISSUE TITLE
Generation on android vs chrome extension is different

### ISSUE THREAD

**Issue by ehanoc** [lesspass/lesspass#409]
With the same exact same inputs (site, login, master psswd + options, length, counter) the generated password is different.

Can someone re-test and verify? 

chrome extension : 3.1.2

android app ver : 3.1.5

**Comment by edouard-lopez** [comment]
Can't reproduce, Verify you don't have capital on first letter.

### Test
* site: `a`
* login: `b`
* master password: `c`

**Firefox `3.1.6`:**

    v3~>C"q'=|4wG,]/

**Chromium `3.1.2`:**

    v3~>C"q'=|4wG,]/

**Android `3.1.5`**

    v3~>C"q'=|4wG,]/

**Comment by guillaumevincent** [comment]
tested also with counter > 10 and everything is fine

**Comment by ehanoc** [comment]
@guillaumevincent i figured out what's wrong. 

When choosing the login and user on android. If you take the suggestion from the keyboard, it adds a whitespace at the end. 

Perhaps as an improvement would be good to trim the inputs? Better UIX? 

Thanks man

**Comment by edouard-lopez** [comment]
We should not temper with user input as it might be a choice to have a space. However, we can notify him if there is a space at the beginning/end.
