### ISSUE TITLE
[Firefox extension] Impossible d'utiliser la touche @

### ISSUE THREAD

**Issue by yereby** [lesspass/lesspass#41]
Sur Firefox ubuntu, on ne peut pas utiliser la touche '@' ce qui empêche de se connecter ou d'entrer un mail en login.
Sur Chrome pas de soucis

A l'appui de la touche 'altgr' pour taper un '@', l'extension disparaît.

**Comment by guillaumevincent** [comment]
@yereby je suis sur Firefox ubuntu 49.0.2 avec LessPass 1.1.0 et je n'ai pas de soucis
Quelle est la version de Firefox que tu utilises ?
Quelle est la version de l'extension que tu utilises ?

**Comment by yereby** [comment]
Je suis sur les mêmes versions que toi, wired.
Quant à ubuntu : la 16.04

**Comment by yereby** [comment]
Apparemment ça ne vient pas lesspass, j'ai le même comportement sur d'autres extensions.
Sorry @+
