### ISSUE TITLE
Variations of the Less Pass Algorithm that are Human Computable

### ISSUE THREAD

**Issue by MichaelWehar** [lesspass/lesspass#415]
Is there a variation of the Less Pass algorithm that is human computable.

For example, I don't ever want to type my master password into the computer.  I would like to do the computation in my head.

**Comment by edouard-lopez** [comment]
That's _possible_…

However, that's **not a realistic approach** as it will take you a huge amount of time to compute your password. Indeed, [the algorithm](https://www.wikiwand.com/en/PBKDF2) manipulate [massive number](https://github.com/lesspass/lesspass/blob/cf252b57101670c769c02c8818e89321daea20c2/cli/tests/test_password_generation.py#L141), conversion from/to hexadecimal and we repeat computation over 100,000 times.

You can look at [cli/tests/test_password_generation.py](https://github.com/lesspass/lesspass/blob/master/cli/tests/test_password_generation.py) and try to duplicate the result by hand.

**Comment by MichaelWehar** [comment]
Thank you very much for the thoughtful reply!

If I understood correctly, then I think that you made a really good point that I hadn't thought of before.  :)

Repeatedly applying a function (such as a hash function) one hundred thousand times to a password makes it more difficult for the brute force attacker to figure out the password because (at least naively) the brute force attacker would have to do 100,000 times as much work for each guess.

If we had some kind of human computable function, then the function would almost definitely be instantaneous for a computer to compute.  That means that the brute force attacker would have an advantage by being able to try many more guesses in less time.

Did I understand your point correctly?  :)
