### ISSUE TITLE
Web extension workflow

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#417]
Hello,
what do you thing about the following workflow for the web extension ?

1. right click in a password field in a page
2. click on LessPass in the context menu item
3. open a password field and ask for user master password
4. generate the password
5. close the popup
6. fill the password in the password field

workflow with shortcut 

1. ctrl + shift + L
2. open a pop up and ask for user master password
3. generate the password
4. Copy in clipboard
5. close the popup

**Comment by guillaumevincent** [comment]
ping @edouard-lopez

**Comment by panther2** [comment]
@guillaumevincent 
How would that influence the current implementation?
Would it be an add-on or a replacement?

Personally, for my use cases, I need the freedom to enter whatever I want in the current input boxes.

**Comment by edouard-lopez** [comment]
### Context Menu
I rarely use context menu as I do most of my manipulation with keyboard and such menu item are difficult to reach IMHO (right click, arrow up/down till you reach the right entry).

### :heart: Shortcut
Plugging the current shortcut to this new behaviour will greatly reduce those friction and ease transition to existing user.

### Simplified dialogue?
You speak only of master password, what about URL/Login/options? Will you pop-up the whole lesspass dialogue or a simplified one?
I often edit the login as I use Lesspass for different accounts (e.g. personal/professional)

### Injecting content
Does this workflow inject content into the page? As it's something we choose not to avoided as of today.

**Comment by guillaumevincent** [comment]
@panther2 the current implementation will not change and we will add a new feature in the context menu.

@edouard-lopez the simplified dialogue is something we need to reach. We are obliged today to click into the copy button and then click into the password field on the site, send click enter.
