### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by mariuccio90** [lesspass/lesspass#419]
Hi wonderful team,

in my environment port 80 and 443 are already in use by Nextcloud; 
I found that these 2 ports are in use in:

[lesspass/install-lesspass.sh](https://github.com/lesspass/lesspass/blob/master/install-lesspass.sh)
`docker run -it --rm -p 443:443 -p 80:80 -v $PWD/letsencrypt:/etc/letsencrypt/ certbot/certbot certonly --standalone --noninteractive --quiet --email $EMAIL --agree-tos -d $DOMAIN
docker run -it --rm -v $PWD/letsencrypt/live/:/certificates/ lesspass/openssl openssl dhparam -out /certificates/$DOMAIN/dhparam.pem 4096
`
and
[lesspass/containers/docker-compose.yml](https://github.com/lesspass/lesspass/blob/master/containers/docker-compose.yml)
`    ports:
      - 80:80
      - 443:443`

is it possible to use for example 8080 and 8443? how?

Thanks.

**Comment by guillaumevincent** [comment]
Hello,
IIRC certbot doesn't work on other ports.
Certbot is use to refresh ssl certificates.
I'm working right now on the new containers.
I will see if it's still the case

**Comment by mariuccio90** [comment]
Thanks for the answer!
in my opinion the best alternative would be to use a reverse proxy.
for nextcloud i am using [This](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion)

so we might need to add these two ENV into Lesspass configuration:
`-e VIRTUAL_HOST=your.domain.com \
              --network=webproxy \`

Do you think it's feasible?

**Comment by guillaumevincent** [comment]
@mariuccio90 looking at docker-compose-letsencrypt-nginx-proxy-companion

**Comment by mariuccio90** [comment]
Hey @guillaumevincent do you have any update on implementation?
Thanks a lot!

**Comment by guillaumevincent** [comment]
Still working on it https://github.com/lesspass/lesspass/commit/407668671c6bab4b385c5a0d455be1d07cc97051

**Comment by mariuccio90** [comment]
let me know if you need testing!

**Comment by guillaumevincent** [comment]
docker-compose-letsencrypt-nginx-proxy-companion is too complicated and only useful to refresh certificates without downtime. I plan to remove the certificate generation from LessPass. 
It's up to the admin system to manage his certificates and share them to the container.
I will define a way to change https port used by docker
