### ISSUE TITLE
Can't access selfhosted instance.

### ISSUE THREAD

**Issue by klundry** [lesspass/lesspass#42]
I have installed docker and docker-compose run the script and it appears to have completed successfully but I can't access it.  What is the address? I tried the ip address of the box I'm running it on. Is it running on a different port?

**Comment by guillaumevincent** [comment]
@klundry it should be running on the domain the script ask for

    cat .env | grep DOMAIN

if you are running a local domain, replace DOMAIN=localhost and open your browser at https://localhost/
