### ISSUE TITLE
webserver_1  | /app/entrypoint.sh: line 23: python: command not found

### ISSUE THREAD

**Issue by robp2175** [lesspass/lesspass#422]
webserver unable to find python, and therefore unable to create lesspass.conf.
Using latest https://github.com/lesspass/lesspass/blob/master/containers/docker-compose.yml

Thank you.

```
Recreating containers_webserver_1 ... done
Starting containers_backend_1     ... done
Attaching to containers_backend_1, containers_webserver_1
webserver_1  | /app/entrypoint.sh: line 23: python: command not found
webserver_1  | cat: /etc/httpd/conf.d/lesspass.conf: No such file or directory
containers_webserver_1 exited with code 0
```

**Comment by guillaumevincent** [comment]
Hello @robp2175 ,
still the same as #421 this is a work in progress, so it doesn't work yet
Wait for the message on the README to be removed
