### ISSUE TITLE
Firefox addon is disable

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#425]
On a android mobile device, when trying to use lesspass addon `3.1.6`, on Firefox Beta, it's disabled with a warning message :

> This addon could not be verified by Firefox Beta.

After uninstalling the addon to try to reinstall it I was hit with the message

> the addon downloaded from addon.mozilla.org could not be installed because it appears to be corrupt.

Im not sure if both errors are related or not as I was poor connection at the moment, so the latter might be due to low connectivity.

**Comment by guillaumevincent** [comment]
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by edouard-lopez** [comment]
Don't look like it, I'm on Firefox Beta `67.0` which is supposed to be already fixed

**Comment by Kcchouette** [comment]
I don't have this problem with Firefox mobile beta (67.0b18; see about:firefox)

**Comment by edouard-lopez** [comment]
I managed to re-install the addon from AMO, and the extensions works fine.

Still on the same Firefox version `67.0`.
