### ISSUE TITLE
Website: Terminal and Cozy Cloud links are broken

### ISSUE THREAD

**Issue by kocio-pl** [lesspass/lesspass#430]
Hi,

In the _Supported Platforms_ section on the [website](https://lesspass.com/#/) there are links to a "Terminal" and a "Cozy Cloud" versions of LessPass, however these links are broken now:
- https://github.com/lesspass/cozy#install
- https://github.com/lesspass/cli#install

Obligatory screenshot :wink:  :

![Screenshot_2019-06-08 Build software better, together](https://user-images.githubusercontent.com/5439713/59152367-c0e1aa00-8a42-11e9-873c-8a76af1fad09.png)

Anyway, this is a nice project and I like that it has ports to different environments! :heart:

**Comment by edouard-lopez** [comment]
Thanks @kocio-pl for the feedback.
The CLI has been rewritten in Python and a Powershell port is also available:
* Python: https://pypi.org/project/lesspass/
* Powershell: https://www.powershellgallery.com/packages/Lesspass/

We no longer support Cozy cloud (see #341).

The site need to be updated.
