### ISSUE TITLE
Firefox extension: permanent "share" tooltip

### ISSUE THREAD

**Issue by kocio-pl** [lesspass/lesspass#431]
In the Firefox extension (Firefox 67.0.1 on Ubuntu 18.04, LessPass 3.1.6) after clicking the second icon from the right ("share") the tooltip is being displayed as long as the form resets and it obsfucates the password field, no matter what I click.

The interesting effect is that this tooltip comes back after generating new password, even if I try change any data in this form, as long as I stay in this "session".

![image](https://user-images.githubusercontent.com/5439713/59152627-5cc1e480-8a48-11e9-8643-24889ca4d2b6.png)

**Comment by edouard-lopez** [comment]
I reproduce in `68.0b8 (64-bit)`:

* generate password ;
* click `share` button

Now you can't toggle password visibility as the button is covered.

### Workaround

* We still have access to the `copy` button, we should be able to see what the password is ;
* The tooltip disappears once the extension's panel is closed.

**Comment by kocio-pl** [comment]
BTW: what is this link useful for? I could not see any password profile (encrypted or not) this way, just a LessPass website.

**Comment by edouard-lopez** [comment]
The idea is for you to be able to share a password profile so you only need to type the master password. In [this example](https://lesspass.com/#/?passwordProfileEncoded=eyJsb2dpbiI6ImFzZCIsInNpdGUiOiJnaXRodWIuY29tIiwidXBwZXJjYXNlIjpmYWxzZSwibG93ZXJjYXNlIjp0cnVlLCJudW1iZXJzIjp0cnVlLCJzeW1ib2xzIjp0cnVlLCJsZW5ndGgiOjIyLCJjb3VudGVyIjoxLCJ2ZXJzaW9uIjoyfQ%3D%3D), I changed:
* login to `asd`
* disable uppercase
* set length to `22`

**Comment by kocio-pl** [comment]
I understand the idea of password profiles and I use it (community templates for popular sites would be great!), but I wonder what can you do with this link? 

I don't see this profile in a browser or downloading via curl (I guess this might be what this link is all about), there's only LessPass webpage, so maybe something is broken?

**Comment by kocio-pl** [comment]
Oh, wait! It is there, I was just fooled, because it looks similar to the webpage... Thanks!

**Comment by kocio-pl** [comment]
Well, it's not so simple...

- I can see your profile
- I can share my settings too when I don't use saved profiles
- If I start with a saved profile (or just accept site name hint), the link shows a blank profile

The other problem is that this link is only available when you type in the password and it does not matter which one, because the link is the same (and it makes sense, since profile is not dependent on passwords). Maybe this icon should be available even before using "Generate" button?

Do you think I should open new ticket (or 2 separate tickets) for these problems?

**Comment by guillaumevincent** [comment]
> The other problem is that this link is only available when you type in the password

this is not a bug, I don't want to polute the main ui with too many actions

**Comment by kocio-pl** [comment]
OK, I see.

What do you think about void links for saved profiles?

**Comment by guillaumevincent** [comment]
> OK, I see.
> 
> What do you think about void links for saved profiles?

I don't understand, void links?

**Comment by kocio-pl** [comment]
I mean this problem:

> If I start with a saved profile (or just accept site name hint), the link shows a blank profile

**Comment by kocio-pl** [comment]
Hi, there was no answer about the second problem I mentioned. Should i open new issue for this or maybe do something else?

**Comment by guillaumevincent** [comment]
Feel free to open another issue
thank you
