### ISSUE TITLE
Translating "Search" label

### ISSUE THREAD

**Issue by kocio-pl** [lesspass/lesspass#435]
Is translating "Search" label possible? 

Changing this line:

https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/src/views/Passwords.vue#L21

into:

```html
<input class="form-control" name="search" placeholder="{{$t('Search')}}" v-model="searchQuery">
```

does not work even if I added this line:

```json
  "Search": "Search",
```

into `en.json` file and I'm not sure if this is doable or it just needs something more.

**Comment by guillaumevincent** [comment]
If you want to add a translation field, you need to run `npm run build:i18n`.
It will update all i18n lang files with the key.

**Comment by kocio-pl** [comment]
After this action I get this result on http://0.0.0.0:8000/#/passwords (when I lick on the "key" icon):

![Screenshot_2019-06-16 LessPass](https://user-images.githubusercontent.com/5439713/59568064-ce67e700-9075-11e9-9a30-ed4bc7d21c51.png)

Main form (on the http://0.0.0.0:8000/#/ ) is fine and properly translated:

![Screenshot_2019-06-16 LessPass(1)](https://user-images.githubusercontent.com/5439713/59568091-2a327000-9076-11e9-9c8d-4413bc6af559.png)

**Comment by kocio-pl** [comment]
I also get this error message in the terminal, but I'm not sure what to do with it:

```
Errors compiling template:

placeholder="{{$t('Search')}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
```

**Comment by guillaumevincent** [comment]
maybe `:placeholder="{{$t('Search')}}"` instead of ` "placeholder="{{$t('Search')}}"`

**Comment by kocio-pl** [comment]
Now the error is different:

```
  Errors compiling template:

  invalid expression: Unexpected token { in

    {{$t('Search')}}

  Raw expression: :placeholder="{{$t('Search')}}"
```

**Comment by guillaumevincent** [comment]
yes sorry

`:placeholder="$t('Search')"`

v-bind expect a function
