### ISSUE TITLE
Feature Request: blank website field by default

### ISSUE THREAD

**Issue by jones137** [lesspass/lesspass#439]
It would be nice if you included a setting to have website's field blank by default in browser addons. I use custom names for my websites and selecting and deleting it every time is tedious.

**Comment by guillaumevincent** [comment]
I will work on this during the summer
This is a good idea

**Comment by guillaumevincent** [comment]
I need to do more test to see if the compromise (hitting backspace) is acceptable.
I would love to have your feedback on this one
