### ISSUE TITLE
Auto complete gets url field out of sync

### ISSUE THREAD

**Issue by javs** [lesspass/lesspass#441]
Seems there is a bug with selecting entries from autocomplete:
![bug](https://user-images.githubusercontent.com/316502/60840120-c09d1180-a19c-11e9-8d3d-c49a1d4a849a.gif)

Note that the two password generations are with the same input data: "domain.com", "user", "password", yet they generate different passwords depending on the method used (i.e. typing "domain.com" vs deleting a character and then using arrows+enter key to select "domain.com").

The first generation actually seems to match input data of "ubdomain.domain.com", "user", "password".

**Comment by pbaity** [comment]
This is basically a guess (still learning Vue), but it might be that [there's no `v-on`](https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/src/views/PasswordGenerator.vue#L17) on the `PasswordGenerator.vue` listening for the input event [emitted in `InputSite.vue`](https://github.com/lesspass/lesspass/blob/master/packages/lesspass-pure/src/components/InputSite.vue#L52), whereas there are for the other events emitted there (`suggestionSelected` and `passwordProfileSelected`). 

Might be totally wrong, but wanted to throw it out there in case it helps solve the problem.
