### ISSUE TITLE
Problems with 8.1.1 on Android

### ISSUE THREAD

**Issue by kocio-pl** [lesspass/lesspass#451]
Tested on fresh 8.1.1 version from F-Droid on Android 5.1.1 and on CyanogenMod 13.0 (based on Android 6.0.1).

- LessPass interface is still in English (I expected Polish translation)
- When clicking on "Settings" the application crashes every time

**Comment by guillaumevincent** [comment]
Translation doesn't exist on mobile :(
Only on web extension

**Comment by guillaumevincent** [comment]
close for #456
