### ISSUE TITLE
No tooltip popups

### ISSUE THREAD

**Issue by pbaity** [lesspass/lesspass#454]
Looks like tooltips are broken on the newest Lesspass:

![notooltip](https://user-images.githubusercontent.com/39106297/61724340-c4539b00-ad3b-11e9-9253-196ad4e7bf89.gif)
(I promise I'm clicking furiously in the above gif)

The `copied!` tooltip not showing up was what brought it to my attention. Tested it out on latest Firefox and Chrome on both Mac and Windows.

**Comment by edouard-lopez** [comment]
Thanks @pbaity, I reproduce on version `9.0.0` in Firefox and Chrome

**Comment by guillaumevincent** [comment]
duplicates https://github.com/lesspass/lesspass/issues/446
I need to push a new version with the fix
