### ISSUE TITLE
Add a change password feature

### ISSUE THREAD

**Issue by FaustXVI** [lesspass/lesspass#457]
For now, the only way to change its master password is through the "Forgot password" feature.
That won't be working anymore once #185 is solved.

Still, the user should be able to change its password. We should have a feature allowing the user to change its password once authenticated and if it can provide the current password.

**Comment by FaustXVI** [comment]
Sorry I am so long to deal with this issue (time management problems).
I am still at the very beginning and there is one thing I can't find out : how do you run your tests with python ? pytest is not in the dependencies so it must be something else... and factory_boy is a mock library so not a runner... Could you help me please ? Thanks

**Comment by guillaumevincent** [comment]
To see how test are run, you can see the github action file: https://github.com/lesspass/lesspass/blob/master/.github/workflows/test.yml

Tell me if you need more info

**Comment by biancarosa** [comment]
@FaustXVI are you still looking at this issue? I'd like to see password profiles encrypted, too, and I currently have the time to help with this issue.

**Comment by FaustXVI** [comment]
Hello,
I am not looking at this issue currently.
Some priorities changes for me and I didn't had time to do it.
I'll be super happy if you find time to do it :)
Thanks a lot!

Xavier Detant

**Comment by guillaumevincent** [comment]
Thank you @biancarosa 
I close it's fixed by https://github.com/lesspass/lesspass/commit/730e7ae0c737d20715c54baf67ba94f9b3d60bd5
