### ISSUE TITLE
Automatically update password

### ISSUE THREAD

**Issue by pinage404** [lesspass/lesspass#461]
LastPass have a great feature called [security challenge](https://helpdesk.lastpass.com/fr/lastpass-security-challenge/) which is able to automatically change the password (that works on many sites but not all) that : 

1. open a new tab
1. go to the login page of the site
1. fill the form to login and send it
1. go to the change password page
1. fill the form and send it
1. update their database

---

For LessPass we could do, for a targeted site :
1. ask user's master password
1. store it in-memory
1. retrieve password's options of this site
1. open a new tab
1. looks for a login link or login form (for one page site)
    * go to the login page for the link case
1. fill the form and send it
    * at this moment, we should : 
        * have the login identifier (e.g. email) retrieved with password's options
        * be able to generate the password with retrieved with password's options and in-memory master password
1. [looks for change password link or change password form
    * go to the change password page for the link case
1. update password https://github.com/lesspass/lesspass/issues/460
1. clear in-memory
    * master password
    * password's options of this site

**Comment by guillaumevincent** [comment]
I close this one.
We will continue the discussion on #460
