### ISSUE TITLE
Migration with encrypted password ?

### ISSUE THREAD

**Issue by heuzef** [lesspass/lesspass#463]
Hi :)
I need to use the migration script for get my profils from lesspass.com

But in [migration.py](https://github.com/lesspass/lesspass/wiki/password-profiles-manipulation-scripts) script you have an password variable for connect to lesspass.com :

``PASSWORD = '<replace_me>'``

But, i actually connect from lesspass.com with the encrypted function, so i have not the encrypted password.

There is possible to get my profil anyway ?

Thanks :)

**Comment by guillaumevincent** [comment]
Encrypted my master password use "lesspass.com" for the site field, your email and your master password.
So open the web extension and generate a LessPass password for site "lesspass.com"

**Comment by heuzef** [comment]
OK :) Simple.
I got it.
Thanks.
