### ISSUE TITLE
Ubuntu Touch App

### ISSUE THREAD

**Issue by beli3ver** [lesspass/lesspass#464]
Hello,

I am thinking about create a Ubuntu Touch app.
First I will create a simple WebApp with the Lesspass webpage.
But then I will create a native app. Is there a JS libary?
Or only working with Python?

Thanks

**Comment by guillaumevincent** [comment]
Hello,
you probably want to integrate https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure in your project

You only need a `<div id="lesspass"></div>` and import lesspass code `<script src="dist/lesspass.min.js"></script>`
