### ISSUE TITLE
Passwords are not the same across "devices"

### ISSUE THREAD

**Issue by nathansizemore** [lesspass/lesspass#465]
foo.com
bar
baz

Windows 10 - Firefox - 6dnR=|ECHa35e@!z
Android - Firefox - 0QY9EJfl.Dg*-f~1
Android - App - 6dnR=|ECHa35e@!z

This can't be expected, right? Are there not unit tests for this?

**Comment by guillaumevincent** [comment]
You set "Foo.com" instead of "foo.com" on Android Firefox.
The first letter is uppercase.
On mobile, keyboard automatically set the first letter uppercase. Chrome browser understand autocapitalize off but Firefox not.

I will let this one open to try to fix it one for all

**Comment by nathansizemore** [comment]
Oh yeah, even though I lowercase foo.com in Android Firefox, when I'm done typing it auto-capitalizes it. Didn't notice. Sorry, my bad!

**Comment by guillaumevincent** [comment]
> Today I learned that autocapitalize="none" doesn't work on Android Firefox if the <input> element doesn't have a type="text" or type="textarea" attribute. I finally fixed a bug found 2 years ago on LessPass!

Finally :)

I will push this version on production this week or next week
