### ISSUE TITLE
Changing the Master Password field doesn't reset the generated password

### ISSUE THREAD

**Issue by Zwyx** [lesspass/lesspass#466]
Hi and congratulations for LessPass brilliant idea (and the just as brilliant three icons fingerprint!),

On the [web app](https://lesspass.com/), after generating a password, changing either the `site` field, `login`, or any options will reset the generated password; but changing the master password won't. Also, hitting Enter after changing the master password won't trigger generation (might be related to #266).

I also have a side question: when I hit a key in the master password field, the three icons fingerprint is changed twice: once when I hit the key, and a second time just after. What is the reason behind that? It's a little bit confusing.

Cheers

**EDIT**:

I might have just understood why the fingerprint is changed twice. Because the first time, it looks random, and the second change is my actual fingerprint. So I guess it's a security protection: if you're making a presentation and someone is recording your screen, it would be possible to retrieve your master password with the sequence of the fingerprints. So random stuff at the beginning prevents that. Well done :-) I still think it's confusing... display the fingerprint at the end of the typing would maybe be less confusing, but that's not a real issue :-)

**Comment by guillaumevincent** [comment]
Hello @Zwyx,
I think it's fixed now.
There is a non regression test for this one, and I tested on Firefox and Chrome successfully.
 
> it's a security protection

Yes it will avoid somebody to find your master password when you screencast LessPass use
