### ISSUE TITLE
USB/Bluetooth Keyboard Emulation

### ISSUE THREAD

**Issue by ghost** [lesspass/lesspass#469]
We could keep lesspass on a dedicated offline device and send password keystrokes to another device with keyboard emulation, this prevents your Master Password from being exposed to an attacker and it's a lot more convenient than typing passwords by hand.

Example: https://github.com/tejado/Authorizer

**Comment by guillaumevincent** [comment]
Hello,
It's probably a good idea, but I think I won't have the skills or the time to investigate it.
I close
