### ISSUE TITLE
Status of docker deployment

### ISSUE THREAD

**Issue by anderwm** [lesspass/lesspass#470]
It's possible I'm being dense here but I can't seem to get the docker-compose.prod.yml up and running. I can't find any directions, but I'm doing the normal docker-compose up things. I made the .env file it is looking for but the nginx container still can't find 'DOMAIN' for some reason.

Am I not suppose to be using this, is there a bug, or can someone point me to the instructions?

**Comment by guillaumevincent** [comment]
I will work on this one first, cleaning everything to have a stable state.
Sorry I needed to find some energy and time to continue working on LessPass.

**Comment by guillaumevincent** [comment]
I close this one,
nginx container will be removed, I'm still working on it

**Comment by michaelimfeld** [comment]
Any updates on this? 
I would like to run my own reverse proxy doing ssl.
