### ISSUE TITLE
Changing my master password implies changing all my passwords ?

### ISSUE THREAD

**Issue by JekoTronik** [lesspass/lesspass#471]
The question speaks for itself. I just want to be sure I didn't miss a thing.

**Comment by panther2** [comment]
Yes, see https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4

**Comment by guillaumevincent** [comment]
Thank you @panther2 

yes this is one of the drawback using a deterministic password manager compared to another password manager.

I close
