### ISSUE TITLE
No "Copied" tooltip appears after copying password to clipboard

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#473]
With reference to #446 and #454 the "Copied" tooltip still does not appear in the Chrome Extension 9.0.0 on Chrome, latest stable, neither on Chrome OS nor on Windows 7.

**Comment by guillaumevincent** [comment]
Yes I will push a new version next week fixing this and other bugs

I added a breaking change (site field is no longer filled) and I want to test it carrefully before pushing this in production

Sorry for the delay

**Comment by panther2** [comment]
@guillaumevincent 

> Yes I will push a new version next week fixing this and other bugs

Great, thanks.

> I added a breaking change (site field is no longer filled) and I want to test it carrefully before pushing this in production

Offtopic, sorry, but I don't know where to ask. Would that be the default behaviour? That would indeed be usability breaking, at least for me. I am dependent on site fields being filled in automatically with my more than 200 passwords.

**Comment by guillaumevincent** [comment]
Imagine your are on `www.example.org`. Actually if you open LessPass it fills the site input with `www.example.org`. In the future it will open the autocompletion for the site input with `example`, `example.org` and `www.example.org`.

You still don't need the database.

I'm doing this because I would like to have the same behavior regarding every devices and a lot of users remove the www and the tld when they use LessPass

**Comment by panther2** [comment]
Thank you, @guillaumevincent for the information.

But how would I know whether I created my password with either `example` or `example.org` or `www.example.org` . I have always used what has been auto-filled by lesspass in the site field.

What about `abc.example.org` , ´def.example.org´ ... would that be reduced to only ´example´, too?

> ...and a lot of users remove the www and the tld when they use LessPass 

What about the lot of users who have to add those information back, then?

Sorry for my insistence ... I just feel that my password tool that has served well for me and almost all of my collegues and friends for years and which I was always promoting proudly will be slipping away...

**Comment by guillaumevincent** [comment]
You're right, this is not ideal.

I will postpone the update so.

> But how would I know whether I created my password with either example or example.org or www.example.org

You know it's www.example.org because it's the longest one.

> What about abc.example.org , def.example.org ... would that be reduced to only example, too?

Yes, in my mind, I was just splitting the code around the dot.

**Comment by panther2** [comment]
Thank you, @guillaumevincent . I am sort of relieved for the moment.

( >You know it's www.example.org because it's the longest one.
In case the autofilled domain had been only `anotherexample.org` an offer of `www.anotherexample.org` would be misleading, then. )

**Comment by guillaumevincent** [comment]
I don't have a lot of feedback from my users. So when a user came, and says: "Hey you next update will force me to stop using it", I like it because it shows that I miss something.

:heart:

**Comment by panther2** [comment]
@guillaumevincent Thank you for that kind feedback. 
I am always at your service when it comes to giving feedback.
