### ISSUE TITLE
Is it possible to host lesspass on AWS S3 as static website?

### ISSUE THREAD

**Issue by Jeonkwan** [lesspass/lesspass#474]
I was wondering since password generation is on the local machine, it would be interesting to host on AWS S3, without a VM. Of course the "database" function will probably not available.

**Comment by guillaumevincent** [comment]
Yes you can. Use [packages/lesspass-pure](https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure) folder, and serve the `dist` folder.
