### ISSUE TITLE
LessPass Firefox (60.9.0esr) add-on unusable ...

### ISSUE THREAD

**Issue by fjld61** [lesspass/lesspass#476]
It appears that the LessPass Firefox add-on has become unusable because the LessPass window closes when I try to tab to or click into the master password field.

LessPass : 9.0.0
Browser   : Firefox   60.9.0esr
OS           : CentOS 7.6 kernel 4.4.168-1.el7.elrepo.x86_64

I haven't tried other browsers; other installed add-ons:

 UBlock Origin
 eID Belgium
 GNOME Shell integration
 HTTPS Everywhere
 Cookie AutoDelete

Tried removing, re-installing and restarting FF.

Please HELP (as I did come to rely on LessPass for quite a number of sites !)

**Comment by guillaumevincent** [comment]
Hello @fjld61,

look like similar to #329 

can you tell me your version of ibus?

    yum list installed | grep -e "^ibus.x86_64"

Similar workaround is to open [moz-extension://956650c1-dd76-4c85-9129-62d4604e0a49/popup.html](moz-extension://956650c1-dd76-4c85-9129-62d4604e0a49/popup.html)

Let me search for an open issue on ibus on centos

**Comment by fjld61** [comment]
Here is the information you are asking for:
$ yum list installed | grep -e "^ibus.x86_64"
ibus.x86_64                           1.5.17-5.el7                 @base     

$ yum list installed | grep -e "^gnome-shell.x86_64"
gnome-shell.x86_64                    3.28.3-11.el7                @base 

If I understand you: I make a bookmark to "moz-extension://956650c1-dd76-4c85-9129-62d4604e0a49/popup.html" and use that instead of the little lesspass icon in the FF "toolbar".
However this does not seem to load anything: possibly the extension "UUID" (?) is wrong. Can I find this string myself ?
Thanks.

**Comment by guillaumevincent** [comment]
@fjld61 thank you I will take a look at this

you can find your uuid in `about:debugging#/runtime/this-firefox` tab

**Comment by fjld61** [comment]
Thanks the moz-extension works now : but I needed to use about:debugging and look for the LessPass add-on in the list. Apparently it was 0ae13994-128e-435d-ac6b-eab9da5313e6 on my system.

Thanks.

**Comment by guillaumevincent** [comment]
Yes the uuid is created during the installation of the web extension

The bug is apparently fixed in the lastest version of gnome-shell.
Your system is up to date right?

**Comment by fjld61** [comment]
Indeed, I updated a couple of days ago.

**Comment by guillaumevincent** [comment]
Hello @fjld61,
it's confirmed it's a problem with ibus on centos 7
See the opened bug: https://bugs.centos.org/view.php?id=16545
