### ISSUE TITLE
Set a default login in extension options

### ISSUE THREAD

**Issue by whiver** [lesspass/lesspass#477]
There is an option in the mobile app to choose a default value that will be used in the login field, avoid to retype each time the same email address. I didn't find anything like that in the extension, did I miss something?

**Comment by whiver** [comment]
@guillaumevincent Would you accept a PR on that if I take a look and try to add an option page to the extension?

**Comment by guillaumevincent** [comment]
@whiver definitively yes :)
I'm completely stuck by my work currently, so any help is welcome :heart:

**Comment by whiver** [comment]
I'll track the progression of the feature on this issue. Here is the list of upcoming steps:

- [ ] Setup the build pipeline, create a first simple-but working option page (no entry point for in the manifest), only the default login is available in the option page
- [ ] Add localization
- [ ] Polish option page design
- [ ] Add a link to the option page in the popup (to be discussed)
- [ ] Add tests
- [ ] Add the password preferences in the option page (length, special characters, etc.)

**Comment by guillaumevincent** [comment]
:+1:

**Comment by guillaumevincent** [comment]
Closing this one, thank you for this, I will publish a new version today!
