### ISSUE TITLE
Master Password verification images leak password trivially

### ISSUE THREAD

**Issue by dragondave** [lesspass/lesspass#48]
![The sample password input gif](https://cdn-images-1.medium.com/max/800/1*wgrq2WIxhyBSfL1Tbr5Qbw.gif)

The password for https://cdn-images-1.medium.com/max/800/1*wgrq2WIxhyBSfL1Tbr5Qbw.gif above is 'passwordpassword' -- this can be trivially determined by trying letters until the verification images are correct for each successive frame. (I did it by hand.)

This means that the master password is leaked if anyone can see your screen, including remotely etc. This is an unacceptable security risk.

I'd suggest that you shouldn't show any verification images until the user is done entering the password. Exactly what that means isn't entirely obvious, but I'd suggest it includes as a minimum
* minimum password length before showing any verification images, sufficient to make brute-forcing expensive even on 'correcthorsebatterystaple' type passwords with low entropy-per-character
* not showing images when the user still has focus on the text box; exceptions might be made if they're also hovering the copy button and haven't edited the password whilst doing so yet.
* reducing entropy in general in the final verification image -- a 99% verification accuracy is probably sufficient for a valid user who has typo'd their password but makes verification of a guessed password from the images more difficult for an offline attacker who has seen only the last image; I'm guessing the current verification image entropy is probably (10 colours * 100 emoji) ^ 3 images which rules out all but one in a billion passwords without querying the remote site, meaning 'correcthorsebatterystaple' type passwords need only dozens (69) of online attempts to get a password.

**Comment by guillaumevincent** [comment]
Will be fix soon by commit https://github.com/lesspass/pure/commit/512d998c8361fa7c9fe935537c7abdca913f82a0

![recorded](https://cloud.githubusercontent.com/assets/943762/20067725/a149dd48-a516-11e6-8dbf-b6fbe5e45cdf.gif)

**Comment by caspear** [comment]
Even the final glyphs leak far too much information about the password.

Assuming there are about 50 of the different glyphs you get 50^3 different combination, allowing the attacker to instantly chop 2^16 or so off the attack complexity.

If their password is as strong as a typical 128bit hash it would now be just beyond brute force reach, but most passwords people actually use almost never have that much entropy.

The best resolution to this would be to remove the glyphs entirely if you care about environments where there are shoulder surfers / CCTV cameras.

**Comment by guillaumevincent** [comment]
@caspear for the discussion we are agree that we hash the masterPassword with sha256 and then we take the sha256 hash to create the fingerprint ?

https://github.com/lesspass/pure/blob/master/src/components/Fingerprint.vue#L49-L59
```
LessPass.createFingerprint(newFingerprint).then(sha256 => {
    const hash1 = sha256.substring(0, 6);
    const hash2 = sha256.substring(6, 12);
    const hash3 = sha256.substring(12, 18);
    this.icon1 = this.getIcon(hash1);
    this.icon2 = this.getIcon(hash2);
    this.icon3 = this.getIcon(hash3);
    this.color1 = this.getColor(hash1);
    this.color2 = this.getColor(hash2);
    this.color3 = this.getColor(hash3);
});
```

https://github.com/lesspass/core/blob/master/index.js#L105-L109
```
function createFingerprint(str) {
    return new Promise(resolve => {
        resolve(crypto.createHmac('sha256', str).digest('hex'))
    });
}
```

**Comment by dragondave** [comment]
You should probably be using a modern hash which is difficult to use on a GPU; an attacker can easily try [billions of SHA256 hashes a second](http://stackoverflow.com/questions/4764026/how-many-sha256-hashes-can-a-modern-computer-compute).

**Comment by dragondave** [comment]
I don't think users need the glyph confirmation most of the time -- the fact that the password doesn't work is enough to suggest something's wrong when logging in, and a user only 'creates' a new password for a website once. Perhaps don't reveal it by default?

**Comment by guillaumevincent** [comment]
I detected errors in my master password very often. To be honest I use almost all the time the fingerprint.

I do not think that trying to solve the problem of CCTV cameras is a good idea. If anyone can see what you type, then he can see the master password. So trying to hide something less important than your master password is useless.

I'm more concerned with the problem of acceleration of cracking by brute force, if someone get your 3 icons. 

I just want that people use the tool for what it is, and clearly show its weaknesses. Then people are free to use it or not.

**Comment by AtoxIO** [comment]
You should try to leak less information. Using 3 * 5 glyphs and no color (125 combinations) should be plenty for detecting errors, and leak far, far less data than you currently do.

**Comment by caspear** [comment]
@guillaumevincent The approach you listed (along with the current implementations of getIcon and getColor) currently leaks 2^27 (46 icons, 14 colours) bits of info about the hash. So, even if you just display the final set of glyphs it will leak that much. Since your hashes are unsalted (and cannot be) you should ideally not be leaking any of your hashes at all if you can at all avoid it.

In a rainbow-table based attack the attack is not so much on the sha256 hash itself but on the entropy of the master password. Using the bits from the glyph essentially knocks them off the entropy of the master password. IME typical "strong" passwords that people remember have between 70 and 90 bits of entropy. Knocking 26 bits off due to the glyph leak substantially simplifies the difficulty of revealing the master password, having approximately the same effect as reducing a 12 character long completely random password to a 7 character long completely random password.

Revealing less information in the glyphs, e.g. as mentioned by @AtoxIO will leak less of the hash, but will still make it considerably easier to attack the password compared to an example without glyphs. Obviously the less you leak the better.

**Comment by diegorv** [comment]
Remove glyph confirmation! KISS hehe ^^

**Comment by edouard-lopez** [comment]
You are right, there is a security issue as we reduce the attack time here but I do not agree that removing it will make the approach more secure.

### Feature

The visual checksum is one answer to the idea that passwords management should be boring and painful (cf. [XKCD 936](https://www.explainxkcd.com/wiki/index.php/936:_Password_Strength)):

> Through 20 years of effort, we've successfully trained everyone to use passwords that are hard for humans to remember, but easy for computers to guess.

This feature **allows to use a pass-phrase well above `20` characters and still feel comfortable typing it**. It removes fear of typos by tackling  them early in the process, and in a funny way (I'm always guessing where was my typo when I saw a new visual checksum).

### Removal

If we remove this, typing long password will be more difficult. So we will fail our users as they will  resort to bad behaviors such as:

0. use **shorter password to reduce risk of typo**. Thus, reducing entropy  ;
0. **display master password more frequently to check for typo**. So no more need to steal the checksum, as is will be easier to just steal the master password ;
0. move forward as they can't check the master password for typos and check the generated password instead. That means restoring **higher cognitive load** to manage their password by having to remember stuff, even approximatively, like last 4 letters for each generated password.

So we are where we started but with less fun.

### Fails

Preventing errors at early stage is one of the criteria from Bastien & Scapin heuristic:

> 5.1. ERROR PROTECTION 
> 
> Definition :
> The criterion Error Protection refers to the means available to detect and prevent data entry errors, command errors, or actions with destructive consequences.

> Rationale(s) :
> It is preferable to detect errors before validation rather than after: the detection is less disruptive.

[_Bastien, J.M.C., Scapin, D. (1993) Ergonomic Criteria for the Evaluation of Human-Computer interfaces_](http://www.cocoaheads.fr/wp-content/uploads/files/Ergonomic_Criteria.pdf) (pp. 33 or 39).

### Future

Thanks for raising the issue, but if the risk of getting the checksum stolen is a threat to you, you should probably consider different approach. In the meantimes, we are discussing the idea of adding on option, in the _connected mode_, to toggle the visual checksum.

So keep tuned :)

**Comment by guillaumevincent** [comment]
I close because the fingerprint doesn't leak master password anymore but reduce entropy of the master password. We will continue on https://github.com/lesspass/lesspass/issues/59

LessPass web extension 1.1.1 fix this

@edouard-lopez can you repost your answer on https://github.com/lesspass/lesspass/issues/59 ?
