### ISSUE TITLE
Add tooltips on menu items

### ISSUE THREAD

**Issue by whiver** [lesspass/lesspass#484]
Hi,
It would be really cool to have tooltips on the menu items to know what the icon refers to, because it's not always easy to know what is the purpose of each icon, especially the key.
Ex:
![image](https://user-images.githubusercontent.com/394565/67436579-41620b00-f5de-11e9-8ace-e6ab37992198.png)

I can make a small PR if you're ok with that.

**Comment by guillaumevincent** [comment]
Sure, good UX improvement
