### ISSUE TITLE
Allow for different options for symbols

### ISSUE THREAD

**Issue by JelleHissink** [lesspass/lesspass#489]
I am looking into using this tool for my automated build and test environment.

However I am running into an issue where I have to use symbols in my password and am having to enter them in multiple bash scripts into .yaml, .ini, .json files etc.

The issue is different file formats have different escapes needed, so for instance # in an linux config file usually means the password is truncated because the line is treated as comment.

The only other option for me would be to don't generate symbols but always include a default prefix like $_a0A
This last option would also allow you to meet minimum password requirements in a very poor fashion.

**Comment by guillaumevincent** [comment]
You are look for different options with the cli?

**Comment by JelleHissink** [comment]
I would think that all options in calculating passwords would need to be implemented in all clients eventually.
Otherwise it would be impossible to recalculate the passwords cosistently.

**Comment by guillaumevincent** [comment]
It would make the tool more complicated in my opinion
Our value proposition should be in the simplicity of the tool

**Comment by edouard-lopez** [comment]
Supporting this is way behind the scope of the project, it's up to you to escape the string for the file types you are targeting.
