### ISSUE TITLE
Toggle password options

### ISSUE THREAD

**Issue by tatyshev** [lesspass/lesspass#49]
Consider a scenario where user forgot actual password options after some changes. 
This can really happen when these options are available like this:

![1](https://cloud.githubusercontent.com/assets/2528926/20070936/95046158-a54c-11e6-81e7-0cf33998fc72.png)

Is there any significant reason to leave these settings so accessible?
Maybe it makes sense to get away from password options?

**Comment by guillaumevincent** [comment]
@tatyshev I want the experience to be identical between all interfaces. The web extension popup on Firefox had some problems if the height of the popup increase. So what you see is a solution for this problem. 

What is your opinion about hidding password options @edouard-lopez ?

**Comment by edouard-lopez** [comment]
Thanks @tatyshev 
@guillaumevincent I rarely modify the options and I reckon most people don't use them ¹. If they do use them, they are probably better using the _connected version_ ².
_Hidding_ can be achieve by different solution:

1. my first proposal was to collapse the block, then toggle when label is click. But this won't fix your issue&nbsp;;
0. Second solution might be to reduce height so the fields are below the fold of the popin but still reachable by a simple scroll. This is both **mouse and finger friendly and is easily discoverable**. Drawback is the scrollbar.

¹: need to investigate this a bit ;
²: we should add intelligence to suggest the _connected version_

**Comment by guillaumevincent** [comment]
The options will be collapsed in the next version.
I close
