### ISSUE TITLE
Copy generated passwords to Wayland clipboard from CLI

### ISSUE THREAD

**Issue by ddelabru** [lesspass/lesspass#491]
The lesspass CLI is capable of copying generated passwords to the X clipboard using `xsel` or `xclip`, but if the error message is any indication, lesspass does not work with any similar command for Wayland. It would be useful to be able to write passwords directly to the Wayland clipboard.

**Comment by guillaumevincent** [comment]
I need to look at the wayland API for this one

**Comment by ddelabru** [comment]
On a second glance, I have found that I managed to get this working just by installing this compatibility layer between the Wayland clipboard and the X clipboard tools: https://github.com/brunelli/wl-clipboard-x11

**Comment by guillaumevincent** [comment]
It will be awesome @ddelabru !

**Comment by guillaumevincent** [comment]
I will create a tag and push a release at the end of this week.
Feel free to ping me if I forgot, I don't have a lot of time at the moment.
