### ISSUE TITLE
Firefox Nigthly Extension not working

### ISSUE THREAD

**Issue by GaboFDC** [lesspass/lesspass#494]
Not 100% sure if is only nightly or in any firefox version is failing, but I'm currently on 72.0a1 and I can't login.
I tried with random fake email and password and always get the error.
I get the generic error "something went wrong" and no idea why. Not sure if there is a way to enable debugging for the extension or something to provide more info. 
If I try from chrome extension it works. If I try from lespass web page in firefox it works.

**Comment by guillaumevincent** [comment]
Really strange.

To debug:

in `about:debugging#/runtime/this-firefox` copy LessPass Internal UUID and open a new tab on `moz-extension://<LessPass Internal UUID>/popup.html`

You can do a right click `Inspect Element`, go on network tab and try to log in again.

I will try to install Firefox nightly

**Comment by GaboFDC** [comment]
Seems like a Cross-Origin issue the site seems to have a capital `L` not sure if that may cause it

![image](https://user-images.githubusercontent.com/1425500/69077962-dea93700-0a04-11ea-954c-8bb773d490d8.png)


PD: There is no need for the `moz-extension://<LessPass Internal UUID>/popup.html` on the first page, there is a handy "inspect" buttos that those the same:
![image](https://user-images.githubusercontent.com/1425500/69078041-026c7d00-0a05-11ea-8665-2783d24e3e26.png)

**Comment by guillaumevincent** [comment]
Thanks for the tip

Did you change the url in the login form to `https://Lesspass.com` because by default it's `https://lesspass.com"`?

**Comment by GaboFDC** [comment]
No, I didn't change it, I dug up a bit more, and the capital `L` seems to be only visual.
After a few more tests, seems like nightly had some update gone wrong, after updating, and reinstalling the plugin seems like is fixed.

**Comment by guillaumevincent** [comment]
ack thank you for the update
