### ISSUE TITLE
Feature request: upload site rules

### ISSUE THREAD

**Issue by fulldecent** [lesspass/lesspass#495]
# Specification

Requesting to add a new command:

```sh
lesspass export-sites
```

It will save a filtered version of your profile, like:

```json
{
    "site": "www.ingdirect.fr",
    "lowercase": false,
    "uppercase": false,
    "symbols": false,
    "numbers": true,
    "counter": 1,
    "length": 6
}
```

and invite you to upload it to: https://lesspass.com/survey

---

# Discussion

The NIST standards for passwords are published at https://pages.nist.gov/800-63-3/sp800-63b.html and they are very good.

And the LessPass default settings are compatible with NIST recommendations. i.e. NIST recommends that the LessPass default-setting should be acceptable for password logins.

Most websites accept LessPass default-setting passwords, but some don't. And those sites suck.

When a website does not accept a LessPass default-setting password the LessPass user will update settings to workaround that.

By inviting LessPass users to upload the above file we can identify and shame websites that have poor password policies. We can directly reference the NIST guidelines and the number of LessPass users that have been inconvenienced. This should help to motivate those websites to change.

**Comment by guillaumevincent** [comment]
> # Specification
> 
> Requesting to add a new command:
> 
> ```shell
> lesspass export-sites
> ```

A new command in the lesspass-cli ?

> 
> It will save a filtered version of your profile, like:
> 
> ```json
> {
>     "site": "www.ingdirect.fr",
>     "lowercase": false,
>     "uppercase": false,
>     "symbols": false,
>     "numbers": true,
>     "counter": 1,
>     "length": 6
> }
> ```

Where did this profile came from?
From LessPass Database ?


> 
> and invite you to upload it to: https://lesspass.com/survey
> # Discussion
> 
> The NIST standards for passwords are published at https://pages.nist.gov/800-63-3/sp800-63b.html and they are very good.
> 
> And the LessPass default settings are compatible with NIST recommendations. i.e. NIST recommends that the LessPass default-setting should be acceptable for password logins.
> 
> Most websites accept LessPass default-setting passwords, but some don't. And those sites suck.
> 
> When a website does not accept a LessPass default-setting password the LessPass user will update settings to workaround that.
> 
> By inviting LessPass users to upload the above file we can identify and shame websites that have poor password policies. We can directly reference the NIST guidelines and the number of LessPass users that have been inconvenienced. This should help to motivate those websites to change.


I like this feature.

**Comment by guillaumevincent** [comment]
ping @fulldecent

**Comment by fulldecent** [comment]
This example came from here https://github.com/lesspass/lesspass/issues/154 and then I adapted it to show the desired format.

**Comment by guillaumevincent** [comment]
so it's a lesspass-cli command to extract profiles saved in lesspass-database right?
And a lesspass-cli to restore those password profiles in LessPass database?

**Comment by fulldecent** [comment]
It is one lesspass-cli command to extract profiles saved in lesspass-database.

Then the end user may upload that file to https://lesspass.com/survey to shame the vendor.

**Comment by edouard-lopez** [comment]
Having a Hall of Shame was something we had in mind, so :+1: 
> We should encourage/force those sites to update their password policies with a hall of shame or something like that.
https://github.com/lesspass/lesspass/issues/280#issuecomment-331097131

And we had a PR to save profiles: _Add a --to-profiles CLI option to save profiles #397_

**Comment by guillaumevincent** [comment]
I close this one in favor of https://github.com/lesspass/lesspass/issues/527
I don't know how we will fill the hall of shame database for now.
