### ISSUE TITLE
Publish browser extension on Opera addons platform

### ISSUE THREAD

**Issue by joriscode** [lesspass/lesspass#496]
The browser extension is not available on the Opera's platform https://addons.opera.com/ although it can be installed from Chrome Web Store. Therefore, it is only a matter of publishing the existing Chrome extension to Opera's platform. Furthermore, the website would have a new icon directing to the extension on the Opera's platform.
I believe this is technically simple but induces a little extra maintenance.

**Comment by guillaumevincent** [comment]
If the upload can be automated yes we would push it to opera.
But last time we look at, it was not possible.

**Comment by joriscode** [comment]
> If the upload can be automated yes we would push it to opera.
It totally makes sense. After a quick search, I found nothing like this.

A workaround would be to indicate on Lesspass website that extensions from Chrome Web Store can be installed to Opera via the official  https://addons.opera.com/en/extensions/details/install-chrome-extensions/.

**Comment by guillaumevincent** [comment]
Maybe we can add this in the wiki for now?

**Comment by joriscode** [comment]
Done! https://github.com/lesspass/lesspass/wiki/FAQ#how-to-install-lesspass-on-opera-web-browser

**Comment by guillaumevincent** [comment]
Thanks @joriscode
