### ISSUE TITLE
Challenge failed for domain

### ISSUE THREAD

**Issue by jdrizzzzz** [lesspass/lesspass#499]
Hi,

I dont really know where to post this.
Im trying to run the install-lesspass.sh, but keep getting the message "Challenge failed for domain" 

Pulling db       ... done
Pulling backend  ... done
Pulling frontend ... done
Pulling nginx    ... done
Removing network lesspass_default
WARNING: Network lesspass_default not found.
Create LetsEncrypt certificate...
Challenge failed for domain domain.name
Some challenges have failed.

What am I doing wrong?

Thank you

**Comment by guillaumevincent** [comment]
You need to set the domain name in env variables.

For now the script is not supported, just here for actual people hosting lesspass database.
