### ISSUE TITLE
supergenpass diffs ?

### ISSUE THREAD

**Issue by ManUtopiK** [lesspass/lesspass#5]
Thanks a lot for your great tool!
I just want to know what are the main differences between lesspass and [SuperGenPass](https://chriszarate.github.io/supergenpass/)?

**Comment by guillaumevincent** [comment]
@ManUtopiK this is roughly the same philosophy. SuperGenPass predates LessPass. I did not know SuperGenPass before. Someone told me about it on reddit.

Technically it uses MD5 as a key derivation function with only 10 rotations.
I use PBKDF2-HMAC-SHA256 with 8192 rotations.

So LessPass is more robust against brutus force.

SuperGenPass doesn't use a login, so you don't have the auto login feature : 

![demo LessPass extension](https://github.com/lesspass/webextension/raw/master/demo.gif?raw=true "LessPass demo")
