### ISSUE TITLE
Make android app as accessibility helper/persistent notification

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#50]
from @Cheesebaron on #6
> If you are making a mobile app, it would be much appreciated if it would work kind of like LastPass on Android, where you can have it **installed as a Accessibility helper with a persistent notification, so it can fill apps to**o. Instead of having to switch between two apps to fill in details and copy pasting values.

**Comment by guillaumevincent** [comment]
I close this one,
this is not something we are working on. Moreover it is something difficult to do with an Android application that is developed on Cordova.
