### ISSUE TITLE
CLI master password unencrypted

### ISSUE THREAD

**Issue by almereyda** [lesspass/lesspass#501]
The `cli` optionally reads a `LESSPASS_MASTER_PASSWORD` environment variable. This is stored unencrypted.

An encrypted storage of this credential similar to the way it works in https://www.npmjs.com/package/vault is aspirable.

**Comment by guillaumevincent** [comment]
So your idea is to add a passphrase parameter and if provide will decrypt the LESSPASS_MASTER_PASSWORD ?

**Comment by AndreaRe9** [comment]
I think that using a LESSPASS_MASTER_PASSWORD read from environment variables is not safe. If the password is stored encrypted, I also think that the solution is not pratictal. In [https://www.npmjs.com/package/vault](url) the Master Password is encrypted with AES-256 using the username as default password, but that is not so safe either. I suggest to completely remove that default setting, even if it would mean type the Master Password every time you use CLI. There is no way I could think of to guarantee authenticity, confidentiality and integrity, at least without asking the user to remind another password, which makes no much sense.

**Comment by guillaumevincent** [comment]
@AndreaRe9 LESSPASS_MASTER_PASSWORD is used for CI system or bash script that require no prompt. It's a feature used by 2 companies at least.

I'm not going to remove the feature.
I try to understand the request from @almereyda.

**Comment by almereyda** [comment]
What can I provide from my side to ease the understanding, what kind of clarification would you need?

I can see very much that security considerations beyond my ability to foresee them may be advisable to look into.

**Comment by guillaumevincent** [comment]
I need to understand what the security issue is with the fact that the environment variable is not encrypted.

And I need to also understand what solution you imagine to mitigate the risk

**Comment by rstmsn** [comment]
Couldn't some nefarius software simply run a check for the 'LESSPASS_MASTER_PASSWORD' enviornmental variable, on the current users path? If it exists, the plain text master password can easily be exported and used in a brute force attack where only the site and login parameters are 'unknown'...

**Comment by guillaumevincent** [comment]
If you run lesspass with the cli you should not enter the master password. Cli will ask you the master password and it will not be saved.

But if you are in a Continuous Integration system you are passing secrets via env variable (see Travis, GitHub actions, etc)

But you should not save your master password in an env variable in .bash_profile for example.

**Comment by guillaumevincent** [comment]
I close, feel free to reopen if needed
LESSPASS_MASTER_PASSWORD env variable will be kept for backward compatibility reason for CI system that use lesspass
