### ISSUE TITLE
Option to delete the auto fill site feature

### ISSUE THREAD

**Issue by ghost** [lesspass/lesspass#504]
I am using custom names for "site" field and find it cumbersome that when I open the addon popup, it automatically fills the site field with a website I'm currently on and focuses on the "login" field instead. This requires me to manually re-focus to site field and delete it and replace it with something else. Please make it possible to have the "site" field blank by default. 

So basically, I would like to replicate the behavior of clicking the addon button on about:blank website without having to actually be on a blank tab.

**Comment by panther2** [comment]
I have about 200 passwords where I rely on the site field being autofilled. So a "blank" would destroy that use case and functionality completely, breaking LessPass for me and others who use LessPass the same way as I do.

What I suggest for use cases like yours is maybe a "delete button" next to the site field (or whrerever) that, when clicked not only removes that content but focuses to that field.

**Comment by jones137** [comment]
I know some people use it. There can just be an optional opt-in setting for blank site field.

**Comment by autonome** [comment]
This is a classic browser UI conundrum: Toolbar buttons can be either per-site and browser-wide, depending on the extension use-case, and it's up to the extension author. It causes no end of confusion. Source: Worked on Firefox core for over a decade.

For the record, I use it almost exclusively for use with the active tab. I'd love to have autofill or autocomplete of username field too.

**Comment by edouard-lopez** [comment]
With _default login_ set, it's the master password field that is focused. 

An option to choose the focused field (_site_, _login_ or _master password_) would allow to support @jones137 use-case and others:
* several login (personal, pro, family, etc.)
* emptying value (<kbd>Ctrl</kbd>+<kbd>A</kbd>, <kbd>Return</kbd>)
* adding custom suffix,
