### ISSUE TITLE
Threat/security model in the wiki

### ISSUE THREAD

**Issue by z0mbie42** [lesspass/lesspass#506]
Hi,
I just found lesspass and found the concept very interesting.

However I'm not sure to understand all the security implications and trade offs made.

So far the 2 big security risks I see are:

* If a master password is weak (not enough entropy, attacker with supercalculator...) then bruteforcing the master password allows to derive all the other passwords
* It's not possible to change the master password without changing all the passwords

I'm missing something?

Also I would love to see a page in the wiki dedicated to explain the security / threat model

Keep the good work!

Best regards,
Sylvain 🇫🇷

**Comment by guillaumevincent** [comment]
No you are totally right, we should document this in the wiki!

Do you have any time to add those 2 in the wiki page?

**Comment by z0mbie42** [comment]
Done in https://github.com/lesspass/lesspass/wiki/Security-model

Feel free to edit or close this issue if this is satisfying.

**Comment by guillaumevincent** [comment]
This is perfect and well written
Thank you
