### ISSUE TITLE
Minimise dangerous clipboard usage by using autofill where possible.

### ISSUE THREAD

**Issue by Lazerbeak12345** [lesspass/lesspass#508]
Hey, I'd like support for some degree of filling out username and password fields with (roughly) a single click.

This is how I've been using the app, thus far:

- I open lesspass
- copy and paste my username into the first field (I often don't remember assigned usernames. This and the next step aren't always needed)
- open lesspass
- enter my master password
- click generate
- copy password (dangerous: other apps and websites can read from the clipboard)
- paste password
- copy some other text so other apps can't read my password from the clipboard

I'd like to use it like this:

- I open lesspass
- enter my master password
- click generate
- click attempt autofill

I am aware that the second process isn't always guaranteed to work, but it's _much_ more secure.

**Comment by guillaumevincent** [comment]
By autofill you mean auto login ?
See https://github.com/lesspass/lesspass/issues/507

And auto login can be less secure than clipboard sniffing.

**Comment by Lazerbeak12345** [comment]
Yes, but you'd still have to enter the master password, so it shouldn't (unless I don't know what I'm talking about) be less secure.

**Comment by Lazerbeak12345** [comment]
But yes, that issue is what I'm talking about.
