### ISSUE TITLE
Every password starts with one of [aeiouy] characters.

### ISSUE THREAD

**Issue by tubelius** [lesspass/lesspass#51]
User powercf pointed this out in https://news.ycombinator.com/item?id=12889807

It seems like every password starts with one of these [aeiouy] characters. This makes me wonder if there's a faster way of breaking these passwords than brute force. I feel unsure about this algorithm.

**Comment by tubelius** [comment]
I guess the explanation is in https://github.com/lesspass/core/blob/master/index.js functions _getPasswordTemplate and _getPasswordChar. But I don't understand the purpose of these limitations. I feel they make the passwords weaker.

**Comment by guillaumevincent** [comment]
This transformation is not for security. The derivation transform a hash into a password.
The security of the algorithm is handle by encryptLogin method.

**Comment by tubelius** [comment]
But it would still be harder to crack the password if the first character could be any character allowed. What is the purpose of the character groups?

**Comment by guillaumevincent** [comment]
@tubelius you don't want to crack the password, you want to crack the master password. When you try to crack the master password, you already have the generated password. It does not change to have the first letter in a larger alphabet.

> This makes me wonder if there's a faster way of breaking these passwords than brute force. I feel unsure about this algorithm.

Can you be more specific ? What do you have in mind ?

**Comment by guillaumevincent** [comment]
@tubelius I close this one.
Does not hesitate to add evidence on the problem. 
For me it sounds more like a problem understanding how the tool works.

**Comment by tubelius** [comment]
This podcast actually explains the problem better: Security Now (MP3): 586: The BlackNurse Attack
https://overcast.fm/+B1Ll36KZc/26:38

I'd feel much more comfortable if these patterns did not exist in the passwords.

**Comment by guillaumevincent** [comment]
@tubelius it's fixed in version 2
See https://github.com/lesspass/lesspass/issues/88
