### ISSUE TITLE
MFA for generating passwords

### ISSUE THREAD

**Issue by emollusion** [lesspass/lesspass#510]
Hi!

For starters, I am new to the product and have found a good interest in it, i have been reading through most open and some closed issues, and I really like the idea of not storing sensitive data, and also store as little as possible of any data, stateless password manager is a really interesting concept.

But I keep ending up with the thought that this is never stronger than the master password.
It is good that you can create unique passwords for each site, one of the purpose of password managers.
Less good that the entire procedure, and key, is dependent on the safety of my master password, whether it is a random string of 14 chars or a simpler password.

This is kind of a concern, since some one could start to brute force their way into accounts.
Sure, with a random 14 char long string for master password, this will take some time, but take less time in the future and is still a possibility today.

To mitigate this, would it be possible to store an MFA?
No passwords will be stored locally or on the cloud.
I suppose this would make one dependent on the online service, or a self hosted service of lesspass, but I would find this reasonable for the features addition security wise.
The feature would in my mind be opt-in, so not breaking any previous data, and could also add to the security regarding the data stored online.

I am not completely sure this would work with stateless, I am not completely read up on the implementation of MFA in this concept but I think the thought is sound, so hopefully some one can say yay or ney?

In addition, if using MFA, the browser extensions should like the mobile version, perhaps support session based, so only have to enter the master password and MFA once per session, or 30 min, or something similar, a bit more user friendly I suppose, maybe this is a completely other feature request, please say so and I could raise another issue regarding this.

Thank you for reading!

**Comment by guillaumevincent** [comment]
In MFA are you thinking about an external key to extend of the entropy of the master password?
If yes it duplicates https://github.com/lesspass/lesspass/issues/376

**Comment by emollusion** [comment]
Perhaps... maybe it goes along the same line, or another approach.
My thought goes towards for example 2 step authentication using google authenticator and similar, to be able to access the password, my point being that lesspass is never safer then the master password, and using a password still possible to remember in ones mind feels rather unsafe, MFA would mitigate this.
If the MFA solution can be stored both on server and on local storage, without unlocking anything, maybe thats a way to go.
Kind of similar to using a private and public key. You have a private key to authenticate against the public key which you can copy to several instances, the private key should of course have a password.
My thought is that a MFA using for example Google Authenticator is a bit more user friendly than keys. Using a private key with password and public key would also keep the lesspass stateless, problem being that if you get your hands on the unit using lesspass, that unit probably have the private key stored and then it is just as safe as just using the master password again.

**Comment by guillaumevincent** [comment]
MFA or to be precise 2FA in case of Google Authenticator will be use to grab a private key on the server to be computed with the master password to generate your passwords.
You are loosing the offline mode no?

For me we should try to allow people to add extra entropy to the master password without loosing the offline mode or the no server way. > #376

**Comment by Andrew-Chen-Wang** [comment]
Hi @guillaumevincent I found this project pretty cool, but I'd like to know a couple of things. Correct me if I'm wrong, but this LessPass product is to have a master password that generates a password? Shouldn't this product not care what your password is? (Used to design a unicode version of libraryofbabel.info which is where I have the idea for GenBank decreasing database size).

**Comment by guillaumevincent** [comment]
Close in favor of #376
