### ISSUE TITLE
Option to change the url by default

### ISSUE THREAD

**Issue by JohanEkblad** [lesspass/lesspass#516]
Lesspass is great, thank you!
Just a quick question. Is it possible to somehow save my custom lesspass hosting url (instead of https://lesspass.com) and maybe even my sign in email address, somewhere in Firefox?

**Comment by guillaumevincent** [comment]
The main idea is to add this into the "Options by default" page in lesspass-pure.
Probably not very hard to do, do you want to create a PR for this ?

**Comment by edouard-lopez** [comment]
A starting point could be to look at the mobile app implementation:

https://github.com/lesspass/lesspass/blob/b81b62709ad1eb46b933314cd4b0ae08f9dea57e/mobile/src/settings/SettingsScreen.js#L47-L52

**Comment by guillaumevincent** [comment]
It will be fixed by https://github.com/lesspass/lesspass/commit/7750813ebe5a77c36dd7eb1dd63647b672f3dce3
Thank you
