### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by rugk** [lesspass/lesspass#517]
It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Comment by guillaumevincent** [comment]
Hello Rugk,
there is no GUI on desktop, only cli. Why should we use Flatpak ?
