### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [lesspass/lesspass#519]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, select the last "! @%"The rightmost part of the text is blocked, which may be an adaptation problem.
App version is 9.1.2, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/79106656-7e48d680-7da5-11ea-8f23-6f0c7f8adba0.png)

**Comment by guillaumevincent** [comment]
Thank you for reporting the issue

**Comment by guillaumevincent** [comment]
Tonight I updated paper (ui lib used by LessPass mobile) and I don't have the issue anymore.
I will produce a beta update to test it.
I just need to fix another unrelated issue in react-navigation before

![image](https://user-images.githubusercontent.com/943762/79280869-be957b00-7eb1-11ea-8fae-bf354f052607.png)

**Comment by franklinbill** [comment]
Thank you!

**Comment by guillaumevincent** [comment]
The version 9.1.6 beta should fix the issue: https://play.google.com/apps/testing/com.lesspass.android

I don't know when the beta will be available due to long review on the Android Store

![image](https://user-images.githubusercontent.com/943762/79391673-4216a100-7f72-11ea-8196-7915f4be947f.png)

Let me know if you can test this beta
Thank you

**Comment by guillaumevincent** [comment]
It will be soon in production, fill free to reopen if the problem is still here
