### ISSUE TITLE
Termux clipboard support

### ISSUE THREAD

**Issue by ElieKadoche** [lesspass/lesspass#520]
I use lesspass-cli on Android via [Termux](https://termux.com/). The option `-c, --copy` does not work.

Termux uses [`termux-clipboard-set`](https://wiki.termux.com/wiki/Termux-clipboard-set) via the [Termux:API](https://wiki.termux.com/wiki/Termux:API) to access the clipboard.

I looked at the existing issues but none of them seem to correspond to this problem. The solution is quite simple and I have implemented it [here](https://github.com/ElieKadoche/lesspass.git).

First time contributing, and not being sure about the validity of this enhancement, I did not create a pull request. Thanks for this amazing project!

**Comment by guillaumevincent** [comment]
Hello Elie,
can you create a pull request?
Thank you
