### ISSUE TITLE
Confirm master password

### ISSUE THREAD

**Issue by Iheb-Haboubi** [lesspass/lesspass#522]
This project is really great , thank you ! 

I think it would be great if the input form had an additional field to confirm the master password, especially if someone is using the CLI and they can't really see the password being typed, which can generate wrong passwords in some cases

**Comment by guillaumevincent** [comment]
Thank you.
What do you think about this pull request: https://github.com/lesspass/lesspass/pull/442 ?

**Comment by Iheb-Haboubi** [comment]
I see you've made some good progress there. 

However, i think that approach has some issues : 
- It's harder to implement and to use 
- user might mix up between different emojis or forget them
- It's prone to bugs as different terminals and different OS will not behave the same way so you have to make a relatively large test case
- you might have to install some icons in terminal, some users may not want any side effects in their environment

That's why i thought this approach can be more practical since it's platform-independent, easier to implement,  and it doesn't require any extra installation

But again, i value the effort you've put in that PR, since you've already started working on it.

**Comment by panther2** [comment]
@guillaumevincent 
In case you plan to implement this additional feature into any GUI please consider to implement it as an option. I for sure would not welcome this additional complexity. I am totally happy with the symbols to verify the corectness of the mater password. Thank you.

**Comment by guillaumevincent** [comment]
@panther2 yes I never think about adding an extra field in the UI, if it's what you think.

@Iheb-Haboubi the pull request is not complete. But having a similar approach like the fingerprint on the cli will solve your issue.

**Comment by guillaumevincent** [comment]
I close with #442 in mind
