### ISSUE TITLE
Similar "Use my master password" android flow in chrome extension

### ISSUE THREAD

**Issue by canercandan** [lesspass/lesspass#525]
Would it be possible to add a similar setting in the chrome extension as the one I am using on the android app.

The setting I am referring to is called "Use my master password" and allows the user to avoid sending a plain text master password during the login.

Although there is this "Encrypt the master password" link right below the login password field in the login form, I already forgot clicking on it several times, ending up using my plain text master password to login to the lesspass server and I had to rely on changing my master password to avoid being compromised.

One option could be to add this setting within the "Settings" screen along with the default login field and password generating related options.

Thanks all.

**Comment by guillaumevincent** [comment]
Yes we should do this!

**Comment by guillaumevincent** [comment]
duplicates #420
