### ISSUE TITLE
Security of Lesspass

### ISSUE THREAD

**Issue by bettyvschmartz** [lesspass/lesspass#526]
Hi,

I am familiar with Master Password by Maarten Billemont and I have just come across Lesspass. I like the look of Lesspass as it improves upon UI limitations of Master Password which doesn't store profiles and can't help with sites that have strange password requirements. 

However, I also came across this https://github.com/lesspass/lesspass/issues/88 where you were massively reducing password entropy. Obviously security is paramount in a password management solution and this doesn't look great. That said, if it has been addressed then that's fair. How has it been addressed?

Also, is the software an implementation of Maarten's idea and algorithm or is it something different?

-- BVS

**Comment by guillaumevincent** [comment]
Hello,
You have the details here https://github.com/lesspass/lesspass/wiki/Overview-of-Password-Generation

**Comment by guillaumevincent** [comment]
> How has it been addressed?

We fixed the bug in less than one week with LessPass version 2 (see #89). Basically LessPass v2 is the algo described in the video: **The horror of LessPass**. Then we kept LessPass v1 and v2 in the app during 3 months with v2 by default (see https://lesspass.github.io/v1/#/). We finally remove LessPass v1.

If it answers your question feel free to close this bug

**Comment by bettyvschmartz** [comment]
Thanks for the overview and responding so quickly. That answers the concerns. 

One final thing, you acknowledge in your article that you based Lesspass on the genius idea by Maarten Billemont, wouldn't giving credit that Lesspass is based on that idea, be fair? Unless it is credited somewhere?

-- BVS

**Comment by guillaumevincent** [comment]
I talked about Maarten Billemont in the podcast, and in some presentations.

but yes sure, @lhunath Maarten can I add a link to your profile in the Readme of this project?

**Comment by lhunath** [comment]
@guillaumevincent Feel free to reference us via masterpassword.app.

**Comment by guillaumevincent** [comment]
Perfect I will thanks
