### ISSUE TITLE
Hall of Shame

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#527]
Hello,
I have had the idea for some time now of a simpler version of LessPass without a connected version. The connected version was introduced to talk about the bad practices of certain sites on the passwords they authorize.
These bad practices "force us" to have LessPass Database. Which is a shame for a stateless password manager.

I don't know how yet, but I would like to have a list of popular sites with poor password management practices to facilitate the user experience on LessPass.

For example: Change the color of the icon to red to say that LessPass does not work on this site. Or a way to generate a tweet to encourage web site to change.

**Comment by fulldecent** [comment]
This issue originated at #495.

Apple has taken on the scope of this issue so I recommend it is removed from our project's scope.

Recommending to close this issue in favor of #534.

**Comment by guillaumevincent** [comment]
I agree

thank you @fulldecent
