### ISSUE TITLE
Custom character class to handle bogus password policies

### ISSUE THREAD

**Issue by elgow** [lesspass/lesspass#528]
Some sites (looking at you Equifax) have odd policies for password character classes, e.g. a restricted set of special characters from which at least one must be used. This totally breaks LessPass because the special chars can only be turned on or off in full, not piecemeal. 

How about adding a "Custom" character class, off by default, that could be activated and populated with whatever oddball set the site demands? The specified set could be stored in the DB as part of the password metadata. This would let individuals work around bad password policies.

An added feature might be collected settings for sites that would otherwise be in the "Hall of Shame". The site name could be checked with that list and the custom character classes pulled up. Upper, Lower, and Numeric would be either on or off, and there would be an explicit list of special characters. This would require some centralized curation, which might be a problem, but the main point would be that once settings for a site were put in place they could never be changed.

**Comment by elgow** [comment]
Recent experience has shown that the passwords generated by lesspass do not change sufficiently with changes in length or password version to work around difficult password policies.  I had a problem trying to use lesspass to create a password that can satisfy a  policy which requires at least one of the characters in the set  `!@#$%^&*()-_+={}[]:<>.?/`  but disallows the set  `*~\|;"',`.   For my input of site name, user name, and secret, it took many tries to get a password that would satisfy the policy, and the settings were so odd that it's essential to record them in the DB. 

Changing password length is relatively ineffective at generating passwords with content different enough to get lucky on the special characters. Notice the similarity in content, across the generated passwords, especially the persistence of the `\`, and note that only one of nine generated passwords satisfies the policy. 

```
for L in {16..8}; do  LESSPASS_MASTER_PASSWORD=baz lesspass -L $L foobar barfoo ; done;
`Mu~Of\#u&GnS7v(
+`MOYf\5#u&zGnv
`fMO%f\#u0&GHn
`6MpO_f\#Au&G
`MOfm6%\#uD&
z`<MPOf6\#u
1`TM{Oef\#
`]3yMIOf\
4`MOK:bf
```

Changes in password version are better, but the banned characters still occur in over half of the generated passwords in this test. 

```
for C in {1..20}; do  LESSPASS_MASTER_PASSWORD=bar lesspass -C $C foo bar; done;
t,lG!P6C>W_%VGzD
%C'DOpe6oBb>U3Fp
lpmUm4'EWcLh::~#
$bi}YB9}hW0?9(m2
9bM<L4K.jVhaSw(v
X.r0/jj>OJ^l9z|/
S5O"4YbdVokW180L
Z+K9nr8Pv4MZJ5Vt
=Y1/<$m[|e.W[TkX
8cob}QlY4`g|wZV%
EIW{p7XleQ-.nM4_
59[muoOY5e?{ewG-
f|8Op\r#Lv8b|h~k
@>1GjMr}*2E0ei3U
n@=pZYXcJ|T3r2$N
I*K7lHqP!f8^=GdK
wq|wixq4/rO.rh;J
Y+YmY.2nI~&E8nAR
b%E2Ej3GN@/G'^0K
y'2d<gAhCS&DFMv"
```
The only sure way to deal with a password policy like the one above, which is the actual policy for my employer, is to allow for inclusion/exclusion of specific characters. This would be better for users in that they would not need to remember idiosyncratic combinations of password length and version, but could simply enter the included or excluded characters copied directly from the password policy. 

Please add the feature of specifying included or excluded characters. As it stands I will need to wrestle with lesspass again when my current password expires, or else give up using lesspass for this password.

**Comment by guillaumevincent** [comment]
I think we shouldn't spend too much time implementing features for sites that make the life of password managers difficult. Rather, these sites should be encouraged to change and apply good practices.

One of the features of LessPass is its simplicity. Implementing this kind of functionality does not make the tool simpler. It will make the interface more complex. It will also slightly reduce the security of the master password because of a stupid rules site.

As a workaround, for those site, just remove the symbols and add a known symbol at the end. Then tweet, and put them in hall of shame list.

I close because I will not implement it

**Comment by elgow** [comment]
Simply put, it is utterly unrealistic to expect all of the sites with bad policies to alter them. For small restrictions in special characters such as the actual example I cited it's likely that the site infrastructure somehow dictates the policy.  They would need to change their infrastructure to make it work with LessPass. The notion that even a small fraction of the sites would do that because of the LessPass Hall of Shame is, I'm sad to say, laughable. 

I certainly understand your concern about UI simplicity, but your advice above that users should generate a password with LessPass and then manually alter it does not result in a usable system. The user has to check the allowed characters every time and remember what character(s) were added, and they have to do this w/o the help of the LessPass DB. 

I think LessPass is a brilliant concept, but due to this issue I cannot reasonably rely on it to handle all of my passwords. At present LessPass does not appear in the "Best Password Managers" articles for CNET, PCMag, Tom's Guide, etc. and with this problem you can be sure that it never will. I hope that you will come around on this, because the many sites with bad password policies are not going to fix it for you.

**Comment by guillaumevincent** [comment]
> LessPass Hall of Shame is, I'm sad to say, laughable.

I was more thinking about Apple, not us. We are too small to force anybody.

> expect all of the sites with bad policies to fix them

Not all, only site that force you to add a symbol but not all symbols. I don't know much.
How many site are concerned?

How do you handle site A refusing `*~\|;"',` and site B refusing `@!/\` ?

Did you expect a user saving this in a password profile in LessPass Database? Or did you expect LessPass to save a default password profile per site?

The user experience will be degraded. If we do nothing, the user experience will be bad because LessPass can't handle web site with very stupid password rules. If we implement the feature, user experience will become awful and we are going to loose our users.

In both case this is not good. But by doing nothing I don't loose my energy working on fixing other's bugs.

Last thing, LessPass users are here because they love the simplicity, and the no sync functionality.
If you need to handle all password rules, and this important for you, then LessPass is probably not for you.

So I'm sorry, my answer will not help you

**Comment by elgow** [comment]
Hi,

I've been editing my comment above to reflect a better understanding of your proposed usage of LessPass in the face of bad site password policies. I'd appreciate if you could read through it to get my better considered statement of what I see as the problem.  I'd say my concern is best expressed by this:

"The effect is that the bad site policy forces users to have slightly less secure passwords so LessPass then forces them to have MUCH less secure passwords. This is counterproductive."

I cannot claim to have cataloged all of the sites with character restrictions in their password policies. I did cite two examples of real sites. My employer's site is obviously of great importance to me. Equifax is of importance to millions of people. The best source of a comprehensive list would be your Hall of Shame. I would be very curious about what sites have policies that can be satisfied using the LessPass options vs. sites that merely exclude a few special characters. My experience has been that the latter are common and I've never seen one that disallows upper case, lower case, or numerics in the password. What purpose to these options really serve? 

What I propose is indeed to allow the user to enter a limited string of characters that will be excluded from the password and to store that string in their DB entry for the site. The UI change would be the addition of one text field whose content is completely optional. If it is empty then LessPass would work just as it now does, so no user would face any disruption. Those who chose to use the field could get strong, working passwords for any site generated by LessPass.

**Comment by guillaumevincent** [comment]
So for Equifax for the cli it will be something like:

    lesspass my.equifax.com email --symbols "!@$*+-"

Am I correct ?

And it will get symbols in pool of char `"!@$*+-"` instead of the whole list of symbols

**Comment by guillaumevincent** [comment]
I still don't want to complexify the UI, but will see, maybe there are a lot of site where we need a custom set of symbols

**Comment by elgow** [comment]
Thank you for looking again at my concern. The list of excluded chars is generally shorter than included chars, so I'd advocate something like 

lesspass my.equifax.com email --exclude "!@$*+-"

That said, your CLI example does expose one issue, (though only for users sophisticated enough to use the CLI). The set of special chars consists mostly of symbols that have syntactic or semantic meaning in the shell. That would lead to things like 

lesspass somesite.com --exclude '"' --exclude "'"  

in order to exclude both `'` and `"`.  From my experience with shells and some quick testing, I think that the quotes are the only real problem chars. Even so, it would require that the `--exclude` argument be able to be repeated.

**Comment by elgow** [comment]
Thank you for adding the --exclude feature to the CLI.  The real value would come with extending it to the other interfaces and the DB. I noticed today that ebay does not allow the "/" character in passwords. I think that, like me, your users will keep running into sites for which lesspass does not work properly until this feature is completely integrated. 

One way of making the feature much more useful and user friendly would be to keep a central registry of excluded characters for sites. It could either be done as part of the github repo or as a separate DB. As long as the number of excluded chars is limited to, say, less than 10 then the DB could be safely maintained in a crowdsourced manner, perhaps w/ moderation of changes to existing entries.  If the lesspass app suggested character exclusions for sites automatically then it would generally just work, w/o any action required from the user. This would provide the simplest UI and trouble-free usability to make lesspass easier to use than any other password manager.

**Comment by elgow** [comment]
I just hit the specal character issue again. This time it was on the CenturyLink site.

> Sorry, the new password you've entered contains a special character that isn't allowed. Please try again. Valid special characters include ! @ ^ & * # $ % ( ) + ~ and Invalid special characters include _ = ` { } | [ ] : " ; ' < > ? , . /

 Since the have ~50M subscribers I'm guessing that some other LessPass users have hit this also. Is any solution in the works?

**Comment by tygerlord** [comment]
Uncheck %!@ 
and if needed add manually an authorized special character.

**Comment by omarali-me** [comment]
Before I had discovered the --exclude option, I used to just disable using special characters and just append the password with !!! 

Since, it's mostly allowed to use an exclamation mark and I've already made up my mind that I"ll append any passwords I generate without special characters with a triple !, it works for me.. is it 'perfect', no.. But, definitely worked.
