### ISSUE TITLE
Dump database for local backup as CLI commands

### ISSUE THREAD

**Issue by elgow** [lesspass/lesspass#529]
It would be very nice to have a way to get a local backup of the contents of my lesspass DB. One simple way to go about this would be to dump the DB as a bunch of CLI commands like 

      lesspass -d -L 20 -C 3  https://some_site.com username

and so on, so that the settings for password generation would be preserved in a usable way in a local file. This would provide a local fallback in case the DB site became unavailable due to network issues, etc.

**Comment by guillaumevincent** [comment]
Hello,
I don't understand correctly. I see 2 features in your request:

## first backup and restore password profiles in CLI

You would like a way to save password profiles saved in LessPass Database with the cli:

    lesspass backup

It will produce something like `20200519-lesspass-database.json`

And a command to load the password profiles backuped like:

    lesspass restore 20200519-lesspass-database.json

## use cli in conjunction with LessPass database

    lesspass login
    lesspass search mysite | lesspass

I don't understand the local fallback

**Comment by elgow** [comment]
Hi,

I'm sorry for my unclear explanation. What I am proposing is a way to dump the contents of the online DB to a local file, in line with your "lesspass backup" example below. I was further proposing that the format for the dumped file be a series of lesspass CLI command lines with the options set to capture the saved settings for each site. My reasoning was that the CLI has a syntax for representing all of the settings in the DB, and the saved CLI commands would be both human readable and usable on their own.

Some command to dump the DB would be needed, e.g.

        lesspass --dump

which would produce a sequence of CLI commands, one for each site in the DB. So I might get output from the command above like

lesspass -C 2 -L 10 https://site1 username
lesspass -n -L 8 https://site2  username2

I could directly use any of those commands to run the CLI to generate a password if for some reason I could not access the online DB.

Given the above feature, one additional feature that would be useful would be a way to load a site's settings from the CLI

        lesspass --save -C 2 -L 10 https://site1 username

would update the DB with the settings given in the CLI command. With that the saved CLI commands could be used to restore the DB.


I hope this is a clearer explanation of my suggestion that the CLI command format could provide the syntax for a DB dump. I use both CLI and the browser plugins, so the CLI is a very natural representation of the settings for me.

Thank you for taking the time to follow up on this and even more for creating lesspass,

  Ed


________________________________

**Comment by guillaumevincent** [comment]
IMO the format of the dump should be easy to read for a computer. It's better to have a dump in json, than a dump in plain text. If we update the cli API, the migration will be harder, because we will need to parse the file.

**Comment by major0** [comment]
I believe this previously came up in #154

**Comment by guillaumevincent** [comment]
`lesspass --save <path>` or `lesspass --save`

and

`lesspass --load <path>`

are in beta in LessPass cli version 10.1.0
