### ISSUE TITLE
Has there been anything like a security Audit or something?

### ISSUE THREAD

**Issue by fourtytwo** [lesspass/lesspass#53]

**Comment by maxime1992** [comment]
I was wondering too ! I think this is an awesome alternative to traditional password manager but how robust is it ? Looking forward some answers about security. :)

**Comment by guillaumevincent** [comment]
We are looking for scientists to help us to write a white paper.
Security is always a dangerous field, but audit are welcome

**Comment by guillaumevincent** [comment]
I close this one,
If a scientist want to help us on this.
I close this bug because the request is still in the blog posts.
