### ISSUE TITLE
Nginx example config

### ISSUE THREAD

**Issue by gkl1368** [lesspass/lesspass#530]
How to config new lesspass docker with nginx? Can you give a nginx example config file? Thanks.

**Comment by guillaumevincent** [comment]
Hello @gkl1368 ,

what do you mean by 

> new lesspass docker 

The new containers from https://github.com/lesspass/lesspass/tree/master/containers will use `httpd` not `nginx`

**Comment by guillaumevincent** [comment]
I close

Feel free to create your own container and ask for some help if you encounter some issue.

you can look at the httpd conf [here](https://github.com/lesspass/lesspass/blob/master/containers/webserver/httpd-ssl.conf#L127-L168)
