### ISSUE TITLE
fine control of passwords gone

### ISSUE THREAD

**Issue by durkis33** [lesspass/lesspass#533]
Hello Guillaume!

Please help, the extension is no longer displaying the controls for stupid passwords. I have the buttons for turning off numbers, letters and special characters but I have no way to control the number of these characters in the password as I used to and no control panel button as there used to be. Tried to take a screenshot but you're too good a programmer, I guess, and Lesspass wouldn't let me.

I am on firefox. login is lp@durklis.33mail.com. Have dropped a tip in the jar.

thanks,

Stu

**Comment by guillaumevincent** [comment]
Hello @durkis33,

nothing change on LessPass side.

What do you mean by :

>  I have the buttons for turning off numbers, letters and special characters but I have no way to control the number of these characters in the password as I used to and no control panel button as there used to be

You can't control the number of chars for a specific set of characters.

**Comment by durkis33** [comment]
really? i was sure that was a feature. perhaps it's just the increasing
level of stupidity in password requirements that has me confused. This one
had a subset of characters that had to be used seven times. (!) I am a
fuzzy thinking artist so its entirely possible i am wrong. Looks like i was.

Thanks for getting back to me, love your project

stu

**Comment by guillaumevincent** [comment]
Hello @durkis33,
yes the number of element for each rules can be from 1 to password length minus number of other rules. The number is random. You can only choose if you should include a char in those rules or not.
I close this one
Thank you for your support :heart:
