### ISSUE TITLE
Feature request: More seamless password generation

### ISSUE THREAD

**Issue by FranzSkuffka** [lesspass/lesspass#535]
I was thinking that the current workflow is cumbersome:
- I have to type the email twice
- I have to manually open the popup
- I have to manually paste my generated password

It would be great if lesspass had some means of understanding the current page and integrating more tightly with the existing UI. That could mean.

- cool: copying the email address from the input field when opening the popup. We can use cues like name, type, id
- even cooler: it replaces the password input of the website with the master password input and adds a little tooltip with the emoji hash etc. All I have to do is type my e-mail and master password (given I can use the default settings)

What do you think?

**Comment by guillaumevincent** [comment]
In term of security I think it's not a good idea to copy the master password in the input field of the web site.
But an auto login feature could be something that will solve your issue.

Something like:

 * ctrl + shift + L open the popup
 * fill the login with you email
 * fille your master password
 * hit enter

it will find an email field in the page, then find a password field in the page and fill them automatically.

**Comment by guillaumevincent** [comment]
I close in favor of https://github.com/lesspass/lesspass/issues/449

**Comment by FranzSkuffka** [comment]
Thanks for the reply. I am afraid I did a poor job describing what I meant:

![image](https://user-images.githubusercontent.com/7485959/87727854-28c7ff80-c7c2-11ea-8aff-b6f90ec67ef0.png)

However, I assume that we do not want the events from keystrokes of the master password to touch the DOM of any site, because any site might be compromised.

**Comment by guillaumevincent** [comment]
Yes exactly 

Are we agree that auto login will solve your 3 points?
