### ISSUE TITLE
Add the possibility for the user to share a password profile file instead of using a database

### ISSUE THREAD

**Issue by biancarosa** [lesspass/lesspass#536]
I know this is a very random idea that would probably involve a lot of refactoring to allow the password profile to come from a file instead of a postgresql database, but I was thinking that it could be a interesting feature since I can use the lesspass website completely offline, but I cannot have a completely offline access with the benefits of the connected version.

It'd also allow the person to sync the profile using their Dropbox | Google Drive | iCloud | whatever software they already use.

Thoughts on it?

**Comment by guillaumevincent** [comment]
Hello @biancarosa,
a sort of import password profile file and export password profile file feature ?
And password profiles can be save in the local storage of you browser.
Something like that?

**Comment by biancarosa** [comment]
Yeah, something like that! 

I'm sure that probably we should tackle #185 before adding it, though, as it'd add more complexity and encrypting the profile is probably more important.

**Comment by guillaumevincent** [comment]
Ok so I close in favour of https://github.com/lesspass/lesspass/issues/529

duplicates: #529
