### ISSUE TITLE
Must Login WIth Each Use

### ISSUE THREAD

**Issue by jasonbunnell** [lesspass/lesspass#539]
Using Lesspass 9.1.9 Extension for Firefox.  Requires login each time.  Have been using for over a year but with the latest update I need to re-authenticate for Lesspass to populate saved fields.

**Comment by guillaumevincent** [comment]
Oh sorry for this,
let me fix this as soon as possible

**Comment by guillaumevincent** [comment]
It will be fixed by https://github.com/lesspass/lesspass/commit/7750813ebe5a77c36dd7eb1dd63647b672f3dce3
Thank you
