### ISSUE TITLE
Get Domain without Subdomain

### ISSUE THREAD

**Issue by finuex** [lesspass/lesspass#540]
- Case:
  1. "https://web.facebook.com/..."
  2. "https://mbasic.facebook.com/..."
- Expected:
  1. "facebook.com"
  2. "facebook.com" 
- Reality:
  1. "web.facebook.com"
  2. "mbasic.facebook.com"

current solution:
> change the address manually

Related discussion:
#45, #148, #199, #258 

Suggestion:
> add a checkbox (Users can specify whether they want subdomains can be included or not)

**Comment by guillaumevincent** [comment]
Hello,
this is a nice idea, but how do get primary domain name ?

what about: `bbc.co.uk` for example ? `co.uk` is a tld

do we want to store common tlds in order to be able to return `bbc.co.uk` ?

**Comment by finuex** [comment]
Hi,
> what about: `bbc.co.uk` for example ? `co.uk` is a tld
> do we want to store common tlds in order to be able to return `bbc.co.uk` ?

maybe that can be the solution. or using this? 
domain = `["bbc","co","uk"]` //split the domain
if the last 2 (domain[domain.length-1-1]=="co|ac|...") are "co","ac" or the other, than primary domain name is from the last 3 if not,then its from the last 2.

I'm not very familiar with domain names, so can this be a solution?

**Comment by guillaumevincent** [comment]
I'm not familiar with DNS neither. I just remember trying to import a big file (>2Mo) with all TLD just to be able to return the primary domain name. But it was 4 years ago.

> if the last 2 (domain[domain.length-1-1]=="co|ac|...") are "co","ac" or the other, than primary domain name is from the last 3 if not,then its from the last 2.

If we cover most of the domain names, then yes, I think we can implement this feature.
We can look at 1m top sites and see how many are using ccTLD

**Comment by claudiusraphaelpaeth** [comment]
As i just faced this issue - lesspass not shorten the url to the name.domain-part - i'd like to know:

- how a modular extension to lesspass shall be designed
- what a subset allowing for use in all versions/editions of lesspass (win/chr/ios/and/cli) would be

... basically: @guillaumevincent could you provide an overview how you would like to see it implemented?

**Comment by guillaumevincent** [comment]
The best way to do this, is to add an option "keep only domain name" and use https://publicsuffix.org/list/public_suffix_list.dat
The only issue I see is on the web where downloading public_suffix_list.dat is not good

**Comment by claudiusraphaelpaeth** [comment]
I was thinking of using REST API calls provided by IANA/WhoIs, as it responses only with valid TLD/ccTLD and accredited registrar for the given domain is also provided, which could be used for a follow-up request for registrar-specific 2nd-level TLDs, e.g. .co.uk .

If that makes sense?

**Comment by guillaumevincent** [comment]
We need to keep the offline mode

I'm not sure I understand the question so, I'm sorry

**Comment by claudiusraphaelpaeth** [comment]
Using a downloaded curated list for the offline-mode surely is the way to go.

This list can be derived from the official Whois-Databases.

My thought was especially targeted at the Chrome-AddOn and the CLI-versions of lesspass, which can easily make use of the given REST-APIs when online and cache the response and therefore store an always up-to-date curated list.

**Comment by guillaumevincent** [comment]
In the next version in the web extension you will have a checkbox to test it live

![image](https://user-images.githubusercontent.com/943762/113458950-5b7b5c00-9414-11eb-809c-01f48f27c07a.png)

It will remove tld from a list of the most popular website.
Feel free to test it if you can
