### ISSUE TITLE
Document all client-server API methods

### ISSUE THREAD

**Issue by ogarcia** [lesspass/lesspass#542]
I don't know if this documentation already exists, but I couldn't find it.

I think that would be a great idea have a good documentation of all methods of LessPass server API. Maybe a single [Swagger][1] could be enough to know how it works.

[1]: https://swagger.io/

**Comment by guillaumevincent** [comment]
All endpoints are tested here : 

 * https://github.com/lesspass/lesspass/blob/master/containers/backend/api/tests/tests_passwords.py
 * https://github.com/lesspass/lesspass/blob/master/containers/backend/api/tests/test_auth.py

I plan to change and break things probably in the future.
Documenting is time consuming, I'm not sure I will have the time to maintain doc and make the api retro compatible

Can you explain me your need regarding the API?

**Comment by ogarcia** [comment]
> Can you explain me your need regarding the API?

I have a [small dumb cli client][1] written in Python to obtain all values from server :smile: 

In the other hand there is a [go server implementation][2] that [recently I fixed][3] to support the last breaking changes.

With a Swagger file (or similar) that have sample request by method is more easy to implement the changes.

[1]: https://github.com/ogarcia/lpacli
[2]: https://github.com/tuxlinuxien/lesspassgo
[3]: https://github.com/tuxlinuxien/lesspassgo/pull/4

**Comment by guillaumevincent** [comment]
Ok so you are doing a server

The actual API should stay like this, but I can't promise. I plan to work on the server, and I may introduce some breaking change :woozy_face: 

Do you want to be notified in advance ?

I close because I didn't plan to document the actual api for now.
But you can look at the test api folder to see code as a living doc.

**Comment by ogarcia** [comment]
> Ok so you are doing a server

No, a client, the server is a @tuxlinuxien work :-D

> The actual API should stay like this, but I can't promise. I plan to work on the server, and I may introduce some breaking change

In this case I suggest you to use API versions. At this point you have several strategies to do this, but the easy one is use the /api/v1/endpoint, /api/v2/endpoint... etc.

Using the URL strategie you can reuse pieces of code and maintain backwards compatibility. And can have /api/endpoint (without vX in URL) pointing to latest version.

> Do you want to be notified in advance ?

If you remember, simply put me a line in this ticket. But if not, no problem, I will notice when my client breaks :wink: 

> I close because I didn't plan to document the actual api for now.
> But you can look at the test api folder to see code as a living doc.

Ok.
