### ISSUE TITLE
encfs + lesspass

### ISSUE THREAD

**Issue by gimzmoe** [lesspass/lesspass#543]
I've been using "CLI" lesspass with encfs
`encfs --extpass="lesspass $clear $USER" $crypt $clear` 
previous to the new ascii outout (very clever) this worked fine to query for the master password and return the lesspass for encfs.  The new behavior appears to include "Master password: `random-icons` Password" as the output.  

Perhaps it was intentional, or an unintentional side-effect, I'm still trying to figure out what exactly changed.

**Comment by guillaumevincent** [comment]
Hello,

it was intentional, I will update the documentation

Could you add a `--no-fingerprint` parameter in your cli to avoid the icons ?

**Comment by gimzmoe** [comment]
that's what was missing, thanks, all better now.
