### ISSUE TITLE
Clipboard should have expiration date

### ISSUE THREAD

**Issue by HerrBert233** [lesspass/lesspass#545]
Hi,

currently, the main source of password transfer from the extension or app to the website is the clipboard.

Here, someone was worried as well about the security of this method: https://github.com/lesspass/lesspass/issues/508

He said something interesting. To reduce the risk, he performs the following step after password has been transferred:
"copy some other text so other apps can't read my password from the clipboard"

I think this should be automatized. There should be a limit how long the password stays in clipboard (e.g. 10 seconds, maybe configurable) then the clipboard is cleared. A similar feature is present on [KeePass](https://keepass.info/features.html#lnkclipboard)

P.S. I am so glad you exist and actively develop this addon! I used this type of password management already since a long time, when it was offered by "Password Hasher". Then the addon got abandoned and I had to use "Phashword" which recently got abandoned, too, then I found you, and the community is quick and alive! Hope for a long future!

Best,
Herbert

**Comment by guillaumevincent** [comment]
If you find a way to do this on the web, I would be happy to integrate this feature.

But see the sandbox folder
