### ISSUE TITLE
Alternative installation without docker ?

### ISSUE THREAD

**Issue by caywin25** [lesspass/lesspass#546]
Hello,

Congratulations for your work. 
Lesspass is an excellent software.
If I want to host my own instance, I could read that it has to be done via Docker.
Is there a dockerless installation please?
Thank you

**Comment by guillaumevincent** [comment]
Hello,
do you have an OS in mind ?

**Comment by caywin25** [comment]
Yes, openbsd :)

**Comment by guillaumevincent** [comment]
Hum, one server I don't know very well.

For the server you will need apache, python 3 and https certificates. What will be the best outcome for you?

I can document the installation pieces in the wiki and you can help improving the doc

**Comment by caywin25** [comment]
Hello, 

Sorry for the late response.
Ideally for me it would be a lesspass installation on a virtual machine and then I have an upstream proxy (nginx) to listen on ports 80 and 443.

Is this possible?

**Comment by guillaumevincent** [comment]
The production is using containers. I don't plan to work on creating another installation for the near future.
Feel free to try to install django directly by cloning this repo and changing the env variable to use sqlite.
Then run gunicorn and proxy pass with nginx.
There is a lot of info on google "gunicorn nginx django"
see django doc also: https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/
I close
