### ISSUE TITLE
How to explain Private vs. connected mode ?

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#55]
> https://twitter.com/edouard_lopez/status/795986826653790208
![explain private vs connected mode](https://cloud.githubusercontent.com/assets/1212392/20101576/e4ae0648-a5c2-11e6-92a2-ef2614888730.jpg)

`MP`: master password

| Private | Connected |
| ---------- | ---------- | 
| No storage | Less to memorize (storage) |
| Only local | Suggest `site`/`login`/`options` |
| Ready to use | Save password Profile |
| Master password stays local | MP stays local |

**Comment by edouard-lopez** [comment]
| Private | Connected |
| ---------- | ---------- | 
| No storage | store on (your) server |
| Master password stays local | MP stays local too! |
| No external communications | Get `site`/`login`/`options` |
| Ready to use | Connect to save passwords profiles |

**Comment by guillaumevincent** [comment]
@edouard-lopez we include this in the wiki and close this one ?

**Comment by edouard-lopez** [comment]
user journey to use connected version
![private to connected mode user journey](https://cloud.githubusercontent.com/assets/1212392/20605575/5ec0d306-b26c-11e6-83ce-af8a58b9726b.jpg)

P.S.: this allow to reference the image in the wiki.
