### ISSUE TITLE
Strange delay when fetching the site name

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#550]
Starting from this morning I experience a strange delay when LessPass Extension catches the site name.

See in this image how the site name stays empty:

![lesspass](https://user-images.githubusercontent.com/20812775/90951059-8dc4e400-e457-11ea-93fd-8ccd0383c307.png)

It takes about minimum 15 seconds until the site name finally appears in the LessPass site name box, instead of appearing instantly - as I am used to.

I am running Chrome latest stable ( 84.0.4147.135) , LessPass 9.2.0 on Windows 10.64, 32 GB RAM. Only Windows Defender as AntiVirus.

I never experienced this behaviour before. I have removed every extension (I only run a few anyway) - but the problem persists even when LessPass is run exclusively.

Any ideas?

**Comment by guillaumevincent** [comment]
If you click again on the web extension, does the site appears instant ?
Or it's every time?

**Comment by panther2** [comment]
@guillaumevincent 

I will test this as soon as the issue occurs again.
The problem here is that the situation described does not occur every time.

It happens somehow arbitrarily. Until now I was not able to figure out possible reasons.

I have checked background processes, RAM-usage etc. when it happened, but I have not been able to identify anything strange or unusual until now.

**Comment by panther2** [comment]
@guillaumevincent I am closing this issue for now. It occurred only once again with Chrome 84 and never again with Chrome 85 - at least until now.
For now I am suspecting a temporary Chrome issue behind it.
I will reopen the issue in case I notice that behaviour again.

**Comment by guillaumevincent** [comment]
Ok thank you for your tests
