### ISSUE TITLE
[iOS] uncheck checkbox white

### ISSUE THREAD

**Issue by MalteKiefer** [lesspass/lesspass#553]
When you uncheck an option for the password generation, there is no checkbox it is white:

![image](https://user-images.githubusercontent.com/59220985/92190539-bf7b7900-ee61-11ea-9adc-db4d8791f597.png)

**Comment by guillaumevincent** [comment]
apparently it's by default on react native paper (lib I use for the apparence)

https://callstack.github.io/react-native-paper/checkbox-ios.html

I'm wondering how a checkbox is displayed unchecked on safari

**Comment by gregfenton** [comment]
You have the option to use React Native Paper's `Checkbox.Android`.  That's what I've ended up doing to ensure consistency on all platforms (you get the "Android" design/behavior on all platforms...).  See https://github.com/callstack/react-native-paper/pull/2116 .

**Comment by guillaumevincent** [comment]
Thank you @gregfenton 
I appreciate your help !

Indeed it's very simple
