### ISSUE TITLE
Show account information when connected

### ISSUE THREAD

**Issue by MalteKiefer** [lesspass/lesspass#555]
When I logged me in, there is no way to see which account I am using.
Maybe you can show some information:

![image](https://user-images.githubusercontent.com/59220985/92190837-6a8c3280-ee62-11ea-8183-ff53279fbf80.png)

**Comment by guillaumevincent** [comment]
Thank you for all your tests, I will try to fix those issues

**Comment by guillaumevincent** [comment]
Fixed by https://github.com/lesspass/lesspass/commit/7662ff61c4866bf2f59c18062535376dcff3f4ba
Will be soon in production
