### ISSUE TITLE
[cli] ModuleNotFoundError: No module named 'termios' on Windows 10

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [lesspass/lesspass#556]
On Windows 10, with python 3.7.9 installed through pyenv-win, lesspass installed with pipx, and MSYS2 bash, I had the following exception:
```bash
Traceback (most recent call last):
  File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\laure\.local\bin\lesspass.exe\__main__.py", line 4, in <module>
  File "c:\users\laure\.local\pipx\venvs\lesspass\lib\site-packages\lesspass\core.py", line 13, in <module>
    from lesspass.fingerprint import getpass_with_fingerprint
  File "c:\users\laure\.local\pipx\venvs\lesspass\lib\site-packages\lesspass\fingerprint.py", line 6, in <module>
    import tty
  File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

I searched through the issues but could not find a duplicate. Other people seem to have no problem running lesspass cli on Windows so maybe there is something wrong with my python setup ? A search online confirms that 'termios' is not supported on Windows though.

**Comment by guillaumevincent** [comment]
Hello,

I don't have a window machine to test

can you give me the version of tty please?

    pip freeze

**Comment by guillaumevincent** [comment]
https://stackoverflow.com/a/52063932/866886

**Comment by Celeborn2BeAlive** [comment]
Since `tty` seems to be a std lib module, I have no version for it (`pip freeze` only display one line `lesspass==10.0.0`, you have no pip dependencies right ? otherwise it seems strange).

Documentation https://docs.python.org/3/library/tty.html confirms:
```
Because it requires the termios module, it will work only on Unix.
```

Maybe if `tty` is not used too much in the codebase it could be replaced with another module ? (or the used functionnalities could be reimplemented)

**Comment by guillaumevincent** [comment]
yes, I need to fix this one and make a conditional import

**Comment by Celeborn2BeAlive** [comment]
Since you don't have a windows I can try to fix it on my side and send you a pull request if you want

**Comment by guillaumevincent** [comment]
@Celeborn2BeAlive it will be awesome

you can look at this example for the import https://gist.github.com/michelbl/efda48b19d3e587685e3441a74457024#file-kbhit-py-L22-L30

Thank you

**Comment by owtotwo** [comment]
Maybe just move the `import tty` and `import termios` to else block of `if os.name == "nt":` in file [fingerprint.py](https://github.com/lesspass/lesspass/blob/master/cli/lesspass/fingerprint.py) head, then it will solve this problem. : )

![lesspass-cli-bug-fix](https://user-images.githubusercontent.com/13444035/95076787-fd134080-0744-11eb-8121-0ed873cc24b2.png)

**Comment by guillaumevincent** [comment]
yes @owtotwo

would you like to create the easy fix ?

**Comment by owtotwo** [comment]
I did an easy fix in [PR](https://github.com/lesspass/lesspass/pull/563).

**Comment by Pierre-Felber** [comment]
I don't think this fix alone will do. With the Patch I get following error:
```
lesspass sdfds sadasd
Master Password: Traceback (most recent call last):
  File "c:\users\1234\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\1234\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\1234\AppData\Local\Programs\Python\Python38\Scripts\lesspass.exe\__main__.py", line 7, in <module>
  File "c:\users\1234\appdata\local\programs\python\python38\lib\site-packages\lesspass\core.py", line 42, in main
    args.master_password = getpass_with_fingerprint(prompt)
  File "c:\users\1234\appdata\local\programs\python\python38\lib\site-packages\lesspass\fingerprint.py", line 142, in getpass_with_fingerprint
    password += c
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by owtotwo** [comment]
@Pierre-Felber It seems to be a new bug because of the return type for function [`getchar`](https://github.com/lesspass/lesspass/blob/473b253971ea4bf8d37b25c2bec9859b440772e2/cli/lesspass/fingerprint.py#L102).

I know that the return type of `msvcrt.getwch()` is `str`, but I am not sure the aim of `getchar` function for `getpass_with_fingerprint`.

I think you can open a new issue for this.

**Comment by Pierre-Felber** [comment]
`msvcrt.getwch()` seems to decode properly, I've tested üöä

**Comment by owtotwo** [comment]
@Pierre-Felber Perhaps the author has no Windows Environment to develop and test.

If you mainly use Windows in daily, you could consider doing the Windows support for lesspass. : )

**Comment by guillaumevincent** [comment]
@Pierre-Felber can you try the latest lesspass version please ? 10.0.1

**Comment by owtotwo** [comment]
@guillaumevincent I tried this. It seems to work well.

**Comment by Pierre-Felber** [comment]
> 
> 
> @Pierre-Felber can you try the latest lesspass version please ? 10.0.1

@guillaumevincent Sorry for the late reply, beeing busy.
ehm, no, not working... 
entering üöä gives us a throw up, therefore i sugested the `msvcrt.getwch()` method
```
Master Password: Traceback (most recent call last):
  File "c:\users\pf\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pf\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pf\AppData\Local\Programs\Python\Python38\Scripts\lesspass.exe\__main__.py", line 7, in <module>
  File "c:\users\pf\appdata\local\programs\python\python38\lib\site-packages\lesspass\core.py", line 42, in main
    args.master_password = getpass_with_fingerprint(prompt)
  File "c:\users\pf\appdata\local\programs\python\python38\lib\site-packages\lesspass\fingerprint.py", line 132, in getpass_with_fingerprint
    c = getchar()
  File "c:\users\pf\appdata\local\programs\python\python38\lib\site-packages\lesspass\fingerprint.py", line 108, in getchar
    ch = msvcrt.getch().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: unexpected end of data
```

**Comment by owtotwo** [comment]
@Pierre-Felber Sorry for my mistake... I installed the version 10.0.1 lesspass in my virtualenv. And test on my version which uses `msvcrt.getwch()`.

`msvcrt.getch()` will only return the first byte of `ü` in utf-8 encoding, which is `0xc3`.

b'\xc3\xbc'.decode('utf-8') is ok but I think `msvcrt.getwch()` would be better. It could work around the unicode problem.

I recommend [`getchar()`](https://github.com/lesspass/lesspass/blob/8494e8490b605c25e40aad99a2bcf9344c37a1f9/cli/lesspass/fingerprint.py#L102)  to return single character(or wide character, it makes no difference in python3) in `str` type, whether it is Windows or other OS. 

The implementation of `msvcrt.getwch()` seems like this one [`msvcrt_getwch_impl()`](https://github.com/python/cpython/blob/77f0a23e7a9fb247101b9b14a060c4ba1c4b87a5/PC/msvcrtmodule.c#L270), which simply calls [`_getwch()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch).

I am not sure if it can cover all situations, different encodings and different operating systems. But it should be fine for most situations I think.

Ref: https://en.wikipedia.org/wiki/Wide_character#Python

**Comment by guillaumevincent** [comment]
does it works with getwch ?

**Comment by owtotwo** [comment]
@guillaumevincent It currently works with `msvcrt.getwch()` (not  need `decode('utf-8')`) on my two Win10 computers, one for `UTF-8` as system default encoding, another for `GBK`.

**Comment by guillaumevincent** [comment]
Ok, @Pierre-Felber can you test 10.0.2 please ?
I don't know if it will generate the appropriate fingerprint for unicode chars

**Comment by Pierre-Felber** [comment]
**üöä** does not crash anymore
fingerprint for **üöä** is 🖥️ 🛏️ ☕
fingerprint on website for **üöä** is ![grafik](https://user-images.githubusercontent.com/19165025/95899935-8d7b0200-0d91-11eb-925c-f56c59fef8ff.png)
so assuming the _monitor_ is used as a replacment for _database_, it is working ok for **üöä**.
Also tested **ßßß**, looks also good.

👍👌✔

By the way, this only works in the _windows terminal_ (tw.exe, which the user needs still to install), in the normal _conhost.exe_ there is no proper fingerprint output possible. This should be documented.

**Comment by guillaumevincent** [comment]
yes you are right
thank you for your tests

**Comment by palash018** [comment]
Is the issue fixed? i tried using bpython today i got same error as @Celeborn2BeAlive  i have python 3.10.9 and windows 11
