### ISSUE TITLE
Change PBKDF algorithm?

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#56]
>  Yeah, going to Scrypt or Argon2 would mitigate a lot of the GPU-based concerns while still offering reasonable in-browser performance. 

https://news.ycombinator.com/item?id=12891720

Need further investigation to see browser velocity of [Scrypt](https://www.wikiwand.com/en/Scrypt) and [Argon2](https://www.wikiwand.com/en/argon2)

### Read

* [Is bcrypt better than scrypt [duplicate]](http://security.stackexchange.com/q/26245/30496) @ security.stackexchange ;
* [What's the advantage of scrypt over bcrypt? [closed]](http://stackoverflow.com/q/1226513/802365) @ stackoverflow ;
* [Password Hashing: PBKDF2, Scrypt, Bcrypt](https://medium.com/@mpreziuso/password-hashing-pbkdf2-scrypt-bcrypt-1ef4bb9c19b3#.514u825tb) @ Medium ;
* [Bcrypt VS Scrypt, Again?](http://crypto.stackexchange.com/q/8632) @ crypto.stackexchange.

**Comment by nothingmuch** [comment]
See also https://password-hashing.net/

**Comment by guillaumevincent** [comment]
Thanks, keep in mind that we want an algorithm working on browsers. And we need an algorithm that don't make our browser freeze or don't came with 1Mo JavaScript library.

**Comment by Darkle** [comment]
Thought you might find this article useful: https://palant.de/2016/10/25/implementing-efficient-pbkdf2-for-the-browser

**Comment by guillaumevincent** [comment]
@Darkle I created a polyfill using webcrypto when available https://github.com/lesspass/core/blob/master/src/pbkdf2.js
We can reach 100k without any problem.

**Comment by guillaumevincent** [comment]
@Darkle if I read properly your article we should try forge https://github.com/digitalbazaar/forge ?

We do pbkdf2 sha256 100k iterations, we use webcrypto and fallback to crypto-browserify when webcrypto is not available.

For the master password we use sha 256 to create the fingerprint.

**Comment by guillaumevincent** [comment]
I will try a scrypt implementation: https://github.com/dchest/scrypt-async-js
The implementation is really fast and work on a lot of browsers.

**Comment by guillaumevincent** [comment]
I close this one, I will reopen this one in case of a version 3.

**Comment by edouard-lopez** [comment]
**Lib Sodium** offers a lot: https://doc.libsodium.org/

> `sodium-universal`
> 
> Universal wrapper for [sodium-javascript](https://www.npmjs.com/package/sodium-javascript) and [sodium-native](https://www.npmjs.com/package/sodium-native) working in Node.js and the Browser
