### ISSUE TITLE
Self hosted lesspass calls out to lesspass.com by default

### ISSUE THREAD

**Issue by BlackthornYugen** [lesspass/lesspass#560]
I'd appreciate any guidence on how the default database can be configured. When deploying my own lesspass there isn't a simple way (that I can see) to change the default lesspass url. Even worse, it calls out to the default database url ( https://lesspass.com/api/passwords/ ) imediatly after loading the page. 

In order to prevent this I had to create a content security policy to prevent this from happening. Locking this down was probably a good idea anyway.

```
Content-Security-Policy: default-src 'self' 'sha256-joEpjG53ygxK65a9X3uPk46B+FEFTSEBBEDzoJMMWgo=' ; style-src 'unsafe-inline' https://lesspass.jskw.dev/lesspass.min.css
```

**Comment by guillaumevincent** [comment]
Hello @BlackthornYugen,

are you speaking on the backend side ?

On the frontend, the BaseURL on the log in page is used to change the backend server used in the code.

**Comment by BlackthornYugen** [comment]
> Hello @BlackthornYugen,
> 
> are you speaking on the backend side ?
> 
> On the frontend, the BaseURL on the log in page is used to change the backend server used in the code.
> 

That's not the behaviour I'm seeing

**Comment by guillaumevincent** [comment]
![image](https://user-images.githubusercontent.com/943762/109508506-39528f00-7aa0-11eb-8ee4-1ef5584a0ec0.png)

> That's not the behaviour I'm seeing

Can you explain why ?

**Comment by BlackthornYugen** [comment]
Before interacting with the website at all it calls out to https://lesspass.com/api/passwords/ -- I didn't dig too much into the source. I ended up just using Content-Security-Policy to stop it from happening.

**Comment by BlackthornYugen** [comment]
![image](https://user-images.githubusercontent.com/3138467/109590089-5d7e9200-7ad9-11eb-9f97-e4099d2ec073.png)

**Comment by BlackthornYugen** [comment]
@guillaumevincent I am 5 months out of date, was this something that was fixed or is this the expected behavior?

**Comment by guillaumevincent** [comment]
Ah no no my bad
By default when the user arrives on the web site, I check if the user is authenticated or not. I use lesspass.com by default.

**Comment by guillaumevincent** [comment]
Hello @BlackthornYugen,

it will be probably fixed by https://github.com/lesspass/lesspass/commit/0f5d2fbd19d378f6593d8b14716c435b6d8f8da3

I close

Thank you for reporting this
