### ISSUE TITLE
Error with self hosted back end and firefox extension

### ISSUE THREAD

**Issue by Enderdead** [lesspass/lesspass#561]
Hello, 
I self-host my own lesspass server with both front and back end. 
I can create an account and log in using the web page.
But when I'm trying to use the firefox extension (9.2.0) in order to log in, I get an error.

The extension says:  "Oops! Something went wrong. Retry in a few minutes."
At the same time, the back end throw an error : "backend_1   | Not Found: /api/auth/jwt/create/"

Do you have an idea of what is going on?
Thank's in advance for your help.

By the way, huge thank's for your work ! 

This is my actual docker image version : 

```
     Container           Repository        Tag       Image Id       Size  
--------------------------------------------------------------------------
lesspass_backend_1    lesspass/backend    latest   fef96f0edf1c   359.8 MB
lesspass_db_1         postgres            9.5      22a523bcc890   196.4 MB
lesspass_frontend_1   lesspass/frontend   latest   0a471cbd0c3b   243.1 MB
```

**Comment by Enderdead** [comment]
Update :
With the extension 9.1.4, every things work fine. 
I assume my back end isn't updated. 
I pull all docker image, remove old one and restart the service using docker compose but nothing change...
Have you an idea ?

**Comment by guillaumevincent** [comment]
Hello,

I think you are not using the appropriate containers:

    https://github.com/lesspass/lesspass/blob/master/containers/docker-compose.yml

quay.io/lesspass/backend:latest
quay.io/lesspass/frontend:latest
quay.io/lesspass/webserver:latest

I use quay.io registry

**Comment by Enderdead** [comment]
Thank's a lot! Everything works fine now.
