### ISSUE TITLE
CLI visual checksum icons not displaying

### ISSUE THREAD

**Issue by executionByFork** [lesspass/lesspass#572]
Hello, I have just installed the lesspass CLI interface using `pip3` and I noticed that the proposed change in #402 has been implemented. I think this is a great feature, but unfortunately it seems my terminal does not support the icons. Below is a screenshot that happens to display 2 of the three icons, but 90% of the time, any passwords I type only shows three hollow boxes.
![lesspass](https://user-images.githubusercontent.com/20407804/101420332-86670080-38b7-11eb-8dd9-265c86599f81.png)

I found #442 and I am a little confused. In the original PR there was a check for a `.ttf` file
```
def user_has_icons_in_terminal():
    return os.path.exists(os.path.expanduser("~/.fonts/icons-in-terminal.ttf"))
```
However this check was removed in [97329c8187](https://github.com/lesspass/lesspass/commit/97329c81871e99b9577658d5dd59eef3c99a0d3f#diff-43784ea52c6af0917fb4a58be0db0252497e883d294715a767474b1a191df11e) which is titled "Use only unicode icons with fingerprint". I am assuming this commit was made for compatibility, so that all terminals would be able to display icons properly. However it seems this is not the case. I am running a `uxvrt` terminal, with the `$TERM` variable set to `rxvt-unicode-256color`. My terminal supports unicode (see below image) but lesspass is not displaying the icons properly. 
![unicode_packages](https://user-images.githubusercontent.com/20407804/101425853-6b998980-38c1-11eb-8a50-d05e3a23b65b.png)
I have other places on this machine where unicode is used. The clue that some icons display properly while others do not tells me that perhaps lesspass is using unicode symbols that are not standard.

Also, since there is no compatibility check ([was here](https://github.com/lesspass/lesspass/blob/9226608f10198358b2ba869e46605257d3231482/cli/lesspass/visual_fingerprint.py#L14)), there is no fallback option for CLI users like me (in the original PR there was a fallback of colored words being used in place of the icons), so I am stuck using either the very broken visual checksum or removing it with the `--no-fingerprint` argument. Either way I can't use the new feature.

I think lesspass should return to using the icons-in-terminal solution originally proposed and implemented in the PR. It was suggested by guillaumevincent to have a `lesspass.tff` installed alongside the CLI tool and I think this would be the best way to maintain consistent compatibility across terminals, if it is feasible.

Is it possible for these icons to be installed alongside lesspass CLI? It seems to me the fingerprint is dependent on these icons, so if there is a package that enables the icon usage, it should be listed as a dependency in pypi. Im not quite sure why the fingerprint is not displaying properly though, so perhaps it's not a missing package issue, and just a problem with how lesspass assumes the unicode symbols it uses are supported in all terminals.

At a minimum, I think there needs to be some sort of argument that can be specified to force lesspass to fall back to using highlighted words in place of unicode symbols, like the original PR had. However it would be much more user friendly if the icons can be made to work in a consistent manner. I believe [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal) allowed for portability?

**Comment by guillaumevincent** [comment]
Hello @executionByFork 

can you help me and run this python script in your terminal ?

```
icon_names = [
    ["fa-hashtag", "#️"],
    ["fa-heart", "❤️"],
    ["fa-hotel", "🏨"],
    ["fa-university", "🎓"],
    ["fa-plug", "🔌"],
    ["fa-ambulance", "🚑"],
    ["fa-bus", "🚌"],
    ["fa-car", "🚗"],
    ["fa-plane", "✈️"],
    ["fa-rocket", "🚀"],
    ["fa-ship", "🚢"],
    ["fa-subway", "🚇"],
    ["fa-truck", "🚚"],
    ["fa-jpy", "💴"],
    ["fa-eur", "💶"],
    ["fa-btc", "₿"],
    ["fa-usd", "💵"],
    ["fa-gbp", "💷"],
    ["fa-archive", "🗄️"],
    ["fa-area-chart", "📈"],
    ["fa-bed", "🛏️"],
    ["fa-beer", "🍺"],
    ["fa-bell", "🔔"],
    ["fa-binoculars", "🔭"],
    ["fa-birthday-cake", "🎂"],
    ["fa-bomb", "💣"],
    ["fa-briefcase", "💼"],
    ["fa-bug", "🐛"],
    ["fa-camera", "📷"],
    ["fa-cart-plus", "🛒"],
    ["fa-certificate", "⭐"],
    ["fa-coffee", "☕"],
    ["fa-cloud", "☁️"],
    ["fa-coffee", "☕"],
    ["fa-comment", "🗨️"],
    ["fa-cube", "📦"],
    ["fa-cutlery", "🍴"],
    ["fa-database", "🖥️"],
    ["fa-diamond", "💎"],
    ["fa-exclamation-circle", "❗"],
    ["fa-eye", "👁️"],
    ["fa-flag", "🏁"],
    ["fa-flask", "⚗️"],
    ["fa-futbol-o", "⚽"],
    ["fa-gamepad", "🎮"],
    ["fa-graduation-cap", "🎓"],
]

for icon in icon_names:
    print(icon[0], icon[1], icon[1].encode("unicode_escape").decode("utf-8"))

```

I bet that your terminal doesn't support 32 bits unicode char

**Comment by executionByFork** [comment]
![unicode_script](https://user-images.githubusercontent.com/20407804/101691330-2d70a700-3a34-11eb-9602-6cabd8152081.png)

**Comment by edouard-lopez** [comment]
@executionByFork I installed `rxvt` `rxvt-unicode` on my ubuntu and the script fail in the same way as you, no issue with Guake terminal however:

![xrvt font issue](https://user-images.githubusercontent.com/1212392/101760017-9c084000-3ada-11eb-8884-0125296a5531.png)

Are you sure the font you use in your shell provide the glyph? You can try another font or use this one in another application
>    ["fa-futbol-o", "⚽"],

**Comment by fcharlier** [comment]
Hi, rxvt/urxvt has several limitations regarding emojis (and large unicode characters)

1. it needs to be explicitly configured with fonts supporting emojis [1] ;
2. it will display "wide" unicode characters as squares if they're larger than the standard character width.

[1] As an example my configuration has:
```
URxvt*font: xft:Fantasque Sans Mono:pixelsize=13::antialias=true,xft:NotoColorEmoji.ttf:::,xft:Symbola:::antialias=true,xft:Code2000:::antialias=true,xft:DejaVu Sans Mono:::antialias=true
URxvt*letterSpace: -1
```
Displays almost all correctly except some of the wider characters:
![2020-12-10-131321_328x746_scrot](https://user-images.githubusercontent.com/165673/101770997-92d29f80-3ae9-11eb-8274-f4338f9cfcde.png)

Changing the ```letterSpace``` to ```URxvt*letterSpace: 5``` allows to display all the emojis correctly but let's face it, it's not looking good for the remaining text.

![2020-12-10-131630_466x788_scrot](https://user-images.githubusercontent.com/165673/101771453-3d4ac280-3aea-11eb-9b4e-b363b9a853de.png)

**Comment by guillaumevincent** [comment]
We can try to find a replacement for :

```
fa-archive 🗄️
fa-bed 🛏️
fa-comment 🗨️
fa-database 🖥️
fa-eye 👁️
```

**Comment by guillaumevincent** [comment]
```
icon_names = [
    ["fa-hashtag", "#️"],
    ["fa-heart", "❤️"],
    ["fa-hotel", "🏨"],
    ["fa-university", "🎓"],
    ["fa-plug", "🔌"],
    ["fa-ambulance", "🚑"],
    ["fa-bus", "🚌"],
    ["fa-car", "🚗"],
    ["fa-plane", "✈️"],
    ["fa-rocket", "🚀"],
    ["fa-ship", "🚢"],
    ["fa-subway", "🚇"],
    ["fa-truck", "🚚"],
    ["fa-jpy", "💴"],
    ["fa-eur", "💶"],
    ["fa-btc", "₿"],
    ["fa-usd", "💵"],
    ["fa-gbp", "💷"],
    ["fa-archive", "📦"],
    ["fa-area-chart", "📈"],
    ["fa-bed", "🛌"],
    ["fa-beer", "🍺"],
    ["fa-bell", "🔔"],
    ["fa-binoculars", "🔭"],
    ["fa-birthday-cake", "🎂"],
    ["fa-bomb", "💣"],
    ["fa-briefcase", "💼"],
    ["fa-bug", "🐛"],
    ["fa-camera", "📷"],
    ["fa-cart-plus", "🛒"],
    ["fa-certificate", "⭐"],
    ["fa-coffee", "☕"],
    ["fa-cloud", "☁️"],
    ["fa-coffee", "☕"],
    ["fa-comment", "🗣"],
    ["fa-cube", "📦"],
    ["fa-cutlery", "🍴"],
    ["fa-database", "🗐"],
    ["fa-diamond", "💎"],
    ["fa-exclamation-circle", "❗"],
    ["fa-eye", "⏿"],
    ["fa-flag", "🏁"],
    ["fa-flask", "⚗️"],
    ["fa-futbol-o", "⚽"],
    ["fa-gamepad", "🎮"],
    ["fa-graduation-cap", "🎓"],
]

for icon in icon_names:
    print(icon[0], icon[1], icon[1].encode("unicode_escape").decode("utf-8"))


```

**Comment by edouard-lopez** [comment]
I can see fa-database and fa-eye character in the issue on mobile, doesn't bode for `rxvt`

**Comment by guillaumevincent** [comment]
@edouard-lopez the change is really recent and was a breaking change visually when we did it (unicode icons are not identical to the font awesome one)

So fixing this by updating the unicode icon will be ok.

> I can can't see fa-database and fa-eye character in the issue on mobile, doesn't bode for rxvt.

You can't distinguish the shape ? or you can't see it ? 

Let's find alternative for fa-database and fa-eye then

**Comment by edouard-lopez** [comment]
I got a box instead of the icon:

![Screenshot_20201210-191148](https://user-images.githubusercontent.com/1212392/101812419-9e3ebe80-3b1b-11eb-9cfc-94ec7ff3761b.jpg)

I'm on Brave mobile

**Comment by edouard-lopez** [comment]
I got the icon on desktop, so might be a font issue on mobile for me:

![lesspass-font-desktop](https://user-images.githubusercontent.com/1212392/101823479-1a8cce00-3b2b-11eb-8c72-4c6aca0e790e.png)

**Comment by guillaumevincent** [comment]
I close this one, it's probably fixed
