### ISSUE TITLE
[iOS] Crash on Save Master Password

### ISSUE THREAD

**Issue by Chrisae9** [lesspass/lesspass#582]
Crash on iPhone Xr iOS 14.2.
Unable to select the option to store a master password locally. I am enjoying this application, I would love added support for Face ID.

https://user-images.githubusercontent.com/25260078/102685495-1443c500-41af-11eb-84e4-39571f497c93.MP4

**Comment by guillaumevincent** [comment]
Thank you for reporting this, I will take a look

**Comment by guillaumevincent** [comment]
I think I found the issue.
AppStore upload are not possible between 23 to 27 of december.

I will upload the fixed version on the 28

**Comment by guillaumevincent** [comment]
link to test https://testflight.apple.com/join/grzBe7bN

**Comment by Chrisae9** [comment]
Downloaded the new update and everything works perfectly. Thank you for the fix.

**Comment by guillaumevincent** [comment]
Nice thanks again
