### ISSUE TITLE
Host website in this repository

### ISSUE THREAD

**Issue by fulldecent** [lesspass/lesspass#588]
Please host https://lesspass.com/#/ using GitHub pages or similar and have the code in this repository under `/Site` or `/lesspass.com/` or similar.

This allows me to directly propose a PR against the website.

**Comment by edouard-lopez** [comment]
It's already in the repo under https://github.com/lesspass/lesspass/tree/master/packages/lesspass-site

**Comment by fulldecent** [comment]
Thank you, got it.

That new version is a scary amount of code for something that should be simple, verifiable and readable. It introduces attack vectors from: TypeScript, Gatsby, Tailwind, yarn and gulp. Whereas I thought HTML and JavaScript were good enough!
