### ISSUE TITLE
Fingerprint reduce master password entropy

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#59]
I create a new issue to discuss about the fingerprint and security

@caspear quote : 

> The approach you listed (along with the current implementations of getIcon and getColor) currently leaks 2^27 (46 icons, 14 colours) bits of info about the hash. So, even if you just display the final set of glyphs it will leak that much. Since your hashes are unsalted (and cannot be) you should ideally not be leaking any of your hashes at all if you can at all avoid it.
> 
> In a rainbow-table based attack the attack is not so much on the sha256 hash itself but on the entropy of the master password. Using the bits from the glyph essentially knocks them off the entropy of the master password. IME typical "strong" passwords that people remember have between 70 and 90 bits of entropy. Knocking 27 bits off due to the glyph leak substantially simplifies the difficulty of revealing the master password, having approximately the same effect as reducing a 12 character long completely random password to a 7 character long completely random password.
> 
> Revealing less information in the glyphs, e.g. as mentioned by @AtoxIO will leak less of the hash, but will still make it considerably easier to attack the password compared to an example without glyphs. Obviously the less you leak the better.

**Comment by edouard-lopez** [comment]
I copy my argument  from #48 here as it's still relevant to the discussion

> You are right, there is a security issue as we reduce the attack time here but I do not agree that removing it will make the approach more secure.
> 
> ### Feature
> 
> The visual checksum is one answer to the idea that passwords management should be boring and painful (cf. [XKCD 936](https://www.explainxkcd.com/wiki/index.php/936:_Password_Strength)):
> 
> > Through 20 years of effort, we've successfully trained everyone to use passwords that are hard for humans to remember, but easy for computers to guess.
> 
> This feature **allows to use a pass-phrase well above `20` characters and still feel comfortable typing it**. It removes fear of typos by tackling  them early in the process, and in a funny way (I'm always guessing where was my typo when I saw a new visual checksum).
> 
> ### Removal
> 
> If we remove this, typing long password will be more difficult. So we will fail our users as they will  resort to bad behaviors such as:
> 
> 0. use **shorter password to reduce risk of typo**. Thus, reducing entropy  ;
> 0. **display master password more frequently to check for typo**. So no more need to steal the checksum, as is will be easier to just steal the master password ;
> 0. move forward as they can't check the master password for typos and check the generated password instead. That means restoring **higher cognitive load** to manage their password by having to remember stuff, even approximatively, like last 4 letters for each generated password.
> 
> So we are where we started but with less fun.
> 
> ### Fails
> 
> Preventing errors at early stage is one of the criteria from Bastien & Scapin heuristic:
> 
> > 5.1. ERROR PROTECTION 
> > 
> > Definition :
> > The criterion Error Protection refers to the means available to detect and prevent data entry errors, command errors, or actions with destructive consequences.
> 
> > Rationale(s) :
> > It is preferable to detect errors before validation rather than after: the detection is less disruptive.
> 
> [_Bastien, J.M.C., Scapin, D. (1993) Ergonomic Criteria for the Evaluation of Human-Computer interfaces_](http://www.cocoaheads.fr/wp-content/uploads/files/Ergonomic_Criteria.pdf) (pp. 33 or 39).
> 
> ### Future
> 
> Thanks for raising the issue, but if the risk of getting the checksum stolen is a threat to you, you should probably consider different approach. In the meantimes, we are discussing the idea of adding on option, in the _connected mode_, to toggle the visual checksum.
> 
> So keep tuned :) 
> 
>

**Comment by nothingmuch** [comment]
Several thoughts:

If I'm not mistaken (i've only skimmed the code), it's computing an HMAC of the password character by character with the login as the secret? If so, with a slight modification on technique as #48, you just need to bruteforce 256 bytes at at a time, given that the login is on the screen next to the image. I this can no longer be done by hand, but with video capture and a bit of coding it should still be easy to attack the master password.

Secondly, salting based on the login means the salt is stored on the target website, so this creates a possibility for offline dictionary attacks on the master password in case of a website breach.

PasswordHasherPlus and Twik expand on the old firefox Password Hasher extension by adding a UUID as a secret key used to seed the HMACs. This reduces the risk, but places a burden on the user of distributing and securing this secret, as well as keeping a backup.

Thirdly, thanks to bitcoin, specialized hardware for bruteforcing sha256 is pretty prevalent. Given the huge gap between ASIC and PC hardware, one could argue that any hard coded default of 8192 iterations provides a very modest amount of key extension.

Recently a competition to select a password hash has concluded with some hash functions that would be more appropriate: https://password-hashing.net/

To use these securely, it should still be possible to at least opt in to setting a private key to serve as the hmac secret or analogue in these other functions.

**Comment by guillaumevincent** [comment]
I close this one,
there is a compromise between the reduction of entropy and usability.
master password icons verification doesn't leak password anymore, but reduce entropy if someone get your icons. If someone look behind you and see your icons, he probably can see you typing your master password.
