### ISSUE TITLE
Question: Seeking additional clarity on KeePass vs LessPass comparison FAQ

### ISSUE THREAD

**Issue by polarathene** [lesspass/lesspass#593]
From the FAQ, [KeePass vs LessPass](https://github.com/lesspass/lesspass/wiki/FAQ#how-does-lesspass-compare-with-other-solutions):

> Store accounts/passwords in a database encrypted with your master password

vs

> Compute a unique password for every account based on your master password; your generated password is never saved

The encrypted database is of little use without the master password to decrypt it. If the attacker did have the master password, they still need the encrypted database to get the contained passwords as they're not derived from the master password.

By contrast, even though LessPass does not store passwords, the master password itself is a form of storage. Once it is known, the users passwords are no longer secured. Profiles to accommodate services that need them aren't likely to deviate much from the services minimum requirements, if the user has explicitly deviated from this it does benefit security, profile parameters such as counter less so.

Profiles however are likely to be stored, and thus similar to the comparison of an encrypted database file. One benefit for LessPass is services may be deterministic in password generation, but which ones are used along with any other account metadata isn't as likely to be obvious. If the attacker isn't after a specific or probably service to login with the targets credentials, this can be less risk of being compromise.

---

> Database can be stolen and brute-forced offline, passwords are not individually encrypted so whole database is vulnerable

vs

> Would have to brute-force websites to guess master passwords, most sites log and mitigate this (reCAPTCHA, blocking multiple attempts, etc)

Assuming a proper master password was used to secure the encrypted database, the offline attack isn't all that feasible. I believe this has been the case with LastPass when it was compromised, attackers had encrypted data but it was effectively useless without the keys to decrypt.

LessPass is described as requiring to attack the websites... a more practical attack would be against a website having a breach where the database with password hashes was compromised. This allows for an offline attack as well. 

LessPass is stronger still, in the sense that not only does the attacker need to perform 100k iterations of PBKDF2 for the master password guess, but the generated password for the website account must also go through that services slow-hash/KDF too. Combined it may raise the computation per guess above that of KeePass.

---

## TL;DR:

- **LessPass master password is almost equivalent to KeePass master password + encrypted database.** KeePass master password is not useful without access to the encrypted database as well.
- LessPass can have profile data stored, which **coupled with a master password enables access to each service the user has an account with**. However having the master password does not reveal all services the user has registered with LessPass generated passwords.
- **LessPass can also have the master password attacked offline.** It only requires access to one database from a service the user has a LessPass password with, which if successful enables the attacker to generate passwords for other services deterministically.

Have I understood this comparison correctly?

For most users and their passwords, a LessPass master password is equivalent to having all passwords it derives, and is more accessible to attackers than cloud-providers or KeePass (or similar apps), in that a single service being breached and leaking password hashes enables attacking to begin?

Not asking for any changes to the wiki, I think it can be safe to assume comparisons from one party can be biased (eg there's no mention about [downsides like changing master password](https://github.com/lesspass/lesspass/issues/471)).

**Comment by guillaumevincent** [comment]
> LessPass master password is almost equivalent to KeePass master password + encrypted database. KeePass master password is not useful without access to the encrypted database as well.

Yes except that with KeePass you don't have access to the future passwords.

> LessPass can have profile data stored, which coupled with a master password enables access to each service the user has an account with. However having the master password does not reveal all services the user has registered with LessPass generated passwords.

Yes but keep in mind that saving password profiles on LessPass Database is for web sites that doesn't accept the default options.

> LessPass can also have the master password attacked offline. It only requires access to one database from a service the user has a LessPass password with, which if successful enables the attacker to generate passwords for other services deterministically.

Yes this is one of the weakness of LessPass. If an attacker get your raw password from a leaked database, they can try to brute force your master password. This is mitigated if the entropy of your master password is enough.

So I don't know how to clarify this. Do you have a proposition ?

**Comment by guillaumevincent** [comment]
I close. 
Feel free to post on this thread to ask for extra help.

**Comment by polarathene** [comment]
> Yes except that with KeePass you don't have access to the future passwords.

I don't quite understand what you mean here by access to future passwords? Are you referring to the attacker having a database copy, and that they will not have any new passwords added by the user updating their password database?

> This is mitigated if the entropy of your master password is enough.

Agreed.

> So I don't know how to clarify this. Do you have a proposition ?

I believe I was just raising some concerns about some bias in the comparison, but anyone else who feels similar will come across this issue when investigating, so nothing really needs to be done :)

**Comment by guillaumevincent** [comment]
> I don't quite understand what you mean here by access to future passwords? Are you referring to the attacker having a database copy, and that they will not have any new passwords added by the user updating their password database?

If someone stole your LessPass master password, he can generate your actual passwords and you future passwords.

If someone stole you Keepass master password + you KeePass database, he will have access only to your actual passwords

**Comment by Lurux** [comment]
> Yes this is one of the weakness of LessPass. If an attacker get your raw password from a leaked database, they can try to brute force your master password. This is mitigated if the entropy of your master password is enough.

I have a question about this statement - even if the LessPass master password can be brute-forced, there is no reason a KeePass password couldn't be brute-forced too, right ?

In that sense, an attacker getting one of your generated passwords would be equivalent of an attacker getting your KeePass DB (aka. it allows brute-forcing it), right ?

That said, I still think the "master password is useless without a DB" aspect of KeePass is an interesting perk to keep in mind here. I wonder if the private key system proposed in #389 would bring this benefit to LessPass to some extent ?

**Comment by guillaumevincent** [comment]
@Lurux keep in mind that your LessPass master password give you access to future passwords also.
KeePass database will just give access to old passwords.

**Comment by polarathene** [comment]
> In that sense, an attacker getting one of your generated passwords would be equivalent of an attacker getting your KeePass DB (aka. it allows brute-forcing it), right ?

<details>
<summary>As stated, the difference here is:</summary>

- **LessPass:** 
  - Master password seeds all other passwords, it effectively is the database, you do not need to acquire additional data to attack.
  - Compromising one password (_eg: through a leak_) enables you to attack the master password more easily, but otherwise without knowing LessPass was used, generic brute-force against the derived password will be much more ineffective vs non-generated passwords from other users, unless the leak was in plain-text (_which the most vulnerable services have higher chance of this bad practice_).
  - Still the attacker must know LessPass was used or allocate resources regardless, this would be pointless with a high entropy master password. Without high entropy master, a single compromise requires you to change the master, and thus update passwords for all accounts to be safe, as opposed to just the compromised account/password with other solutions.
- **KeePass:** 
  - Unlike LessPass, the attacker can't do much with knowledge of the user managing passwords with a solution like KeePass, unless they're capable of getting a copy of the users password DB, this can raise difficulty a fair amount and would likely mean you're being targeted specifically.
- **1Password:** 
  - Just adding this one for additional context. It likewise encrypts a password database with a master password, however compromising the sync servers is irrelevant as these only have the encrypted DB, and the master password is not only user input but also client-side input of 128-bit "secret" additional entropy that does not cross the network IIRC, only decrypted locally.
  - They do however offer an app which enables unlocking the DB via fingerprint scan if enabled, and on some business/family plans, if an admin account is compromised, password reset can be used against accounts within that group (_requires access to both email accounts IIRC_), so there are additional weaknesses if the user/admin opts for conveniences.

</details>

_Or a more terse comparison:_

- **LessPass:**
  - Most practical attack requires generating passwords via LessPass, hashing them (_unless access to leaked plain-text_) and comparing.
  - Besides LessPass, any profile parameters must be known if used, and master password must be low enough entropy.
- **KeePass:**
  - More Secure - A copy of the users PW DB is required if attacking master password to gain access to all passwords.
  - Added Friction - A DB must be accessible and backups in case of data loss event.
- **1Password:**
  - In addition to a DB (_where backups and sync is handled for you_), client devices must have a secret key that boosts master password entropy by 128-bit, but at the cost of added friction.

As long as passwords are generated with sufficient entropy, they won't be brute-forced, and a master password should always be high entropy (but still memorable), that even with a plain-text leak you should not be at risk there.

You'd be more prone to malware keyloggers ,where LessPass is at a slight disadvantage but 2FA should help defend against that.

If someone has sufficient resources, it doesn't matter what you do.. As brute-force attacks against a password hash isn't the only way to get information for those that want something badly enough.

---

> That said, I still think the "master password is useless without a DB" aspect of KeePass is an interesting perk to keep in mind here. I wonder if the private key system proposed in #389 would bring this benefit to LessPass to some extent ?

I think you meant https://github.com/lesspass/lesspass/issues/376 for private key feature?

This boosts entropy which is helpful (_users with less secure passwords like "pass1234!" effectively become a prefix/suffix_), IIRC the secret key becomes the actual master password (or helps derive it) and your typed input master password encrypts/decrypts that, something like that.

But as the issue discusses, one of the benefits of LessPass would be lost as you then need to rely on having that key available on the system you want to use LessPass on, so it becomes similar to needing a DB, but with less sync concerns.

The other issue you referenced though discusses private/public key cryptography I think? With one mentioning using QR codes to pass the secret around from a separate device/source. I suppose you could use something like Diffie-Hellman key exchange,  where LessPass will pick a random number internally as it's secret and can use one of the RFC7919 params, your other device can do the same, they both use the DH parameters to calculate a value to share publicly, and after exchanging that with one another they can do some more math each and will have the same really large number that nobody eavesdropping will be able to calculate (provided the modulus is large enough, such as 2048-bit FFDHE or curve 256-bit ECDHE)

That can then be hashed into a temporary encryption key allowing you to generate/transfer your secret key more securely between devices where it doesn't matter if someone witnesses the transfer, as they won't have access to the unecrypted secret key, and while that's semi-useful for an untrusted device (_eg: at a netcafe_), that wouldn't prevent the untrusted device from attempting to steal the secret key once decrypted, but a little safer than only a keyboard input master password or always having the secret key copied to each device in storage.

Not much benefit for your personal devices with that separation approach, other than maybe keeping the secret key on another device less susceptible to being compromised. Without the network or camera/QR sort of transfer, manual input of 128-bit would be more lengthy (_20 values from a set of 96 ASCII characters, 11 values from a set of 3000 emoji, the latter might be less but would be more friction to input ironically_), without network to automate, you'd also be exchanging the two numbers the two devices exchange of similar size as well adding more friction.

The 2FA/MFA requests I didn't quite follow, as all data required is already available locally (_nothing needs to be retrieved from a server_), what is the intention of the added authentication that couldn't be worked around? (_a local device compromise empowers the attacker considerably already_)
