### ISSUE TITLE
[Packaging] Add this program as a flatpak on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [lesspass/lesspass#594]
Hi. Making this cute program available as flatpak on FlatHub is much better & secure for Linux that using it as browser extension, isn't it ?

Notes on flatpak on FlatHub:
1. home page of FlatHub is:
    https://www.flathub.org/home
2. FlatHub repositories are at:
    https://github.com/flathub
3. when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
4. FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 kinds regarding this point: some are packaged by their developers like Verge full node wallet, while other are packaged by person other than their developers.
5. all packages on FlatHub are signed .....
6. even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
7. FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

**Comment by guillaumevincent** [comment]
The only problem I have is a time problem. I don't plan to do this in the near future. 
I close. I will reopen if I have time or a huge demand for this kind of tool.
I'm sorry

**Comment by pabloab** [comment]
Could be left open to give more visibility, so a contributor could send a PR in this regard.
