### ISSUE TITLE
SSL certificate broken

### ISSUE THREAD

**Issue by tim-peters** [lesspass/lesspass#596]
The SSL certificate of lesspass.com seems to be broken (out of date?). Due to the HTTP Strict Transport Security (HSTS) setting the website is not available at all. Since the credential storage uses the same domain it does not work as well atm. 

Since this is a core functionality I would suggest to fix this issue with the highest prio.

**Comment by guillaumevincent** [comment]
Sorry for this,
without any reason Lets Encrypt didn't send me a notification email about the certificate expiration date.

Certificate is updated
Thank you for the issue. And sorry again
