### ISSUE TITLE
Write password generation specification 

### ISSUE THREAD

**Issue by fulldecent** [lesspass/lesspass#602]
Draft: https://github.com/lesspass/lesspass/wiki/Password-Generation-Specification

---

Recommend to remove these others files and improve the above file:

https://github.com/lesspass/lesspass/wiki/Overview-of-Password-Generation

https://github.com/lesspass/lesspass/wiki/Generated-password-info

**Comment by guillaumevincent** [comment]
What problem do you try to solve here ?

**Comment by fulldecent** [comment]
Trying to create a stateless open source password manager named LessPass.

First step to making something is having a specification.

**Comment by fulldecent** [comment]
Also, I'd like to compare the existing implementations (there are several) and see if there are issues. Comparing to one standard is easier (O(N)) than comparing each to each other (O(N^2)).

**Comment by guillaumevincent** [comment]
> Also, I'd like to compare the existing implementations (there are several) and see if there are issues. Comparing to one standard is easier (O(N)) than comparing each to each other (O(N^2)).

Existing implementation in other repositories ?

Feel free to create the wiki specification page if you want. I don't know if it's worth the time.

But "Overview of Password Generation" is interesting for learning purposes. And yes maybe "Generated password info" don't have a lot of values here. We can probably find those info in your spec.

I close, you can ping me in this issue if you decide to finish the first version of the spec. I will delete the appropriate page on the wiki. Thank you
