### ISSUE TITLE
[core] remove javascript minification and ES6

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#61]
The well known [@bcrypt](https://twitter.com/bcrypt) write a [blog post](https://diracdeltas.github.io/blog/backdooring-js/) : backdooring our javascript using minifier bugs.

We should : 

- study our minified version
- using non minified version of lesspass-core
- maybe remove ES6 code

**Comment by edouard-lopez** [comment]
Also need to read [The JavaScript Trap](https://www.gnu.org/philosophy/javascript-trap.html) by Richard Stallman.

**Comment by guillaumevincent** [comment]
fixed in version 5.2.2 of lesspass/core
