### ISSUE TITLE
Login Issue with 9.4.2

### ISSUE THREAD

**Issue by jasonbunnell** [lesspass/lesspass#610]
Cannot login.  Get this error:
"The email and password you entered did not match our records. Please double-check and try again."

I am 100% certain the master password is correct.  

There seem to be a number of issues in addition to this.  I use the Firefox addon.  Is there a way to uninstall this version and revert to an older version?

**Comment by jasonbunnell** [comment]
Yes.

**Comment by guillaumevincent** [comment]
@jasonbunnell is this fixed now ?
Yes I want to enforce no master password are send to LessPass Database unencrypted.

May I recommend you to reset your password and keep the `Encrypt my master password` option checked ?
Sorry for this, I tried to make it the more smooth as possible (adding an information panel) but it was not enough apparently
