### ISSUE TITLE
Already saved password profile is not loaded correctly on reopening

### ISSUE THREAD

**Issue by OlegRakovitch** [lesspass/lesspass#611]
Hello. After latest version update I've noticed that username is not automatically specified anymore.

Steps to reproduce:
1. Sign in into LessPass through browser extension
2. Go to website where username was stored previously. For example `github.com`
3. Click on extension.

Expected behavior:
1. Username field should be filled with the previously saved value

Actual behavior:
1. Username field is empty
2. Username can be auto-filled if you click on key icon and click on the website entry `github.com`

**Comment by guillaumevincent** [comment]
Fixed in version 9.2.5
Thank you for reporting
