### ISSUE TITLE
Unable to login to Lesspass database via Chrome/Firefox extension

### ISSUE THREAD

**Issue by pbaity** [lesspass/lesspass#613]
A few days ago I noticed that I was no longer able to sign into the Lesspass database via the Chrome extension. I didn't think much of it - I noticed the extension had just updated to 9.5.1 and figured maybe there was a bug. I tried using the Firefox extension which had not updated yet, and it still worked.

However, today I still can't log in and I haven't seen anyone else raise the issue. I updated the Firefox extension and am experiencing the same problem there now too. Signing in at lesspass.com still works, but I've tried uninstalling the extensions and reinstalling them, as well as changing my password, but nothing has fixed it so far. Hopefully it's not just me!

Details:
Browser: Brave Version 1.22.71 (Chromium: 89.0.4389.114, Official Build, x86_64), also tried Firefox 87.0 (64-bit)
Lesspass: 9.5.1
OS: MacOS Catalina 10.15.7, also tried on Windows 10
Error:
![image](https://user-images.githubusercontent.com/39106297/114182715-f2627f80-9910-11eb-96ac-862ef1d4f850.png)
Occasionally I also just get a generic "Something went wrong, try again later" error.

**Comment by guillaumevincent** [comment]
Hello @pbaity ,

can you uncheck `Encrypt my master password ` in the settings ?

See https://github.com/lesspass/lesspass/issues/610

**Comment by pbaity** [comment]
@guillaumevincent Shoot, missed that issue somehow - sorry to waste your time! 🤦 

I like this feature and will definitely update my password to take advantage of it.

**Comment by guillaumevincent** [comment]
Do not apologize, several of you have raised the problem. It's my fault.
Great, it's better not to send your master password, but the encrypted version!
