### ISSUE TITLE
can't login with firefox plugin since update of 6th april

### ISSUE THREAD

**Issue by Karine-Karine** [lesspass/lesspass#614]

**Comment by tannerntannern** [comment]
I believe this is affecting the chrome plugin as well.  I get "Oops! Something went wrong. Retry in a few minutes." when trying to login

**Comment by tannerntannern** [comment]
@Karine-Karine is this the same issue you're experiencing?

@guillaumevincent, this has rendered the browser extension unusable.  The only workaround I have at the moment is to use the demo at https://lesspass.com, which is apparently less secure (according to the page)

**Comment by edouard-lopez** [comment]
I can't reproduce on:
* Firefox 88.0b7 (64-bit) Linux Mint
* Lesspass extension 9.4.0

**Comment by guillaumevincent** [comment]
https://github.com/lesspass/lesspass/issues/613

**Comment by guillaumevincent** [comment]
@Karine-Karine and @tannerntannern you are probably using you master password unencrypted on LessPass Database.
May I recommend you to reset your password and keep the Encrypt my master password option checked ?

You can also uncheck the option in the options

**Comment by tannerntannern** [comment]
Thank you for the swift reply @guillaumevincent!  That was indeed my problem.  I should have searched the closed issues more thoroughly but I was a little flustered because I couldn't login to a company video call, haha.  Sorry to waste your time.

**Comment by edouard-lopez** [comment]
@guillaumevincent A release note would help on this one

**Comment by guillaumevincent** [comment]
@edouard-lopez where ?

I added an information page on the web extension for this.

**Comment by Karine-Karine** [comment]
@tannerntannern I had exactly the same problem but I fixed it when I unchecked the Encrypt my master password option. Thank you @guillaumevincent

**Comment by guillaumevincent** [comment]
Thanks for let us know
I'll keep this issue open for a couple of weeks
