### ISSUE TITLE
Current versions seems broken auth

### ISSUE THREAD

**Issue by ogarcia** [lesspass/lesspass#615]
Latest version perform auth in `/auth/jwt/refresh/` instead of `/api/auth/jwt/refresh/` and `/auth/jwt/create/` instead of `/api/auth/jwt/create/`.

Seems that have retrocompatibility to don't break with old servers versions, but I think that is broken:
```
x.x.x.x - - [19/Apr/2021:17:03:21 +0200] "OPTIONS /auth/jwt/refresh/ HTTP/2.0" 405 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
x.x.x.x - - [19/Apr/2021:17:03:21 +0200] "OPTIONS /api/auth/jwt/refresh/ HTTP/2.0" 204 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
x.x.x.x - - [19/Apr/2021:17:03:21 +0200] "POST /api/auth/jwt/refresh/ HTTP/2.0" 401 13 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
x.x.x.x - - [19/Apr/2021:17:03:34 +0200] "OPTIONS /auth/jwt/create/ HTTP/2.0" 405 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
x.x.x.x - - [19/Apr/2021:17:03:34 +0200] "OPTIONS /api/auth/jwt/refresh/ HTTP/2.0" 204 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
x.x.x.x - - [19/Apr/2021:17:03:34 +0200] "POST /api/auth/jwt/refresh/ HTTP/2.0" 401 13 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"
```

As can I see, it asks for non `/api/` and `/api/` in `/refresh` but dontt do the same with `/create` and calls to `/refesh` again.

**Comment by ogarcia** [comment]
In the other hand I suggest you that use a versioning API. Something like `/1/auth/jwt/refresh/`. This can avoid problems in future.

**Comment by guillaumevincent** [comment]
@ogarcia what base url are you using ?

**Comment by guillaumevincent** [comment]
Ok but if you updated your containers, you should be fine.

https://github.com/lesspass/lesspass/blob/master/containers/backend/api/urls.py#L20-L21

So by default everything is behind `/api/` but if you use api.FQDN, it proxy pass directly to `/api/`

https://github.com/lesspass/lesspass/blob/master/containers/webserver/httpd-ssl.conf#L146-L157

**Comment by ogarcia** [comment]
Yes, but try serve it in `https://api.lesspass.com/api/`, don't work :cry:

**Comment by guillaumevincent** [comment]
`https://api.lesspass.com/` not `https://api.lesspass.com/api/`

**Comment by ogarcia** [comment]
The URL is an example. I say that if you have your server in `/api/` it don't work.

Going back to my initial comment I can see that client app do:
1. `OPTIONS /auth/jwt/refresh/` this gives an error because is serving in `/api/`.
2. `OPTIONS /api/auth/jwt/refresh/`, ok this exist, do post
3. `POST /api/auth/jwt/refresh/`, this returns 401 because the token is expired, lets create a new token
4. `OPTIONS /auth/jwt/create/`, if the last call was in `/api` I would not try to use not `/api`, but, no problem, is only one more request.
5. `OPTIONS /api/auth/jwt/refresh/` **here is the error** Must try to call to `/api/auth/jwt/create/`, but instead of it, try to refresh again the expired token.

**Comment by guillaumevincent** [comment]
@ogarcia ok let's go more slowly because I don't understand everything.

So first 

> Going back to my initial comment I can see that client app do:

Which client app ? Web extension or mobile app ?

Because the web extension use `api.lesspass.com` for the base URL now. When the user open the web extension the request endpoint used is `/auth/jwt/refresh/`. There is no `/api/` here. number 2 doesn't exists.

There is a 404 error I need to fix on `api/auth/jwt/refresh/` endpoint. But ignore this one.

**Comment by ogarcia** [comment]
> @ogarcia ok let's go more slowly because I don't understand everything.

No problem. The truth is that I explain like the ass :joy: 

> So first
> 
> > Going back to my initial comment I can see that client app do:
> 
> Which client app ? Web extension or mobile app ?

Chrome extension

> Because the web extension use `api.lesspass.com` for the base URL now. When the user open the web extension the request endpoint used is `/auth/jwt/refresh/`. There is no `/api/` here. number 2 doesn't exists.

In my case, the chrome extension do all the steps.

**Comment by guillaumevincent** [comment]
are you running `LessPass version: 9.5.1` ?

You can see this in the little info icon in the top menu.

**Comment by ogarcia** [comment]
> are you running `LessPass version: 9.5.1` ?
Yes `LessPass version: 9.5.1`

**Comment by guillaumevincent** [comment]
ok so you are speaking about the 404 error ?

I think I understand now

Let me fix this

**Comment by guillaumevincent** [comment]
If this is not the case, please reopen this issue

**Comment by ogarcia** [comment]
No, this is a fix, but I thought that you wanted to maintain backward compatibility

**Comment by guillaumevincent** [comment]
But if you put `https://mycustomdomain.org/api` in LessPass Database Url in the option it should work no ?

**Comment by ogarcia** [comment]
> But if you put `https://pass.example.com/api` in LessPass Database Url in the option it should work no ?

Yes yes. But as I saw that requests were being made with `/api/` and without `/api/` I thought that you wanted to maintain backward compatibility by your own. But, mistery solved!

**Comment by guillaumevincent** [comment]
Thank you for your report and your patience !
