### ISSUE TITLE
Server API versioning

### ISSUE THREAD

**Issue by ogarcia** [lesspass/lesspass#617]
Instead of use directly `/auth/` and `/passwords/` I suggest you that use API versioning. This have several advantages.
1. Know what versions of the client are you using simply looking the requested URLs.
2. More easy configuration of reverse proxy, because you can redirect `/apiversion/` to backend and use same URL for other uses.
3. Can introduce break changes without break anything. For example, the movile app can use a different version than browser extension.
4. Maintain backward compatibility. If a client has not latest version for example.

**Comment by guillaumevincent** [comment]
Yes if we introduce a breaking change in the future it will be with a `/v2/` base endpoint.
But we didn't introduce a breaking change in the API. I only introduce a base URL change and a bug in the token refresh mechanism.

**Comment by guillaumevincent** [comment]
What I try to say is:

Before API url was `https://lesspass.com/api/auth/` and `https://lesspass.com/api/password/`. Those URLs are still working, there is a backward compatibility.

I added `https://api.lesspass.com/auth/` and `https://api.lesspass.com/password/`. This is an addition not a breaking change.

Client was updated to use the new URLs. I missed to change the token refresh URLs
