### ISSUE TITLE
Allow secure domains to provide Password-Options

### ISSUE THREAD

**Issue by florianb** [lesspass/lesspass#62]
Allow Lesspass to preconfigure the password-options based on the domain, by fetching f.e. a `pwdoptions.txt` from the given domain (of course only via a secure connection).

This file could contain information about

- the minimum password length
- the maximum password length
- allowed characters/-classes
- necessary characters/-classes

**Comment by edouard-lopez** [comment]
Thanks @florianb, that's a discussion we had but we are focused on others things. FYI, here is the [`password` object](https://github.com/lesspass/pure/blob/f2b91d3a93322c10f7671e68727fe8c6248d74c4/test/password.js#L25) we store:

```
{
        site: 'example.org',
        login: 'test',
        uppercase: true,
        lowercase: true,
        numbers: true,
        symbols: true,
        length: 12,
        counter: 1,
}
```

**Comment by florianb** [comment]
Unfortunately this won't be enough since there still exist webpages only allowing a subset of symbols to be used in the password.

**Comment by guillaumevincent** [comment]
@florianb In the next release we will save also password template, and it will allow much complex params:

```
var options = {
    ...
    template: 'vcVCns'
};
```

Maybe it will help

**Comment by florianb** [comment]
Great - thanks for your fast response! 💝

**Comment by guillaumevincent** [comment]
Because of the breach found with password template in the version 1 of LessPass, we will drop password template in v2.
Now generated password will contain at least one char from subset (lowercase,uppercase,digits,symbols).
I close this one because site will not create a `pwdoptions.txt`, so we can't know the "best" profile for a site.
