### ISSUE TITLE
[Want To Contribute] How to Add Chinese Translation?

### ISSUE THREAD

**Issue by ianpan870102** [lesspass/lesspass#623]
As titled, I'd like to contribute to the README by adding Chinese translation (currently there are only English, German, French, and Italian). If you're open to accepting translations, I can start working on it this week in my free time :-) My plan is to put out both a Traditional Chinese version (for Taiwan and Hong Kong), and a Simplified Chinese version (for Mainland China).

**Comment by edouard-lopez** [comment]
@ianpan870102 Thanks for the proposal!
I guess you are talking about the _How does it work?_ article, as we already have [chinese translations for the app](https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure/src/i18n).

If so, the posts are versionned in a dedicated repo: https://github.com/lesspass/blog/tree/main/_posts.

Cheers

**Comment by ianpan870102** [comment]
Yes, thanks for the pointer! The blog repo is what I was looking for.
