### ISSUE TITLE
Hidding the generated password 

### ISSUE THREAD

**Issue by vjfernan** [lesspass/lesspass#64]
Feature request: 
In the browser extension, would it be possible to hide the generated password, for example behind asterisks for security purposes?
Thank you.

**Comment by tatums** [comment]
IMO this should be the default behavior in the browser extension AND the website.

**Comment by guillaumevincent** [comment]
@tatums @vjfernan the generated password is in an input because it's the only way we found to copy the password in different browsers. Add text to the clipboard directly in JavaScript is not something easy. We use clipboard to do so, and clipboard need a textarea or an input.
Maybe we need to push further and see if the generated password can hide without remove the copy feature.

**Comment by abueide** [comment]
@guillaumevincent Hmm, github does it when you click the button to copy to clipboard when you go to clone a repository. At least, its possible.

**Comment by guillaumevincent** [comment]
@abueide there is an input field too :

![2016-11-15 10_02_29-lesspass_lesspass_ lesspass open source password manager](https://cloud.githubusercontent.com/assets/943762/20299328/c212c1e8-ab1a-11e6-9d01-c131a65ca6be.png)

**Comment by edouard-lopez** [comment]
@vjfernan could you elaborate on the why? 

When creating a new entry KeePass shows the password by default:
![keepass-visible-password](https://cloud.githubusercontent.com/assets/1212392/20326200/0b0d7c2c-ab88-11e6-8890-70500e25cd7b.png)

**Comment by edouard-lopez** [comment]
A simple solution will be to obfuscate the generated password using CSS. Here is what I got with the following rules:

    color: black;
    text-shadow: -5px -5px 1px black, -4px -4px 1px black, -3px -3px 1px black, -2px -2px 1px black, -1px -1px 1px black, 0px 0px 1px black, 1px 1px 1px black, 2px 2px 1px black, 3px 3px 1px black, 4px 4px 1px black, 5px 5px 1px black;

![opacify-generated-password](https://cloud.githubusercontent.com/assets/1212392/20326402/e7805418-ab88-11e6-9c0e-c703cf324e2b.png)

A longer `text-shadow` can still reduce the leak of information but you got the idea. Also password is still selectable by mouse if need be:

![opacify-generated-password-2](https://cloud.githubusercontent.com/assets/1212392/20326546/90e2245a-ab89-11e6-97ca-788e22bd2f32.png)

**Comment by guillaumevincent** [comment]
@edouard-lopez we should try to hide the input field and keep the copy past function.

**Comment by vjfernan** [comment]
@edouard-lopez For security. 

Not in my KeePass:

![image](https://cloud.githubusercontent.com/assets/23368434/20344365/bf26db12-abf2-11e6-8238-3022206d7ffa.png)

IMHO, all apps should hide the password fields by default and allow to show it if it is necessary.

**Comment by guillaumevincent** [comment]
@vjfernan Amazon on mobile show password by default

**Comment by guillaumevincent** [comment]
We found an astuce with simple click. So we can hide generated password. Will be fixed in next version.

**Comment by vjfernan** [comment]
That's great! Thank you.
