### ISSUE TITLE
Is the Firefox Plugin offline ?

### ISSUE THREAD

**Issue by skyerjoe** [lesspass/lesspass#643]
**Windows 64 bit** 
**FF Version 89.0**

Does the firefox plugin working in offline mode ? 

If not how i can use lesspass without an own database offline ? 

best regards

**Comment by guillaumevincent** [comment]
LessPass password generation works offline
If you need to save password profiles, LessPass database is needed. You can run a LessPass database locally, or use the one available for free at api.lesspass.com

**Comment by edouard-lopez** [comment]
You can find more info in the [FAQ: Does LessPass use a hosted database?](https://github.com/lesspass/lesspass/wiki/FAQ#does-lesspass-use-a-hosted-database)
