### ISSUE TITLE
"search and open" functionality

### ISSUE THREAD

**Issue by laubster** [lesspass/lesspass#647]
Just daydreaming...

```
$ sitelogin bank
Enter master password:
Multiple candidates found (see below); be more specific.
bigbank https://login.monster_bank.com/start scott@gmail.com
localbank https://online.friendly_credit_union.com/users/login scott@gmail.com

$ sitelogin localbank
Enter master password:
scott@gmail.com has been loaded to clipboard 
xdg-open has been called for https://online.friendly_credit_union.com/users/login
password for this entry: w"8]G.*w@>4tD_x!
```
Points:
- single command to search entries and visit site if single hit found
- searches local profile database that's stored encrypted
- the searchable keywords are separate from the URL field & are used to differentiate entries (can't just search URLs: consider 2 paypal accounts)
- feels like more of a wrapper around lesspass, but keywords in profile would be needed
- keystroke flow after browser pops to foreground: tab to user_id field, ctrl-v to paste user_id, tab to password field, alt-tab to terminal, (somehow highlight password), shift-ctrl-c to copy password, alt-tab to browser, ctrl-v to paste password. Clunky, but not far off keepassxc flow.
- big stretch: would be handy to somehow piggyback on gpg-agent to avoid repeated password entry

**Comment by guillaumevincent** [comment]
LessPass Database will be closed in March. [See announcement](https://blog.lesspass.com/2022-12-29/decommissioning-lesspass-database). This issue is no longer relevant. Closing it.
