### ISSUE TITLE
Android UI main page is not scrollable

### ISSUE THREAD

**Issue by muusik** [lesspass/lesspass#664]
First, thanks for the great password management system. I am generally very happy with it.

I'm using an Android device with a smaller screen. When entering password parameters, the on-screen keyboard covers most of the UI -- the Master Password text box and everything below it. When I hide the OSK, the Generate button or generated password box is still partially hidden by the lower toolbar. Meanwhile, (edit: regardless of whether OSK is visible or not) I cannot scroll the UI elements up or down, so I have to hide the OSK between entering Login and the Master Password and if there are any buttons below the Generate button, I don't have access to them. This means that the app is just barely functional for me by a margin of about 8 pixels, but it could be greatly improved by wrapping the UI elements of the main page in a scrollable widget, much like the Settings and Help pages already are, and the Sign In page also probably should be.

**Comment by muusik** [comment]
I'm using LessPass 9.3.0 from f-droid, which is the latest one available for my device. The phone is a somewhat niche Marshall London running Android 5.0.2. Resolution is 720x1280.

To clarify: on Main page and Sign In page, scrolling does not work regardless of whether OSK is visible.

**Comment by guillaumevincent** [comment]
So if I understand correctly, when you are on the main page, OSK hidden/closed, the generate button is partially visible and you cannot scroll down?

I will push next week version 9.5.0 on fdroid that may fix this for you. I will do more test with smaller screen and this version of Android.

Thank you for the info

**Comment by fl0rian-p** [comment]
Hi @guillaumevincent,
Using the 9.5.0 version from the play store, on a sony xperia z3 compact. On the main page, the field for the generated password can't be seen anymore (see the screenshot below) and we can't scroll down. 
![screenshot_less_pass](https://user-images.githubusercontent.com/2789427/140059029-8e987f5e-4a79-454b-a541-815a65ff81bd.png)

Hope this helps, in identifying the issue !

Thanks !

**Comment by guillaumevincent** [comment]
Thank you,
yes it helps, let me try to fix this.

**Comment by guillaumevincent** [comment]
It will be fixed on version 9.5.1
Thank you for your helps

**Comment by muusik** [comment]
9.5.3 has made it to f-droid and I can confirm that it fixes the scrolling problem. Thank you!

Also, I have to say that the way it now adapts to system dark mode looks great.

**Comment by guillaumevincent** [comment]
Thank you for your issue and feedback !
