### ISSUE TITLE
New Automatic Encryption Sign In Breaks Ability to Login For Multiple Encrypted Passwords

### ISSUE THREAD

**Issue by jonmchan** [lesspass/lesspass#669]
The new sign in process is lacking the ability to encrypt the password multiple times locking me out from the ability to log in to my account. If I understand correctly, a single encryption of the password is being applied right now for all logins. This breaks the use case where the password is encrypted 2 times or more. As such, I can no longer log in to my account and access my passwords.

![image](https://user-images.githubusercontent.com/1827190/139467310-4bc989f0-a1f1-4d75-a23d-5b84c22a6024.png)

**Comment by guillaumevincent** [comment]
Even if I like the hack, there is no really security addition by doing so. I recommend using the forgot password mechanism to reset your password or change your password within the app.

**Comment by jonmchan** [comment]
I would argue this functionality can slightly limit or hamper pure keylogging (with no mouse click logging) attempts. I will concede this type of protection is not too strong and could be improved if there were multiple encryption buttons (they could just be different seeds) that would be presented at random where the user would have to input the right sequence but a keylogging/mouse logging technique would not be able to determine what the original sequence was.

**Comment by guillaumevincent** [comment]
If somebody successfully installed a keylogger on your laptop, generating the password will be really simple. He will try to encrypt the password once, then twice, etc.
I don't want to add features that reduce the user experience.

**Comment by jonmchan** [comment]
I actually use this to access my password on public computers (internet cafe, etc.). 

The feature I'm talking about is have multiple encryption algorithms, say your encryption is through sequence, 1-4-5. Have the different encryption options randomly move around the screen every time you click it hampering replay attacks. Because the algorithms placements are shuffled each time, this defeats keyloggers and mouse replays.

```
|---|
|123|
|456|
|789|
|---|
Click 1

|---|
|369|
|258|
|147|
|---|
Click 4

|---|
|246|
|813|
|579|
|---|
Click 5
```
