### ISSUE TITLE
How do you build the docker container?

### ISSUE THREAD

**Issue by texneus** [lesspass/lesspass#672]
I'm trying to figure out how to self host a Lesspass database.  The wiki only has this to say on the matter:

> If you don't want to use our database, you can deploy your own Docker container. You will need to build the container yourself.

Unless I just missed something, I see no instructions or further guidance.  I stumbled around and was finally able deploy the ready-made container via docker-compose and self signed certs, but at best I'm getting nothing but 404 errors...the actual web content/API seems to be missing in these images?  What steps are necessary to "build the container myself"?

**Comment by guillaumevincent** [comment]
Hello,

I need to update the wiki. I stopped offering support on containers and self-hosting. It takes a lot of time for very little demand.

You need to be familiar with containers.

Containers are available here:

https://github.com/lesspass/lesspass/tree/main/containers

Copying docker-compose.yml and .env files in a folder, and running `docker-compose up -d` should do the job.

If you are running `docker-compose up -d` inside the containers then you need to generate the ssl self signed certificates (see https://github.com/lesspass/lesspass/blob/main/containers/ssl/create_ca_and_ee.sh), you need to update .env.

`docker-compose logs` should give you some information

Environment is listening on port 80 and port 443. Add lesspass.local (or the domain you use) in your hosts file, then visit https://lesspass.local/

Hope it helps

**Comment by texneus** [comment]
> I stopped offering support on containers and self-hosting.

I am sorry to hear this as I think this is an amazingly simple and effective solution to a difficult problem.  Unfortunately not being able to self host will be a deal breaker for me.  I've done everything you stated to setup the container, except I changed all the instances of the host name I could find to the name of my local server.  I can try leaving it as-is as suggested to see if I can get it going, but before I proceed further does this statement imply that the containers will be (or already are) out of date and no longer updated as part of this project?

**Comment by guillaumevincent** [comment]
The container are up to date, https://www.lesspass.com is using those containers.

But when I say "I stopped offering support" I mean:
 * I will not publish my automated ansible installation/backups scripts (they are not configurable enough)
 * If I need to change the containers structure, add new container, etc, I will not create automated migration scripts. I will just change them for my need.
 * I will not spend to much time on admin system support issues (like how to generate SSL certificates, how to renew them, etc)

Now if you understand containers, you have some devops knowledge, and know how to use an orchestration tool like docker-compose, you can easily consume the main docker-compose.yml file.

By the way, if the community really wants self-hosting (if the demand is high enough) then that support could come back. But for now this is not the case.

**Comment by texneus** [comment]
OK, that's fair and pretty consistent with other docker projects I am using.  Let me try some more to get it going with the hints you provided and maybe I can help update the documentation...

**Comment by texneus** [comment]
So here is where I am at...I could use a bit more guidance, perhaps.

The Dockered Lesspass local webpage does indeed work if I do not modify anything and add www/admin/api/lesspass.local to my hosts file.  However -

- Firefox plugin (9.5.1) does not work - I cannot register an email.  I get "Oops!  Something went wrong.  Retry in a few minutes".  On the server console I see the following for each attempt to register.  Is this possibly related to #651 and the self signed certificates?
```
frontend_1   | 192.168.128.5 - - [01/Dec/2021:03:25:49 +0000] "OPTIONS /auth/users/ HTTP/1.1" 405 150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "192.168.1.18"
webserver_1  | 192.168.1.18 - - [01/Dec/2021:03:25:49 +0000] "OPTIONS /auth/users/ HTTP/2.0" 405 150
webserver_1  | 192.168.1.18 - - [01/Dec/2021:03:25:49 +0000] "OPTIONS /auth/users/ HTTP/2.0" 405 150
```

- I don't see any mention of it, but I assume admin.lesspass.local should pull up some kind of a web admin interface.  I get a "Not Found" in Firefox and the following on the server console.  How do you access the admin page?
```
backend_1    | [2021-12-01 03:29:56 +0000] [13] [DEBUG] GET /
backend_1    | Not Found: /
backend_1    | 192.168.128.5 - - [01/Dec/2021:03:29:57 +0000] "GET / HTTP/1.1" 404 179 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
webserver_1  | 192.168.1.18 - - [01/Dec/2021:03:29:56 +0000] "GET / HTTP/2.0" 404 179
webserver_1  | 192.168.1.18 - - [01/Dec/2021:03:29:56 +0000] "GET / HTTP/2.0" 404 179
```

- Trying to use my own server DNS name does not seem to work at all.  I have changed all the lesspass.local entries in .env, adjusted the domains in ssl/domains.ext, and also in ssl/create_ca_and_ee.sh.  It appears you are using Apache as the web server, and while I am not an Apache expert, it's configuration does not seem to be hardwired to use lesspass.local.  What is the secret to using a different domain, such as "myserver.local"?

Thank you once again!

**Comment by guillaumevincent** [comment]
1 - Probably because of missing ALLOWED_HOSTS in .env and in docker-compose.yml https://github.com/lesspass/lesspass/blob/main/containers/backend/lesspass/settings.py#L26-L30
I will fix this.
2 - Can you try https://admin.lesspass.local/admin ?
3 - Changing FRONTEND_HOST and FQDN are enough I think. You need to stop webserver container and start it. `docker-compose down && docker-compose up -d`

**Comment by texneus** [comment]
Finally circling back to this...

1 - Is this something I can fix myself by adding ALLOWED_HOSTS in the .env file?  What format should it be?  I tried variations of lesspass.local and I can't seem to get it to work.

2 - That does work, it give me a Django Administration login page.  Is this local to the docker image or do I need a account with Django somewhere (I'm not familiar with Django).  If local, how do you set up an administrator account, or is accessing this even necessary?

3 - Changed FRONTEND_HOST and FQDN just gives "server not found" (Firefox error) by DNS name, and "Not Found. The requested resource was not found on this server." (404 server error per the console) by IP address.

Are there any other things I can try?

**Comment by guillaumevincent** [comment]
1 - `ALLOWED_HOSTS=.example.org,.lesspass.local` do not forget the `.` at the beginning.

2 - You need to create a super admin using the cli `python manage.py createsuperuser` in the backend container (using `docker exec -it <container_name> bash`

3 - You stop and start the container ?

**Comment by texneus** [comment]
1 - Doesn't seem to change anything, unfortunately.
2 - (didn't try)
3 - Yes, and even pruned between runs to try it all fresh.

Sorry, I'm kinda at my wits end on this.  I'm starting to see why the decision to not support self hosting was made.  I will probably stop here, I'm just spinning my wheels.

Brief summary of steps to get as far as I have, should anyone want to try again.

Note:  As of today the Wiki implies you are responsible for building the docker containers.  The required docker containers are actually already built and includes a docker-compose script.  Running the containers is not difficult.  Configuring them correctly seems to be.

### ON THE SERVER:

Clone the git repository to a local PC (I suspect all that is needed is the containers directory, but this is easy enough)
```
git clone https://github.com/lesspass/lesspass.git
cd lesspass/containers
```

Generate self signed certificates (for testing purposes only - use your favourite service for actual deployment)
`ssl/create_ca_and_ee.sh`

Modify the .env file to add allowed hosts*
```
nano .env
...
ALLOWED_HOSTS=.lesspass.local
```

Start the docker containers:
`docker-compose up`


### ON A CLIENT:
Add lesspass.local URLs to client computer's hosts file
```
nano /etc/hosts
...
[Ser.Ver.IP.Adr]   lesspass.local
[Ser.Ver.IP.Adr]   www.lesspass.local
[Ser.Ver.IP.Adr]   api.lesspass.local
[Ser.Ver.IP.Adr]   admin.lesspass.local
...
```

In a web browser, navigate to `https://www.lesspass.local`.  After accepting the certificate errors, you should now see a screen that is similar to www.lesspass.com.

Change the API URL to https://api.lesspass.local

Create a new user to start accessing the local lesspass server instance.

What I haven't figured out:
Pretty much everything else.

- Using a URL via dns name (www.myserver.local vs. www.lesspass.local)
- The API seems to be inaccessible (attempts to create an account on the web page or browser plugin only result in "Oops! Something went wrong. Retry in a few minutes")
- There is an admin interface at `admin.lesspass.local/admin`, but I haven't looked to see what's inside.

Thank you @guillaumevincent, I truly do appreciate your patience and assistance!

**Comment by guillaumevincent** [comment]
Hello,

thank you for your time testing this.

> Using a URL via dns name (www.myserver.local vs. www.lesspass.local)

Using another DNS should now work after this patch: https://github.com/lesspass/lesspass/commit/432b3042a3f21bfacdf992bc618f75c93471a376


> The API seems to be inaccessible (attempts to create an account on the web page or browser plugin only result in "Oops! Something went wrong. Retry in a few minutes")

You need to change the URL used in the web extension. In the web extension options.

> There is an admin interface at admin.lesspass.local/admin, but I haven't looked to see what's inside.

It's the page that allows you to manage users

**Comment by VlaK0r** [comment]
Hello!
Thank you for your project.

What do I need to change if I want to deploy the project via docker on a server with the address http://localhost:8080 ?
Without SSL
