### ISSUE TITLE
[Android / Security] Add an option to NOT copy the password when generating

### ISSUE THREAD

**Issue by Lurux** [lesspass/lesspass#673]
Hi,

Since a recent update we no longer have an option to generate a password without copying it at the same time, which is definitely a security concern.

Since I mostly use the app to generate passwords that I will later type on my computer, the clipboard functionality is of no use for me, and I would prefer to disable it.

I assume this change was made to things faster; maybe we should have two buttons in this case: "generate and show" vs. "generate and copy" ?

Thanks for the amazing work,
Lurux.

**Comment by guillaumevincent** [comment]
Hello,

I added the functionality in version 9.6.0, it will be available tonight on Open Testing on Android Store and later next week on the different stores.

Thank you

**Comment by Lurux** [comment]
Wow, I'm actually impressed by your reactivity !

Thanks a lot :smile:
