### ISSUE TITLE
Firefox Plugin with V 9.6.4

### ISSUE THREAD

**Issue by jasonbunnell** [lesspass/lesspass#681]
I am using Firefox 95.0.2.  LessPass updated automatically today it seems.  The plugin now does not open.

**Comment by gab12** [comment]
hi 
I confirm I have the same problem.
For me lesspass.min.js is in the root by the code call in dist/

So I replaced
- in popup.html:
`<link rel="stylesheet" href="dist/lesspass.min.css" />`
by
`<link rel="stylesheet" href="lesspass.min.css" />`

and in popup.js:
`  script.src = 'dist/lesspass.min.js';`
by
`  script.src = 'lesspass.min.js';`

And after the addon works.

Note: I never use this addon and see the code before 10min. Maybe My fix is bad.

**Comment by mooreye** [comment]
![lesspass-bug](https://user-images.githubusercontent.com/93423596/147328780-ecf9003b-77c0-4e30-96a3-92dd39103a7d.png)
This is how it looks like for me, after clicking the icon it shows a very thin empty popup.

**Comment by TGM** [comment]
Totally WTF!

**Comment by sg-s** [comment]
same experience here. is it possible to roll back to the previous version?

**Comment by uberneko** [comment]
Same issue here - Mint 20.2 - Firefox 95.0.1 64bits
Exactly like mooreye picture -

**Comment by llyama** [comment]
> same experience here. is it possible to roll back to the previous version?

I rolled back to the previous version from the [firefox addons site](https://addons.mozilla.org/en-GB/firefox/addon/lesspass/versions/) and turned off auto updates for this extension.

**Comment by sg-s** [comment]
9.4.1 works for me

looks like 9.5.0 is broken for everyone

**Comment by guillaumevincent** [comment]
Hello,
sorry I broke the web extension working on the CICD.
9.5.0 should work.

Let me check

Note for myself: Don't do maintenance before holiday

**Comment by PlanetRenox** [comment]
> 9.5.0 should work.

No, I had to revert to 9.4.1
Past couple days wasn't a good experience.

**Comment by guillaumevincent** [comment]
![image](https://user-images.githubusercontent.com/943762/147389776-6cae909e-ceda-4943-9698-2a5f5966ae54.png)

**Comment by guillaumevincent** [comment]
![image](https://user-images.githubusercontent.com/943762/147389812-fb33d064-6a75-4b46-bead-9e60ee78e984.png)

**Comment by sg-s** [comment]
@guillaumevincent thank you so much! we appreciate the work you're doing, this is a great project!

**Comment by tazdij** [comment]
I am running the latest the latest 9.6.4, which automatically updated (which is now disabled after this incident) My plugin does not pop open the dialog

It has been rather inconvenient, as I rely on this to regenerate all of my passwords on all sites and event utilize different operands on each. Please fix urgently.

In the interim, I am thinking of forking, reverting, and directly installing into my browser from my own build. This is rather inconvenient though.

Thanks,
-Don

**Comment by guillaumevincent** [comment]
@tazdij please let the auto update, the version will be rollbacked to 9.5.0
Or manually update to 9.5.0

**Comment by tazdij** [comment]
@guillaumevincent Sorry, but with the possibility that an automatic update, could possibly disable my ability to regenerate a password which I need to log into a system which I utilize for business is just not a good strategy. This was seriously detrimental, to the billable hours I was able to invoice over the last few days. I am not willing to risk this again. In fact, I am likely going to run my own API server also. Then if it goes out, it will solely be my fault. And I cannot be mad at anyone else, for impacting my income. 

Thanks for your continued work on improving this system, I will try to merge the changes and update frequently.

Thanks,
-Don

**Comment by kir0ul** [comment]
Same problem here on Firefox 95.0.1 and LessPass 9.6.4.

![image](https://user-images.githubusercontent.com/6053592/147767883-5f8212bc-2720-4fdd-844b-fd951dcc3421.png)

**Comment by mooreye** [comment]
For me uninstalling and reinstalling the addon fixed it, it didn't update on its own.

**Comment by kir0ul** [comment]
> For me uninstalling and reinstalling the addon fixed it, it didn't update on its own.

Same for me, uninstalling then reinstalling put it back to version 9.5.0 which is working, thanks @mooreye :pray:

**Comment by guillaumevincent** [comment]
I don't understand why Firefox don't rollback automatically. 9.6.4 doesn't exist 

![Screenshot_20220101-215658](https://user-images.githubusercontent.com/943762/147860066-887449e8-107b-4db1-ace1-df8060b8ef83.jpg)

**Comment by guillaumevincent** [comment]
I pushed a version 9.6.5 to fix the auto rollback issue.
Sorry for this, I will be more careful next time.

**Comment by sg-s** [comment]
thank you @guillaumevincent for fixing it!
