### ISSUE TITLE
no longer populating content add-on in firefox

### ISSUE THREAD

**Issue by benbyford** [lesspass/lesspass#683]
Clicking on the lesspass icon in firefox pops up a small empty bubble. 
Only happened very recently. 
I'm running FF 95.0 (64-bit)

**Comment by kir0ul** [comment]
@benbyford Does it looks like the screenshots in https://github.com/lesspass/lesspass/issues/681?
 Also what's your version of LessPass?

**Comment by benbyford** [comment]
Yep same issue

**Comment by guillaumevincent** [comment]
Can you update the web extension and use the latest version 9.6.5 ?
Thank you
