### ISSUE TITLE
Missing pagination

### ISSUE THREAD

**Issue by kktuax** [lesspass/lesspass#693]
Despite have a big number of profiles (124 in my case), only the first page of profiles is shown on the web UI. Search however works and is able to find profiles beyond the first page. It seems like page navigation has disappeared.

Tested with latest firefox and chromium.

![image](https://user-images.githubusercontent.com/3185625/150937487-07820208-761d-4b77-a174-ec2c1e2acc21.png)

**Comment by aperezvelasco** [comment]
It also happens to me with Chrome version 97.0.4692.99

**Comment by guillaumevincent** [comment]
I will fix this asap

**Comment by guillaumevincent** [comment]
It will be fixed in web-extension 9.6.6

**Comment by guillaumevincent** [comment]
It's fixed on lesspass.com

**Comment by kktuax** [comment]
Thank you! It works perfectly again
