### ISSUE TITLE
create superuser

### ISSUE THREAD

**Issue by gkl1368** [lesspass/lesspass#699]
I deploy lesspass in my self host. When I run python manage.py createsuperuser，It always show enter key. What is this key means？

**Comment by guillaumevincent** [comment]
Hello @gkl1368 

the key is probably a reference to https://github.com/lesspass/lesspass/blob/main/containers/backend/api/models.py#L33

We forgot to add it in the  LesspassUserManager here https://github.com/lesspass/lesspass/blob/main/containers/backend/api/models.py#L6-L26

It's a bug
