### ISSUE TITLE
save password profiles on localStorage

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#70]
It will be interesting to save password profiles on localStorage instead of using the connected version.

**Comment by edouard-lopez** [comment]
_instead_? Do you mean to replace remote storage by local one? 
That means you will have to remember the profiles if you switch to other devices…

**Comment by guillaumevincent** [comment]
@edouard-lopez yes and maybe a sync button when connected to le LessPass Database.

**Comment by guillaumevincent** [comment]
I close this one, the store (every information LessPass app use) is now saved in localStorage
