### ISSUE TITLE
Make login more secure with 2FA via emailed code or OTP.

### ISSUE THREAD

**Issue by feature-engineer** [lesspass/lesspass#709]
I love the idea of a stateless password manager, it's a really neat solution for syncing all my passwords.
However, once the extra parameters are known to an attacker, all the generated passwords are as good as a single password used for all the sites. 
Enabling the login via the master password alone lowers the security of the system. 

I suggest 2FA as additional login security. There's node-2fa which seems very easy to add (or pyOTP if used in backend), and adding an option to get code via email, which should be even more secured as no secret should be kept on the server for the latter to work, should also be very easy to add, as django supports sending emails.

I trust that the user profile is saved in encrypted form on the DB (I couldn't locate where it's done in the code, I'm not that familiar with Django).

**Comment by guillaumevincent** [comment]
LessPass Database will be closed in March. [See announcement](https://blog.lesspass.com/2022-12-29/decommissioning-lesspass-database). This issue is no longer relevant. Closing it.
