### ISSUE TITLE
Query api.lesspass.com for profile data using rest or cli

### ISSUE THREAD

**Issue by Mo0nbase** [lesspass/lesspass#710]
Hi there I want to Integrate my password infrastructure with lesspass however I'm just having some peace of mind issues when it comes to the public api. To be clear I think the public api is great however I just need a way to backup my profiles to various local and cloud services so in the event of a down on the api's end or it gets breached or I can't access it for whatever reason I have options. I was just wondering how exactly i can query the rest api directly to return all my password profiles in json or how through the cli app I could do the same. I don't mean to undermine the philosophy of the database I just think redundancy is important. I could self host but this would be much simpler and get the job done for my application.

**Comment by guillaumevincent** [comment]
Hello,

you just want to save your profiles locally ?

please use LessPass cli for this https://github.com/lesspass/lesspass/blob/main/cli/README.md

`lesspass --save`

Thank you

**Comment by guillaumevincent** [comment]
And if you want to consume the API, you can see how it's done in the cli: https://github.com/lesspass/lesspass/blob/main/cli/lesspass/connected.py

**Comment by Mo0nbase** [comment]
Awesome thank you for this closing now. Just a note that the usage for --save in the help section for the cli was a bit confusing i thought i had to provide the application with the api url. Many Thanks!
