### ISSUE TITLE
Will the password generation change if I update my CLI 

### ISSUE THREAD

**Issue by omarali-me** [lesspass/lesspass#713]
My current CLI's version (Linux ubuntu) is 10.0.2 and I noticed the latest version is 10.1.0 

I'm wondering if I update to the latest version, will it change the password-generation algorithm. In fact, the real question is, will you somehow manage to preserve backward compatibility as you upgrade the versions ... I'm sure version 3 will be completely different but incremental improvements - will those change the password-generation ?

**Comment by edouard-lopez** [comment]
Your concern is legit, and we have several practices to maintain compatibility :
1. we follow [SemVer](https://semver.org/), so minor and patch version stay compatibles ;
2. we have plenty of [tests and CI pipeline](https://github.com/lesspass/lesspass/actions) to prevent incompatibilities ;
3. we keep old versions available: https://github.com/lesspass/v1

**Comment by omarali-me** [comment]
Thanks for the response. So I suppose, as long as I stay on a major version, I should be good. 

I wonder if it's possible to have a switch (CLI) or an option in newer versions to say use an older version. So, let's say I have 15 different passwords already being managed by lesspass version M.x.x and I want to shift to M+1.x.x 

So new passwords I generate, can be generated using the new fancier M+1 version, but whenever I use say older password profiles, I can say lesspass -v=10.0.1 to generate using an older version.. 

It's a bit silly .. but what do you think ?

**Comment by guillaumevincent** [comment]
If we change the algorithm, yes we will just add a way to generate the password with the old version
I'm closing this one, I'm not planning to change the algo soon.
