### ISSUE TITLE
When I use the --copy option it copies Error: Can't open display: (null) Copied to clipboard

### ISSUE THREAD

**Issue by tintin10q** [lesspass/lesspass#716]
I would expect `lesspass site example.com --counter 1 --copy` to copy the password to the clipboard. But instead it copies:

Copied to clipboard

to the clipboard.

I installed lesspass with  
python3 -m pip install --user lesspass

**Comment by guillaumevincent** [comment]
Hello @tintin10q,

which OS are you using ?

https://github.com/lesspass/lesspass/blob/main/cli/lesspass/clipboard.py#L18-L44

Can you run this in your terminal and tell me if you see the same error ?

`xclip -selection clipboard mypassword`

**Comment by tintin10q** [comment]
Yes it that gives me `Error: Can't open display: (null)`

**Comment by guillaumevincent** [comment]
Ok so `xclip` is not installed correctly ?

**Comment by guillaumevincent** [comment]
I closing this one, you need xclip installed on your system to be able to use this command
