### ISSUE TITLE
Your iOS app works on macOS (M1) too

### ISSUE THREAD

**Issue by gmacar** [lesspass/lesspass#717]
Your app in the Apple App Store works perfectly on macOS too (Apple Silicon M1 processors): you can ask Apple to add the "verified for macOS" badge in the App Store. 👍

<img width="1512" alt="LessPass on macOS" src="https://user-images.githubusercontent.com/26346831/163577064-0bbb52fb-d022-4f37-b367-64610029a447.png">

**Comment by guillaumevincent** [comment]
Oh nice, I will add support for mac os then
Thank you for testing

**Comment by guillaumevincent** [comment]
It should be available for new Apple Silicon M1 processors now.
Thank you
