### ISSUE TITLE
Scrolling issue on iPhone SE 2020

### ISSUE THREAD

**Issue by HiramTheHero** [lesspass/lesspass#720]
When I use lesspass on my iPhone, I run into issues after putting in all the info to generate a password. After doing so, I am met with the following screen and can’t do anything about it. (Making the app, essentially, useless.)

![1B4FD0AD-4525-43DB-8C77-BB2C64AD8F87](https://user-images.githubusercontent.com/22198719/166147523-1af7c585-921f-43dc-a44e-2da353ff15cf.png)

In the App Store, it says that there was an issue that fixed the scrolling, but it still doesn’t look like it is fixed.

![17670786-63AB-40FB-8EE1-AFDA796CE56E](https://user-images.githubusercontent.com/22198719/166147585-053d12cf-769c-4c3e-bd83-3fd1f54cd499.jpeg)

Thank you for the hard work on the app.

**Comment by guillaumevincent** [comment]
I will try to reproduce it on a simulator ASAP
sorry for the late reply

**Comment by guillaumevincent** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-05-25 at 23 07 28](https://user-images.githubusercontent.com/943762/170367632-04d8e24f-b560-4db9-93f9-8a4ec83bdd7f.png)

I try to upgrade some package, and I don't have the same issue on an iPhone SE simulator
I will try to produce a new version next week

**Comment by guillaumevincent** [comment]
I'm closing this one, if you still have the issue, please reopen
