### ISSUE TITLE
Add ability to logout with lesspass cli

### ISSUE THREAD

**Issue by Mo0nbase** [lesspass/lesspass#725]
So recently for my password profiles i wanted to change my registered email address for the api.lesspass.com database. Well there was no options to do this in any of the applications so I saved all my profiles through the CLI using `lesspass --save`. It then prompted for a email and password and saved the profiles. Then I went and deleted all the profiles on the old email. My problem is that I can't get lesspass CLI to log me out of the database account that i signed in on so i can use a different email to then `lesspass --load` my profiles. There should be a way to change your email and a way to logout of the CLI.

**Comment by guillaumevincent** [comment]
Hello,
I probably need to add a way to disconnect from database.

Tokens are saved in this file https://github.com/lesspass/lesspass/blob/main/cli/lesspass/connected.py#L13
Config path : https://github.com/lesspass/lesspass/blob/main/cli/lesspass/connected.py#L13

You can delete `~/.config/lesspass/config.json` file to logout

**Comment by guillaumevincent** [comment]
This feature is present in the latest version of LessPass cli 10.2.0
Thank you for reporting this idea
