### ISSUE TITLE
Should I worry about password length?

### ISSUE THREAD

**Issue by atgumart** [lesspass/lesspass#726]
Hello!
Based on what I've read in the wiki, the bigger the password length is, the more entropy it will consume to generate a password. So, using a strong and complicated master password, should I worry about how big the length is?

**Comment by guillaumevincent** [comment]
https://pages.nist.gov/800-63-3/sp800-63b.html

> A.2 Length
> Password length has been found to be a primary factor in characterizing password strength [[Strength]](https://pages.nist.gov/800-63-3/sp800-63b.html#strength) [[Composition]](https://pages.nist.gov/800-63-3/sp800-63b.html#composition). Passwords that are too short yield to brute force attacks as well as to dictionary attacks using words and commonly chosen passwords.

In short prefer a long password than a complex shorter one
