### ISSUE TITLE
Backup Preferences

### ISSUE THREAD

**Issue by trinityzhub** [lesspass/lesspass#728]
LessPass is awesome, Is it possible to backup the preference ( such as Options user given earlier, Length and counter for each entry)

### **Just consider a scenario:**
Lesspass server shutdown unexpectedly, May be some github fork will help us to generate password. 
But still we might be forgotten Options /Length /Counter for that particular entry

I guess my suggestion is not foolish one, it will be very helpful if you can provide backup feature.

**WHY PREFERENCE IS NOT FIXING BY USER:**

- Some sites not allowing some special character
- Incrementing counter for each "password change" recommendation from domain

### For lesspass creator:
I would like to thank for your effort on creating such a great tool

_please ignore grammatical mistakes_

**Comment by guillaumevincent** [comment]
Hello @trinityzhub,
Thank you for your kind words.

Backup is possible only using the cli now.
`lesspass --help` to see the doc

**Comment by guillaumevincent** [comment]
LessPass Database will be closed in March. [See announcement](https://blog.lesspass.com/2022-12-29/decommissioning-lesspass-database). This issue is no longer relevant. Closing it.
