### ISSUE TITLE
doesn't work on Safari on iOS 

### ISSUE THREAD

**Issue by sg-s** [lesspass/lesspass#73]
> Available everywhere LessPass is a web application and works on all devices (computer, smartphone, tablet and your smartTV)

The form doesn't render on iOS (see screenshot below). 

![img_0073](https://cloud.githubusercontent.com/assets/6005346/20234660/568d08e0-a84d-11e6-89f9-a71611bb91e7.PNG)

maybe linked to #33?

**Comment by panther2** [comment]
LessPass works fine with Safari, Chrome, Opera Coast here on IPad with iOS 10.1.1

**Comment by guillaumevincent** [comment]
@sg-s lesspass-webcrypto is just an experiment. For now we use nodejs crypto browserified library. So no it's not related.
**Which version of iOS and Safari are you using ?**

**Comment by sg-s** [comment]
hey, thanks for the response! I tested this on a iPad Pro running iOS 10.0.2. i'll try updating and report back.

**Comment by sg-s** [comment]
updated to 10.1.1, still don't see it... are you seeing the form on lesspass.com @panther2 ?

**Comment by guillaumevincent** [comment]
@sg-s maybe ES6 error
What version of Safari ?

**Comment by sg-s** [comment]
i can't see a way of figuring this out -- it's the latest version, which ships with iOS 10.1.1

**Comment by guillaumevincent** [comment]
Open Safari and go to http://whatsmyuseragent.com

**Comment by guillaumevincent** [comment]
It works for me on Iphone OS 10.1.1
Apple WebKit 602.2.14
Safari 602.1

**Comment by panther2** [comment]
> updated to 10.1.1, still don't see it... are you seeing the form on lesspass.com @panther2 ?

Yes, I do.

**Comment by sg-s** [comment]
i give up. my user agent on my iPad is the same as @guillaumevincent, but it doesn't seem to show up. works fine on my ancient iPhone, though, so it's probably something weird about my iPad. I'm going to close this, as I don't think this bug has anything to do with lesspass.com
