### ISSUE TITLE
Android app should mark clipboard content as sensitive

### ISSUE THREAD

**Issue by Tachi107** [lesspass/lesspass#734]
On Android 13, a clipboard preview will pop up every time the user copies something. Apps copying sensitive content to the clipboard can tell it to Android, so that the popup preview will get suppressed.

See Android's documentation for info on how to do it; it looks trivial: <https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent>

![Screenshot_20220918-192334.png](https://user-images.githubusercontent.com/34214253/190920611-b252365b-788f-4f08-933a-83a1fc4af876.png)

**Comment by guillaumevincent** [comment]
@Tachi107 thank you for reporting this, I will look at it

**Comment by guillaumevincent** [comment]
It will be fixed in version 9.7.1

Internal testing available here: https://play.google.com/apps/internaltest/4698635866249182586

I updated the code to the latest version of React Native, so I need to do more test before pushing it into production.

**Comment by Tachi107** [comment]
Awesome, thanks!

**Comment by guillaumevincent** [comment]
It's on production version 9.7.2
Thank you for reporting this issue.

**Comment by Tachi107** [comment]
Thank you again for the fix :D
