### ISSUE TITLE
self-hosted container setup not working - webserver keeps restarting

### ISSUE THREAD

**Issue by ipiazza** [lesspass/lesspass#736]
Hello team,
first of all thanks for the great product! I use it a lot and I also brought my family and team mates do the same.

I am trying to leave as less details as possible about the places where I have an account and thus a username and a password, hence I am attempting to setup lesspass in self-hosted mode.

I basically copied the docker-compose.yml and .env files together with the .ssl directory and put under the docker-compose directory lesspass.

I ran the script create_ca_and_ee.sh but it didn't as it was stating it couldn't create the certificate file as a directory with the same name was existing.

So I tweaked the script renaming lesspass.crt and lesspass.key in the script with certificate.crt and certificate.key and that helped.

Now I built the stack with docker-compose up -d but the webserver keeps restarting and the log reports the following:

**2022-10-28T20:26:12.565775350Z SSLCertificateFile: file '/usr/local/apache2/conf/ssl/lesspass.crt' does not exist or is empty
2022-10-28T20:26:19.348269153Z AH00526: Syntax error on line 140 of /usr/local/apache2/conf/extra/httpd-ssl.conf:**

Though, I created the ssl directory under the lesspass docker-compose directory copying the crt and key files I got from the script onto lesspass.crt and lesspass.key directories respectively.

Can you please give me a hand understand what I am doing wrong?

Thanks a lot,
RJ

**Comment by guillaumevincent** [comment]
Hello @ipiazza 

sorry for the late reply

If you change the name of the default certificate, you also need to update `CRT_PATH=ssl/lesspass.crt` and `KEY_PATH=ssl/lesspass.key` in your .env.

https://github.com/lesspass/lesspass/blob/main/containers/.env#L15-L16

Did you do that ?

**Comment by ipiazza** [comment]
Apologize @guillaumevincent, I was even slower... :)

Please find down below my `.env` file. I stripped out the `POSTGRES_PASSWORD, SECRET_KEY, DATABASE_PASSWORD` variables.

`POSTGRES_DB=postgres`
`POSTGRES_USER=postgres`
`ALLOWED_HOSTS=.lesspass.local`
`DATABASE_ENGINE=django.db.backends.postgresql`
`DATABASE_NAME=postgres`
`DATABASE_USER=postgres`
`DATABASE_HOST=db`
`DATABASE_PORT=5432`
`FRONTEND_HOST=www.lesspass.local`
`FQDN=lesspass.local`
`EMAIL=admin@lesspass.local`
`CRT_PATH=ssl/lesspass.crt`
`KEY_PATH=ssl/lesspass.key`
`DEBUG=0`
`COMPOSE_PROJECT_NAME=lesspass`
`EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend`
`EMAIL_HOST=localhost`
`EMAIL_PORT=25`
`EMAIL_HOST_USER=`
`EMAIL_USE_TLS=0`
`EMAIL_USE_SSL=0`

Are you able to point me towards what I am doing wrong?

Thanks!

**Comment by guillaumevincent** [comment]
Do you have `ssl/lesspass.crt` and `ssl/lesspass.crt` present ?

> So I tweaked the script renaming lesspass.crt and lesspass.key in the script with certificate.crt and certificate.key and that helped.

You probably want 

```
CRT_PATH=ssl/certificate.crt
KEY_PATH=ssl/certificate.key
```

no ?
