### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Eloitor** [lesspass/lesspass#737]
I'm trying to package lesspass for void linux. https://github.com/void-linux/void-packages/pull/39181

I'm using the source "pure-9.5.6" from github, which includes tests. However some tests fail: https://pastebin.com/SkbSYddC

Is this a known problem? What should I do?

### Details
<details>
<summary>Tests results</summary>
<pre>
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.1.2, pluggy-1.0.0
rootdir: /builddir/lesspass-pure-v9.5.6/cli
plugins: flake8-1.1.1
collected 82 items

tests/test_cli.py ...................................                    [ 42%]
tests/test_fingerprint.py F                                              [ 43%]
tests/test_functional.py FF.                                             [ 47%]
tests/test_interaction.py F                                              [ 48%]
tests/test_password_generation.py ..................                     [ 70%]
tests/test_profile.py ........................                           [100%]

=================================== FAILURES ===================================
_____________________________ test_get_fingerprint _____________________________

    def test_get_fingerprint():
>       assert get_mnemonic(b"password") == "⚗️🗄️🍺"

tests/test_fingerprint.py:5: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

password = b'password'

    def get_mnemonic(password):
>       fingerprint = get_fingerprint(get_hmac_sha256(password.encode("utf-8")))
E       AttributeError: 'bytes' object has no attribute 'encode'

lesspass/fingerprint.py:87: AttributeError
_________________________ TestFunctional.test_exclude __________________________

self = <tests.test_functional.TestFunctional testMethod=test_exclude>

    def test_exclude(self):
        p = pexpect.spawn(
            'python3 lesspass/core.py  site login masterpassword -d -L6 --exclude "0123456789"'
        )
        output = p.read().decode()
    
>       self.assertTrue("error: you can't exclude all chars available" in output)
E       AssertionError: False is not true

tests/test_functional.py:40: AssertionError
_________________ TestFunctional.test_length_below_the_minimum _________________

self = <tests.test_functional.TestFunctional testMethod=test_length_below_the_minimum>

    def test_length_below_the_minimum(self):
        p = pexpect.spawn(
            "python3 lesspass/core.py  site login masterpassword --lowercase --digits --length 2"
        )
        output = p.read().decode()
    
>       self.assertTrue("error: argument -L/--length: 2 is out of range, choose in [5-35]" in output)
E       AssertionError: False is not true

tests/test_functional.py:18: AssertionError
___________________ TestInteraction.test_keyboard_interrupt ____________________

self = <tests.test_interaction.TestInteraction testMethod=test_keyboard_interrupt>

    def test_keyboard_interrupt(self):
        p = pexpect.spawn("python3 lesspass/core.py --prompt")
>       p.expect("Site: ")

tests/test_interaction.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.10/site-packages/pexpect/spawnbase.py:343: in expect
    return self.expect_list(compiled_pattern_list,
/usr/lib/python3.10/site-packages/pexpect/spawnbase.py:372: in expect_list
    return exp.expect_loop(timeout)
/usr/lib/python3.10/site-packages/pexpect/expect.py:179: in expect_loop
    return self.eof(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pexpect.expect.Expecter object at 0x7f0100926080>
err = EOF('End Of File (EOF). Exception style platform.')

    def eof(self, err=None):
        spawn = self.spawn
    
        spawn.before = spawn._before.getvalue()
        spawn._buffer = spawn.buffer_type()
        spawn._before = spawn.buffer_type()
        spawn.after = EOF
        index = self.searcher.eof_index
        if index >= 0:
            spawn.match = EOF
            spawn.match_index = index
            return index
        else:
            spawn.match = None
            spawn.match_index = None
            msg = str(spawn)
            msg += '\nsearcher: %s' % self.searcher
            if err is not None:
                msg = str(err) + '\n' + msg
    
            exc = EOF(msg)
            exc.__cause__ = None # in Python 3.x we can use "raise exc from None"
>           raise exc
E           pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
E           <pexpect.pty_spawn.spawn object at 0x7f0100924f10>
E           command: /usr/bin/python3
E           args: ['/usr/bin/python3', 'lesspass/core.py', '--prompt']
E           buffer (last 100 chars): b''
E           before (last 100 chars): b'ted.py", line 6, in <module>\r\n    import requests\r\nModuleNotFoundError: No module named \'requests\'\r\n'
E           after: <class 'pexpect.exceptions.EOF'>
E           match: None
E           match_index: None
E           exitstatus: None
E           flag_eof: True
E           pid: 3957
E           child_fd: 13
E           closed: False
E           timeout: 30
E           delimiter: <class 'pexpect.exceptions.EOF'>
E           logfile: None
E           logfile_read: None
E           logfile_send: None
E           maxread: 2000
E           ignorecase: False
E           searchwindowsize: None
E           delaybeforesend: 0.05
E           delayafterclose: 0.1
E           delayafterterminate: 0.1
E           searcher: searcher_re:
E               0: re.compile(b'Site: ')

/usr/lib/python3.10/site-packages/pexpect/expect.py:122: EOF
=============================== warnings summary ===============================
lesspass/cli.py:109
  /builddir/lesspass-pure-v9.5.6/cli/lesspass/cli.py:109: DeprecationWarning: invalid escape sequence '\ '
    help=f"[beta] Save your password profiles. /!\ File not encrypted. Use carefully. (default: {backup_file})",

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_fingerprint.py::test_get_fingerprint - AttributeError: 'byt...
FAILED tests/test_functional.py::TestFunctional::test_exclude - AssertionErro...
FAILED tests/test_functional.py::TestFunctional::test_length_below_the_minimum
FAILED tests/test_interaction.py::TestInteraction::test_keyboard_interrupt - ...
=================== 4 failed, 78 passed, 1 warning in 3.06s ====================
</pre>
</details>

**Comment by edouard-lopez** [comment]
The `lesspass-pure` package is in JavaScript, you are not executing the correct tests or you are talking about the CLI (which is written in Python).

Our pipeline is run with Python [version `3.6` and `3.8`](https://github.com/lesspass/lesspass/actions/runs/1858855351).

@guillaumevincent Did you test against `3.10`?

**Comment by edouard-lopez** [comment]
#738 is passing with `3.10`

**Comment by Eloitor** [comment]
> The `lesspass-pure` package is in JavaScript, you are not executing the correct tests or you are talking about the CLI (which is written in Python).

I'm talking about the cli.

> 
> Our pipeline is run with Python [version `3.6` and `3.8`](https://github.com/lesspass/lesspass/actions/runs/1858855351).
> 
> @guillaumevincent Did you test against `3.10`?

Which source am I supposed to use? Right now I'm using `https://github.com/lesspass/lesspass/archive/refs/tags/pure-v${version}.tar.gz`. I tried to use the sources from pypi, but it seems that those do not include tests...

**Comment by edouard-lopez** [comment]
#738 is based on the latest commit on `main` so you can try

https://github.com/lesspass/lesspass/archive/84e185a3bc92d12bd5beb10d3f1ea7d87c18d577.zip

**Comment by Eloitor** [comment]
I tried with the sources from https://github.com/lesspass/lesspass/archive/84e185a3bc92d12bd5beb10d3f1ea7d87c18d577.zip but I got the same error...

**Comment by edouard-lopez** [comment]
### Reproduce

I can't reproduce your problem when I download the zip in a `pipenv shell` with python `3.10.7`

```
❯ pipenv shell                                                                                                                                                                                                     
❯ cd lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/                                                                                               

❯ cd cli/                                                                                                                                                      
~/projects/contributions/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/cli                                                                                                                                     

❯ pip install --requirement=./test-requirements.txt                                                                                                            
Requirement already satisfied: tox in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r ./test-requirements.txt (line 1)) (3.27.0)                      
Requirement already satisfied: pytest in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r ./test-requirements.txt (line 2)) (7.2.0)                    
Requirement already satisfied: flake8 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r ./test-requirements.txt (line 3)) (5.0.4)                  
Requirement already satisfied: mock in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r ./test-requirements.txt (line 4)) (4.0.3)                      
Requirement already satisfied: pexpect in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r ./test-requirements.txt (line 5)) (4.8.0)                   
Requirement already satisfied: pluggy>=0.12.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (1.0.0)       
Requirement already satisfied: py>=1.4.17 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (1.11.0)          
Requirement already satisfied: tomli>=2.0.1 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (2.0.1)         
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/
site-packages (from tox->-r ./test-requirements.txt (line 1)) (20.16.6)                                                                                                                                            
Requirement already satisfied: six>=1.14.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (1.16.0)         
Requirement already satisfied: filelock>=3.0.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: packaging>=14 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r ./test-requirements.txt (line 1)) (21.3)         
Requirement already satisfied: attrs>=19.2.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r ./test-requirements.txt (line 2)) (22.1.0)
Requirement already satisfied: iniconfig in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r ./test-requirements.txt (line 2)) (1.1.1)         
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r ./test-requirements.txt (line 2)) (
1.0.1)                     
Requirement already satisfied: pycodestyle<2.10.0,>=2.9.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r ./test-requirements.txt (line 3))
 (2.9.1)                                                                                                                                                                                                           
Requirement already satisfied: pyflakes<2.6.0,>=2.5.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r ./test-requirements.txt (line 3)) (2.
5.0)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r ./test-requirements.txt (line 3)) (0.7.
0)
Requirement already satisfied: ptyprocess>=0.5 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pexpect->-r ./test-requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from packaging>=14->tox->-r ./test-requirements.txt
 (line 1)) (3.0.9)
Requirement already satisfied: platformdirs<3,>=2.4 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20
.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox->-r ./test-requirements.txt (line 1)) (2.5.2)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.
4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox->-r ./test-requirements.txt (line 1)) (0.3.6)
```

### Tests execution

```
❯ ./test                                                                                                                                                       
Requirement already satisfied: pip in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (22.3)                                                                   
Collecting pip                                                                                                                                                                                                     
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)                                                                                                                                                                 
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 3.3 MB/s eta 0:00:00                                                                                                                                      
Installing collected packages: pip                                                                                                                                                                                 
  Attempting uninstall: pip                                                                                                                                                                                        
    Found existing installation: pip 22.3                                                                                                                                                                          
    Uninstalling pip-22.3:                                                                                                                                                                                               Successfully uninstalled pip-22.3
Successfully installed pip-22.3.1                                                                                                                                                                                  Processing /home/edouard/projects/contributions/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/cli
  Preparing metadata (setup.py) ... done                                                                                                                                                                           Requirement already satisfied: requests in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from lesspass==10.1.0->-r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from requests->lesspass==10.1.0->-r requirements.txt (
line 1)) (1.26.12)                                                                                       
Requirement already satisfied: idna<4,>=2.5 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from requests->lesspass==10.1.0->-r requirements.txt (line 1)) 
(3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from requests->lesspass==10.1.0->-r requirements.tx
t (line 1)) (2.1.1)                                                                                      
Requirement already satisfied: certifi>=2017.4.17 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from requests->lesspass==10.1.0->-r requirements.txt (lin
e 1)) (2022.9.24)
Building wheels for collected packages: lesspass                                                         
  Building wheel for lesspass (setup.py) ... done                                                        
  Created wheel for lesspass: filename=lesspass-10.1.0-py3-none-any.whl size=12031 sha256=8dc7a30dc3b2beff3569c40a4008a399147be5d2328bda16a18f8f727723530c
  Stored in directory: /tmp/pip-ephem-wheel-cache-zjplmqi7/wheels/6a/f2/81/a5a1fddc2e8baf1fb7d899f8d48afae348aa058e8f787c7e52
Successfully built lesspass
Installing collected packages: lesspass
  Attempting uninstall: lesspass
    Found existing installation: lesspass 10.1.0
    Uninstalling lesspass-10.1.0:
      Successfully uninstalled lesspass-10.1.0
Successfully installed lesspass-10.1.0
Requirement already satisfied: tox in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r test-requirements.txt (line 1)) (3.27.0)
Requirement already satisfied: pytest in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r test-requirements.txt (line 2)) (7.2.0)
Requirement already satisfied: flake8 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r test-requirements.txt (line 3)) (5.0.4)
Requirement already satisfied: mock in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r test-requirements.txt (line 4)) (4.0.3)
Requirement already satisfied: pexpect in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from -r test-requirements.txt (line 5)) (4.8.0)
Requirement already satisfied: filelock>=3.0.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: tomli>=2.0.1 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: pluggy>=0.12.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: py>=1.4.17 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: six>=1.14.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: packaging>=14 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from tox->-r test-requirements.txt (line 1)) (21.3)
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/
site-packages (from tox->-r test-requirements.txt (line 1)) (20.16.6)
Requirement already satisfied: attrs>=19.2.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r test-requirements.txt (line 2)) (22.1.0)
Requirement already satisfied: iniconfig in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r test-requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pytest->-r test-requirements.txt (line 2)) (1.
0.1)
Requirement already satisfied: pycodestyle<2.10.0,>=2.9.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r test-requirements.txt (line 3)) (
2.9.1)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r test-requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: pyflakes<2.6.0,>=2.5.0 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from flake8->-r test-requirements.txt (line 3)) (2.5.
0)
Requirement already satisfied: ptyprocess>=0.5 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from pexpect->-r test-requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from packaging>=14->tox->-r test-requirements.txt (
line 1)) (3.0.9)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.
4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox->-r test-requirements.txt (line 1)) (0.3.6)
Requirement already satisfied: platformdirs<3,>=2.4 in /home/edouard/.env/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87-oE2QiJ1e/lib/python3.10/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20
.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox->-r test-requirements.txt (line 1)) (2.5.2)
.................................................................................
----------------------------------------------------------------------
Ran 81 tests in 1.303s

OK
```

### Context

```
❯ python --version
Python 3.10.7

❯ pip freeze 
attrs==22.1.0
certifi==2022.9.24
charset-normalizer==2.1.1
distlib==0.3.6
exceptiongroup==1.0.1
filelock==3.8.0
flake8==5.0.4
idna==3.4
iniconfig==1.1.1
lesspass @ file:///home/edouard/projects/contributions/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/cli
mccabe==0.7.0
mock==4.0.3
packaging==21.3
pexpect==4.8.0
platformdirs==2.5.2
pluggy==1.0.0
ptyprocess==0.7.0
py==1.11.0
pycodestyle==2.9.1
pyflakes==2.5.0
pyparsing==3.0.9
pytest==7.2.0
requests==2.28.1
six==1.16.0
tomli==2.0.1
tox==3.27.0
urllib3==1.26.12
virtualenv==20.16.6
```

**Comment by guillaumevincent** [comment]
In your tests:

`import requests\r\nModuleNotFoundError: No module named \'requests\'\r\n'`

Do you need to install also python dependencies ?

https://github.com/lesspass/lesspass/blob/main/cli/setup.py#L19

And also, can you check the lang of the system ?

`echo $LC_ALL`

I'm not sure the terminal is correctly configured to handle UTF-8 chars

**Comment by Eloitor** [comment]
Hi again, I missed the `requests` dependency. I just tested using the steps described here.

```
pipenv shell                                                                                                                                                                                                     
cd lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/                                                                                               
cd cli/                                                                                                                                                      
pip install --requirement=./test-requirements.txt
./test
```

And it worked. However using pytest gives a failing test with the message "AttributeError: 'bytes' object has no attribute 'encode' ". I don't understand why. I used:

```
pipenv shell                                                                                                                                                                                                     
cd lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/                                                                                               
cd cli/                                                                                                                                                      
pip install --requirement=./test-requirements.txt
python3 -m pytest
```

And the result was:

```
========================================== test session starts ===========================================
platform linux -- Python 3.11.1, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/eloi/test/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/cli
collected 82 items

tests/test_cli.py ...................................                                              [ 42%]
tests/test_fingerprint.py F                                                                        [ 43%]
tests/test_functional.py ...                                                                       [ 47%]
tests/test_interaction.py .                                                                        [ 48%]
tests/test_password_generation.py ..................                                               [ 70%]
tests/test_profile.py ........................                                                     [100%]

================================================ FAILURES ================================================
__________________________________________ test_get_fingerprint __________________________________________

    def test_get_fingerprint():
>       assert get_mnemonic(b"password") == "⚗️🗄️🍺"

tests/test_fingerprint.py:5:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

password = b'password'

    def get_mnemonic(password):
>       fingerprint = get_fingerprint(get_hmac_sha256(password.encode("utf-8")))
E       AttributeError: 'bytes' object has no attribute 'encode'

lesspass/fingerprint.py:87: AttributeError
============================================ warnings summary ============================================
lesspass/cli.py:109
  /home/eloi/test/lesspass-84e185a3bc92d12bd5beb10d3f1ea7d87c18d577/cli/lesspass/cli.py:109: DeprecationWarning: invalid escape sequence '\ '
    help=f"[beta] Save your password profiles. /!\ File not encrypted. Use carefully. (default: {backup_file})",

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================== short test summary info =========================================
FAILED tests/test_fingerprint.py::test_get_fingerprint - AttributeError: 'bytes' object has no attribute 'encode'
================================ 1 failed, 81 passed, 1 warning in 1.22s =================================
```

**Comment by guillaumevincent** [comment]
I need to understand why this test is not failing in the CI.

Because I can't see why this is working: `get_mnemonic(b"password")` A byte string cannot be `password.encode("utf-8")`

We are probably not running this test

**Comment by guillaumevincent** [comment]
Ok so the CI was not running this test. It should be good now.
Sorry, the test was not in a unittest class, so unittest module just ignored it.

**Comment by Eloitor** [comment]
By the way, which version of lesspass should I use to package for Void Linux?
I thought v9.7.2.tar.gz might be the right choice, although it seems that it was last updated on October 20th. 
Thank you in advance.

**Comment by guillaumevincent** [comment]
main branch ?

https://github.com/lesspass/lesspass/archive/refs/heads/main.zip

**Comment by Eloitor** [comment]
To create a package for the cli version of lesspass for void, I'd need to use the source tar.gz from a specific version, but I see that the names are not consistent:
[mobile-v9.7.3.tar.gz](https://github.com/lesspass/lesspass/archive/refs/tags/mobile-v9.7.3.tar.gz), [pure-v9.5.6.tar.gz](https://github.com/lesspass/lesspass/archive/refs/tags/pure-v9.5.6.tar.gz)
Is there a reason for the different name pattern?

Moreover the releases in PyPI do not match the ones in this repo: [lesspass-10.1.1.tar.gz](https://files.pythonhosted.org/packages/1d/51/8eb29a008eab0b95c486e30393478b4654e8f4c58c2e3d0829ec0de4445c/lesspass-10.1.1.tar.gz) (which is outdated and doesn't include the tests.

I guess using [mobile-v9.7.3.tar.gz](https://github.com/lesspass/lesspass/archive/refs/tags/mobile-v9.7.3.tar.gz) would be fine, but I want to be sure.

**Comment by guillaumevincent** [comment]
The tag are needed for different application.
mobile is the mobile app, the tag is needed by FDroid
pure is the core web component, used by the website and the web extension.
Versions are diffferent, just ignore them.

Version on pypi is 10.1.1 yes, https://github.com/lesspass/lesspass/blob/main/cli/lesspass/version.py

If you want a specific version, use the sha256 of one commit. For example https://github.com/lesspass/lesspass/archive/0d4453bb29c1ad51fbec2d7677bcaa8957a7a68f.zip

**Comment by Eloitor** [comment]
Hi, it's generally a good idea to package specific versions of software to ensure that users have access to a stable and reliable version. In this case, it seems like the best option would be to package the version of the software that is available on PyPI. However, it appears that the tests for the software are missing from these sources. Is it possible to add the tests to the PyPI sources?

**Comment by guillaumevincent** [comment]
@Eloitor it is not. The fixed versions which are more stable is a pipe dream. A more stable version is a fast moving main branch with a lot of tests (unit, e2e, production testing).

Version on pypi are automatically uploaded as soon as I put a new version number here https://github.com/lesspass/lesspass/blob/main/cli/lesspass/version.py#L1

I can add the tests to the pypi sources yes. But I don't understand your need. If you want a fixed version, take one commit.

> To create a package for the cli version of lesspass for void, I'd need to use the source tar.gz from a specific version

Yes so take a specific sha256. If you want one, take the latest commit from the main branch.

**Comment by Eloitor** [comment]
This is a [requirement for packaging software for void](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): 

"Software need to be used in version announced by authors as ready to use by the general public - usually called releases. Betas, arbitrary VCS revisions, templates using tip of development branch taken at build time and releases created by the package maintainer won't be accepted."

The versions released in pypi count as "announced  by authors as ready to use by the general public". If you can add the tests to the sources there, I will package lesspass for void (it requires packages to pass the tests for each new release)

**Comment by guillaumevincent** [comment]
@Eloitor is like for FDroid a cli-vX.Y.Z tag works for you ?

**Comment by Eloitor** [comment]
Awesome, I'll package lesspass for void linux and for alpine linux using the releases cli-vX.Y.Z.

Thank you!
