### ISSUE TITLE
Need for sanitizing password export CSV file

### ISSUE THREAD

**Issue by deepers** [lesspass/lesspass#748]
I've exported my passwords to CSV using `--export` in the CLI and then tried importing them into Bitwarden (I selected Chrome CSV as the format). Unfortunately this doesn't work that well for passwords containing a `,` character. Would you be able to sanitize the CSV output so that `,` characters in passwords are properly quoted? Thanks!

**Comment by guillaumevincent** [comment]
I will fix this
Thank you

**Comment by deepers** [comment]
Thanks @guillaumevincent. I really like the concept of Lesspass, and I've enjoyed using the CLI and web extension.

**Comment by guillaumevincent** [comment]
It has been fixed on version 10.2.1
https://pypi.org/project/lesspass/10.2.1/

**Comment by deepers** [comment]
Thanks @guillaumevincent. It works now!
