### ISSUE TITLE
[webextension] Lag when clicking on LessPass icon

### ISSUE THREAD

**Issue by vendforce** [lesspass/lesspass#75]
theres a delay when you click on the lesspass icon in firefox it shows the dropdown arrow then the rest of the login box appears about 1 sec later, its not very fluid 

please fix thanks

**Comment by guillaumevincent** [comment]
The lag doesn't appear in chrome extension.
It's looks like a Firefox issue.

**Comment by guillaumevincent** [comment]
So the lag appear in chrome too
I merge those two

**Comment by edouard-lopez** [comment]
For me the lag vary a lot and is usually between 2-6s on Firefox, almost none existent on Chrome.

@vendforce I'm using plenty of extensions (20+) that might slowdown my Firefox, what about you?

**Comment by vendforce** [comment]
No I'm only using about three extensions

**Comment by guillaumevincent** [comment]
Actually we are using the non minified version in the web extension because of Mozilla.
I reduced the bundle size. I will investigate and see if it helps.

**Comment by guillaumevincent** [comment]
I changed how LessPass load bundle javascript
It will be fix in web extension 2.1.1
