### ISSUE TITLE
[webextension] Lag when clicking on Chrome icon

### ISSUE THREAD

**Issue by jajajaime** [lesspass/lesspass#76]
Same as [#75](https://github.com/lesspass/lesspass/issues/75) but on Chrome.
[I recorded the lag here.](https://dl.dropboxusercontent.com/u/1886325/LessPassChromeLag.mov)
Running Chrome Version 54.0.2840.98 (64-bit) on macOS 10.12.1.

**Comment by guillaumevincent** [comment]
Thank you same as #75 
I close this one

Thank you
