### ISSUE TITLE
A different password is generated if logged into the API server

### ISSUE THREAD

**Issue by davidebeatrici** [lesspass/lesspass#766]
#767

**Comment by guillaumevincent** [comment]
I'm sorry I didn't understand the issue

**Comment by davidebeatrici** [comment]
I'm referring to the browser's extension.

When I log in, the generated password is wrong even if the fields are the same.

**Comment by edouard-lopez** [comment]
@davidebeatrici did you see the discussion on #767?

**Comment by davidebeatrici** [comment]
Thank you, it definitely seems to be the same issue.
