### ISSUE TITLE
[webextension] Command+Shift+L doesn't work on Chrome on Mac

### ISSUE THREAD

**Issue by jajajaime** [lesspass/lesspass#77]
Running Chrome Version 54.0.2840.98 (64-bit) on macOS 10.12.1.

Being on a Mac, I also tried cmd+shift+L just in case, with no luck.

**Comment by guillaumevincent** [comment]
The shortcut is `Command+Shift+L` https://github.com/lesspass/webextension/blob/master/extension/manifest.json
Will search to see if a chrome bug.

**Comment by sg-s** [comment]
shortcut doesn't work for me either. on macOS 10.12.1, running Chromium 51.0.2683.0 (64-bit)

**Comment by guillaumevincent** [comment]
@sg-s and @jajajaime does `Command+Shift+L` mapped to a shortcut on OS x ?

**Comment by guillaumevincent** [comment]
There is a[ bug on chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=657985&q=shortcut%20Command%2BShift%2BL&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) for this one

**Comment by jajajaime** [comment]
Still nothing.
Running Chrome 55.0.2883.75.

**Comment by sg-s** [comment]
doesn't work on firefox either

**Comment by guillaumevincent** [comment]
@sg-s yes https://github.com/lesspass/lesspass/issues/23
It will be fixed in version 52

**Comment by guillaumevincent** [comment]
I merge #23 
For now shortcut works on Chrome on Windows and Linux.

**Comment by guillaumevincent** [comment]
@jajajaime can you test shortcuts `Command+Shift+L` and `Ctrl+Shift+L` and Chrome 56 on https://w3c.github.io/uievents/tools/key-event-viewer.html?

**Comment by jajajaime** [comment]
This is what I get

cmd + shift + L
<img width="1141" alt="screen shot 2017-02-13 at 9 38 30 am" src="https://cloud.githubusercontent.com/assets/13631233/22895131/4de9de8a-f1d0-11e6-9be5-911ccdaf2306.png">


ctrl + shift + L
<img width="1182" alt="screen shot 2017-02-13 at 9 39 04 am" src="https://cloud.githubusercontent.com/assets/13631233/22895130/4de48926-f1d0-11e6-9984-1c2a23035697.png">

**Comment by guillaumevincent** [comment]
yeah the bug is fixed on firefox!
@jajajaime any updates on Chrome 57.0.2987 on mac os?
can you check you have no conflict in extension shortcuts > open tab with chrome://extensions/configureCommands

**Comment by jajajaime** [comment]
It was set to nothing. Once I set it up, the shortcut works.

**Comment by guillaumevincent** [comment]
Ok lets close this one so
Thank you for your patience

**Comment by sg-s** [comment]
thanks! works for me on chromium 58!
