### ISSUE TITLE
add support for getting the master password from a command

### ISSUE THREAD

**Issue by monperrus** [lesspass/lesspass#773]
today, the master password can be given in CLI, environment variable or live prompt.

it would be great to add support for getting the master password from a command.

```
--master-pw-program "get-master.sh"
lesspass --master-pw-program "get-master.sh" http://example.com foo
```
get-master.sh would do whatever we want, such as talking to a hardware token (#387) or to the native password keyring.

**Comment by edouard-lopez** [comment]
I reckon you are looking for parameter expansion/command substitution syntax in your shell:

Sh/Bash/Zsh [syntax](https://tldp.org/LDP/abs/html/commandsub.html)
```
$ lesspass foo.org username $(echo $RANDOM)
```

Fish [syntax](https://fishshell.com/docs/current/language.html#command-substitution)
```
❯ lesspass foo.org username (random)
```

**Comment by guillaumevincent** [comment]
Yes this can be handled by your terminal as mentionned by @edouard-lopez
