### ISSUE TITLE
Extension adding 3-icon fingerprint everywhere ?

### ISSUE THREAD

**Issue by KaKi87** [lesspass/lesspass#775]
Hello,

I find the 3-icon password fingerprint to be a very clever way to tell the user whether they typed their password properly without revealing what they typed at all.

So, I'm wondering, like there are browser extensions that add a *reveal* button to all password inputs on all pages, if it would be possible to create a one that adds the 3-icon fingerprint ?

Thanks

**Comment by edouard-lopez** [comment]
If I'm understanding you question correctly, you want a visual fingerprint on each website password's field, right?

If that's so, I'm not aware of such an extension on Firefox and as [we described in the wiki](https://github.com/lesspass/lesspass/wiki/Visual-Fingerprint):

> Visual fingerprint (or visual checksum) is here to help detect and correct typos **on the master password.**

So having a visual fingerprint on each password field means on each password, i.e. 3 different icons for each site. So, you are going back to having to “know” each of the password or their visual fingerprint to know whether you made a mistake or not. LessPass aims to help you avoid having to know all your password by asking you only one (the master password)

**Comment by KaKi87** [comment]
> you want a visual fingerprint on each website password's field, right?

That's right.

> you are going back to having to “know” each of the password or their visual fingerprint to know whether you made a mistake or not.

True.

Well, I use LessPass for critical accounts, and a password manager for normal accounts.

So, first, I could use the visual fingerprint for my password manager.

But I also have special accounts, which need special passwords, for special reasons (e.g. shared with other people who all need to know it by heart).

Those are cases where I could also use the visual fingerprint.

Thanks

**Comment by KaKi87** [comment]
Alright, I'll probably import it into a new project of mine.

Thanks
