### ISSUE TITLE
Mobile: Keyboard navigation not working in PasswordGeneratorScreen

### ISSUE THREAD

**Issue by ramenhost** [lesspass/lesspass#778]
I've been using Samsung Dex with physical keyboard. It gets bothersome when pressing tab does not move the focus to next input field (site -> login -> masterpassword). I would love to have that at least in the PasswordGeneratorScreen.   

#### Tested on:
Android 13 (OneUI 5.1)
Lesspass 9.7.2 (latest Playstore release as of 11-Aug-2023)

**Comment by guillaumevincent** [comment]
> It gets bothersome when pressing does not move the focus to next input field

When pressing what?

**Comment by ramenhost** [comment]
Oops, markdown mistake. Updated the description.
Pressing tab key does not navigate between the input fields. This is not exclusive to Dex and applies to "Done" or "Next" keys shown in on-screen keyboards as well.

**Comment by ramenhost** [comment]
It appears that handling the physical keyboard 'tab' key in React Native is not as straightforward as I anticipated. I've made a PR that enhances the user experience on soft keyboard. This also facilitates 'enter' key navigation using a physical keyboard, which is something I'll have to settle for.
