### ISSUE TITLE
How lesspass protects master password from being bruteforced?

### ISSUE THREAD

**Issue by 0xcrypto** [lesspass/lesspass#779]
I might be wrong as I haven't tested this yet, but I think the way Lesspass works seems to be insecure. 

Let's say I generate a password with lesspass for a website. The website got hacked and the password got leaked. Now an attacker might be able to bruteforce the master password from the same knowledge that lesspass uses to generate same passwords again.

To generate a password,  lesspass creates an SHA256 hash using master password and a salt having website URL, username, and a counter. Counter is just integers incremented. Website URL and username can be obtained from hacked databases. Master password then, can be bruteforced using commonly known passwords or random passwords. It is just a matter of time that master password gets cracked. Easier the master password, faster it will be cracked.

**Comment by 0xcrypto** [comment]
Oh wait, yes. The password should not be complete hash.

**Comment by guillaumevincent** [comment]
Yeah it's pbkdf2 encryption with 100k iterations.
If you use a strong master password (>20 chars) you should be fine for the next couple of years at least.
