### ISSUE TITLE
Extra Password Field

### ISSUE THREAD

**Issue by abueide** [lesspass/lesspass#78]
Having an extra, optional, password field that would compare against the first password field would be useful to prevent typos with a long master password.

**Comment by guillaumevincent** [comment]
@abueide the fingerprint is the solution for this no ?
Memorize your three icons and it will show you a typo
![fingerprint](https://lesspass.com/dist/masterPasswordPattern.png)

**Comment by abueide** [comment]
Oh thats what those are for... interesting concept. Sorry about that then.

**Comment by guillaumevincent** [comment]
yes :)
no problem 

it shows that is not very clear

**Comment by abueide** [comment]
Are those generated from the master password or the hash password? If from the hash password, you'd have to memorize it for each website? Also how likely is a collision where 2 different passwords show the same symbols?

**Comment by guillaumevincent** [comment]
@abueide from master password only. There is 59^3 different combinaisons. So it's suffisant to avoid collisions on typo.
