### ISSUE TITLE
Mobile Font Does Not Differentiate Between Zero and O

### ISSUE THREAD

**Issue by sandsalamand** [lesspass/lesspass#780]
The .ttf file has a special zero to differentiate it from O, but this is not displayed in the app (android). This makes it very difficult to tell whether a character is a zero or an O when typing it manually into another device.

**Comment by edouard-lopez** [comment]
Thanks for taking the time to share about your experience. 

The only `ttf` font mention I found for Android in our source code is [for the icons](https://github.com/lesspass/lesspass/blob/91810ea9f736021ab93662f30a104ccd3574f717/mobile/android/app/build.gradle#L84). 

On my device, the `O` (capital `o`) and `0` (zero) are rendered differently. Here is a screenshot from my device that use PixelExperience (Android 13.0)

![LessPass-font-O-0](https://github.com/lesspass/lesspass/assets/1212392/f73143e4-8489-4510-a8cd-66fb4aedd7c4)

**Comment by sandsalamand** [comment]
Ok, I'm unable to reproduce it now. Maybe I had just assumed that the font of the generated password was the same as the font for the site input field, where the zero and O look similar.

Is there a reason for using two different fonts there? 
 [Here](https://github.com/lesspass/lesspass/tree/main/mobile%2Fassets%2Ffonts) is the generated password font.

**Comment by edouard-lopez** [comment]
The font change was to fix #490. 
Input fields are either automatically filled (_e.g._ URL) or typed by the user (willingly), so no need ambiguity exists. However, the password is generated by the app and should be readable when you can't use the copy/paste feature and need to read character by character. For instance, when generated on phone to use on the Desktop or vice versa.

So we only focus the change where it is needed.
