### ISSUE TITLE
Certificate expired on www.lesspass.com

### ISSUE THREAD

**Issue by arkeros** [lesspass/lesspass#788]
The certificate for www.lesspass.com expired on 11/6/2023.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

![image](https://github.com/lesspass/lesspass/assets/991767/7fd2df88-c741-42a9-a842-b3d6e278546a)

**Comment by edouard-lopez** [comment]
That's fixed (related to #765
![image](https://github.com/lesspass/lesspass/assets/1212392/1167988b-a594-4a88-8e1f-1f373cc7df75)
