### ISSUE TITLE
Firefox extension shortcut not working on OS X

### ISSUE THREAD

**Issue by alexandru** [lesspass/lesspass#79]
I installed the extension and tried `Cmd+Shift+L` and `Control+Shift+L`, but aren't working.

- Firefox: 50.0 (beta channel), tried with a fresh instance with no extensions installed
- macOS Sierra 10.12.1

**Comment by guillaumevincent** [comment]
Yes it's a known bug https://github.com/lesspass/lesspass/issues/23
Wait for next version of Firefox
