### ISSUE TITLE
The LessPass application is no longer available on the Apple App Store

### ISSUE THREAD

**Issue by dcharbon** [lesspass/lesspass#793]
First, thank you to the folks who make this app 👏 It's awesome and appreciated. I recently had to upgrade my phone and have discovered that the app has been removed from the App store. Is this intended? Thanks!

**Comment by guillaumevincent** [comment]
I renewed the Apple Developer Program today. I will keep this issue open until the application is in the store.

**Comment by guillaumevincent** [comment]
LessPass has been updated and can be downloaded on the app store

**Comment by dcharbon** [comment]
@guillaumevincent Thank you!!
