### ISSUE TITLE
add a keyboard shortcut to open the LessPass pop-up

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#8]
I'm lazy and don't like to use my mouse to open the extension pop-up. 

Using the form is straight-forward and fast, adding a keyboard shortcut will reduce friction even more (good for power-user).

**Comment by guillaumevincent** [comment]
It will be fixed in Aurore version

fixed by https://github.com/lesspass/webextension/commit/af87ebcc8898458fc66345052ccde5da283174dc

**Comment by guillaumevincent** [comment]
This doesn't work on Firefox

**Comment by guillaumevincent** [comment]
Firefox doesn't support `_execute_browser_action` command.
[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1246034)
Probably will be fix in Firefox 52

I close and open an issue for Firefox
