### ISSUE TITLE
Suggestion: a lighter, cache-enabled mobile-friendly frontend

### ISSUE THREAD

**Issue by alexandru** [lesspass/lesspass#80]
I forked [lesspass/pure](https://github.com/lesspass/pure) into [alexandru/lesspass-pure](https://github.com/alexandru/lesspass-pure) and have modified it like this:

1. increased the iterations count [as instructed](https://github.com/lesspass/lesspass/issues/38#issuecomment-260276133)
2. added [HTML5 app cache](http://www.w3schools.com/HTML/html5_app_cache.asp), such that it can work offline
3. imported the `manifest.json` file, along with `apple-touch-` and `favicon` and `icon` meta tags from the `frontend` project

I now have it deployed at https://lesspass.alexn.org/ and it's pretty cool. 

I suggest a lighter `frontend` project, without the marketing, ready to be forked for self-deployment and for easy changing of config options.

Cheers,

**Comment by guillaumevincent** [comment]
@alexandru thank you for this,
I will check this

the lighter frontend without the marketing is `lesspass-pure`

**Comment by guillaumevincent** [comment]
@alexandru On mobile it freeze completely my browser during more than 5 seconds. Iphone 6. :cry: 

I see that you update the debounce timing to 3s. On mobile it's a breath. :+1:  Need to add this on lesspass/pure.

Need to add app.cache too. :+1: 

Thank you

**Comment by alexandru** [comment]
@guillaumevincent yeah, it's very slow, it's very slow in Firefox on the desktop as well, but personally I don't mind :) 

Btw, the problem isn't the time it takes to calculate that password, but that the interface freezes. If it would be possible to split the required computation in batches of work executed asynchronously to keep the interface from freezing, along with a loading spinner, it would have been much better.

Of course, maybe this would be a non-issue with another algorithm, like Scrypt or something, just throwing suggestions.

**Comment by guillaumevincent** [comment]
@alexandru If Safari fix the bug on webcrypto we will migrate on 100k without any problem. I already worked on a webcrypto implementation that is really fast : https://github.com/lesspass/core/blob/master/webcrypto.js. `npm run test:webcrypto`

I'm looking also to make the computation in a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) with a spinner.

And maybe we will migrate to 100k if there is on mobile a native alternative.
Scrypt is good but not implemented well on browser, see https://github.com/lesspass/lesspass/issues/56

**Comment by guillaumevincent** [comment]
I close
Feel free to create a PR for the HTML5 app cache if you want in https://github.com/lesspass/frontend
