### ISSUE TITLE
[webextension] Typo on forgot password link

### ISSUE THREAD

**Issue by aharris88** [lesspass/lesspass#81]
I found a small typo in the Chrome extension. I couldn't find the part in the code where this was, or I would have submitted a pull request:

Forgot you password ?

should be

Forgot your password?

you should be your
And there shouldn't be a space before the question mark

**Comment by guillaumevincent** [comment]
@aharris88 thank you, do you want to create the pull request to be in the contributors ? 
https://github.com/lesspass/pure/blob/master/src/views/Login.vue#L89

**Comment by aharris88** [comment]
Thanks. I created a PR. https://github.com/lesspass/pure/pull/1

**Comment by guillaumevincent** [comment]
thank you
