### ISSUE TITLE
More in depth overview of project

### ISSUE THREAD

**Issue by abueide** [lesspass/lesspass#83]
So what i've gathered from poking around the pure module is the actual password generator that is used on the website, firefox and chrome plugins. If i change something on this, it will also change on the website, and plugins right?
Also, i'm trying to do "npm run build" but every time i run into something new to npm install. Can some one give me a more precise build instruction with a list of dependancies?

**Comment by guillaumevincent** [comment]
`lesspass-pure` is the pure component used by cozy, webextension and frontend. See the package.json file for every projects.

To update the frontend for example, we need to build the new `lesspass-pure`, push on npm, install `lesspass-pure` on frontend project (`npm install --save lesspass-pure`) and rebuild frontend (`npm run build`)

> Also, i'm trying to do "npm run build" but every time i run into something new to npm install. Can some one give me a more precise build instruction with a list of dependancies?

can you do 

    npm --version
    node --version

**Comment by guillaumevincent** [comment]
I close. 
I checked the build is idempotent.
Feel free to post on this thread to ask for extra help.

**Comment by abueide** [comment]
@guillaumevincent thanks
