### ISSUE TITLE
Some consonants and symbols are never in a generated password

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#84]
@tgulacsi [found](https://github.com/lesspass/lesspass/issues/82) a bug on [_getPasswordChar](https://github.com/lesspass/core/blob/master/index.js#L89-L103) method. 

`_getPasswordChar`  take a `charType` (consonant lowercase, vowel lowercase, consonant uppercase, vowel uppercase, number and symbol) and a `charCode`.
For a given char type (example: `C`=consonant uppercase) and a char code (`49`= number 1) we return the equivalent in the password chars:

    const passwordsChars = {
        ...
        C: 'BCDFGHJKLMNPQRSTVWXZ',
        ...
    };

    'BCDFGHJKLMNPQRSTVWXZ'[49 % 20]
    'M'

The problem is that this `charCode` can have only 16 different values because it is retrieved from a hex chain.

So 4 consonants letters (20 consonants - 16 values) and 9 symbols (25 symbols - 16 values) are never reach.

~~The impact on security is low, because the transformation (prettyPrint) is only here to render a `pbdkf2` hash. The security is in the `_encryptLogin` function.~~

**Comment by tgulacsi** [comment]
I disagree: the printed & used passwords uses a shorter alphabet than advertised, which weakens the security.

For the default 12 length, 
  'vc' it is 5^6*20^6 = 10^13 vs. 5^6*16^6 = 2.6 * 10^12 , 
  for 'vcs' it is 5^4*20^4*25^4 = 3.9*10^13 vs. 5^4*16^8 = 2.7*10^12.
An order of magnitude less possibility!

**Comment by guillaumevincent** [comment]
@tgulacsi What threat is there ?
I'm talking about `how to find the master password by brute force`.

For this the attacker needs the password generated (stolen in a database). It must assume the password information (default information) plus the email (also in the database) and the name of the site.
For all those information the attacker need to build one generated password after another and compare with the stolen one.

So I still don't understand why default 12 length is a problem. 
Let's try to stay as simple as possible.

**Comment by tgulacsi** [comment]
You're right, the master password is not at risk, just the generated passwords are weaker than they should be (narrower alphabet).

**Comment by guillaumevincent** [comment]
will be fix in lesspass/core v2
