### ISSUE TITLE
LessPass application on Android store is not an official application

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#85]
A vigilant user has informed me that a LessPass application is available on the American Android store. 
This is **not an official application**.

---

![don't use](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Dialog-stop-hand.svg/200px-Dialog-stop-hand.svg.png)
**Do not use this one and do not enter your master password.**

---

We will contact the creator.
If developers on Android have advice on how to handle this, do not hesitate.

https://play.google.com/store/apps/details?id=br.com.wgbn.lesspass

**screenshots:**

![unnamed](https://cloud.githubusercontent.com/assets/943762/20323028/7be13b58-ab7b-11e6-9fcb-06a60f62b5a1.png)
![unnamed2](https://cloud.githubusercontent.com/assets/943762/20323030/7be6c46a-ab7b-11e6-9b2e-ef983014fa47.png)
![unnamed3](https://cloud.githubusercontent.com/assets/943762/20323029/7be5a968-ab7b-11e6-9faa-81d92775fac0.png)

**Comment by edouard-lopez** [comment]
Also you should be aware that @iDams already started to work on an android port. Please see #6.

**Comment by iDams** [comment]
Hey, just so you know I've created the issue but I am not working on porting the project on android. 
I think @Rudloff is ;)

**Comment by guillaumevincent** [comment]
@iDams yes I edited the post, I'm working on it actually

**Comment by guillaumevincent** [comment]
The creator replied and it would seem that his intentions are not bad.
The name and the description of the application will change.
I keep the issue open until it's done.

**Comment by guillaumevincent** [comment]
Walter Gandarella remove the application from the store
I close
