### ISSUE TITLE
"Connected" version does not stay logged in

### ISSUE THREAD

**Issue by blahgeek** [lesspass/lesspass#86]
It seems that my account is automatically logged out after a short period of time (several hours?), is this a bug or intentional feature? Can this be changed? Thanks!

I'm using chrome extension version.

**Comment by guillaumevincent** [comment]
Hi,
it's a feature, your are automatically logged out after 15 minutes of inactivity.
https://github.com/lesspass/backend/blob/ac2a9aa3b0e4fe36a1c3ac24d1f291d900b00932/lesspass/settings.py#L124
