### ISSUE TITLE
More keyboard shortcuts would be great

### ISSUE THREAD

**Issue by blahgeek** [lesspass/lesspass#87]
e.g.

- Press Enter in `Master Password` field -> copy generated password
- Ctrl-Shift-? -> Toggle "abc" option
- Ctrl-Shift-? -> Toggle "ABC" option
-....

**Comment by guillaumevincent** [comment]
We will improve shortcut when chrome and firefox fix existings bugs (https://github.com/lesspass/lesspass/issues/77 and https://github.com/lesspass/lesspass/issues/23)

**Comment by edouard-lopez** [comment]
More shortcuts mean increasing probability of conflicts with existing shortcuts (from others extensions and OS). In order to manage such conflicts it will require us to add an interface to let the user customize their shortcuts.

And as you can see shortcuts are buggy across browsers…

**Comment by blahgeek** [comment]
Ok, thanks, Understood... But some simple shortcuts (like pressing Enter after entering master password copies the generated password?) should be easy to implementation, am I correct?

**Comment by guillaumevincent** [comment]
@blahgeek copy paste on the web should be easy, but it is not. We use clipboardjs that relies on both Selection and execCommand APIs to copy the password. I don't know how to copy password with only Js triggered by an event. Will try to improve this part.

**Comment by guillaumevincent** [comment]
@blahgeek in version 2 you will be able can hit enter to generate password.
And tab + enter to copy

I close and for now we stay with only one shortcut to open the web extension.
After you can fill the form and use tab, space to check uncheck and enter to build password.
