### ISSUE TITLE
How to import passwords? 

### ISSUE THREAD

**Issue by edent** [lesspass/lesspass#9]

**Comment by edent** [comment]
Is it possible to import passwords from another password manager?

**Comment by guillaumevincent** [comment]
@edent LessPass has no database and does not save passwords. The philosophy of the tool is very different from other password management tools. It is therefore difficult to import passwords from another password manager.
LessPass passwords derived from information that only you know (site/login/master password).

Imagine a password in keepass for **facebook.com** generated  **qz4w9clO**
In LessPass with master password : **password** and login **contact@example.org** password is derived to **otYS4,exET6:** for **facebook.com**
We don't have a way to make the derivation equals to **qz4w9clO**

In the future of LessPass, all information can be saved except master password. Maybe we will develop a way to encourage people to change passwords to LessPass passwords. 
**We can imagine importing sites and logins from other password manager.**

@edent Is this is what you had in mind ? (with the connected version)

**Comment by edent** [comment]
Ah! I see, that's not made very clear on the (mobile) website. 

I like that philosophy, but it has two problems. 

1. I need to change *all* my passwords. That's a few hundred accounts. 
2. How does this cope if a site forces me to change my password? For example Dropbox recently reset my password, and my work needs me to change pw every 90 days. 

Will have a play with it and see if it works for my needs

**Comment by guillaumevincent** [comment]
1/ Change all your passwords will not be instantaneous. We need to gamify the process. But without the new connected version, for now the feature is pending.
2/ To change your password without changing your master password, there is a counter field. Connected version will help you to memorize those info for you.
