### ISSUE TITLE
Reversing Hashes with Similar Input

### ISSUE THREAD

**Issue by abueide** [lesspass/lesspass#92]
Given a large set of hashes generated by a master password, is it possible to use the hashes to find the master password? Can some one link a good resource on the topic?

For example is a hash of the string "randomtext" going to bear absolutely no resemblence/patterns to the hash "randomtext1", except for cases of coincidence?

Thanks in advance

**Comment by sg-s** [comment]
> For example is a hash of the string "randomtext" going to bear absolutely no resemblence/patterns to the hash "randomtext1", except for cases of coincidence?

it shouldn't, if you use a good cryptographic hashing function, which lesspass does. here's the [wikipedia](https://en.wikipedia.org/wiki/PBKDF2) article on PBKDF2, which lesspass uses

**Comment by abueide** [comment]
@sg-s allright. what i'm wondering is if an attacker had the hashes of a large amount of variations of the master password ("randomtext", "randomtext1", "randomtext2" ..., "randomtext1000"), is there any way for the attacker to weaken the hash or possibly reverse it, the password being randomtext.

**Comment by sg-s** [comment]
that sort of attack is precisely what a "Cryptographic hash function" like SHA-2 stronger than just a "hash function" like md5. i'd suggest you read up more about the hashing function used here, as your question is about its security, rather than its implementation here: look for "collision resistance".

**Comment by guillaumevincent** [comment]
MD5 is not bad because there is some collision, it's bad because it's fast.

I close to clean repo, feel free to continue on this thread.
Thanks

**Comment by abueide** [comment]
@sg-s yeah thanks. that's what I was looking for. I didn't really know the terms to search for the subject, or how it was done here, so thats why I asked here. It was just a question that came up while I was thinking about this project and was curious to learn more, not necessarily that I thought there was a problem with the software. Anyways thanks!
