### ISSUE TITLE
Interface for v2

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#93]
Quote from @guillaumevincent extracted from #88:
> @abe33 here an idea of how we handle the migration with UI
> ![screenshot from 2016-11-19 13-32-12](https://cloud.githubusercontent.com/assets/943762/20455455/9b6f09f8-ae5c-11e6-8fe3-c69decb19363.png)

**Comment by edouard-lopez** [comment]
@guillaumevincent why move the version so far from the button? Dummy question: 

> Is the version related to the site?

**Comment by guillaumevincent** [comment]
There is no dummy questions, only dummy answers. 
The version is not related to the site. Maybe drop down generated button is more appropriate

**Comment by guillaumevincent** [comment]
here the [jsfiddle](https://jsfiddle.net/p0berz4f/)

**Comment by guillaumevincent** [comment]
Here the new interface much better on mobile:

![screen shot 2016-11-23 at 18 53 27](https://cloud.githubusercontent.com/assets/943762/20573276/52f6cbf6-b1af-11e6-97d1-34ceac201180.png)
![screen shot 2016-11-23 at 18 53 38](https://cloud.githubusercontent.com/assets/943762/20573277/52f7bcf0-b1af-11e6-8f7d-c875dac4eeb1.png)
![screenshot_20161123-185538](https://cloud.githubusercontent.com/assets/943762/20573314/80816234-b1af-11e6-915b-0db72ac2d51e.png)
![screenshot_20161123-185916](https://cloud.githubusercontent.com/assets/943762/20573315/808360ac-b1af-11e6-99c6-cf3b5e59108e.png)
![screenshot_20161123-185923](https://cloud.githubusercontent.com/assets/943762/20573313/80813192-b1af-11e6-8b07-7edda073e414.png)
![screenshot_20161123-185927](https://cloud.githubusercontent.com/assets/943762/20573311/806f4f86-b1af-11e6-95c4-3b9de10a05d7.png)
![screenshot_20161123-185931](https://cloud.githubusercontent.com/assets/943762/20573312/807f4a3a-b1af-11e6-8c1a-2a58e93509c4.png)

**Comment by edouard-lopez** [comment]
@guillaumevincent I add some description. Screenshot and description will be useful for the changelog/blog post.

**Comment by abe33** [comment]
Hi there, nice work!

As @edouard-lopez, I find the version selector a bit hidden. While v2 will be released, one might want to replace all its previously generated passwords with v2 ones and I think it might be worth putting it up front.
Also, why using a select input for version? As is, you need 3 actions to get to v1: open the settings, click on the select then click on the version. Given that there's only two options right now (and versions won't grow as fast as to have dozen of them in a near future) I think a segmented control would offer a better UX here (see http://www.lukew.com/ff/entry.asp?1950 for reference).

**Comment by guillaumevincent** [comment]
@abe33 : @edouard-lopez spend all day asking me to remove this ugly select 😄 
Ok you win ! I will improve this

**Comment by edouard-lopez** [comment]
I showed the UI to @delphine-graeff, she gave me some useful feedbacks.

### Where am I?

There is few distinction between private mode (default) and connected mode.
We could mitigate this by having different theme in both mode/panes like what Firefox do with their private mode. Below you can clearly which one is private

![firefox-private-vs-public-browsing](https://cloud.githubusercontent.com/assets/1212392/20603541/44958b70-b262-11e6-853d-1927b1390542.png)
![chrome-incognito](https://cloud.githubusercontent.com/assets/1212392/20603435/d44ceda4-b261-11e6-8e3f-37a328ceff12.png)

Similar situation between generation pane and sign-in/register pane. Evolving the header like a mini-breadcrumd might be enough:

**private mode**
> Lesspass › private

**connected mode**, wording should be considered (e.g. _connected_ vs. _online_, etc.):
> Lesspass › connected

**sign-in**
> Lesspass › sign-in

etc.
### `copy` button is confusing

 _"What is copied?"_ was one of the question as there is nothing new to copy. The button use the same location as the `generate` button and is just after the `Master Password` field so look like that's what we copy or the whole profile. 

Github display the field, which is not really a good thing in our case and as visually state what has been copied (by selecting the URL)

![lesspass-github-copy-default](https://cloud.githubusercontent.com/assets/1212392/20603245/ea4a65b0-b260-11e6-93a4-337382671892.png)

![lesspass-github-copy-done](https://cloud.githubusercontent.com/assets/1212392/20603241/e6c07038-b260-11e6-82c7-476a482dafd6.png)

**Comment by guillaumevincent** [comment]
Here the new interface much better on mobile:

### v2

| screenshot | description |
| --- | --- |
`v2` will become the default. | ![img_2177](https://cloud.githubusercontent.com/assets/943762/20626587/0a8cc592-b31b-11e6-8c83-6e1ab690c084.PNG)
`v1` will become **obsolete, but still available** | ![img_2193](https://cloud.githubusercontent.com/assets/943762/20626540/bff4004a-b31a-11e6-93c5-20a42bd3fb86.PNG)
You can now **select the algorithm version**.<br>Options have been revamp to be more user-friendly. |  ![img_2178](https://cloud.githubusercontent.com/assets/943762/20626619/33ab211c-b31b-11e6-8da6-7804b9cf2fc1.PNG)
the switch to `webcrypto` API allows **faster generation of stronger password** (100k iterations). | ![img_2204](https://cloud.githubusercontent.com/assets/943762/20626640/619b3dc8-b31b-11e6-84af-6bbb1719e41e.PNG)
Generated password is now hidden by default. <br>New layout is more **mobile-friendly**. | ![img_2205](https://cloud.githubusercontent.com/assets/943762/20626680/9e62977e-b31b-11e6-847f-cb16be26c9c4.PNG)
Once the password is generated you can **copy it securily**. | ![img_2206](https://cloud.githubusercontent.com/assets/943762/20626706/b7f069dc-b31b-11e6-9584-d2ae19119b18.PNG)
If you need to **type it on another device** you can display it by clicking on it | ![img_2208](https://cloud.githubusercontent.com/assets/943762/20626753/fe0f8c72-b31b-11e6-96c7-b3da25e0d21f.PNG)


What do you think @abe33 ?

**Comment by abe33** [comment]
Looks good to me 👍 

I guess the v1/v2 buttons are just toggles from one version to the other?

**Comment by guillaumevincent** [comment]
@abe33 yes, you click on it and see color changing for header and button

**Comment by guillaumevincent** [comment]
I close the new version is online
