### ISSUE TITLE
Add Option for "Connected" to "Remember Me"

### ISSUE THREAD

**Issue by philip-ulrich** [lesspass/lesspass#94]
I find myself having to re-login to my personal hosted "Connected" version multiple times a day. I find this very annoying and personally do not value the security of hiding the values hidden by such from anyone logged into my computer. Can we add an optional "Remember Me" to keep logged in to the connected version?

**Comment by guillaumevincent** [comment]
@philip-ulrich We increased token validity by 45 minutes. We went from 15 minutes to 60 minutes.
It allows to wait a little while waiting for this functionality.

**Comment by philip-ulrich** [comment]
Much appreciated! Still think a "remember me" button that is good for like a month (less would be fine too I guess) would be awesome! I understand y'all are working on 2.0 though so if you decide to implement, take your time. No rush. :)

**Comment by guillaumevincent** [comment]
I agree and we will develop this functionality

**Comment by philip-ulrich** [comment]
Is there any update on this? The actual functionality should be pretty simple to implement. I can try to help with this if needed.

**Comment by guillaumevincent** [comment]
@philip-ulrich feel free to propose a PR.
a simple solution is to increase JWT_EXPIRATION_DELTA on the backend up to 7 days because we do not protect very critical data. User can logout (it remove actual jwt).

what do you think ?

**Comment by philip-ulrich** [comment]
Okay, that's fair. Normally a remember me checkbox would be more appropriate, but since this is something that most people wouldn't use on a public computer (or if they would, I'd hope they would care to log out)... I suppose that we can just set the default to 7 days. Like you said, the data isn't very sensitive so there isn't much harm in the setting. Let me take a look and throw over a PR

**Comment by philip-ulrich** [comment]
Not sure if you noticed this or not, but the sub module hasn't been updated in the lesspass repo yet. (Unless my phone is showing the commits I correctly)

**Comment by guillaumevincent** [comment]
@philip-ulrich I will update it manually tomorrow

**Comment by philip-ulrich** [comment]
Put in a PR for you to save you some work.
