### ISSUE TITLE
Remember "Site" field for current domain in connected mode

### ISSUE THREAD

**Issue by blahgeek** [lesspass/lesspass#95]
This is related to #45 . Say we are in `account.example.com` and create a new password in lesspass with site field set to `example.com`, next time we visit `account.example.com` to login, lesspass would still have the site field set to `account.example.com` by default. It would be great if lesspass (connected mode) would remember that I used the Site `example.com` while visiting `account.example.com` and would give me that Site value every time I am visiting `account.example.com`.

**Comment by guillaumevincent** [comment]
@blahgeek if you save `account.example.com` in the connected mode you will see `account.example.com` in the saved profiles. In site if you start typing `accoun...` you can select the autocomplete `account.example.com`.

What you want is to autofill by a subdomain if present when visiting corresponding domain ?

**Comment by blahgeek** [comment]
Yes, I mean if I save `example.com` while visiting `account.example.com`, next time I visit `account.example.com` and open the lesspass extension, the Site field should be default to `example.com`, without typing `examp...` and select it from dropdown.

(Also, here `example.com` can be any string, not necessary anything related to `account.example.com`)

**Comment by cristianszwarc** [comment]
love the concept behind lesspass, and I'm also wondering about domain changes or sites with multiple domains as an example messenger.com and facebook.com, in #45 someone said something about detecting a "Service name", detecting that may be tricky but what about a per user list of services which will include a list of domains Facebook would include two domains and maybe others will have a *.somedomain.com.. so you can user the current site field or select the service from your own created list. following..

**Comment by philip-ulrich** [comment]
I've also been pained by this issue. The dropdown should really reflect all subdomains for the domain as options. So, for instance, I go to `google.com`, but I have saved logins for `accounts.google.com` and `www.google.com`. While on any google.com subdomain (or naked domain), the list should show all of these as options as it is not likely that I have multiple logins for the same site.

**Comment by edouard-lopez** [comment]
@blahgeek maybe we can have a cascading approach to this issue. For instance, if we use your example (visit `account.example.com` and save `example.com`): 

* first we look for the top-level domain `example.com` ;
* then we look for the full domain name `account.example.com` ;
* merge all results and show.

@guillaumevincent What do you think?

**Comment by edouard-lopez** [comment]
@cristianszwarc the `messenger.com` vs. `facebook.com` is another issue.

**Comment by cristianszwarc** [comment]
@edouard-lopez correct, but anyway, if a dropdown is provided with suggestions but you can also type in to search for any other saved domains this will be fix. (the dropdown should allow me to select facebook while I'm on the messenger domain)

**Comment by edouard-lopez** [comment]
@cristianszwarc you can do that in the connected mode

**Comment by cristianszwarc** [comment]
@edouard-lopez thanks!

**Comment by guillaumevincent** [comment]
With version 2 coming by default in 7 days here are the rules:

 * protocols `http(s)://` and `www.` are removed
 * we use only root domain (so `http://accounts.google.com/` return `google.com`)

Sometimes you need different password for same login, same domain but different subdomains.
For this special use case, we think that is a special profile should be created on LessPass Database (connected version).

So when user connect on www.google.com we will return the first password profile matching one of this criteria in order:

 * `passwordProfile.site === 'www.google.com'`
 *  `passwordProfile.site.endsWith('google.com')`
so `https://accounts.google.com/` return site `google.com` so password profile for `www.google.com`
