### ISSUE TITLE
LessPass core for react-native

### ISSUE THREAD

**Issue by sochix** [lesspass/lesspass#96]
Hi! I started playing with react-native to create less-pass client. Now, I have a problem:
- library pbkdf2 that lesspass used isn't working on react-native, because it's requires a lot of nodejs staff (Buffer, Stream, timer, process, etc...)
- I found crypto-js pbkdf2 (see here: https://github.com/sytelus/CryptoJS). It works fine, only for small number of iterations =< 1000. For big number of iterations it requires > 1 min to complete.

Any ideas, how can I continue developing? 

The best and hardest solution that I have in my mind right now -> write an react-native-module to work directly with Andorid or iOS api. If some one could help with this it would be wonderful!

**Comment by guillaumevincent** [comment]
@sochix I'm implementing lesspass-core 6.
You can try with `npm install --save lesspass@6.0.0-beta.2`

But for now you can also build the interface with a fake `generatePassword(site, login, masterPassword, passwordProfile)` method and I will look at the integration of LessPass core.

**Comment by guillaumevincent** [comment]
I close this one.
We will add native pbkdf2 library
